Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-03, with the labels that each got.

#3442 Add keymap support for WebMKS remote consoles
  app/helpers/vmware_console_helper.rb
  app/views/shared/_remote_console_footer.haml
  app/views/vm_common/console_webmks.html.haml
Labels: bug, consoles, fine/yes, gaprindashvili/yes

#3347 Menu pluggability improvements
  app/presenters/menu/item.rb
  app/presenters/menu/manager.rb
  app/presenters/menu/section.rb
  app/presenters/menu/yaml_loader.rb
  spec/presenters/menu/custom_loader_spec.rb
Labels: enhancement, gaprindashvili/no, menus

#3487 Fix Default Views settings for Service Catalogs
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes, services

#3180 Remove replacement of whole right cell and instead render flash message div so flash message isn't doubled
  app/controllers/miq_policy_controller/conditions.rb
Labels: bug, control, gaprindashvili/yes

#3502 babelrc - explicitly mention browser support
  .babelrc
Labels: developer, gaprindashvili/no

#3398 Change the way that network device details are displayed
  app/controllers/application_controller.rb
  app/controllers/guest_device_controller.rb
  app/controllers/physical_server_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/toolbar/guest_device_center.rb
  app/helpers/application_helper/toolbar/guest_devices_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/guest_device_helper.rb
  app/helpers/guest_device_helper/textual_summary.rb
  app/helpers/physical_server_helper/textual_summary.rb
  app/views/guest_device/show.html.haml
  app/views/guest_device/show_list.html.haml
  app/views/layouts/listnav/_guest_device.html.haml
  app/views/physical_server/show.html.haml
  config/routes.rb
  product/views/GuestDevice.yaml
  spec/controllers/guest_device_controller_spec.rb
  spec/controllers/physical_server_controller_spec.rb
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#3508 Revert "Hide region from Cloud provider forms if it's not required"
  app/controllers/ems_common.rb
Labels: bug, compute/cloud, fine/no, gaprindashvili/no

#3448 Remove variable interpolations from gettext strings
  app/controllers/ems_common.rb
  app/controllers/generic_object_definition_controller.rb
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/mixins/actions/vm_actions/retire.rb
  app/controllers/security_group_controller.rb
  app/helpers/generic_object_definition_helper/textual_summary.rb
Labels: gaprindashvili/no, internationalization, technical debt

#3496 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#3507 Add RBAC and Tagging Support to Ansible Credentials
  app/controllers/ansible_credential_controller.rb
  app/helpers/ansible_credential_helper/textual_summary.rb
  app/helpers/application_helper/toolbar/ansible_credential_center.rb
  app/helpers/application_helper/toolbar/ansible_credentials_center.rb
  config/routes.rb
  spec/controllers/ansible_credential_controller_spec.rb
Labels: automation/ansible, blocker, enhancement, gaprindashvili/yes

#3515 Do not inherit decorators from other than MiqDecorator
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/hawkular/middleware_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
Labels: compute/cloud, gaprindashvili/no, technical debt

#3516 Fix tool tip when tagging Ansible Credential from its summary page
  app/helpers/application_helper/toolbar/ansible_credential_center.rb
Labels: automation/ansible, enhancement, gaprindashvili/yes

#3506 Webpack - clean up loaders, support es6 in node_modules
  config/webpack/loaders/angular.js
  config/webpack/loaders/babel.js
  config/webpack/loaders/coffee.js
  config/webpack/loaders/erb.js
  config/webpack/loaders/react.js
  config/webpacker.yml
  package.json
Labels: dependencies, gaprindashvili/no

#3523 Fix travis issues with manageiq-graphql by updating deps
  package.json
Labels: dependencies, gaprindashvili/no

#3520 Do not inherit CloudManagerDecorator from EMS decorator
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
Labels: compute/cloud, gaprindashvili/no, technical debt

#3519 Drop middleware decorator quadicon definition
  app/decorators/manageiq/providers/hawkular/middleware_manager_decorator.rb
Labels: gaprindashvili/no, middleware, technical debt

#3521 Do not use try unnecessarily on EMS decorator type/auth_status
  app/decorators/ext_management_system_decorator.rb
Labels: compute/cloud, gaprindashvili/no, technical debt

#3513 Add RBAC and Tagging Support to Ansible Repositories
  app/controllers/ansible_repository_controller.rb
  app/helpers/ansible_repository_helper/textual_summary.rb
  app/helpers/application_helper/toolbar/ansible_repositories_center.rb
  app/helpers/application_helper/toolbar/ansible_repository_center.rb
  config/routes.rb
  spec/controllers/ansible_repository_controller_spec.rb
Labels: automation/ansible, blocker, enhancement, gaprindashvili/yes

#3494 Access show cost by in chargeback report for restricted user
  app/controllers/report_controller/reports/editor.rb
  app/helpers/report_helper/editor.rb
  spec/controllers/miq_report_controller/reports/editor_spec.rb
Labels: bug, cloud intel/chargeback, gaprindashvili/yes

#3527 add additional presets for v2v
  .babelrc
  package.json
Labels: enhancement, gaprindashvili/no, javascript infrastructure

#3537 Use fileicon instead of the newly introduced state_icon in decorators
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/vm_or_template_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: enhancement, gaprindashvili/no, gtls

#3535 Delete dead methods
  app/controllers/mixins/ems_common_angular.rb
  app/controllers/pxe_controller/pxe_servers.rb
Labels: gaprindashvili/no, technical debt

#3539 Remove default endpoints for :ems_nuage_network_with_authentication
  spec/controllers/mixins/ems_common_angular_spec.rb
Labels: gaprindashvili/yes, test

#3531 Apply RBAC filtering to cloud networks when creating floating ips
  app/controllers/floating_ip_controller.rb
Labels: bug, fine/yes, gaprindashvili/yes, networks

#3540 [Gaprindashvili] - Spec test failure fix.
  spec/controllers/miq_ae_class_controller_spec.rb
Labels: test

#3533 Fix CI specs by adding persistent user|group|role object
  spec/controllers/ops_controller/ops_rbac_spec.rb
  spec/controllers/ops_controller_spec.rb
  spec/helpers/application_helper/views_shared_spec.rb
  spec/presenters/tree_builder_ops_rbac_spec.rb
Labels: gaprindashvili/yes, test

#3416 [GAPRINDASHVILI] Update japanese & chinese translations for gaprindashvili
  locale/ja/ManageIQ_UI_Classic.po
  locale/zh_CN/ManageIQ_UI_Classic.po
Labels: internationalization

#3451 [GAPRINDASHVILI] Update manageiq-ui-components to 1.0.16 for gaprindashvili
  bower-locker.bower.json
  bower.json
Labels: blocker, dependencies

#3551 Solve a bug where a pdf button would't work for PhysicalInfra Provider
  app/helpers/ems_physical_infra_helper/textual_summary.rb
Labels: bug, compute/physical infrastructure, gaprindashvili/no

#3528 Enable to add tag for configuration provider
  app/controllers/provider_foreman_controller.rb
Labels: bug, gaprindashvili/yes

#3543 asset_data_uri - fix bower_components paths
  app/assets/stylesheets/pdf/_fontawesome.scss.erb
  app/assets/stylesheets/pdf/_patternfly.scss.erb
Labels: bug, gaprindashvili/no

#3544 ProviderForeman - fix overriden list_row_id to return string id
  app/controllers/provider_foreman_controller.rb
Labels: bug, configuration management, gaprindashvili/no

#3546 $http - redirect to login on 401, same as API
  app/assets/javascripts/miq_angular_application.js
  app/assets/javascripts/miq_api.js
  app/assets/javascripts/miq_application.js
Labels: enhancement, gaprindashvili/no

#3550 Fixing error while try to download the physical server summary as PDF
  config/routes.rb
Labels: bug, gaprindashvili/yes

#3549 .travis.yml - only run ruby specs in all ruby versions, js once
  .travis.yml
Labels: gaprindashvili/no, test

#3532 Fixing bug while try to perform a physical server action
  app/assets/javascripts/components/physical_infrastructures/physical-server-toolbar.js
  spec/javascripts/components/physical_infrastructures/physical-server-toolbar_spec.js
Labels: bug, gaprindashvili/yes

#3490 [GAPRINDASHVILI] Fix tool tip while setting the ownership for vm's
  bower-locker.bower.json
  bower.json
Labels: bug, compute/infrastructure

#3441 [GAPRINDASHVILI] Updated gettext catalogs for Gaprindashvili update
  locale/ManageIQ_UI_Classic.pot
  locale/en/ManageIQ_UI_Classic.po
  locale/es/ManageIQ_UI_Classic.po
  locale/fr/ManageIQ_UI_Classic.po
  locale/pt_BR/ManageIQ_UI_Classic.po
Labels: internationalization, unmergeable

#3559 Enable jsx to be loaded from js tests in jest
  jest.config.js
Labels: bug

#3556 Load the custom.css that bypasses the asset pipeline on every screen
  app/views/dashboard/saml_login.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/login.html.haml
  app/views/layouts/remote_console.html.haml
  app/views/layouts/report_only.html.haml
Labels: enhancement, gaprindashvili/yes, graphics, pending core

#3547 StaticController - add ApplicationHelper for helpers
  Rakefile
  app/controllers/static_controller.rb
  app/views/static/test_haml.html.haml
Labels: enhancement, gaprindashvili/no

#3575 tsconfig - enable allowJs, jsx:"react"
  tsconfig.json
Labels: enhancement, gaprindashvili/no

#3563 [GAPRINDASHVILI] Fix Travis failing and ansible repository controller spec
  spec/controllers/ansible_repository_controller_spec.rb
Labels: automation/ansible, test

#3574 Fix name of 'Physical Infrastructure Providers' on the Physical Infrastructure Providers page
  app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
Labels: bug, gaprindashvili/yes

#3524 Show policy status when running policy simulation
  app/controllers/application_controller/policy_support.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/vm_or_template_decorator.rb
Labels: blocker, bug, control, gaprindashvili/yes, gtls

#3552 Fix for the infinte spinner on Playbook Catalog Item Edit Form Reset
  app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
  app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
Labels: automation/automate, bug, gaprindashvili/yes

#3568 Fixed code that displays values saved for NTP Servers for selected zone
  app/controllers/ops_controller/settings/common.rb
  app/views/ops/_settings_evm_servers_tab.html.haml
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: blocker, bug, gaprindashvili/yes, settings

#3412 [FINE] - Show custom reports in menu editor as available reports.
  app/controllers/application_controller.rb
  app/controllers/report_controller/menus.rb
  app/controllers/report_controller/schedules.rb
  spec/controllers/miq_report_controller/menus_spec.rb
  spec/controllers/miq_report_controller/trees_spec.rb
  spec/controllers/report_controller_spec.rb
Labels: blocker, bug, cloud intel/reporting

#3573 Add Default View settings for Automation Ansible screens
  app/controllers/application_controller.rb
  app/views/configuration/_ui_2.html.haml
Labels: automation/ansible, enhancement, gaprindashvili/no, settings

#3522 Add RBAC and Tagging Support to Ansible Playbooks
  app/controllers/ansible_playbook_controller.rb
  app/controllers/application_controller.rb
  app/helpers/ansible_playbook_helper/textual_summary.rb
  app/helpers/application_helper/toolbar/ansible_playbook_center.rb
  app/helpers/application_helper/toolbar/ansible_playbooks_center.rb
  config/routes.rb
  spec/controllers/ansible_playbook_controller_spec.rb
Labels: automation/ansible, blocker, enhancement, gaprindashvili/yes

#3541 Add view selector to Ansible Repositories
  app/helpers/application_helper.rb
Labels: automation/ansible, bug, gaprindashvili/no

#3579 ManageIQ global cleanup, use for (old) component registry
  app/assets/javascripts/miq_global.js
  app/helpers/reactjs_helper.rb
  app/javascript/packs/application-common.js
Labels: gaprindashvili/no, technical debt

#3577 webpacker.yml - remove .vue
  config/webpacker.yml
Labels: gaprindashvili/no, technical debt

#3561 Adds hypervisor_hostname to details and list view for OS Infra Host
  app/helpers/host_helper/textual_summary.rb
  product/views/Host.yaml
Labels: bug, compute/infrastructure, enhancement, gaprindashvili/no

#3565 Generic Object - fix extra vm.angularForm and nonused angularForm
  app/views/static/generic_object/custom-image-component.html.haml
  app/views/static/generic_object/main_custom_button_form.html.haml
Labels: bug, gaprindashvili/no, generic objects

#3511 Hide disabled tabs
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: bug, compute/containers, gaprindashvili/no

#3566 networkRouterFormController - fix bad use/nonuse of $scope
  app/assets/javascripts/controllers/network_router/network_router_form_controller.js
Labels: bug, gaprindashvili/no, networks

#3529 Update description on VMRC configuration tab
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: bug, compute/infrastructure, fine/yes, gaprindashvili/yes

#3567 Provisioning properties tab should reflect that tenant will be chosen automatically
  app/views/miq_request/_prov_dialog_cloud_quota.html.haml
Labels: bug, compute/infrastructure, gaprindashvili/yes

#3569 Fixed CSP for webmks Console
  app/controllers/vm_remote.rb
Labels: bug, consoles, gaprindashvili/yes

#3581 Rename ERB spec files to HAML as we no longer have any ERBs
  spec/views/miq_request/_prov_options.html.haml_spec.rb
  spec/views/miq_request/_prov_vm_grid.html.haml_spec.rb
Labels: gaprindashvili/no, technical debt, test

#3583 Remove caching
  app/helpers/ops_helper/my_server.rb
Labels: gaprindashvili/no, settings, technical debt

#3576 Webpack - CommonsChunkPlugin - force for node_modules
  config/webpack/shared.js
Labels: enhancement, gaprindashvili/no

#3526 Untangling QuadiconHelper::Decorator and its shared methods
  app/decorators/ext_management_system_decorator.rb
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/physical_server_decorator.rb
  app/decorators/vm_or_template_decorator.rb
  app/helpers/quadicon_helper.rb
  app/helpers/quadicon_helper/decorator.rb
  lib/miq_decorator.rb
Labels: gtls, refactoring

#3602 Do not display policy shield on single quads in GTL view
  app/helpers/quadicon_helper.rb
  spec/helpers/quadicon_helper_spec.rb
Labels: bug, gaprindashvili/no, gtls

#3614 [GAPRINDASHVILI] Update gaprindashvili to manageiq-ui-components 1.0.18
  bower-locker.bower.json
  bower.json
Labels: blocker, dependencies

#3582 Remove unnecessary stub
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: gaprindashvili/no, test

#3610 Revert changes to description on VMRC configuration tab
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: bug, compute/infrastructure

#3613 Replace miqrequired with required
  app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml
Labels: bug, gaprindashvili/yes, settings

#3571 Consume patternfly.js through rubygems instead of bower
  app/assets/javascripts/application.js
  app/assets/stylesheets/pdf/_patternfly.scss.erb
Labels: bug, gaprindashvili/no

#3609 Drop the unnecessary argument from the quadicon decorator methods
  app/decorators/ext_management_system_decorator.rb
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
  app/decorators/physical_server_decorator.rb
  app/decorators/storage_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: cleanup, gaprindashvili/no, gtls

#3439 Use new dialog-user feature for custom buttons for more object types
  app/controllers/mixins/custom_button_dialog_form_mixin.rb
  app/controllers/ops_controller.rb
  app/services/dialog_local_service.rb
  spec/controllers/mixins/custom_button_dialog_form_mixin_spec.rb
Labels: automation/automate, enhancement

#3611 Unify fileicon and free_space_fileicon for StorageDecorator
  app/decorators/storage_decorator.rb
  spec/helpers/quadicon_helper_spec.rb
Labels: cleanup, gaprindashvili/no, gtls

#3616 Define single_quad methods for each model decorator that has a quadicon
  app/decorators/availability_zone_decorator.rb
  app/decorators/cloud_network_decorator.rb
  app/decorators/cloud_object_store_container_decorator.rb
  app/decorators/cloud_object_store_object_decorator.rb
  app/decorators/cloud_subnet_decorator.rb
  app/decorators/cloud_tenant_decorator.rb
  app/decorators/cloud_volume_backup_decorator.rb
  app/decorators/cloud_volume_decorator.rb
  app/decorators/cloud_volume_snapshot_decorator.rb
  app/decorators/container_build_decorator.rb
  app/decorators/container_decorator.rb
  app/decorators/container_group_decorator.rb
  app/decorators/container_image_decorator.rb
  app/decorators/container_image_registry_decorator.rb
  app/decorators/container_node_decorator.rb
  app/decorators/container_project_decorator.rb
  app/decorators/container_replicator_decorator.rb
  app/decorators/container_route_decorator.rb
  app/decorators/container_service_decorator.rb
  app/decorators/container_template_decorator.rb
  app/decorators/container_volume_decorator.rb
  app/decorators/ems_cluster_decorator.rb
  app/decorators/ext_management_system_decorator.rb
  app/decorators/flavor_decorator.rb
  app/decorators/floating_ip_decorator.rb
  app/decorators/host_aggregate_decorator.rb
  app/decorators/host_decorator.rb
  app/decorators/load_balancer_decorator.rb
  app/decorators/manageiq/providers/cloud_manager/auth_key_pair_decorator.rb
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/configuration_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/network_port_decorator.rb
  app/decorators/network_router_decorator.rb
  app/decorators/orchestration_stack_decorator.rb
  app/decorators/physical_server_decorator.rb
  app/decorators/resource_pool_decorator.rb
  app/decorators/security_group_decorator.rb
  app/decorators/storage_decorator.rb
  app/decorators/vm_or_template_decorator.rb
Labels: gaprindashvili/no, gtls

#3445 [FINE] Remove duplicate flash message on tag reset
  app/views/layouts/_tag_edit_items.html.haml
Labels: bug, tagging

#3626 Display flash message after Cloud Network delete is initiated.
  app/controllers/cloud_network_controller.rb
  spec/controllers/cloud_network_controller_spec.rb
Labels: blocker, bug, gaprindashvili/yes, networks

#3562 Added Max Retries text field on Instance screen
  app/controllers/miq_ae_class_controller.rb
  app/helpers/miq_ae_class_helper.rb
  app/views/miq_ae_class/_instance_fields.html.haml
  app/views/miq_ae_class/_instance_form.html.haml
Labels: automation/automate, enhancement, gaprindashvili/no

#3620 Move out the policy simulation result logic from the related quads
  app/decorators/miq_template_decorator.rb
  app/decorators/vm_or_template_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, gtls, refactoring

#3618 Ops Database: do not store vmdb_tables in the session.
  app/helpers/ops_helper/textual_summary.rb
  app/presenters/tree_builder_ops_vmdb.rb
Labels: gaprindashvili/no, settings, technical debt

#3612 Fix for Cloud image tagging from a list
  app/controllers/ems_common.rb
  spec/controllers/ems_common_controller_spec.rb
Labels: bug, compute/cloud, gaprindashvili/yes

#3617 Do not display GTL toolbars on non-GTL screens when navigating from the list
  app/controllers/generic_object_definition_controller.rb
  spec/controllers/generic_object_definition_controller_spec.rb
Labels: bug, gaprindashvili/yes, generic objects

#3621 Fix displaying 'CPU' and 'CPU Cores' when creating chargeback rate
  app/helpers/chargeback_helper.rb
  app/views/chargeback/_tier_first_row.haml
Labels: bug, cloud intel/chargeback, gaprindashvili/yes

#3624 Support single quad for Physical Infrastructure Provider quadicons
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/helpers/quadicon_helper.rb
  app/views/configuration/_ui_1.html.haml
Labels: bug, gaprindashvili/yes, gtls

#3625 Respect RBAC rules for physical server quadicon settings
  app/views/configuration/_ui_1.html.haml
Labels: bug, gaprindashvili/yes, settings

#3275 [FINE] Corrects sections and their names in New Subnet form
  app/views/cloud_subnet/new.html.haml
Labels: bug, networks

#3512 Change column title from "Updated on" to "Last refresh"
  product/views/ManageIQ_Providers_EmbeddedAutomationManager_ConfigurationScriptSource.yaml
Labels: automation/ansible, bug, gaprindashvili/yes

#2213 Restore the Delete button for servers in a zone
  app/controllers/ops_controller/diagnostics.rb
  app/helpers/application_helper/toolbar/diagnostics_zone_center.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_roles_by_server.rb
  spec/helpers/application_helper/toolbar/diagnostics_zone_center_spec.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
Labels: bug, gaprindashvili/yes, settings

#3628 Support single quad for Network Provider quadicons
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/helpers/quadicon_helper.rb
  app/views/configuration/_ui_1.html.haml
Labels: bug, gaprindashvili/yes, gtls, settings

#3629 Fix storage_controller to show custom buttons
  app/controllers/storage_controller.rb
Labels: automation/automate, bug, gaprindashvili/yes, toolbars

#3637 Add a column title for the Disk size Unit
  app/views/vm_common/_reconfigure.html.haml
Labels: bug, compute/infrastructure, gaprindashvili/yes

#3638 TextualSummary: remove unneeded physical infra partials
  app/helpers/physical_server_helper/textual_summary.rb
  app/views/physical_server/_textual_firmware_table.html.haml
  app/views/physical_server/_textual_network_adapter_table.html.haml
Labels: compute/physical infrastructure, gaprindashvili/no, technical debt

#3640 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#3632 Add Keystone Domain to EmsInfra form
  app/views/ems_infra/_form.html.haml
Labels: blocker, bug, enhancement, gaprindashvili/yes

#3619 [FINE] Fix tool tip while setting the ownership for VMs
  bower.json
Labels: bug, compute/infrastructure, pending core

#3650 Follow up for Restore delete server
  app/presenters/tree_builder.rb
Labels: bug, gaprindashvili/yes, settings

#3647 Fix untranslated entry when adding a new Schedule
  app/controllers/report_controller/schedules.rb
  app/views/layouts/_edit_email.html.haml
  app/views/report/_schedule_form.html.haml
Labels: bug, gaprindashvili/no, internationalization

#3649 Remove delete button for PhysicalServer
  app/helpers/application_helper/toolbar/physical_server_center.rb
  app/helpers/application_helper/toolbar/physical_servers_center.rb
Labels: cleanup, compute/physical infrastructure, gaprindashvili/no

#3652 [GAPRINDASHVILI] Follow-up to Restore server delete button in Diagnostics
  app/presenters/tree_builder_roles_by_server.rb
Labels: bug

#3341 Use correct role feature check for block|object storage summary page
  app/controllers/application_controller.rb
  app/controllers/ems_storage_controller.rb
  spec/controllers/ems_storage_controller_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#3564 Support for hidden columns in reports and views
  app/controllers/application_controller.rb
  lib/report_formatter/text.rb
  spec/controllers/host_controller_spec.rb
Labels: enhancement, gaprindashvili/yes, gtls, transformation

#3661 Show message when trying to edit item with missing Provisioning request
  app/controllers/catalog_controller.rb
  app/views/catalog/_sandt_tree_show.html.haml
  spec/controllers/catalog_controller_spec.rb
Labels: bug, gaprindashvili/yes, services

#3659 Display filters in accordion in Host Aggregates page
  app/helpers/application_helper.rb
  config/routes.rb
Labels: bug, compute/infrastructure, gaprindashvili/no

#3525 Allow datetime (existence of Resource) fields in report definition of chargeback for VM/Container/...* report
  app/controllers/report_controller/reports/editor.rb
Labels: cloud intel/chargeback, enhancement, gaprindashvili/yes

#3605 Offer rate columns in chargeback report
  app/controllers/report_controller/reports/editor.rb
Labels: cloud intel/chargeback, enhancement, gaprindashvili/no

#3578 Fix compare and drift field counters
  app/controllers/application_controller/compare.rb
  spec/controllers/application_controller/compare_spec.rb
Labels: bug

#3633 Add new JS component API (from #3228)
  app/assets/javascripts/miq_application.js
  app/assets/javascripts/miq_global.js
  app/javascript/miq-component/component-typings.ts
  app/javascript/miq-component/helpers.js
  app/javascript/miq-component/miq-component.spec.js
  app/javascript/miq-component/react-blueprint.tsx
  app/javascript/miq-component/registry.ts
  app/javascript/miq-component/utils.ts
  app/javascript/packs/application-common.js
  app/javascript/typings/globals.d.ts
  package.json
Labels: developer, enhancement, gaprindashvili/no

#3663 [GAPRINDASHVILI] ui-components: update to 1.0.19
  bower-locker.bower.json
  bower.json
Labels: dependencies

#3668 Correct positioning of dialog form buttons
  app/views/shared/dialogs/_dialog_user.html.haml
Labels: bug, formatting/styling, gaprindashvili/yes

#3631 Use fileicon instead state_icon in container provider powerstate quad
  app/decorators/manageiq/providers/container_manager_decorator.rb
Labels: bug, gaprindashvili/no, gtls

#3646 Remove unused GTL partials for list, tile and grid
  app/views/layouts/gtl/_grid.html.haml
  app/views/layouts/gtl/_list.html.haml
  app/views/layouts/gtl/_tile.html.haml
Labels: cleanup, gaprindashvili/no, gtls

#3538 update:ui - ensure we always see all the js engines
  lib/tasks/manageiq/ui_tasks.rake
  package.json
  tools/ci/setup_js_env.sh
Labels: dependencies, gaprindashvili/yes

#3468 Add Vault credentials to the UI for Embedded Ansible
  app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
  app/assets/javascripts/controllers/miq_ae_class/ae_method_form_controller.js
  app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
  app/controllers/catalog_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/helpers/service_helper/textual_summary.rb
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
  app/views/miq_ae_class/_method_inputs.html.haml
  spec/helpers/service_helper/textual_summary_spec.rb
  spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
Labels: automation/ansible, enhancement, gaprindashvili/yes

#3545 Update Expression Editor Styling
  app/assets/stylesheets/patternfly_overrides.scss
  app/controllers/application_controller/filter.rb
  app/views/layouts/_exp_editor.html.haml
  app/views/layouts/_filter_expression.html.haml
  app/views/layouts/exp_atom/_editor.html.haml
  app/views/miq_ae_class/_method_form.html.haml
  app/views/miq_policy/_alert_details.html.haml
  app/views/miq_policy/_condition_details.html.haml
  app/views/miq_policy/_form_expression.html.haml
  app/views/miq_policy/_policy_details.html.haml
Labels: enhancement, formatting/styling, gaprindashvili/no

#3630 Use keys for policySimulation when single quad is rendered
  app/helpers/quadicon_helper.rb
Labels: bug

#3675 Allow Schedule to have also custom MiqReport in Filter
  app/controllers/report_controller/schedules.rb
Labels: bug, cloud intel/reporting, gaprindashvili/yes

#3554 Enable grid as view model for policy assignment screens
  app/controllers/application_controller/policy_support.rb
Labels: bug, gaprindashvili/yes

#3682 API js - use base64encode which can deal with UTF8 passwords
  app/assets/javascripts/miq_api.js
  app/javascript/packs/compat-common.js
  app/views/layouts/login.html.haml
  package.json
Labels: blocker, bug, dependencies, gaprindashvili/yes

#3684 Add vault credential display for the playbook retirement tab
  app/views/catalog/_sandt_tree_show.html.haml
Labels: automation/ansible, enhancement, gaprindashvili/yes

#3644 Fix mismatching categories with values when assigning tags
  app/controllers/application_controller/tags.rb
  app/views/layouts/_tag_edit.html.haml
Labels: bug

#3674 Graphql lanaguage service / ignore .flow.js files
  config/webpack/shared.js
Labels: developer, gaprindashvili/no

#3680 Fail with an error on /ping immediately if DB is not accessible
  app/controllers/ping_controller.rb
Labels: bug, gaprindashvili/yes

#3683 vertical_navbar - a element to use exisitng param, href
  app/views/layouts/_vertical_navbar.html.haml
Labels: bug, gaprindashvili/no, menus

#3692 Fix typo in flash message after refreshing Ansible Tower Providers
  app/controllers/application_controller/ci_processing.rb
Labels: automation/ansible, bug, gaprindashvili/no

#3687 Fix TextEncoderLite in old browsers
  app/javascript/packs/compat-common.js
  package.json
  spec/javascripts/miq_api_spec.js
  spec/javascripts/support/jasmine.yml
Labels: bug, gaprindashvili/yes

#3689 AeResolveOptions - use ng-if instead of ng-show
  app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml
Labels: automation/automate, bug, gaprindashvili/yes

#3645 MiqPolicy: cleanup handle_selection_buttons a bit.
  app/controllers/miq_policy_controller.rb
Labels: control, gaprindashvili/no, technical debt

#3698 Fixed id of currentTab
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
Labels: blocker, bug, compute/containers, gaprindashvili/yes

#3694 Allow scm_url to take ssh with ssh protocol
  app/assets/javascripts/directives/url_validation.js
  app/views/ansible_repository/_repository_form.html.haml
Labels: automation/ansible, bug, gaprindashvili/yes

#3435 Make filters saved in Workloads displayed in accordion
  app/controllers/application_controller/advanced_search.rb
  app/helpers/application_helper.rb
Labels: bug

#3643 Do not pass flash messages in the URL.
  app/controllers/application_controller.rb
  app/controllers/application_controller/ci_processing.rb
  app/controllers/application_controller/dialog_runner.rb
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/application_controller/tags.rb
  app/controllers/auth_key_pair_cloud_controller.rb
  app/controllers/chargeback_controller.rb
  app/controllers/cloud_network_controller.rb
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/cloud_subnet_controller.rb
  app/controllers/cloud_tenant_controller.rb
  app/controllers/cloud_volume_backup_controller.rb
  app/controllers/cloud_volume_controller.rb
  app/controllers/configuration_controller.rb
  app/controllers/ems_cloud_controller.rb
  app/controllers/ems_common.rb
  app/controllers/ems_infra_controller.rb
  app/controllers/floating_ip_controller.rb
  app/controllers/host_aggregate_controller.rb
  app/controllers/host_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/miq_ae_tools_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_request_controller.rb
  app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb
  app/controllers/mixins/actions/vm_actions/disassociate_floating_ip.rb
  app/controllers/mixins/actions/vm_actions/evacuate.rb
  app/controllers/mixins/actions/vm_actions/live_migrate.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/controllers/mixins/actions/vm_actions/resize.rb
  app/controllers/mixins/actions/vm_actions/retire.rb
  app/controllers/mixins/containers_common_mixin.rb
  app/controllers/mixins/ems_common_angular.rb
  app/controllers/mixins/find_record.rb
  app/controllers/mixins/generic_form_mixin.rb
  app/controllers/mixins/manager_controller_mixin.rb
  app/controllers/network_router_controller.rb
  app/controllers/ops_controller/settings.rb
  app/controllers/ops_controller/settings/analysis_profiles.rb
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/upload.rb
  app/controllers/orchestration_stack_controller.rb
  app/controllers/report_controller/reports/editor.rb
  app/controllers/report_controller/schedules.rb
  app/controllers/restful_redirect_controller.rb
  app/controllers/security_group_controller.rb
  app/controllers/service_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_cloud_controller.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  spec/controllers/application_controller/dialog_runner_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/miq_ae_tools_controller_spec.rb
  spec/controllers/miq_policy_controller_spec.rb
Labels: bug, fine/no, gaprindashvili/no, technical debt

#3695 Deduplicate the orchestration stack decorator and join their definitions
  app/decorators/manageiq/providers/cloud_manager/orchestration_stack_decorator.rb
  app/decorators/orchestration_stack_decorator.rb
Labels: bug, cleanup, gaprindashvili/no

#3688 Display Adv Search in Volume Snapshots/Backups pages
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
Labels: bug, expressions/filters, gaprindashvili/yes, storage

#3704 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation
