Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-12, with the labels that each got.

#5020 Increase memory limit for NodeJS to 4G
  bin/webpack
  bin/webpack-dev-server
Labels: developer, hammer/yes

#5019 CloudTennant -> CloudTenant
  app/helpers/application_helper.rb
  app/javascript/components/cloud-tenant-form/cloud-tenant-form.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
  app/views/cloud_tenant/edit.html.haml
  app/views/cloud_tenant/new.html.haml
Labels: technical debt

#5017 Service catalog icon fix
  app/views/catalog/_svccat_tree_show.html.haml
Labels: bug, gaprindashvili/yes, graphics, hammer/yes

#5016 Fix rubocop warning under app/services/c*
  app/services/cloud_tenant_dashboard_service.rb
  app/services/container_dashboard_service.rb
  app/services/container_topology_service.rb
  app/services/customize_fields_visibility_service.rb
Labels: hammer/no, technical debt

#5023 Codeclimate eslint configuration
  .codeclimate.yml
  app/javascript/.eslintrc.js
  app/javascript/.eslintrc.json
  app/javascript/miq-redux/redux-router-actions.js
  app/javascript/miq-redux/store.js
  app/javascript/packs/globals.js
  app/javascript/packs/provider-dialogs-common.js
  app/javascript/packs/provisioning-actions-common.js
  app/javascript/provider-dialogs/modal.js
  config/.eslintrc.json
  config/webpack/configuration.js
  config/webpack/production.js
  config/webpack/shared.js
  package.json
Labels: technical debt

#5032 Delete the ImageEncodeHelper as it is no longer used anywhere
  app/controllers/application_controller.rb
  app/helpers/image_encode_helper.rb
  spec/views/layouts/listnav/_availability_zone.html.haml_spec.rb
  spec/views/layouts/listnav/_cloud_network.html.haml_spec.rb
  spec/views/layouts/listnav/_cloud_subnet.html.haml_spec.rb
  spec/views/layouts/listnav/_cloud_tenant.html.haml_spec.rb
  spec/views/layouts/listnav/_ems_cloud.html.haml_spec.rb
  spec/views/layouts/listnav/_ems_cluster.html.haml_spec.rb
  spec/views/layouts/listnav/_ems_container.html.haml_spec.rb
  spec/views/layouts/listnav/_ems_network.html.haml_spec.rb
  spec/views/layouts/listnav/_flavor.html.haml_spec.rb
  spec/views/layouts/listnav/_floating_ip.html.haml_spec.rb
  spec/views/layouts/listnav/_host_aggregate.html.haml_spec.rb
  spec/views/layouts/listnav/_load_balancer.html.haml_spec.rb
  spec/views/layouts/listnav/_network_port.html.haml_spec.rb
  spec/views/layouts/listnav/_network_router.html.haml_spec.rb
  spec/views/layouts/listnav/_orchestration_stack.html.haml_spec.rb
  spec/views/layouts/listnav/_persistent_volume.html.haml_spec.rb
  spec/views/layouts/listnav/_security_group.html.haml_spec.rb
Labels: hammer/no, technical debt

#4987 Add top row information into the storage manager quadicons
  app/decorators/manageiq/providers/storage_manager_decorator.rb
  spec/decorators/manageiq/providers/storage_manager_decorator_spec.rb
Labels: blocker, bug, gtls, hammer/yes

#5035 Fix rubocop warning under services/[rs]*
  app/services/request_type_visibility_service.rb
  app/services/retirement_visibility_service.rb
  app/services/service_template_fields_visibility_service.rb
Labels: technical debt

#5034 Fix rubocop warning under services/p*
  app/services/privilege_checker_service.rb
  app/services/prometheus_proxy_service.rb
  app/services/pxe_iso_visibility_service.rb
Labels: technical debt

#5033 Fix rubocop warning under services/n*
  app/services/network_topology_service.rb
  app/services/network_visibility_service.rb
  app/services/number_of_vms_visibility_service.rb
Labels: technical debt

#4993 Angular dashboard - move to es6, stop requesting template on load
  app/assets/javascripts/components/dropdown-menu.js
  app/assets/javascripts/components/widget-chart.js
  app/assets/javascripts/components/widget-empty.js
  app/assets/javascripts/components/widget-error.js
  app/assets/javascripts/components/widget-footer.js
  app/assets/javascripts/components/widget-menu.js
  app/assets/javascripts/components/widget-report.js
  app/assets/javascripts/components/widget-rss.js
  app/assets/javascripts/components/widget-spinner.js
  app/assets/javascripts/components/widget-wrapper.js
  app/javascript/.eslintrc.json
  app/javascript/angular/dashboard/dropdown-menu.js
  app/javascript/angular/dashboard/index.js
  app/javascript/angular/dashboard/widget-chart.js
  app/javascript/angular/dashboard/widget-empty.js
  app/javascript/angular/dashboard/widget-error.js
  app/javascript/angular/dashboard/widget-footer.js
  app/javascript/angular/dashboard/widget-menu.js
  app/javascript/angular/dashboard/widget-report.js
  app/javascript/angular/dashboard/widget-rss.js
  app/javascript/angular/dashboard/widget-spinner.js
  app/javascript/angular/dashboard/widget-wrapper.js
  app/javascript/angular/index.js
  app/javascript/packs/angular-common.js
  app/javascript/spec/dashboard/mocks.js
  app/javascript/spec/dashboard/widget-empty.spec.js
  app/javascript/spec/dashboard/widget-wrapper.spec.js
  app/views/static/dropdown-menu.html.haml
Labels: cloud intel/dashboard, refactoring

#5029 select: use @pf3/select instead of bootstrap-select
  app/javascript/packs/globals.js
  app/views/report/_column_lists.html.haml
  config/webpack/shared.js
  package.json
Labels: blocker, bug, cloud intel/reporting, hammer/yes

#5025 Fix rubocop warings under services/[ghl]*
  app/services/git_repository_service.rb
  app/services/hawkular_proxy_service.rb
  app/services/linked_clone_visibility_service.rb
Labels: technical debt

#5024 Fix rubocop warings under services/[de]*
  app/services/dialog_field_visibility_service.rb
  app/services/ems_dashboard_service.rb
  app/services/ems_infra_dashboard_service.rb
Labels: technical debt

#5037 Include cloud tenant name column in Security Group list view
  product/views/SecurityGroup.yaml
Labels: enhancement, gtls

#5042 [Changelog] Update for Sprint 100
  CHANGELOG.md
Labels: documentation

#5026 eslint - upgrade to 5, upgrade plugins
  package.json
  tools/ci/before_install.sh
Labels: developer

#5028 Data driven form submit button disable config.
  app/javascript/forms/data-driven-form.jsx
  package.json
Labels: bug, react

#5030 Fix CatalogItem tree_select()
  app/controllers/catalog_controller.rb
Labels: bug, hammer/yes, services

#4862 Fix rubocop warnings in OpsController*
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/db.rb
  app/controllers/ops_controller/diagnostics.rb
  app/controllers/ops_controller/ops_rbac.rb
  app/controllers/ops_controller/settings.rb
  app/controllers/ops_controller/settings/analysis_profiles.rb
  app/controllers/ops_controller/settings/automate_schedules.rb
  app/controllers/ops_controller/settings/cap_and_u.rb
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  app/controllers/ops_controller/settings/rhn.rb
  app/controllers/ops_controller/settings/schedules.rb
  app/controllers/ops_controller/settings/tags.rb
  app/controllers/ops_controller/settings/upload.rb
  app/controllers/ops_controller/settings/zones.rb
Labels: hammer/no, technical debt

#5047 Use widget's title in flash messages
  app/controllers/report_controller/widgets.rb
Labels: bug, cloud intel/reporting, hammer/yes

#5027 Move require/mock from jest.setup to helpers
  app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
  app/javascript/spec/dashboard/widget-empty.spec.js
  app/javascript/spec/dashboard/widget-wrapper.spec.js
  app/javascript/spec/helpers/API.js
  app/javascript/spec/helpers/addFlash.js
  app/javascript/spec/helpers/angular.js
  app/javascript/spec/helpers/getJSONFixtures.js
  app/javascript/spec/helpers/miqAjaxButton.js
  app/javascript/spec/helpers/miqSparkle.js
  app/javascript/spec/helpers/mockAsyncRequest.js
  app/javascript/spec/helpers/sprintf.js
  app/javascript/spec/service-form/service-form.spec.js
  app/javascript/spec/toolbar-actions/toolbar-actions-delete.spec.js
  app/javascript/spec/toolbar-actions/toolbar-actions-generic.spec.js
  config/jest.setup.js
Labels: hammer/no, technical debt, test

#5050 Remove unnecessary images from the layout folder
  app/assets/images/layout/base-single.svg
  app/assets/images/layout/base.svg
  app/assets/images/layout/clearpix.gif
  app/assets/images/layout/minus.gif
  app/assets/images/layout/plus.gif
  app/assets/images/layout/reflection.png
Labels: cleanup, graphics, technical debt

#5051 Add missing single_quad definitions for ansible-related entities
  app/decorators/configuration_script_source_decorator.rb
  app/decorators/manageiq/providers/ansible_tower/automation_manager/configuration_script_decorator.rb
  app/decorators/manageiq/providers/ansible_tower/automation_manager/playbook_decorator.rb
  app/decorators/manageiq/providers/automation_manager/inventory_group_decorator.rb
  app/decorators/manageiq/providers/automation_manager/inventory_root_group_decorator.rb
  app/decorators/manageiq/providers/embedded_ansible/automation_manager/playbook_decorator.rb
  app/decorators/manageiq/providers/embedded_automation_manager/configuration_script_source_decorator.rb
Labels: bug, gtls, hammer/yes

#5059 Do not try to display icon as image on Monitoring -> Alerts cards
  app/views/shared/views/_show_alerts_overview.html.haml
Labels: bug, control, gaprindashvili/yes, hammer/yes

#5054 Use the uib-tab parameter for switching tabs on the tasks screen
  app/controllers/miq_task_controller.rb
Labels: bug, hammer/yes, tasks

#5038 uib-tooltip - respect newlines in tooltips
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, enhancement, services

#5041 Fix rendering of VMware floppy drive
  app/helpers/vm_helper.rb
Labels: bug, compute/infrastructure, hammer/yes

#5061 Fix rubocop warnings under app/helpers/a*
  app/helpers/ansible_repository_helper/textual_summary.rb
  app/helpers/automate_tree_helper.rb
Labels: technical debt

#5053 Fix rubocop warnings in ApplicationHelper
  app/helpers/application_helper.rb
  app/helpers/application_helper/dialogs.rb
  app/helpers/application_helper/toolbar_builder.rb
  app/helpers/application_helper/toolbar_chooser.rb
Labels: technical debt

#5048 Fix rubocop warnings in app/decorators/*
  app/decorators/storage_decorator.rb
  app/decorators/vm_decorator.rb
Labels: technical debt

#5062 Drop support for IE10 when transpiling javascript using babel
  .babelrc.js
Labels: gaprindashvili/no

#5052 Drop jQuery calls from the webpack-compiled JS codebase
  app/javascript/http_api/fetch.js
  app/javascript/packs/provider-dialogs-common.js
  app/javascript/provider-dialogs/modal.js
  app/javascript/react/textual_summary_click.js
Labels: hammer/no, refactoring

#5046 Replaces angular ownership form with data-driven-form
  .babelrc
  app/assets/javascripts/controllers/ownership/ownership_form_controller.js
  app/javascript/.eslintrc.json
  app/javascript/components/set-service-ownership-form/index.jsx
  app/javascript/components/set-service-ownership-form/schema.js
  app/javascript/forms/data-driven-form.jsx
  app/javascript/http_api/http.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/set-service-ownership-form/set-service-ownership-form.spec.js
  app/views/shared/views/_ownership.html.haml
  spec/javascripts/controllers/ownership/ownership_form_controller_spec.js
Labels: hammer/no, react

#5065 Fix travis - jest
  app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
  app/javascript/spec/service-form/service-form.spec.js
  app/javascript/spec/set-service-ownership-form/set-service-ownership-form.spec.js
  config/jest.setup.js
Labels: test

#5043 Fix rubocop warnings in services/[tu]*
  app/services/topology_service.rb
  app/services/user_validation_service.rb
Labels: technical debt

#5063 Add IDs to vertical menu leaf items
  app/views/layouts/_vertical_navbar.html.haml
Labels: enhancement, menus

#5064 Fix multi-target Set Ownership
  app/controllers/mixins/actions/vm_actions/ownership.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: bug, compute/infrastructure, gaprindashvili/yes, hammer/yes

#5066 Monitoring > Alerts - sparkle when loading
  app/assets/javascripts/controllers/alerts/alerts_list_controller.js
  app/assets/javascripts/controllers/alerts/alerts_most_recent_controller.js
  app/assets/javascripts/controllers/alerts/alerts_overview_controller.js
  app/assets/javascripts/services/alerts_center_service.js
Labels: bug, control, gaprindashvili/yes, hammer/yes

#5056 Fix failing creating new Alert in Control > Explorer
  app/controllers/miq_policy_controller/alerts.rb
  spec/controllers/miq_policy_controller/alerts_spec.rb
Labels: blocker, bug, control, hammer/yes

#5073 [HAMMER] select: use @pf3/select instead of bootstrap-select
  app/javascript/packs/globals.js
  app/views/report/_column_lists.html.haml
  config/webpack/shared.js
  package.json
  yarn.lock
Labels: blocker, bug, cloud intel/reporting

#4951 Catch 400 error and display it in flash message in GOD
  app/assets/javascripts/components/generic_object/main-custom-button-form-component.js
  spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js
Labels: automation/automate, bug, generic objects, hammer/yes

#5068 Added i18n form data-driven-forms default validation messages.
  app/javascript/forms/data-driven-form.jsx
  package.json
Labels: enhancement

#5080 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: developer, gaprindashvili/yes, hammer/yes

#5081 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#5086 spec_helper - fix filename after FactoryBot rename
  spec/spec_helper.rb
Labels: hammer/no, technical debt

#5087 Fix travis badge to use the master branch.
  README.md
Labels: developer

#5088 Alias moment to fix moment-strftime dependency
  config/webpack/shared.js
Labels: dependencies

#5074 Enable JSX for eslint - codeclimate & yarn run lint
  .codeclimate.yml
  app/javascript/.eslintrc.json
  app/javascript/components/miq-about-modal.jsx
  app/javascript/components/service-form/index.jsx
  app/javascript/forms/form-buttons-redux.jsx
  app/javascript/forms/form-buttons.jsx
  app/javascript/forms/miq-button.jsx
  app/javascript/react/generic_group_wrapper.jsx
  app/javascript/react/textual_summary_wrapper.jsx
  package.json
Labels: developer, hammer/no

#5077 Fix rubocop warnings in app/helpers/h*
  app/helpers/host_aggregate_helper/textual_summary.rb
  app/helpers/host_helper/textual_summary.rb
Labels: technical debt

#5079 Fix rubocop warnings in app/helpers/[mn]*
  app/helpers/miq_ae_class_helper.rb
  app/helpers/network_port_helper/textual_summary.rb
  app/helpers/network_router_helper/textual_summary.rb
  app/helpers/number_helper.rb
Labels: technical debt

#5083 Fix rubocop warnings in app/helpers/o*
  app/helpers/ops_helper.rb
  app/helpers/ops_helper/textual_summary.rb
  app/helpers/orchestration_stack_helper/textual_summary.rb
Labels: technical debt

#5084 Fix rubocop warnings in app/helpers/p*
  app/helpers/persistent_volume_helper/textual_summary.rb
  app/helpers/physical_server_helper/textual_summary.rb
  app/helpers/planning_helper.rb
  app/helpers/provider_configuration_manager_helper.rb
Labels: technical debt

#5078 Fix rubocop warnings in app/helpers/[ijl]*
  app/helpers/infra_networking_helper/textual_summary.rb
  app/helpers/js_helper.rb
  app/helpers/load_balancer_helper.rb
  app/helpers/load_balancer_helper/textual_summary.rb
Labels: technical debt

#5072 Fix rubocop warnings in app/helpers/[fg]*
  app/helpers/flavor_helper/textual_summary.rb
  app/helpers/generic_object_definition_helper/textual_summary.rb
  app/helpers/gtl_helper.rb
Labels: technical debt

#5071 Fix rubocop warnings in app/helpers/e*
  app/helpers/ems_cloud_helper/textual_summary.rb
  app/helpers/ems_cluster_helper/textual_summary.rb
  app/helpers/ems_container_helper/textual_summary.rb
  app/helpers/ems_infra_helper/textual_summary.rb
  app/helpers/ems_physical_infra_helper/textual_summary.rb
Labels: technical debt

#5069 Fix rubocop warnings in app/helpers/c*
  app/helpers/c3_helper.rb
  app/helpers/catalog_helper/textual_summary.rb
  app/helpers/cloud_object_store_object_helper/textual_summary.rb
  app/helpers/cloud_resource_quota_helper.rb
  app/helpers/cloud_subnet_helper/textual_summary.rb
  app/helpers/compliance_summary_helper.rb
  app/helpers/configuration_helper/configuration_view_helper.rb
  app/helpers/container_build_helper/textual_summary.rb
  app/helpers/container_group_helper/textual_summary.rb
  app/helpers/container_helper/textual_summary.rb
  app/helpers/container_image_helper.rb
  app/helpers/container_image_registry_helper.rb
  app/helpers/container_summary_helper.rb
Labels: technical debt

#4999 Add MenuUpdateMixin
  app/controllers/mixins/menu_update_mixin.rb
  spec/controllers/mixins/menu_update_mixin_spec.rb
Labels: menus

#5094 Don't assign bool value to variable that already has it
  app/controllers/report_controller.rb
  app/views/report/_export_custom_reports.html.haml
Labels: hammer/no, refactoring

#5097 Use onchange only for radio buttons
  app/assets/javascripts/miq_ujs_bindings.js
Labels: bug, gaprindashvili/yes, hammer/yes

#5095 Region Replication - refresh code mirror after load
  app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
  app/views/ops/_settings_replication_tab.html.haml
Labels: bug, hammer/yes, settings

#5093 Fix rubocop warnings in app/helpers/t*
  app/helpers/term_of_service_helper.rb
  app/helpers/textual_mixins/textual_advanced_settings.rb
  app/helpers/textual_mixins/textual_authentications_status.rb
  app/helpers/textual_mixins/textual_devices.rb
  app/helpers/textual_mixins/textual_drift.rb
  app/helpers/textual_mixins/textual_filesystems.rb
  app/helpers/textual_mixins/textual_init_processes.rb
  app/helpers/textual_mixins/textual_metrics_status.rb
  app/helpers/textual_mixins/textual_patches.rb
  app/helpers/textual_mixins/textual_scan_history.rb
  app/helpers/textual_mixins/vm_common.rb
  app/helpers/textual_summary_helper.rb
Labels: hammer/no, technical debt

#5102 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#5091 Fix rubocop warnings in app/helpers/r*
  app/helpers/report_helper.rb
  app/helpers/report_helper/timer.rb
  app/helpers/resource_pool_helper.rb
  app/helpers/resource_pool_helper/textual_summary.rb
Labels: technical debt

#5092 Fix rubocop warnings in app/helpers/s*
  app/helpers/service_helper/textual_summary.rb
  app/helpers/storage_helper/textual_summary.rb
Labels: technical debt

#5096 Fix CatalogItem tree_select()
  app/controllers/catalog_controller.rb
Labels: blocker, bug, hammer/yes, services

#5089 [HAMMER] Update json i18n catalogs for hammer
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
Labels: internationalization

#5107 add WEBPACK_VERBOSE (default off), only output some warnings when enabled
  config/webpack/loaders.js
  config/webpack/shared.js
Labels: developer

#5109 [HAMMER] Update ui-components to 1.1.19 for hammer
  package.json
  yarn.lock
Labels: dependencies

#5108 Clean out cache of MiqProductFeature at CUD tenant actions in UI process
  app/assets/javascripts/components/ops/tenant-component.js
  app/controllers/ops_controller/ops_rbac.rb
  config/routes.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
  spec/javascripts/components/ops/tenant-component_spec.js
Labels: blocker, bug

#5070 Remove component from component name
  app/assets/javascripts/components/ae_resolve_options/ae-resolve-options.js
  app/assets/javascripts/components/generic_object/custom-button-group-form.js
  app/assets/javascripts/components/generic_object/custom-image.js
  app/assets/javascripts/components/generic_object/generic-object-definition.js
  app/assets/javascripts/components/generic_object/generic-object-table.js
  app/assets/javascripts/components/generic_object/main-custom-button-form.js
  app/assets/javascripts/components/generic_object/main-custom-button-group-form.js
  app/assets/javascripts/components/ops/log-collection-form.js
  app/assets/javascripts/components/ops/tenant.js
  app/assets/javascripts/components/physical_infrastructures/change-password.js
  app/assets/javascripts/components/vm_cloud/vm-cloud-add-security-group.js
  app/assets/javascripts/components/vm_cloud/vm-cloud-remove-security-group.js
  app/views/ems_physical_infra/change_password.html.haml
  app/views/generic_object_definition/_custom_button_form.html.haml
  app/views/generic_object_definition/_custom_button_group_form.html.haml
  app/views/generic_object_definition/_generic_object_definition_form.html.haml
  app/views/ops/_tenant_form.html.haml
  app/views/static/ae_resolve_options/ae-resolve-options.html.haml
  app/views/static/generic_object/custom-image.html.haml
  app/views/static/generic_object/generic_object_definition.html.haml
  app/views/static/generic_object/main_custom_button_form.html.haml
  app/views/static/generic_object/main_custom_button_group_form.html.haml
  app/views/vm_common/_add_security_group.html.haml
  app/views/vm_common/_remove_security_group.html.haml
  spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js
  spec/javascripts/components/ops/tenant_spec.js
  spec/javascripts/components/physical_infrastructures/change-password_spec.js
  spec/javascripts/components/vm_cloud/vm-cloud-add-security-group_spec.js
  spec/javascripts/components/vm_cloud/vm-cloud-remove-security-group_spec.js
Labels: hammer/no, technical debt
