Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-09, with the labels that each got.

#4576 Remove phantomjs bind polyfill
  bower.json
  spec/javascripts/support/jasmine.yml
Labels: dependencies

#4549 Lazy load StorageManagers upon volume creation
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/views/cloud_volume/attach.html.haml
  app/views/cloud_volume/backup_new.html.haml
  app/views/cloud_volume/backup_select.html.haml
  app/views/cloud_volume/detach.html.haml
  app/views/cloud_volume/edit.html.haml
  app/views/cloud_volume/new.html.haml
  app/views/cloud_volume/snapshot_new.html.haml
Labels: blocker, bug, fine/yes, gaprindashvili/yes, storage

#4584 aggregate_status_card - fix i18n typo
  app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js
Labels: bug, gaprindashvili/no, internationalization

#4586 Don't use string arithmetic in gettext strings
  app/controllers/catalog_controller.rb
Labels: gaprindashvili/no, internationalization, technical debt

#4577 Fix creation of internal rss widget
  app/controllers/report_controller/widgets.rb
  app/views/report/_widget_form_rss.html.haml
Labels: bug, cloud intel/reporting, gaprindashvili/no

#4588 CloudNetworkController: fix rubocop warnings
  app/controllers/cloud_network_controller.rb
Labels: gaprindashvili/no, technical debt

#4567 Add Chassis to PhysicalInfra dashboard and listnav
  app/decorators/physical_chassis_decorator.rb
  app/helpers/ems_physical_infra_helper/textual_summary.rb
  app/views/layouts/listnav/_ems_physical_infra.html.haml
  spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb
Labels: compute/physical infrastructure, enhancement, ux/approved

#4575 Enable 'Paste' button only if the copied and selected target class are the same
  app/views/shared/buttons/_ab_form.html.haml
  spec/views/shared/buttons/_ab_form.html.haml_spec.rb
Labels: automation/automate, bug, fine/yes, gaprindashvili/yes

#4561 Replaced obsolete method for record fetching with RBAC in PXE controller
  app/controllers/pxe_controller/pxe_image_types.rb
Labels: rbac, refactoring

#4547 [FINE] Add date only options for chargeback grouping fine and 4517
  app/views/report/_form_filter_chargeback.html.haml
Labels: blocker, cloud intel/chargeback, enhancement

#4583 Fix missing flash_msg_div in ops/settings/zone_form
  app/controllers/ops_controller.rb
  app/views/ops/_zone_form.html.haml
  spec/views/ops/_zone_form.html.haml_spec.rb
Labels: bug, gaprindashvili/no, settings

#4505 Add restful redirect rule for notifications arriving from V2V
  app/controllers/restful_redirect_controller.rb
Labels: enhancement, gaprindashvili/no, notifications

#4596 Describe better chargeback metric in Rate Editor
  app/controllers/chargeback_controller.rb
  app/views/chargeback/_cb_rate_edit_table.html.haml
  app/views/chargeback/_cb_rate_show.html.haml
Labels: cloud intel/chargeback, enhancement

#4599 Update 'About Modal' plugin section styling
  app/assets/stylesheets/about_modal_background.scss
  app/views/layouts/_about_modal.html.haml
Labels: enhancement, formatting/styling, gaprindashvili/no, ux/approved

#4589 Fix error flash messages when creating tasks
  app/controllers/cloud_network_controller.rb
  app/controllers/cloud_subnet_controller.rb
  app/controllers/cloud_tenant_controller.rb
  app/controllers/cloud_volume_backup_controller.rb
  app/controllers/floating_ip_controller.rb
  app/controllers/host_aggregate_controller.rb
  app/controllers/mixins/actions/vm_actions/rename.rb
  app/controllers/network_router_controller.rb
  app/controllers/physical_server_controller.rb
  app/controllers/security_group_controller.rb
  app/controllers/vm_remote.rb
  spec/controllers/mixins/actions/vm_actions/rename_spec.rb
Labels: bug, compute/cloud, gaprindashvili/no

#4606 Login with Service Unavailable - show a flash message instead of generic error popup
  app/assets/javascripts/miq_application.js
  app/javascript/http_api/api.js
Labels: bug, cloud intel/dashboard, fine/yes, gaprindashvili/yes

#4590 Update open_nodes when creating new element
  app/controllers/miq_ae_class_controller.rb
Labels: automation/automate, bug, gaprindashvili/no

#4572 Fix duplicate in tree after class deletion in miq_ae_class_controller
  app/controllers/miq_ae_class_controller.rb
Labels: automation/automate, bug, gaprindashvili/yes

#4605 Disable volume backup create and restore button when not supported
  app/helpers/application_helper/button/cloud_volume_backup_create.rb
  app/helpers/application_helper/button/cloud_volume_backup_restore.rb
  app/helpers/application_helper/toolbar/cloud_volumes_center.rb
Labels: bug, gaprindashvili/no, storage

#4601 Replaced obsolete method for record fetching with RBAC in container_common_mixin
  app/controllers/mixins/containers_common_mixin.rb
  spec/controllers/container_image_controller_spec.rb
Labels: rbac, refactoring

#4592 Convert all pf-select directives to miq-select
  app/assets/javascripts/angular_modules/module_alerts_center.js
  app/assets/javascripts/components/ansible-credential-options.js
  app/views/ansible_credential/_credential_form.html.haml
  app/views/ansible_repository/_repository_form.html.haml
  app/views/auth_key_pair_cloud/_form.html.haml
  app/views/catalog/_st_angular_form.html.haml
  app/views/cloud_object_store_container/new.html.haml
  app/views/cloud_tenant/new.html.haml
  app/views/cloud_volume/_common_new_edit.html.haml
  app/views/cloud_volume/backup_select.html.haml
  app/views/cloud_volume/detach.html.haml
  app/views/ems_container/ad_hoc/_chart_view_form.html.haml
  app/views/ems_container/ad_hoc/_list_view_form.html.haml
  app/views/flavor/_flavor_form.html.haml
  app/views/floating_ip/_common_new_edit.html.haml
  app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
  app/views/miq_ae_class/_angular_inputs_form.html.haml
  app/views/network_router/_common_new_edit.haml
  app/views/security_group/_fw_rules.haml
  app/views/security_group/new.html.haml
  app/views/shared/views/_retire.html.haml
  app/views/shared/views/_show_alerts_most_recent.html.haml
  app/views/shared/views/_show_alerts_overview.html.haml
  app/views/static/ae_resolve_options/ae-resolve-options-component.html.haml
  app/views/static/cloud_network/cloud-network-form.html.haml
  app/views/static/cloud_subnet/cloud-subnet-form.html.haml
  app/views/static/cloud_volume_backup/volume_select.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-create-vms.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-general.html.haml
  app/views/static/edit_alert_dialog.html.haml
  app/views/static/generic_object/generic_object_table.html.haml
  app/views/static/generic_object/main_custom_button_form.html.haml
  app/views/static/miq-request-options.html.haml
  app/views/static/vm_cloud/add_security_group.html.haml
  app/views/static/vm_cloud/remove_security_group.html.haml
  app/views/vm_common/_reconfigure.html.haml
Labels: refactoring

#4376 [RFE] Allow to upload and display a custom brand image on login/header
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/upload.rb
  app/views/dashboard/login.html.haml
  app/views/layouts/_header.html.haml
  app/views/ops/_settings_custom_logos_tab.html.haml
  config/routes.rb
Labels: enhancement, fine/yes, gaprindashvili/yes

#4610 [FINE] NetworkRouter: Fix button support for create
  app/helpers/application_helper/button/network_router_new.rb
Labels: bug, networks

#4598 Replaced obsolete method for record fetching with RBAC in application controller
  app/controllers/application_controller.rb
Labels: refactoring

#4608 CloudVolumeController: fix rubocop warnings
  app/controllers/cloud_volume_controller.rb
Labels: technical debt

#4607 CloudVolumeBackupController: fix rubocop warning
  app/controllers/cloud_volume_backup_controller.rb
Labels: technical debt

#4597 Fix rubocop warning in CloudTenantController
  app/controllers/cloud_tenant_controller.rb
Labels: technical debt

#4591 CloudSubnetController: fix rubocop warnings
  app/controllers/cloud_subnet_controller.rb
Labels: technical debt

#4600 [FINE] Lazy load StorageManagers upon volume creation
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/views/cloud_volume/attach.html.haml
  app/views/cloud_volume/backup_new.html.haml
  app/views/cloud_volume/backup_select.html.haml
  app/views/cloud_volume/detach.html.haml
  app/views/cloud_volume/edit.html.haml
  app/views/cloud_volume/new.html.haml
  app/views/cloud_volume/snapshot_new.html.haml
Labels: blocker, bug, storage

#4613 bower to npm: moment*
  app/assets/javascripts/application.js
  app/javascript/packs/globals.js
  bower.json
  package.json
Labels: dependencies

#4614 Alerts - fix bug when severity null
  app/assets/javascripts/services/alerts_center_service.js
Labels: bug, monitor

#4620 bower to npm - jquery-ujs & jquery.observe_field
  app/assets/javascripts/application.js
  app/javascript/packs/globals.js
  bower.json
  package.json
Labels: dependencies

#4618 bower to npm - jasmine-jquery
  bower.json
  package.json
  spec/javascripts/support/jasmine.yml
Labels: dependencies

#4612 bower: remove QS
  app/assets/javascripts/application.js
  app/assets/javascripts/miq_application.js
  bower.json
Labels: dependencies

#4622 global pack - move angular, and all npm angular modules to the globals pack
  app/assets/javascripts/application.js
  app/assets/javascripts/miq_angular_application.js
  app/javascript/packs/globals.js
Labels: dependencies

#4617 bower to npm: jquery ui
  app/assets/javascripts/application.js
  app/javascript/packs/globals.js
  bower.json
  package.json
Labels: dependencies

#4625 Do not include UiServiceMixin in services where it is not being used
  app/services/container_project_dashboard_service.rb
  app/services/ems_dashboard_service.rb
  app/services/ems_physical_infra_dashboard_service.rb
  app/services/hawkular_proxy_service.rb
Labels: gaprindashvili/no, technical debt

#4621 Fixed Schedules accordion swapping logic.
  app/assets/javascripts/miq_explorer.js
  app/controllers/report_controller.rb
  app/controllers/report_controller/schedules.rb
  spec/controllers/report_controller/schedules_spec.rb
Labels: blocker, bug, cloud intel/reporting, gaprindashvili/no

#4587 Fix rubocop warnings in ChargebackController
  app/controllers/chargeback_controller.rb
Labels: technical debt

#4579 Fix rubocop warnings in ReportController::Widgets
  app/controllers/report_controller/widgets.rb
Labels: gaprindashvili/no, technical debt

#4626 bower to npm - codemirror & angular-ui-codemirror
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/javascript/packs/globals.js
  bower.json
  config/initializers/assets.rb
  package.json
Labels: dependencies

#4593 Fix physical infra topology tree building algorithm
  app/services/physical_infra_topology_service.rb
Labels: compute/physical infrastructure, refactoring

#4585 CatalogController: fix rubocop warnings
  app/controllers/catalog_controller.rb
Labels: technical debt

#4624 Use fonticon + background for data collection in textual summaries
  app/helpers/textual_mixins/textual_data_collection_state.rb
Labels: gaprindashvili/no, technical debt

#4637 Fixed a typo in parameter name
  app/controllers/application_controller/filter/expression.rb
Labels: bug, expressions/filters, gaprindashvili/yes

#4627 Fix jquery-ui includes
  app/javascript/packs/globals.js
  app/views/vm_common/console_webmks.html.haml
  config/initializers/assets.rb
Labels: dependencies

#4594 Allow nesting physical chassis
  app/services/physical_infra_topology_service.rb
  spec/services/physical_infra_topology_service_spec.rb
Labels: compute/physical infrastructure, enhancement

#4640 bower to npm: angular-dragdrop & angular-ui-sortable
  app/assets/javascripts/application.js
  app/javascript/packs/globals.js
  bower.json
  package.json
Labels: dependencies

#4642 bower to npm - patternfly-bootstrap-treeview
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/javascript/packs/globals.js
  bower.json
  package.json
Labels: dependencies

#4535 Showing Location LED state for physical chassis
  app/helpers/physical_chassis_helper/textual_summary.rb
  app/helpers/physical_server_helper/textual_summary.rb
  product/views/PhysicalChassis.yaml
  product/views/PhysicalServer.yaml
  spec/helpers/physical_chassis_helper/textual_summary_spec.rb
Labels: compute/physical infrastructure, enhancement

#4650 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#4646 Enable selectpicker on all dropdowns when editing a custom button
  app/views/shared/buttons/_ab_options_form.html.haml
Labels: automation/automate, bug, gaprindashvili/no, graphics

#4647 Fixing Physical Network Port page
  app/controllers/physical_network_port_controller.rb
Labels: bug, compute/physical infrastructure, gaprindashvili/no

#4649 Make filters saved in Templates & Images screen displayed in accordion
  app/controllers/application_controller/advanced_search.rb
Labels: bug, expressions/filters, gaprindashvili/yes

#4651 Do not invoke view details callback on notifications without links
  app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
  app/views/static/notification_drawer/notification-body.html.haml
Labels: bug, gaprindashvili/no, notifications

#4645 Fix applying filter from Advanced Search in My Services
  app/controllers/application_controller/advanced_search.rb
Labels: bug, gaprindashvili/yes, services

#4638 Fix ems_cloud description textual summary
  app/helpers/ems_cloud_helper/textual_summary.rb
  spec/helpers/ems_cloud_helper/textual_summary_spec.rb
  spec/shared/helpers/textual_summary_helper_methods.rb
Labels: bug, compute/cloud, gaprindashvili/yes

#4653 Do not show tooltip on listicons in GTLs when they're not clickable
  app/controllers/application_controller.rb
Labels: bug, gaprindashvili/no, gtls

#4630 Rely on decorators for topologies and dashboards instead of UiServiceMixin
  app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js
  app/decorators/tag_decorator.rb
  app/services/container_dashboard_service.rb
  app/services/topology_service.rb
  app/services/ui_service_mixin.rb
  spec/services/container_dashboard_service_spec.rb
Labels: gaprindashvili/no, graphics, technical debt

#4628 Queue operations for pglogical replication set-up
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: enhancement, settings

#4662 Add React textual summary for PXE images
  app/views/pxe/_pxe_server_details.html.haml
Labels: bug, gaprindashvili/no

#4667 angular.validators - work around nodeValidator=={}
  app/javascript/packs/globals.js
  package.json
Labels: dependencies

#4664 ApplicationController::Automate: fix rubocop warnings
  app/controllers/application_controller/automate.rb
Labels: technical debt

#4663 AdvancedSearch: fix rubocop warnings
  app/controllers/application_controller/advanced_search.rb
Labels: technical debt

#4657 ContainerNodeController: fix rubocop warning
  app/controllers/container_node_controller.rb
Labels: technical debt

#4656 ContainerDashboardController: fix rubocop warning
  app/controllers/container_dashboard_controller.rb
Labels: technical debt

#4636 Additional fixes for rubocop warnings
  app/controllers/alert_controller.rb
  app/controllers/alerts_list_controller.rb
  app/controllers/alerts_most_recent_controller.rb
  app/controllers/alerts_overview_controller.rb
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/controllers/auth_key_pair_cloud_controller.rb
Labels: technical debt

#4669 Use existing Zone not 'default' for MiqServer.my_zone or in request
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/application_controller/performance_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/mixins/actions/vm_actions/rename_spec.rb
  spec/controllers/pxe_controller_spec.rb
  spec/views/shared/views/ems_common/_show.html.haml_spec.rb
Labels: test

#4633 Worker Settings: save memory threshold as an integer
  app/controllers/ops_controller/settings/common.rb
Labels: blocker, bug, gaprindashvili/yes, settings

#4462 Converted vmCloudEvacuateForm to component
  app/assets/javascripts/components/vm_cloud/vm_cloud_evacuate_form.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_evacuate_form_controller.js
  app/views/static/evacuate-form.html.haml
  app/views/vm_common/_evacuate.html.haml
  spec/javascripts/components/vm_cloud/vm_cloud_evacuate_form_spec.js
  spec/javascripts/controllers/vm_cloud/vm_cloud_evacuate_form_controller_spec.js
Labels: angular dialogs, gaprindashvili/no, refactoring

#4506 [GAPRINDASHVILI] Update json catalogs for gaprindashvili update release
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
Labels: blocker, internationalization

#4659 Fixed some inconsistencies on provider dashboards.
  app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js
  app/controllers/container_dashboard_controller.rb
  app/services/container_dashboard_service.rb
  app/services/ems_dashboard_service.rb
  app/views/container_dashboard/show.html.haml
  app/views/static/pf_charts/aggregate-status-card.html.haml
Labels: bug, dashboards, gaprindashvili/yes

#4670 angular.validators - update and remove imports-loader workaround
  app/assets/javascripts/miq_angular_application.js
  app/javascript/packs/globals.js
  package.json
Labels: dependencies

#4644 Replaced obsolete RBAC test while removing automate instances
  app/controllers/miq_ae_class_controller.rb
Labels: technical debt

#4668 Display Provider dropdown while creating Orchestration Catalog Item
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
  spec/views/catalog/_form.html.haml_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes, services

#4673 Kubeclient::Client stops at :discover
  spec/controllers/ems_container_controller_spec.rb
Labels: test

#4675 Fixed to show 0 Provider in aggregate status card
  app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js
Labels: bug, dashboards, gaprindashvili/yes

#4654 Add specs related to Adv Search and filters saved in Templates & Images screen
  spec/controllers/application_controller/advanced_search_spec.rb
Labels: gaprindashvili/yes, test

#4674 Encrypt replication subscription's password before queuing save operation
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: bug, settings, technical debt

#4634 Fix duplicate infra_networking_spec files and merge them together
  spec/controllers/infra_network_controller_spec.rb
  spec/controllers/infra_networking_controller_spec.rb
Labels: gaprindashvili/no, refactoring, test

#4603 Fix toolbar buttons for Hosts displayed thru Host Aggregate's details page
  app/controllers/ems_common.rb
  app/controllers/host_aggregate_controller.rb
  spec/controllers/host_aggregate_controller_spec.rb
Labels: bug, compute/infrastructure, gaprindashvili/yes

#4239 Makes get_task_args a bit more readable
  app/controllers/mixins/ems_common_angular.rb
Labels: compute/cloud, technical debt

#4678 Use fa-archive as an icon indicating archived machine state
  app/assets/images/svg/currentstate-archived.svg
  app/helpers/quadicon_helper.rb
  app/presenters/tree_builder_archived.rb
  app/presenters/tree_node/vm_or_template.rb
  spec/presenters/tree_builder_archived_spec.rb
  spec/presenters/tree_builder_images_spec.rb
  spec/presenters/tree_builder_instances_spec.rb
  spec/presenters/tree_node/vm_or_template_spec.rb
Labels: gaprindashvili/no, graphics, gtls

#4211 Add sysprep support for ovirt
  app/services/customize_fields_visibility_service.rb
  app/views/miq_request/_prov_field.html.haml
  app/views/shared/views/_prov_dialog.html.haml
  spec/services/customize_fields_visibility_service_spec.rb
Labels: compute/infrastructure, enhancement

#4681 Fix adding a new Service Catalog Item
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#4692 Fix the view details link on notifications that were retrieved via API
  app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
  app/views/static/notification_drawer/notification-body.html.haml
Labels: bug, gaprindashvili/no

#4693 [GAPRINDASHVILI] Fix spec failures
  spec/controllers/miq_report_controller/dashboards_spec.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: bug/sporadic test failure, test

#4003 Add links to networks and subnets for infra nodes
  app/controllers/host_controller.rb
  app/helpers/host_helper/textual_summary.rb
  app/views/host/show.html.haml
  spec/helpers/host_helper/textual_summary_spec.rb
Labels: compute/infrastructure, enhancement, wip

#4641 bower to npm - angular-patternfly & dependencies
  app/assets/javascripts/application.js
  app/assets/javascripts/miq_angular_application.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/pdf/_fontawesome.scss
  app/javascript/packs/globals.js
  bower.json
  config/webpack/loaders.js
  package.json
  spec/javascripts/globals_pack_spec.js
Labels: dependencies

#4604 Replaced obsolete method for record fetching with RBAC in ci_processing
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/checked_id_mixin.rb
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/cloud_network_controller_spec.rb
  spec/controllers/cloud_object_store_container_spec.rb
  spec/controllers/cloud_object_store_object_spec.rb
  spec/controllers/network_router_controller_spec.rb
Labels: rbac, technical debt

#4702 [GAPRINDASHVILI] Update ui-components to 1.0.35 for gaprindashvili
  bower.json
Labels: dependencies

#4616 Use the new powerstate icons in treeview for VMs
  app/assets/stylesheets/patternfly_overrides.scss
  app/presenters/tree_builder_genealogy.rb
  app/presenters/tree_builder_network.rb
  app/presenters/tree_node/assigned_server_role.rb
  app/presenters/tree_node/hash.rb
  app/presenters/tree_node/node.rb
  app/presenters/tree_node/vm_or_template.rb
  package.json
  spec/presenters/tree_builder_genealogy_spec.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
Labels: gaprindashvili/no, graphics, hammer/yes

#4708 Fixed code to get tests to pass
  app/controllers/application_controller/ci_processing.rb
Labels: bug/sporadic test failure, hammer/yes, storage

#4691 [GAPRINDASHVILI] Fix open url
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/controllers/application_controller/buttons.rb
  app/services/dialog_local_service.rb
  app/views/shared/dialogs/_dialog_provision.html.haml
  app/views/shared/dialogs/_dialog_user.html.haml
  config/routes.rb
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
  spec/services/dialog_local_service_spec.rb
Labels: automation/automate, blocker, bug

#4707 Delete obsolete power state images
  app/assets/images/svg/currentstate-connecting.svg
  app/assets/images/svg/currentstate-disconnected.svg
  app/assets/images/svg/currentstate-image_locked.svg
  app/assets/images/svg/currentstate-install_failed.svg
  app/assets/images/svg/currentstate-maintenance.svg
  app/assets/images/svg/currentstate-migrating.svg
  app/assets/images/svg/currentstate-never.svg
  app/assets/images/svg/currentstate-non_operational.svg
  app/assets/images/svg/currentstate-not_responding.svg
  app/assets/images/svg/currentstate-off.svg
  app/assets/images/svg/currentstate-on.svg
  app/assets/images/svg/currentstate-orphaned.svg
  app/assets/images/svg/currentstate-paused.svg
  app/assets/images/svg/currentstate-powering-down.svg
  app/assets/images/svg/currentstate-powering-up.svg
  app/assets/images/svg/currentstate-powering_down.svg
  app/assets/images/svg/currentstate-powering_up.svg
  app/assets/images/svg/currentstate-preparing_for_maintenance.svg
  app/assets/images/svg/currentstate-reboot_in_progress.svg
  app/assets/images/svg/currentstate-retired.svg
  app/assets/images/svg/currentstate-shelved.svg
  app/assets/images/svg/currentstate-shelved_offloaded.svg
  app/assets/images/svg/currentstate-standby.svg
  app/assets/images/svg/currentstate-suspended.svg
  app/assets/images/svg/currentstate-template.svg
  app/assets/images/svg/currentstate-terminated.svg
  app/assets/images/svg/currentstate-unknown.svg
  app/assets/images/svg/currentstate-wait_for_launch.svg
Labels: gaprindashvili/no, graphics, hammer/yes

#4699 Fixed code to check for correct RBAC feature when adding/editing report
  app/controllers/report_controller/reports/editor.rb
  spec/controllers/miq_report_controller/reports/editor_spec.rb
Labels: bug, cloud intel/reporting, gaprindashvili/yes

#4712 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation

#4704 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation
