Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-05, with the labels that each got.

#3880 [GAPRINDASHVILI] Update ui-components to 1.0.26 for gaprindashvili
  bower-locker.bower.json
  bower.json
Labels: dependencies

#3836 Remove memory chart for Amazon Availability Zones
  app/controllers/application_controller/performance.rb
Labels: bug, charts

#3870 Change @edit[:new][:timer_typ] to @edit[:new][:timer].typ
  app/views/report/_schedule_form_timer.html.haml
Labels: bug, cloud intel/reporting, darga/yes, euwe/yes, fine/yes, gaprindashvili/yes

#3830 Add support for displaying storage device details
  app/controllers/physical_server_controller.rb
  app/helpers/physical_server_helper/textual_summary.rb
  app/views/physical_server/show.html.haml
  spec/controllers/physical_server_controller_spec.rb
Labels: compute/physical infrastructure

#3829 remove unused pngs
  app/assets/images/100/customization_template.png
  app/assets/images/100/customizationtemplate.png
  app/assets/images/100/discover.png
  app/assets/images/100/drift.png
  app/assets/images/100/element.png
  app/assets/images/100/event_logs.png
  app/assets/images/100/firewallrule.png
  app/assets/images/100/fixnum.png
  app/assets/images/100/genealogy.png
  app/assets/images/100/hash.png
  app/assets/images/100/key.png
  app/assets/images/100/last-heartbeat.png
  app/assets/images/100/miq_alert.png
  app/assets/images/100/miq_alert_profile.png
  app/assets/images/100/miq_condition.png
  app/assets/images/100/miq_event_definition.png
  app/helpers/textual_summary_helper.rb
Labels: cleanup, gaprindashvili/no, graphics

#3875 Add missing single_quad definitions for models displayed under Services
  app/decorators/orchestration_template_decorator.rb
  app/decorators/service_decorator.rb
  app/decorators/service_template_ansible_tower_decorator.rb
  app/decorators/service_template_catalog_decorator.rb
  app/decorators/service_template_decorator.rb
Labels: bug, gaprindashvili/no, graphics

#3869 Dashboard controller style fixes.
  app/controllers/dashboard_controller.rb
Labels: dashboards, gaprindashvili/no, technical debt

#3882 Validate Help->Documentation screen against the documentation feature
  app/controllers/support_controller.rb
Labels: bug, fine/yes, gaprindashvili/yes

#3873 Split flash, navbar and listnav related bits off ApplicationHelper
  app/helpers/application_helper.rb
  app/helpers/application_helper/flash.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/navbar.rb
Labels: gaprindashvili/no, technical debt

#3859 Remove unnecessary code around the quadicon rendering on drift screens
  app/views/layouts/listnav/_compare_sections.html.haml
Labels: compute/cloud, gaprindashvili/no

#3867 Policy controller style fixes.
  app/controllers/miq_policy_controller.rb
Labels: gaprindashvili/no, technical debt

#3903 Remove ancient code that was able to set multiple tree sizes
  app/controllers/application_controller.rb
  app/helpers/application_helper/toolbar_builder.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/configuration_helper/configuration_view_helper.rb
  spec/controllers/vm_cloud_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: cleanup, gaprindashvili/no

#3878 bug 1570570: cloud volume create fixes
  app/controllers/cloud_volume_controller.rb
  app/views/cloud_volume/_common_new_edit.html.haml
Labels: blocker, bug, compute/cloud, gaprindashvili/yes

#3199 Showing authentication status in Physical Provider list
  product/views/ManageIQ_Providers_PhysicalInfraManager.yaml
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#3881 Disable Look up Group for Amazon, Database and External with SAML
  app/views/ops/_rbac_group_details.html.haml
  spec/views/ops/_rbac_group_details.html.haml_spec.rb
Labels: bug, euwe/yes, fine/yes, gaprindashvili/yes, settings

#3607 Generalized case statement so it responds to the method change in the core
  app/controllers/application_controller/ci_processing.rb
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: bug, compute/cloud, gaprindashvili/no

#3835 Timeprofile copy fix
  app/assets/javascripts/controllers/configuration/time_profile_form_controller.js
  app/controllers/configuration_controller.rb
  app/views/configuration/_timeprofile_form.html.haml
  spec/javascripts/controllers/configuration/time_profile_form_controller_spec.js
Labels: angular dialogs, bug, euwe/yes, fine/yes, gaprindashvili/yes

#3893 Fix Dialog's API call for Datastore
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: automation/automate, bug, gaprindashvili/yes

#3902 remove unused images from toolbar folder
  app/assets/images/toolbars/and.png
  app/assets/images/toolbars/not.png
  app/assets/images/toolbars/or.png
  app/assets/images/toolbars/tree-large.png
  app/assets/images/toolbars/tree-small.png
  app/assets/images/toolbars/tree_large.png
  app/assets/images/toolbars/tree_small.png
Labels: cleanup, gaprindashvili/no, graphics

#3744 Adapting the Network Devices page to the new ports relationship
  app/controllers/guest_device_controller.rb
  app/helpers/guest_device_helper/textual_summary.rb
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#3913 Pass correct credential parameters depending on the credential type
  app/controllers/mixins/ems_common_angular.rb
  spec/controllers/mixins/ems_common_angular_spec.rb
Labels: bug, compute/cloud, compute/infrastructure, gaprindashvili/yes

#3294 Implementing change password view
  app/assets/javascripts/components/physical_infrastructures/change-password-component.js
  app/controllers/ems_common.rb
  app/controllers/ems_physical_infra_controller.rb
  app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
  app/views/ems_physical_infra/change_password.html.haml
  app/views/static/ems_physical_infra/change_password.html.haml
  config/routes.rb
  spec/javascripts/components/physical_infrastructures/change-password-component_spec.js
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#3896 Fix Ansible Tower Service Catalog new item creation
  app/controllers/catalog_controller.rb
Labels: bug, fine/yes, gaprindashvili/yes, services

#3898 Delete unnecessary line of the code in column lists haml
  app/views/shared/buttons/_column_lists.html.haml
Labels: formatting/styling, gaprindashvili/no, technical debt

#3813 Chart tooltips should match table
  app/assets/javascripts/miq_application.js
Labels: blocker, bug, charts, gaprindashvili/yes

#3796 Replaced deprecated function
  app/controllers/network_router_controller.rb
  spec/controllers/network_router_controller_spec.rb
Labels: rbac, refactoring

#3906 Customization dialogs: style fixes.
  app/controllers/miq_ae_customization_controller/dialogs.rb
Labels: automation/automate, gaprindashvili/no, technical debt

#3920 Discover: do no pass flash in params. Fix style.
  app/controllers/mixins/actions/host_actions/discover.rb
Labels: compute/infrastructure, gaprindashvili/no, technical debt

#3924 [Changelog] Update for Sprint 85
  CHANGELOG.md
Labels: documentation

#3923 Consistency on toolbar buttons for physical server list page
  app/helpers/application_helper/toolbar/physical_servers_center.rb
Labels: bug, compute/physical infrastructure, gaprindashvili/no

#3922 Replace old methods by new in catalog controller
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: rbac, refactoring

#3888 Floating ip controller
  app/controllers/floating_ip_controller.rb
  spec/controllers/floating_ip_controller_spec.rb
Labels: networks, refactoring

#3891 Refactoring method in ops_rbac.rb to use new RBAC call
  app/controllers/ops_controller/ops_rbac.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: rbac, refactoring

#3887 Refactoring provision method to use new rbac call
  app/controllers/physical_server_controller.rb
  spec/controllers/physical_server_controller_spec.rb
Labels: compute/physical infrastructure, refactoring

#3927 BZ1504209: Add backup create/restore to volume list actions
  app/helpers/application_helper/toolbar/cloud_volumes_center.rb
Labels: bug, gaprindashvili/yes, storage

#3914 Add missing gettext into MiqAeCustomizationController
  app/controllers/miq_ae_customization_controller/dialogs.rb
Labels: automation/automate, gaprindashvili/no, internationalization

#3931 Added React component factory.
  app/javascript/miq-component/helpers.js
  app/javascript/packs/component-definitions-common.js
Labels: enhancement, gaprindashvili/no, javascript infrastructure

#3900 Display what is being edited in the report menu editor
  app/controllers/report_controller.rb
Labels: bug, cloud intel/reporting, gaprindashvili/yes

#3930 [FINE] - Follow up fix to address another condition
  app/controllers/miq_ae_customization_controller/dialogs.rb
Labels: blocker, bug, old dialogs

#3937 Ask Codeclimate to not complain about duplication in decorators
  .codeclimate.yml
Labels: developer

#3935 Wrap type-based tooltips in quadicons with ui_lookup
  app/decorators/ext_management_system_decorator.rb
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/physical_server_decorator.rb
  app/decorators/vm_or_template_decorator.rb
Labels: gaprindashvili/no, gtls, internationalization

#3932 Configuration controller style fixes.
  app/controllers/configuration_controller.rb
Labels: configuration management, gaprindashvili/no, technical debt

#3933 Render the correct toolbar for the infra networking switches
  app/controllers/infra_networking_controller.rb
  spec/controllers/infra_networking_controller_spec.rb
Labels: bug, compute/infrastructure, gaprindashvili/no

#3934 Compare: style fixes.
  app/controllers/application_controller/compare.rb
Labels: compute/infrastructure, gaprindashvili/no, technical debt

#3936 Update patternfly to version 3.46
  manageiq-ui-classic.gemspec
Labels: dependencies

#3916 OpsRbac - specs for user add/edit
  spec/controllers/ops_controller/ops_rbac_user_spec.rb
  spec/support/ops_user_helper.rb
Labels: gaprindashvili/yes, settings, test

#3940 Add an extra .remote-console class on the remote console footer
  app/assets/stylesheets/remote_console.scss
  app/views/shared/_remote_console_footer.haml
Labels: formatting/styling, gaprindashvili/no

#3735 [GAPRINDASHVILI] Check @record has description method before using provider_region row
  app/helpers/ems_cloud_helper/textual_summary.rb
  app/helpers/ems_network_helper/textual_summary.rb
Labels: blocker, bug, compute/cloud, networks

#3926 Selection of a dialog is required for a playbook catalog item
  app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: automation/ansible, blocker, bug, gaprindashvili/yes

#3938 Change text color to blue for different columns when displaying Drift for VM
  app/controllers/application_controller/compare.rb
Labels: compute/infrastructure, enhancement, gaprindashvili/no

#3871 Add view selector to Block/Object Storage Managers
  app/helpers/application_helper.rb
Labels: bug, gaprindashvili/yes, storage

#3868 Call rubocop -a on code that I am maintaining
  app/decorators/filesystem_decorator.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_ae_class.rb
  app/presenters/tree_builder_automate_inline_method.rb
  app/presenters/tree_builder_automate_simulation_results.rb
  app/presenters/tree_builder_belongs_to_vat.rb
  app/presenters/tree_builder_catalog_items.rb
  app/presenters/tree_builder_catalogs_class.rb
  app/presenters/tree_builder_chargeback_assignments.rb
  app/presenters/tree_builder_chargeback_rates.rb
  app/presenters/tree_builder_chargeback_reports.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_compliance_history.rb
  app/presenters/tree_builder_configuration_manager.rb
  app/presenters/tree_builder_datacenter.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_diagnostics.rb
  app/presenters/tree_builder_images.rb
  app/presenters/tree_builder_instances.rb
  app/presenters/tree_builder_iso_datastores.rb
  app/presenters/tree_builder_menu_roles.rb
  app/presenters/tree_builder_orchestration_templates.rb
  app/presenters/tree_builder_policy.rb
  app/presenters/tree_builder_policy_profile.rb
  app/presenters/tree_builder_policy_simulation.rb
  app/presenters/tree_builder_protect.rb
  app/presenters/tree_builder_provisioning_dialogs.rb
  app/presenters/tree_builder_pxe_customization_templates.rb
  app/presenters/tree_builder_pxe_servers.rb
  app/presenters/tree_builder_region.rb
  app/presenters/tree_builder_report_dashboards.rb
  app/presenters/tree_builder_report_export.rb
  app/presenters/tree_builder_report_reports.rb
  app/presenters/tree_builder_report_saved_reports.rb
  app/presenters/tree_builder_report_widgets.rb
  app/presenters/tree_builder_sections.rb
  app/presenters/tree_builder_snapshots.rb
  app/presenters/tree_builder_storage_pod.rb
  app/presenters/tree_builder_tags.rb
  app/presenters/tree_builder_timelines.rb
  app/presenters/tree_builder_utilization.rb
  app/presenters/tree_builder_vandt.rb
  app/presenters/tree_builder_vat.rb
  app/presenters/tree_builder_vms_and_templates.rb
  app/presenters/tree_node/compliance.rb
  app/presenters/tree_node/compliance_detail.rb
  app/presenters/tree_node/hash.rb
  app/presenters/tree_node/miq_ae_namespace.rb
  app/presenters/tree_node/miq_policy.rb
  app/presenters/tree_node/miq_report_result.rb
  app/presenters/tree_node/miq_scsi_target.rb
  app/presenters/tree_node/node.rb
Labels: technical debt, trees

#3791 tag mapping UI: Hardcode arbirtrary values instead of "computing"
  app/controllers/ops_controller/settings/label_tag_mapping.rb
Labels: refactoring

#3699 Adding physical switches list and summary pages
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/controllers/ems_common.rb
  app/controllers/physical_switch_controller.rb
  app/decorators/physical_switch_decorator.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/toolbar/physical_switch_center.rb
  app/helpers/application_helper/toolbar/physical_switches_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_physical_infra_helper/textual_summary.rb
  app/helpers/physical_switch_helper.rb
  app/helpers/physical_switch_helper/textual_summary.rb
  app/helpers/quadicon_helper.rb
  app/presenters/menu/default_menu.rb
  app/services/ui_service_mixin.rb
  app/views/configuration/_ui_1.html.haml
  app/views/layouts/listnav/_physical_switch.html.haml
  app/views/physical_switch/show.html.haml
  app/views/physical_switch/show_list.html.haml
  config/routes.rb
  product/views/PhysicalSwitch.yaml
  spec/controllers/physical_switch_controller_spec.rb
Labels: dependencies

#3947 Change text for columns when displaying Compare for VMs/Templates/Hosts
  app/controllers/application_controller/compare.rb
Labels: bug, formatting/styling, gaprindashvili/no

#3884 Rbac refactoring - Report controller schedules
  app/controllers/report_controller/schedules.rb
  spec/controllers/report_controller/schedules_spec.rb
Labels: gaprindashvili/no, rbac, refactoring

#3885 refactoring methods in catalog_controller_spec.rb
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: gaprindashvili/no, refactoring, services, test

#3948 Add spec tests to check rendered toolbars on Block/Object Storage Managers
  spec/controllers/ems_block_storage_controller_spec.rb
  spec/controllers/ems_object_storage_controller_spec.rb
Labels: gaprindashvili/yes, test

#3797 Fix selecting ALL filter and changing it to default on Physical Infra
  app/controllers/application_controller/filter.rb
Labels: bug, gaprindashvili/yes

#3925 Made "Advanced" tab visible for all Server nodes.
  app/controllers/ops_controller/settings/common.rb
  app/views/ops/_all_tabs.html.haml
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: enhancement, gaprindashvili/no, settings

#3957 Allow downloading of AuthKeyPair private keys if they are available
  app/controllers/auth_key_pair_cloud_controller.rb
  app/helpers/application_helper/button/auth_key_pair_cloud_download.rb
  app/helpers/application_helper/toolbar/auth_key_pair_cloud_center.rb
  config/routes.rb
  spec/helpers/application_helper/buttons/auth_key_pair_cloud_download_spec.rb
Labels: bug, compute/cloud, enhancement, gaprindashvili/no

#3952 Remove :match_via_decendants for ConfiguredSystem::ConfiguredSystem
  app/controllers/automation_manager_controller.rb
  app/controllers/provider_foreman_controller.rb
  app/presenters/tree_builder_automation_manager_providers.rb
  app/presenters/tree_builder_configuration_manager.rb
Labels: bug, euwe/yes, fine/yes, gaprindashvili/yes, rbac

#3965 page_title - don't require leading ": " in @page_title
  app/helpers/application_helper/title.rb
  app/views/layouts/login.html.haml
  spec/helpers/application_helper/title_spec.rb
Labels: enhancement, gaprindashvili/yes

#3959 Update spec tests to check rendered toolbars on Block/Object Storage Managers
  spec/controllers/ems_block_storage_controller_spec.rb
  spec/controllers/ems_object_storage_controller_spec.rb
Labels: gaprindashvili/yes, test

#3966 Fix alignment of quadicon in Compare View
  app/assets/stylesheets/patternfly_overrides.scss
  app/views/shared/_compare_header_expanded.html.haml
Labels: bug, formatting/styling, gaprindashvili/no

#3945 Utilize a new 'miq-select' directive for dialog fields
  app/assets/javascripts/miq_angular_application.js
Labels: angular dialogs, bug, gaprindashvili/yes

#3978 http - send cookie
  app/javascript/http_api/http.js
Labels: transformation

#3962 Add Search to Currencies' drop down when adding/editing Chargeback Rate
  app/views/chargeback/_cb_rate_edit.html.haml
Labels: cloud intel/chargeback, enhancement

#3826 Display browser local time in retirement form
  app/assets/javascripts/controllers/retirement/retirement_form_controller.js
  app/assets/javascripts/directives/datetimepicker.js
Labels: bug, gaprindashvili/yes, services

#3423 Make view selector of All Generic Objects page work
  app/controllers/service_controller.rb
Labels: bug, gaprindashvili/yes

#3615 Hide "Hide Deprecated" checkbox and remove "Deprecated" column when provisioning infra VM
  app/controllers/application_controller/miq_request_methods.rb
  app/views/miq_request/_pre_prov.html.haml
  app/views/miq_request/_pre_prov_images.html.haml
  app/views/miq_request/_prov_vm_grid.html.haml
Labels: bug, compute/infrastructure, gaprindashvili/yes

#3721 Fix opening incorrect tag page, opened for Ansible Playbooks navigated through Repository summary page
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_playbook_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/helpers/application_helper/toolbar_chooser.rb
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_playbook_controller_spec.rb
  spec/controllers/ansible_repository_controller_spec.rb
  spec/helpers/application_helper/toolbar_chooser_spec.rb
Labels: bug, gaprindashvili/yes, tagging

#3899 Add ability to search through the available fields while editing report
  app/views/report/_column_lists.html.haml
Labels: cloud intel/reporting, enhancement, gaprindashvili/no, ux/approved

#3654 Fix displaying services after applying a filter (2)
  app/controllers/service_controller.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, expressions/filters, gaprindashvili/yes, services

#3980 Restrict quadicon class demodulization for Physical* records only
  app/helpers/quadicon_helper.rb
  spec/helpers/quadicon_helper_spec.rb
Labels: bug, gaprindashvili/no, gtls

#3985 Replace ff-template with pficon-template
  app/decorators/container_template_decorator.rb
  app/decorators/customization_template_decorator.rb
  app/decorators/manageiq/providers/ansible_tower/automation_manager/configuration_script_decorator.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/orchestration_template_decorator.rb
  app/decorators/service_resource_decorator.rb
  app/helpers/orchestration_stack_helper/textual_summary.rb
  app/helpers/quadicon_helper.rb
  app/helpers/service_helper/textual_summary.rb
  app/helpers/vm_helper/textual_summary.rb
  app/presenters/tree_builder_genealogy.rb
  app/presenters/tree_builder_orchestration_templates.rb
  app/presenters/tree_node/configuration_script_base.rb
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/catalog/_svccat_tree_show.html.haml
  spec/presenters/tree_node/configuration_script_base_spec.rb
  spec/presenters/tree_node/customization_template_spec.rb
  spec/presenters/tree_node/orchestration_template_spec.rb
  spec/presenters/tree_node/service_resource_spec.rb
Labels: enhancement, gaprindashvili/no, graphics

#3917 Use update_attributes for saving a user's groups
  app/controllers/ops_controller/ops_rbac.rb
  spec/controllers/ops_controller/ops_rbac_user_spec.rb
Labels: bug, gaprindashvili/yes, settings

#3854 Support VM Reconfigure for VMware vCloud provider
  app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
  app/views/vm_common/_reconfigure.html.haml
  spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js
Labels: enhancement, gaprindashvili/yes

#3905 Removing listnav duplicate code
  app/helpers/application_helper/listnav.rb
Labels: gaprindashvili/no, menus, refactoring

#3989 Remove compliances include from Host.yaml
  product/views/Host.yaml
Labels: blocker, bug, fine/yes, gaprindashvili/yes

#3964 Fix Categories order for Reporting charts
  lib/report_formatter/chart_common.rb
Labels: blocker, bug, charts, fine/yes, gaprindashvili/yes

#3991 [Changelog] Update for Sprint 86
  CHANGELOG.md
Labels: documentation

#3988 Error modal - ensure visibility over other modals
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, gaprindashvili/yes, transformation

#3974 Fix Save button which wasn't responding while editing Chargeback Rate
  app/controllers/chargeback_controller.rb
Labels: bug, cloud intel/chargeback

#3995 Display Cloud Tenants relation at Network Manager
  app/helpers/ems_network_helper/textual_summary.rb
Labels: enhancement

#3080 Add Scrutinizer code quality badge.
  README.md
Labels: developer, gaprindashvili/no

#3997 Remove gemnasium link from the README.md as it got discontinued
  README.md
Labels: developer

#3996 Remove summary_only conditions from controllers as it is unused
  app/controllers/mixins/generic_show_mixin.rb
  app/controllers/mixins/vm_show_mixin.rb
  app/controllers/vm_common.rb
Labels: cleanup, gaprindashvili/no

#4000 Remove redundant SummaryViewRestful toolbar
  app/helpers/application_helper/toolbar/summary_view_restful.rb
  app/helpers/application_helper/toolbar_chooser.rb
Labels: cleanup, gaprindashvili/no, toolbars

#3831 Add reporting session threshold options for logging
  app/controllers/application_controller/session_size.rb
Labels: developer, fine/yes, gaprindashvili/yes

#3971 Do not override kubevirt token with default token
  app/controllers/mixins/ems_common_angular.rb
Labels: bug, compute/containers

#3364 Report data cleanup
  app/controllers/application_controller.rb
  app/controllers/ems_physical_infra_controller.rb
  spec/controllers/report_controller/schedules_spec.rb
Labels: gaprindashvili/no, gtls, technical debt

#3972 Network adapter reconfiguration for vCloud provider
  app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/views/vm_common/_reconfigure.html.haml
Labels: enhancement, gaprindashvili/yes

#3992 Display port group for VM instances
  app/helpers/textual_mixins/textual_devices.rb
  spec/helpers/textual_mixins/textual_devices_spec.rb
Labels: compute/infrastructure, enhancement, gaprindashvili/no

#4009 Fix textual summary display in tenants.
  app/views/ops/_rbac_tenant_details.html.haml
Labels: bug, gaprindashvili/no, settings

#4006 bz 1570570: Fix typo in earlier commit
  app/views/cloud_volume/_common_new_edit.html.haml
Labels: bug, gaprindashvili/yes, storage

#4011 Remove dead code related to Tenant
  app/controllers/ops_controller/ops_rbac.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: bug, gaprindashvili/yes, technical debt, test

#3967 Ability to see/save Config settings for Region and Zone records.
  app/controllers/ops_controller/settings/common.rb
  app/helpers/ops_helper.rb
  app/views/ops/_all_tabs.html.haml
  app/views/ops/_settings_advanced_tab.html.haml
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: enhancement, gaprindashvili/no, settings

#4010 Render notifications fetched from the API in the correct order
  app/assets/javascripts/services/event_notifications_service.js
Labels: bug, fine/yes, gaprindashvili/yes

#4016 Add the VMWare Virtual Ethernet Card model type to the VM summary
  app/helpers/textual_mixins/textual_devices.rb
  spec/helpers/textual_mixins/textual_devices_spec.rb
Labels: compute/infrastructure, enhancement, gaprindashvili/no
