Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-06, with the labels that each got.

#4018 String & gettext fixes in advanced tab warning
  app/helpers/ops_helper.rb
  app/views/ops/_settings_advanced_tab.html.haml
Labels: internationalization, settings, technical debt

#4015 Display number of containers on the top right quad of container prov
  app/decorators/manageiq/providers/container_manager_decorator.rb
Labels: compute/containers, gaprindashvili/no, gtls

#4023 Use with_groups instead of with_current_user_groups
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
Labels: bug, gaprindashvili/yes, rbac, test

#4005 [GAPRINDASHVILI] API transformRequest support + http service
  app/assets/javascripts/miq_api.js
Labels: blocker, transformation

#3660 Generalizing methods for button operation handling
  app/controllers/application_controller/ci_processing.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/generic_feature_button.rb
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb
Labels: button actions, pending core, technical debt

#4021 Fix wrongly displayed policy shield on container & cloud provider quads
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
Labels: bug, compute/cloud, compute/containers, gaprindashvili/no, gtls

#4024 Do not inherit physical infra decorator from ems decorator
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
Labels: cleanup

#4025 Add a separate decorator for Network Providers
  app/decorators/manageiq/providers/network_manager_decorator.rb
Labels: bug, gaprindashvili/no, gtls, networks

#4020 [FINE] Ensure dropdown gets selectpicker refreshed after values set
  app/assets/javascripts/dialog_field_refresh.js
  spec/javascripts/dialog_field_refresh_spec.js
Labels: blocker, bug

#4029 Delete redundant openshift/kubernetes provider decorators
  app/decorators/manageiq/providers/kubernetes/container_manager_decorator.rb
  app/decorators/manageiq/providers/openshift/container_manager_decorator.rb
Labels: cleanup, gaprindashvili/no, gtls

#4008 OPS: server settings cleanup
  app/controllers/ops_controller/settings/common.rb
  app/helpers/ops_helper.rb
  app/views/ops/_settings_server_tab.html.haml
Labels: gaprindashvili/no, technical debt

#3953 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: dependencies

#3999 Setting different colors for physical infra components on topology view
  app/assets/stylesheets/application.css
  app/assets/stylesheets/physical_infra_topology.scss
Labels: compute/physical infrastructure, ux/review

#4028 Rename VmOrTemplateDecorator to VmDecorator
  app/decorators/vm_decorator.rb
Labels: cleanup, gaprindashvili/no, gtls

#4031 Fix parent ems links in textual summaries.
  app/helpers/cloud_network_helper/textual_summary.rb
  app/helpers/ems_network_helper/textual_summary.rb
  app/helpers/floating_ip_helper/textual_summary.rb
  app/helpers/load_balancer_helper/textual_summary.rb
  app/helpers/network_port_helper/textual_summary.rb
  app/helpers/security_group_helper/textual_summary.rb
Labels: bug, gaprindashvili/no, textual summaries

#3977 Reload classifications when adding or editing the tag expression for groups
  app/views/layouts/exp_atom/_edit_tags.html.haml
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: bug, gaprindashvili/yes, settings

#4033 InfraManagerDecorator should not inherit from EMS decorator
  app/decorators/manageiq/providers/infra_manager_decorator.rb
Labels: cleanup, compute/infrastructure, gaprindashvili/no, gtls

#4002 Use pficon-unknown fonticon for unknown Operating Systems in quads
  app/decorators/miq_template_decorator.rb
  app/decorators/vm_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: enhancement

#3958 Add a new "Endpoint URL" field in AWS endpoints
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/mixins/ems_common_angular.rb
  app/views/layouts/angular-bootstrap/_endpoints_for_url.html.haml
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/mixins/ems_common_angular_spec.rb
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Labels: compute/cloud, enhancement, gaprindashvili/no

#4042 Drop fileicon for NetworkSwitchDecorator
  app/decorators/switch_decorator.rb
Labels: graphics, networks, technical debt

#4041 Drop fileicon for ServiceResourceDecorator
  app/decorators/service_resource_decorator.rb
Labels: gaprindashvili/no, graphics, services, technical debt

#4026 Make quadicons consistent and working for Block & Object Storage Providers
  app/assets/images/svg/vendor-cinder.svg
  app/assets/images/svg/vendor-swift.svg
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/decorators/manageiq/providers/storage_manager_decorator.rb
  app/helpers/quadicon_helper.rb
  app/views/configuration/_ui_1.html.haml
Labels: gaprindashvili/no, graphics, gtls, settings, storage, technical debt

#4039 Drop unnecessary fonticon from ConfigurationProfileDecorator
  app/decorators/configuration_profile_decorator.rb
Labels: configuration management, gaprindashvili/no, graphics, technical debt

#3983 Add support for ssh key pair credentials to rhv
  app/assets/javascripts/controllers/ems_keypair/ems_keypair_controller.js
  app/controllers/mixins/ems_common_angular.rb
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  spec/controllers/ems_infra_controller_spec.rb
  spec/javascripts/controllers/ems_keypair/ems_keypair_controller_spec.js
Labels: blocker, compute/infrastructure, gaprindashvili/yes

#4040 Do not use generic object fileicon if no picture specified
  app/decorators/generic_object_decorator.rb
Labels: gaprindashvili/no, generic objects

#4038 Drop the fileicon in ConfiguredSystemDecorator
  app/decorators/configured_system_decorator.rb
Labels: configuration management, gaprindashvili/no, graphics, technical debt

#4036 dialogUser spec - fix sporadic spec failures
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
Labels: bug/sporadic test failure, test

#4044 fix deprecated passing class to AR notification
  app/presenters/tree_builder_vms_and_templates.rb
Labels: bug, compute/infrastructure, gaprindashvili/no

#4030 Remove the quadicon definition from the ExtManagementSystemDecorator
  app/decorators/ext_management_system_decorator.rb
Labels: cleanup, gaprindashvili/no, gtls

#4050 Drop fileicon for ansible jobs
  app/decorators/manageiq/providers/ansible_tower/automation_manager/job_decorator.rb
Labels: gaprindashvili/no, graphics

#4049 Drop fileicon for configuration script decorator
  app/decorators/manageiq/providers/ansible_tower/automation_manager/configuration_script_decorator.rb
Labels: gaprindashvili/no, graphics

#4047 Drop fileicon for LanDecorator
  app/decorators/lan_decorator.rb
Labels: gaprindashvili/no, graphics

#4053 Remove fileicon from InventoryGroupDecorators
  app/decorators/manageiq/providers/automation_manager/inventory_group_decorator.rb
  app/decorators/manageiq/providers/automation_manager/inventory_root_group_decorator.rb
Labels: gaprindashvili/no, graphics

#4037 Removing obsolete method for cluster button action handling
  app/controllers/application_controller/ci_processing.rb
Labels: button actions, refactoring

#4052 Drop fileicon from authentication decorators
  app/decorators/manageiq/providers/automation_manager/authentication_decorator.rb
  app/decorators/manageiq/providers/embedded_automation_manager/authentication_decorator.rb
Labels: gaprindashvili/no, graphics

#4063 Force selectpicker refresh after dialog-user component initialization
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/assets/javascripts/services/miq_service.js
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
  spec/javascripts/services/miq_service_spec.js
Labels: angular dialogs, blocker, bug, gaprindashvili/yes

#4046 Add missing single_quad definition for ConfiguredSystemDecorator
  app/decorators/configured_system_decorator.rb
Labels: bug, configuration management, gaprindashvili/no, gtls

#4055 Pull out policy shield icon to a constant and replace with fonticon
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/network_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
  app/decorators/manageiq/providers/storage_manager_decorator.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/physical_server_decorator.rb
  app/decorators/vm_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, graphics, refactoring

#4064 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#4056 Do not expose unnecessary QuadiconHelper methods as singleton methods
  app/helpers/quadicon_helper.rb
Labels: cleanup, gaprindashvili/no, gtls

#4058 Remove angular2+ webpack workaround
  config/webpack/shared.js
Labels: developer, gaprindashvili/no

#4054 Pull out health_state from physical infra decorators to the helper
  app/decorators/physical_server_decorator.rb
  app/decorators/physical_switch_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: compute/physical infrastructure, gaprindashvili/no, refactoring

#4067 Add single_quad definition for configuration profiles
  app/decorators/configuration_profile_decorator.rb
Labels: configuration management, gaprindashvili/no

#3912 Add Redfish provider creation dialog
  app/assets/images/svg/vendor-redfish.svg
  app/assets/images/svg/vendor-redfish_ph_infra.svg
  app/controllers/ems_common.rb
  app/controllers/mixins/ems_common_angular.rb
  app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: graphics, ux/approved

#4059 [GAPRINDASHVILI] Backport Webpack related changes
  .babelrc
  .eslintrc.json
  config/webpack/configuration.js
  config/webpack/loaders.js
  config/webpack/loaders/angular.js
  config/webpack/loaders/assets.js
  config/webpack/loaders/babel.js
  config/webpack/loaders/coffee.js
  config/webpack/loaders/erb.js
  config/webpack/loaders/sass.js
  config/webpack/shared.js
  config/webpacker.yml
  package.json
  yarn.lock
Labels: blocker, transformation

#4071 [GAPRINDASHVILI] Rake task changes for update:ui
  lib/tasks/manageiq/ui_tasks.rake
  tools/ci/setup_js_env.sh
Labels: blocker, developer, transformation

#4075 Replace orchestration-stack.png with its icon in textual summaries
  app/helpers/service_helper/textual_summary.rb
Labels: gaprindashvili/no, graphics, refactoring, textual summaries

#4074 Replace miq_request.png with pficon-unknown in MiqProvisionDecorator
  app/decorators/miq_provision_decorator.rb
Labels: gaprindashvili/no, graphics, refactoring

#4022 Display providers' suspended status in their quadicon
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/network_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
  app/decorators/manageiq/providers/storage_manager_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, gtls

#3979 Hide "Add New Network Manager" unless Nuage is enabled
  app/helpers/application_helper/button/ems_network.rb
  spec/helpers/application_helper/toolbar/ems_networks_center_spec.rb
Labels: bug, enhancement, gaprindashvili/yes

#4080 Add patternfly-react in ui-classic
  package.json
Labels: dependencies, gaprindashvili/no

#4088 Use fonticons instead of fileicons in the RegistryItemDecorator
  app/decorators/registry_item_decorator.rb
  manageiq-ui-classic.gemspec
Labels: dependencies, gaprindashvili/no, graphics

#4089 Don't use generic object definition fileicon if no picture present
  app/decorators/generic_object_definition_decorator.rb
Labels: gaprindashvili/no, graphics

#4073 Do not try to prepend TreeNode images with 100/
  app/presenters/tree_node/node.rb
Labels: cleanup, gaprindashvili/no, trees

#4093 Use fonticon for the warning in catalog edit provision confirm modal
  app/views/catalog/_confirmation_modal.html.haml
Labels: gaprindashvili/no, graphics

#4092 Replace q.png with vendor-redhat.svg in the automate simulation tree
  app/presenters/tree_builder_automate_simulation_results.rb
  spec/presenters/tree_builder_automate_simulation_results_spec.rb
Labels: gaprindashvili/no, graphics

#4079 Delete all code that's related to the old dialog editor
  app/assets/javascripts/miq_application.js
  app/assets/javascripts/miq_tree.js
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/miq_ae_customization_controller/dialogs.rb
  app/controllers/mixins/sandbox.rb
  app/helpers/application_helper/button/dialog.rb
  app/helpers/application_helper/button/dialog_add_box.rb
  app/helpers/application_helper/button/dialog_add_element.rb
  app/helpers/application_helper/button/dialog_add_tab.rb
  app/helpers/application_helper/button/dialog_res_discard.rb
  app/helpers/application_helper/button/dialog_resource_remove.rb
  app/helpers/application_helper/dialogs.rb
  app/helpers/application_helper/toolbar/dialog_center.rb
  app/views/miq_ae_customization/_dialog_details.html.haml
  app/views/miq_ae_customization/_dialog_edit_tree.html.haml
  app/views/miq_ae_customization/_dialog_field_form.html.haml
  app/views/miq_ae_customization/_dialog_field_form_dynamic_options.html.haml
  app/views/miq_ae_customization/_dialog_field_form_non_dynamic_options.html.haml
  app/views/miq_ae_customization/_dialog_field_form_overridable_dynamic_options.html.haml
  app/views/miq_ae_customization/_dialog_form.html.haml
  app/views/miq_ae_customization/_dialog_group_form.html.haml
  app/views/miq_ae_customization/_dialog_info_form.html.haml
  app/views/miq_ae_customization/_dialog_res_remove.html.haml
  app/views/miq_ae_customization/_dialog_resource.html.haml
  app/views/miq_ae_customization/_dialog_resources.html.haml
  app/views/miq_ae_customization/_dialog_tab_form.html.haml
  app/views/miq_ae_customization/_field_value_entry.html.haml
  app/views/miq_ae_customization/_field_values.html.haml
  config/routes.rb
  spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
  spec/controllers/miq_ae_customization_controller_spec.rb
  spec/helpers/application_helper/buttons/dialog_add_box_spec.rb
  spec/helpers/application_helper/buttons/dialog_add_element_spec.rb
  spec/helpers/application_helper/buttons/dialog_add_tab_spec.rb
  spec/helpers/application_helper/buttons/dialog_res_discard_spec.rb
  spec/helpers/application_helper/buttons/dialog_resource_remove_spec.rb
  spec/helpers/application_helper/buttons/dialog_spec.rb
  spec/helpers/application_helper/dialogs_spec.rb
  spec/javascripts/miq_application_spec.js
  spec/routing/miq_ae_customization_routing_spec.rb
  spec/views/miq_ae_customization/_dialog_res_remove.html.haml_spec.rb
  spec/views/miq_ae_customization/_dialog_resource.html.haml_spec.rb
Labels: cleanup, gaprindashvili/no

#4099 Remove unused compliance_img singleton method from QuadiconHelper
  app/helpers/quadicon_helper.rb
Labels: cleanup, gaprindashvili/no

#3993 Use {report,request}_admin_user?
  app/controllers/application_controller.rb
  app/controllers/application_controller/current_user.rb
  app/controllers/chargeback_controller.rb
  app/controllers/configuration_controller.rb
  app/controllers/report_controller.rb
  app/controllers/report_controller/menus.rb
  app/controllers/report_controller/saved_reports.rb
  app/helpers/application_helper/button/miq_request_delete.rb
  app/presenters/tree_builder_report_saved_reports.rb
  app/views/layouts/_adv_search_body.html.haml
  app/views/layouts/_adv_search_footer.html.haml
  spec/controllers/report_controller/widget_spec.rb
  spec/helpers/application_helper/buttons/miq_request_delete_spec.rb
Labels: bug, enhancement

#4072 Make sure @edit[:current].config[:server][:zone] is set
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: bug, gaprindashvili/no, settings

#4082 Fix Request Info for Catalog Items
  app/controllers/miq_request_controller.rb
Labels: bug, gaprindashvili/no, services

#4095 Clean up SASS rules for icon customizations
  app/assets/stylesheets/icon_customizations.scss
Labels: cleanup, gaprindashvili/no

#4098 Convert health state and provider status quadrant icons to fonticons
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, graphics

#3998 Use browser's native printing dialog when exporting summaries to PDF
  app/assets/stylesheets/pdf/_summary.scss
  app/assets/stylesheets/pdf_summary.css
  app/assets/stylesheets/pdf_summary.scss
  app/controllers/application_controller/report_downloads.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/toolbar/dashboard_summary_toggle_view.rb
  app/helpers/application_helper/toolbar/summary_view.rb
  app/helpers/application_helper/toolbar/x_summary_view.rb
  app/views/layouts/show_pdf.html.haml
  config/initializers/assets.rb
  spec/controllers/application_controller/report_downloads_spec.rb
Labels: documentation, enhancement, gaprindashvili/no, textual summaries

#3954 Fixing Provider PhysicalSwitches page summary show
  app/helpers/application_helper.rb
  app/helpers/ems_physical_infra_helper/textual_summary.rb
  app/views/layouts/listnav/_ems_physical_infra.html.haml
Labels: compute/physical infrastructure

#4106 Fix js spec related to widgets
  package.json
Labels: dependencies, test

#4057 Prefix all angular-bootstrap directives with uib-
  app/assets/javascripts/services/alerts_center_service.js
  app/views/cloud_topology/show.html.haml
  app/views/container_topology/show.html.haml
  app/views/infra_topology/show.html.haml
  app/views/layouts/_tabs.html.haml
  app/views/network_topology/show.html.haml
  app/views/physical_infra_topology/show.html.haml
  app/views/shared/views/_alerts_list.html.haml
  app/views/shared/views/_show_alerts_overview.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-existing-vms.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-no-provider.html.haml
  app/views/static/notification_drawer/notification-body.html.haml
  app/views/static/wizard.html.haml
Labels: angular dialogs, gaprindashvili/no, technical debt

#4085 TextualSummary: unify power stated.
  app/helpers/host_helper/textual_summary.rb
  app/helpers/physical_server_helper/textual_summary.rb
  app/helpers/physical_switch_helper/textual_summary.rb
  app/helpers/textual_mixins/textual_power_state.rb
  app/helpers/vm_cloud_helper/textual_summary.rb
  app/helpers/vm_helper/textual_summary.rb
Labels: enhancement, gaprindashvili/no, textual summaries, ux/approved

#4077 Render predefined piecharts using pure CSS instead of PNGs
  app/assets/images/100/piecharts/compare/0.png
  app/assets/images/100/piecharts/compare/1.png
  app/assets/images/100/piecharts/compare/10.png
  app/assets/images/100/piecharts/compare/11.png
  app/assets/images/100/piecharts/compare/12.png
  app/assets/images/100/piecharts/compare/13.png
  app/assets/images/100/piecharts/compare/14.png
  app/assets/images/100/piecharts/compare/15.png
  app/assets/images/100/piecharts/compare/16.png
  app/assets/images/100/piecharts/compare/17.png
  app/assets/images/100/piecharts/compare/18.png
  app/assets/images/100/piecharts/compare/19.png
  app/assets/images/100/piecharts/compare/2.png
  app/assets/images/100/piecharts/compare/20.png
  app/assets/images/100/piecharts/compare/3.png
  app/assets/images/100/piecharts/compare/4.png
  app/assets/images/100/piecharts/compare/5.png
  app/assets/images/100/piecharts/compare/6.png
  app/assets/images/100/piecharts/compare/7.png
  app/assets/images/100/piecharts/compare/8.png
  app/assets/images/100/piecharts/compare/9.png
  app/assets/images/100/piecharts/datastore/0.png
  app/assets/images/100/piecharts/datastore/1.png
  app/assets/images/100/piecharts/datastore/10.png
  app/assets/images/100/piecharts/datastore/11.png
  app/assets/images/100/piecharts/datastore/12.png
  app/assets/images/100/piecharts/datastore/13.png
  app/assets/images/100/piecharts/datastore/14.png
  app/assets/images/100/piecharts/datastore/15.png
  app/assets/images/100/piecharts/datastore/16.png
  app/assets/images/100/piecharts/datastore/17.png
  app/assets/images/100/piecharts/datastore/18.png
  app/assets/images/100/piecharts/datastore/19.png
  app/assets/images/100/piecharts/datastore/2.png
  app/assets/images/100/piecharts/datastore/20.png
  app/assets/images/100/piecharts/datastore/3.png
  app/assets/images/100/piecharts/datastore/4.png
  app/assets/images/100/piecharts/datastore/5.png
  app/assets/images/100/piecharts/datastore/6.png
  app/assets/images/100/piecharts/datastore/7.png
  app/assets/images/100/piecharts/datastore/8.png
  app/assets/images/100/piecharts/datastore/9.png
  app/assets/stylesheets/application.css
  app/assets/stylesheets/patternfly_overrides.scss
  app/assets/stylesheets/piecharts.scss
  app/controllers/application_controller/compare.rb
  app/decorators/storage_decorator.rb
Labels: gaprindashvili/no, graphics, technical debt

#4108 Fix missing bottom-right fonticons on provider quadicons
  app/helpers/quadicon_helper.rb
Labels: bug, gaprindashvili/no, gtls

#4107 Generalize the printing views/layouts for future reusability
  app/assets/stylesheets/print.scss
  app/controllers/application_controller/report_downloads.rb
  app/views/layouts/print.html.haml
  app/views/layouts/print/textual_summary.html.haml
  app/views/layouts/show_pdf.html.haml
  config/initializers/assets.rb
  spec/controllers/application_controller/report_downloads_spec.rb
Labels: gaprindashvili/no, refactoring, textual summaries

#4110 Fix missing single_quad for container services
  app/decorators/container_service_decorator.rb
Labels: bug, gaprindashvili/no, gtls

#4109 Do not store cockpit popups in session
  app/controllers/container_node_controller.rb
  app/controllers/vm_remote.rb
Labels: bug, consoles, gaprindashvili/yes

#4087 General spec cleanupFix spec user stubbing
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_playbook_controller_spec.rb
  spec/controllers/ansible_repository_controller_spec.rb
  spec/controllers/application_controller/filter/expression_spec.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/cloud_network_controller_spec.rb
  spec/controllers/cloud_subnet_controller_spec.rb
  spec/controllers/cloud_tenant_controller_spec.rb
  spec/controllers/cloud_volume_controller_spec.rb
  spec/controllers/configuration_controller_spec.rb
  spec/controllers/ems_block_storage_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_cluster_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/ems_object_storage_controller_spec.rb
  spec/controllers/ems_physical_infra_controller_spec.rb
  spec/controllers/ems_storage_controller_spec.rb
  spec/controllers/floating_ip_controller_spec.rb
  spec/controllers/generic_object_controller_spec.rb
  spec/controllers/generic_object_definition_controller_spec.rb
  spec/controllers/host_controller_spec.rb
  spec/controllers/infra_networking_controller_spec.rb
  spec/controllers/miq_report_controller/trees_spec.rb
  spec/controllers/miq_request_controller_spec.rb
  spec/controllers/network_router_controller_spec.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
  spec/controllers/ops_controller_spec.rb
  spec/controllers/physical_switch_controller_spec.rb
  spec/controllers/provider_foreman_controller_spec.rb
  spec/controllers/report_controller/schedules_spec.rb
  spec/controllers/resource_pool_controller_spec.rb
  spec/helpers/application_helper/buttons/condition_policy_spec.rb
  spec/helpers/application_helper/buttons/condition_spec.rb
  spec/helpers/application_helper/views_shared_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/presenters/tree_builder_ops_rbac_spec.rb
  spec/shared/controllers/shared_examples_for_cloud_network_controller.rb
  spec/shared/controllers/shared_examples_for_cloud_subnet_controller.rb
  spec/shared/controllers/shared_examples_for_ems_block_storage_controller.rb
  spec/shared/controllers/shared_examples_for_ems_network_controller.rb
  spec/shared/controllers/shared_examples_for_ems_object_storage_controller.rb
  spec/shared/controllers/shared_examples_for_ems_storage_controller.rb
  spec/shared/controllers/shared_examples_for_floating_ip_controller.rb
  spec/shared/controllers/shared_examples_for_load_balancer_controller.rb
  spec/shared/controllers/shared_examples_for_network_port_controller.rb
  spec/shared/controllers/shared_examples_for_network_router_controller.rb
  spec/shared/controllers/shared_examples_for_security_group_controller.rb
Labels: cleanup, test

#4068 Adding Physical Switches to Physical Infra topology page
  app/assets/stylesheets/physical_infra_topology.scss
  app/services/physical_infra_topology_service.rb
  app/services/ui_service_mixin.rb
  app/views/physical_infra_topology/show.html.haml
Labels: compute/physical infrastructure, ux/approved

#4104 Update PatternFly to v3.48.4
  manageiq-ui-classic.gemspec
Labels: dependencies, gaprindashvili/no

#4096 Use fonticons for dialog/widget import status identificaiton
  app/helpers/application_helper/import_export_helper.rb
  app/views/miq_ae_customization/_dialog_import_export.html.haml
  app/views/report/_export_widgets.html.haml
  spec/helpers/application_helper/import_export_helper_spec.rb
Labels: gaprindashvili/no, graphics, technical debt

#4100 Use fonticons and proper tooltips in policy simulation quadrants
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, graphics, technical debt

#3856 Replaced ror form with react form component
  app/controllers/vm_common.rb
  app/helpers/hide_partial_helper.rb
  app/javascript/components/vm-snapshot-form-component.jsx
  app/javascript/packs/component-definitions-common.js
  app/views/vm_common/_snap.html.haml
  package.json
  spec/helpers/hide_partial_helper_spec.rb
Labels: compute/infrastructure, gaprindashvili/no, react

#4125 Add Gluster vendor svg
  app/assets/images/svg/vendor-gluster.svg
Labels: gaprindashvili/no, graphics

#4118 Use fonticons for sorting items on the provisioning form
  app/assets/images/16/sort_down.png
  app/assets/images/16/sort_up.png
  app/views/miq_request/_pre_prov.html.haml
  app/views/miq_request/_prov_configured_system_grid.html.haml
  app/views/miq_request/_prov_ds_grid.html.haml
  app/views/miq_request/_prov_host_grid.html.haml
  app/views/miq_request/_prov_iso_img_grid.html.haml
  app/views/miq_request/_prov_pxe_img_grid.html.haml
  app/views/miq_request/_prov_template_grid.html.haml
  app/views/miq_request/_prov_vc_grid.html.haml
  app/views/miq_request/_prov_vm_grid.html.haml
  app/views/miq_request/_prov_windows_image_grid.html.haml
Labels: gaprindashvili/no, graphics

#4090 Use svg/fonticons for store types in the storage decorator
  app/decorators/storage_decorator.rb
Labels: gaprindashvili/no, graphics, technical debt

#4126 Remove JS calls that operate with the nonexistent #adv_search_img
  app/controllers/application_controller/filter.rb
Labels: cleanup, gaprindashvili/no

#4114 Client-side print/export to PDF for dashboard widgets
  app/assets/stylesheets/print.scss
  app/controllers/application_controller/report_downloads.rb
  app/presenters/widget_presenter.rb
  app/views/layouts/print/report.html.haml
Labels: cloud intel/dashboard, enhancement, gaprindashvili/no

#4121 Updated PR#3889 refactoring RBAC in Security Group controller
  app/controllers/security_group_controller.rb
  spec/controllers/security_group_controller_spec.rb
Labels: rbac, refactoring

#3889 RBAC refactor - security_group_controller
  app/controllers/security_group_controller.rb
  spec/controllers/security_group_controller_spec.rb
Labels: rbac, refactoring

#4129 Use fonticons for embedded items in automate and catalogs
  app/views/catalog/_form_resources_info.html.haml
  app/views/miq_ae_class/_class_fields.html.haml
  app/views/miq_ae_class/_inputs.html.haml
Labels: gaprindashvili/no, graphics

#4120 Remove unnecessary ref to 16/blue-circle.png from report timelines
  app/controllers/report_controller/reports.rb
Labels: gaprindashvili/no, graphics

#4091 Remove Discovered IP Address field from Physical Infra Provider
  app/helpers/ems_physical_infra_helper/textual_summary.rb
  product/views/ManageIQ_Providers_PhysicalInfraManager.yaml
Labels: bug, compute/physical infrastructure, gaprindashvili/no

#4128 Add the missing powering_down quadrant machine state
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, graphics

#4131 Don't get right provider based on position in array
  spec/controllers/automation_manager_controller_spec.rb
Labels: bug, gaprindashvili/yes, test

#4124 Delete all unused PNG files under app/assets/images/16
  app/assets/images/16/blank.png
  app/assets/images/16/blue-circle.png
  app/assets/images/16/checkmark.png
  app/assets/images/16/clear.png
  app/assets/images/16/equal-green.png
  app/assets/images/16/failed.png
  app/assets/images/16/na.png
  app/assets/images/16/notequal-red.png
  app/assets/images/16/notequalgreen.png
  app/assets/images/16/passed.png
  app/assets/images/16/placeholder.png
  app/assets/images/16/zoom-hover.png
  app/assets/images/16/zoom.png
Labels: cleanup, gaprindashvili/no, graphics

#4132 Depend on react-select to fix nested dependencies
  package.json
Labels: bug, dependencies, gaprindashvili/no

#4133 Added missing tooltips for some quadicon quadrants
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/cloud_manager_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/manageiq/providers/infra_manager_decorator.rb
  app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
  app/decorators/storage_decorator.rb
  app/decorators/vm_decorator.rb
Labels: gaprindashvili/no, gtls

#4127 Fix error on default filters page
  app/presenters/tree_builder_default_filters.rb
Labels: bug, gaprindashvili/no, settings

#4034 Refactor quadicon settings logic under My Settings
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/helpers/configuration_helper.rb
  app/helpers/quadicon_helper.rb
  app/views/configuration/_ui_1.html.haml
  spec/helpers/quadicon_helper_spec.rb
Labels: gaprindashvili/no, refactoring

#4076 Removing obsolete method for storage button action handling
  app/controllers/application_controller/ci_processing.rb
  app/controllers/ems_common.rb
  app/controllers/host_controller.rb
  app/controllers/storage_controller.rb
Labels: storage, technical debt

#4097 Use fonticons for host/vm hardware peripherals on the devices screns
  app/decorators/disk_decorator.rb
  app/decorators/guest_device_decorator.rb
  app/helpers/textual_mixins/textual_devices.rb
  app/views/host/_config.html.haml
  app/views/vm_common/_config.html.haml
  manageiq-ui-classic.gemspec
  spec/helpers/textual_mixins/textual_devices_spec.rb
  spec/presenters/tree_node/guest_device_spec.rb
Labels: dependencies, gaprindashvili/no, graphics

#4134 Display cloud subnets in the top-right quadrant of network providers
  app/decorators/manageiq/providers/network_manager_decorator.rb
Labels: gaprindashvili/no, gtls, networks

#4140 Ensure new dialog user component is used for service reconfiguration
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/controllers/service_controller.rb
  app/services/dialog_local_service.rb
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
  spec/services/dialog_local_service_spec.rb
Labels: angular dialogs, blocker, bug, gaprindashvili/yes

#4048 Prefer fonticon for resource pool if it's not vapp
  app/decorators/resource_pool_decorator.rb
Labels: gaprindashvili/no, graphics

#4145 Remove all middleware routes as they're obsolete
  config/routes.rb
Labels: cleanup, gaprindashvili/no, middleware

#4144 Remove unnecessary compare routes
  config/routes.rb
  spec/routing/availability_zone_routing_spec.rb
  spec/routing/cloud_tenant_routing_spec.rb
  spec/routing/ems_cloud_routing_spec.rb
  spec/routing/ems_infra_routing_spec.rb
  spec/routing/ems_physical_infra_routing_spec.rb
  spec/routing/ems_storage_routing_spec.rb
  spec/routing/flavor_routing_spec.rb
  spec/routing/resource_pool_routing_spec.rb
  spec/routing/security_group_routing_spec.rb
  spec/routing/storage_routing_spec.rb
Labels: cleanup, gaprindashvili/no

#4146 Use decorators for icons/images in the compressed compare view
  app/controllers/application_controller/compare.rb
Labels: bug, gaprindashvili/no, graphics

#4152 Get Network adapters reconfigure data only when the reconfigure is supported
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
Labels: blocker, bug, gaprindashvili/yes

#4148 Fixing textual summary payload mount for multilabel components
  app/helpers/textual_multilabel.rb
Labels: bug, gaprindashvili/no, textual summaries

#4139 Add icon for host_failure event.
  app/decorators/miq_event_definition_decorator.rb
Labels: control, enhancement, gaprindashvili/no, graphics

#4151 Remove the PNG image support from the toolbars
  app/assets/images/toolbars/approve.png
  app/assets/images/toolbars/cockpit.png
  app/assets/images/toolbars/commit.png
  app/assets/images/toolbars/delete.png
  app/assets/images/toolbars/discard.png
  app/assets/images/toolbars/edit.png
  app/assets/images/toolbars/export.png
  app/assets/images/toolbars/import.png
  app/assets/images/toolbars/new.png
  app/assets/images/toolbars/order.png
  app/assets/images/toolbars/paste.png
  app/assets/images/toolbars/placeholder.png
  app/assets/images/toolbars/redo.png
  app/assets/images/toolbars/relative_date.png
  app/assets/images/toolbars/remove.png
  app/assets/images/toolbars/specific_date.png
  app/assets/images/toolbars/squashed-false.png
  app/assets/images/toolbars/squashed-true.png
  app/assets/images/toolbars/undo.png
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/physical_switch_center.rb
  app/helpers/application_helper/toolbar/physical_switches_center.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
  app/helpers/application_helper/toolbar_builder.rb
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: cleanup, graphics, toolbars

#4062 Added separate features for Requests subtabs
  app/controllers/application_controller.rb
  app/controllers/miq_request_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/miq_request.rb
  app/helpers/application_helper/button/miq_request_approval.rb
  app/helpers/application_helper/button/miq_request_delete.rb
  app/helpers/application_helper/toolbar/miq_request_center.rb
  app/helpers/application_helper/toolbar/miq_requests_center.rb
  app/presenters/menu/default_menu.rb
  spec/helpers/application_helper/buttons/miq_request_approval_spec.rb
  spec/helpers/application_helper/buttons/miq_request_delete_spec.rb
Labels: enhancement, gaprindashvili/no, requests

#3956 Add to the reconfigure screen the ability to attach ISOs to CDRoms (VMware)
  app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/views/vm_common/_reconfigure.html.haml
  spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js
Labels: enhancement, gaprindashvili/no, requests

#4159 Fix Datastore decorator format string
  app/decorators/storage_decorator.rb
Labels: bug, gaprindashvili/no, storage

#4143 Faster report result index pages
  app/controllers/chargeback_controller.rb
  app/controllers/mixins/saved_report_paging.rb
  app/controllers/report_controller/saved_reports.rb
  app/helpers/application_helper/button/report_download_choice.rb
  app/helpers/application_helper/button/report_only.rb
  spec/controllers/chargeback_controller_spec.rb
  spec/controllers/miq_report_controller/trees_spec.rb
  spec/controllers/report_controller_spec.rb
Labels: cloud intel/chargeback, gaprindashvili/yes

#4156 Fix error on localized worker settings screen
  app/controllers/ops_controller/settings/common.rb
Labels: blocker, bug, gaprindashvili/yes, settings

#4161 [GAPRINDASHVILI] Update ui-components to 1.0.29 for Gaprindashvili
  bower.json
Labels: blocker

#4166 Fix include domain prefix behavior for catalog entrypoint selection
  app/helpers/automate_tree_helper.rb
Labels: blocker, bug, gaprindashvili/yes, services

#4163 Remove unused Ansible Repository page refresh
  app/controllers/ansible_repository_controller.rb
  spec/controllers/ansible_repository_controller_spec.rb
Labels: automation/ansible, technical debt

#4172 Change the paste image with a fonticon in custom button forms
  app/views/shared/buttons/_ab_form.html.haml
Labels: bug, gaprindashvili/no, graphics

#4170 Fixed Automate import domain from git repository to use current user.
  app/services/git_based_domain_import_service.rb
  spec/services/git_based_domain_import_service_spec.rb
Labels: automation/automate, bug, gaprindashvili/yes

#4171 Use fonticons for relative/specific date selection in exp editor
  app/views/layouts/exp_atom/_edit_field.html.haml
  app/views/layouts/exp_atom/_edit_find.html.haml
Labels: bug, gaprindashvili/no, graphics

#4174 Enforce version 2.13.2 of redux-devtools-extension
  package.json
Labels: bug, dependencies

#4130 Use the client-side printing for reports where the PDF was generated synchronously
  app/controllers/application_controller/report_downloads.rb
  app/helpers/application_helper/toolbar/chargeback_center.rb
  app/helpers/application_helper/toolbar/compare_view.rb
  app/helpers/application_helper/toolbar/drift_view.rb
  app/helpers/application_helper/toolbar/gtl_view.rb
  app/helpers/application_helper/toolbar/miq_capacity_view.rb
  app/helpers/application_helper/toolbar/x_gtl_view.rb
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: enhancement, gaprindashvili/no

#4162 Don't allow network manager edit if the network manager doesn't support it
  app/controllers/ems_common.rb
  app/controllers/ems_network_controller.rb
  spec/controllers/ems_common_controller_spec.rb
Labels: bug, gaprindashvili/yes, networks

#4017 Fix to show meaningful policy name when add/delete it in audit.log
  app/controllers/application_controller/ci_processing.rb
  app/controllers/miq_policy_controller.rb
Labels: control, enhancement

#4180 Don't show Add Flavor in sublist view
  app/helpers/application_helper/button/new_flavor.rb
  spec/helpers/application_helper/buttons/new_flavor_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes, toolbars

#4179 Make policy assignment, simulation and tagging quads non-clickable
  app/assets/stylesheets/patternfly_overrides.scss
  app/controllers/application_controller/policy_support.rb
  app/controllers/application_controller/tags.rb
  app/helpers/gtl_helper.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: blocker, bug, gaprindashvili/yes, gtls

#4178 Ensure lodash 3 is available via bower
  bower.json
  lib/manageiq/ui/classic/engine.rb
  manageiq-ui-classic.gemspec
Labels: bug, dependencies, gaprindashvili/no

#4184 [GAPRINDASHVILI] Update ui-components to 1.0.30 for gaprindashvili
  bower-locker.bower.json
  bower.json
Labels: blocker, dependencies

#4084 Adding power operation in physical switch pages
  app/helpers/application_helper/toolbar/physical_switch_center.rb
  app/helpers/application_helper/toolbar/physical_switches_center.rb
  app/javascript/miq_observable.js
  app/javascript/packs/toolbar-actions.js
  app/javascript/toolbar-actions/refresh.js
  app/javascript/toolbar-actions/restart.js
  app/views/physical_switch/show.html.haml
  app/views/physical_switch/show_list.html.haml
Labels: compute/physical infrastructure, enhancement

#4197 Increase maxlength for playbooks' host option field
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: automation/ansible, bug, gaprindashvili/yes

#4177 Don't enforce v2.13.2 of redux-devtools-extension
  package.json
Labels: dependencies, gaprindashvili/no

#4183 Add spec to fail on indirect inheritance of MiqDecorator
  spec/decorators/miq_decorator_spec.rb
Labels: developer, gaprindashvili/no, test

#4182 Fix issues in Reconfigure/Resize
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_resize_form_controller.js
  app/controllers/mixins/actions/vm_actions/resize.rb
  app/views/vm_common/_resize.html.haml
Labels: bug, gaprindashvili/yes

#4205 webpack:paths - always load inflectors
  lib/tasks/manageiq/ui_tasks.rake
Labels: bug, gaprindashvili/yes

#4185 Remove remaining references to toolbar images
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/layouts/_policy_sim.html.haml
  app/views/miq_ae_tools/_import_export.html.haml
  app/views/ops/_diagnostics_savedreports.html.haml
  app/views/ops/_ldap_forest_entries.html.haml
Labels: cleanup, gaprindashvili/no, graphics

#4203 Update patternfly-sass to 3.51.1
  manageiq-ui-classic.gemspec
Labels: dependencies

#4176 @button_group removal
  app/controllers/application_controller/compare.rb
  app/controllers/automation_manager_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/mixins/vm_show_mixin.rb
  app/controllers/provider_foreman_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/toolbar/compare_center.rb
  app/helpers/application_helper/toolbar/infra_networking_center.rb
  app/helpers/application_helper/toolbar/x_miq_template_center.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/helpers/application_helper/toolbar/x_vm_snapshot_center.rb
  app/helpers/application_helper/toolbar/x_vm_vmtree_center.rb
  app/helpers/application_helper/toolbar_builder.rb
  app/helpers/application_helper/toolbar_chooser.rb
  spec/controllers/infra_networking_controller_spec.rb
Labels: technical debt, toolbars

#4204 [GAPRINDASHVILI] Faster report result index pages
  app/controllers/chargeback_controller.rb
  app/controllers/mixins/saved_report_paging.rb
  app/controllers/report_controller/saved_reports.rb
  app/helpers/application_helper/button/report_download_choice.rb
  app/helpers/application_helper/button/report_only.rb
  spec/controllers/chargeback_controller_spec.rb
  spec/controllers/miq_report_controller/trees_spec.rb
  spec/controllers/report_controller_spec.rb
Labels: blocker, cloud intel/chargeback

#4208 [FINE] Faster report result index pages
  app/controllers/application_controller.rb
  app/controllers/chargeback_controller.rb
  app/controllers/report_controller/saved_reports.rb
  app/helpers/application_helper/button/report_download_choice.rb
  app/helpers/application_helper/button/report_only.rb
  spec/controllers/chargeback_controller_spec.rb
  spec/controllers/miq_report_controller/trees_spec.rb
Labels: blocker, cloud intel/chargeback

#4165 Remove dead methods from NumberHelper
  app/helpers/number_helper.rb
  spec/helpers/number_helper_spec.rb
Labels: gaprindashvili/no, technical debt

#4200 Remove the exception to not show listicons in GTLs
  app/controllers/application_controller.rb
Labels: gaprindashvili/no, gtls, refactoring

#4215 update patternfly-react dependency to 2.10.1
  package.json
Labels: dependencies

#4219 [GAPRINDASHVILI] Update ui-components to 1.0.31
  bower.json
Labels: blocker, dependencies

#4045 Add folder dropdown to VM Migrate.
  app/views/miq_request/_prov_vm_migrate_dialog.html.haml
Labels: compute/infrastructure, enhancement, gaprindashvili/no

#4198 Reprioritize icons and images for GTLs, prefer images first
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
Labels: gaprindashvili/no, graphics, gtls

#4227 Fix nonexistent pficon-error-octagon
  app/assets/javascripts/import.js
  app/views/ops/_settings_advanced_tab.html.haml
  spec/javascripts/import_spec.js
Labels: bug, graphics

#4078 Display two new added columns in Openscap rule results page
  product/views/OpenscapRuleResult.yaml
Labels: pending core

#4225 Escape special chars in tooltip & text of TreeBuilder's root
  app/presenters/tree_builder.rb
Labels: blocker, bug, gaprindashvili/yes, trees

#4226 Change reconfigure setup to include values configured with originally
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/assets/javascripts/controllers/dialog_user/dialog_user_reconfigure_controller.js
  app/assets/javascripts/services/dialog_user_submit_error_handler_service.js
  app/controllers/application_controller/dialog_runner.rb
  app/controllers/service_controller.rb
  app/services/dialog_local_service.rb
  app/views/shared/dialogs/_reconfigure_dialog.html.haml
  spec/controllers/service_controller_spec.rb
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
  spec/services/dialog_local_service_spec.rb
Labels: blocker, bug, gaprindashvili/yes, pending core

#4199 Remove all references to the unnecessary listicon instance variable
  app/controllers/application_controller.rb
  app/controllers/application_controller/report_data_additional_options.rb
  app/controllers/automation_manager_controller.rb
  app/controllers/chargeback_controller.rb
  app/controllers/configuration_job_controller.rb
  app/controllers/container_image_controller.rb
  app/controllers/host_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/miq_request_controller.rb
  app/controllers/mixins/explorer_show.rb
  app/controllers/orchestration_stack_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  spec/support/controller_helper.rb
Labels: gaprindashvili/no, gtls, refactoring

#4201 Use the browser's native printing for asynchronously generated saved reports
  app/controllers/application_controller/report_downloads.rb
  app/helpers/application_helper/button/pdf.rb
  app/helpers/application_helper/button/render_report_pdf.rb
  app/helpers/application_helper/toolbar/report_view.rb
  app/views/layouts/print/report.html.haml
  spec/helpers/application_helper/buttons/render_report_pdf_spec.rb
Labels: enhancement, gaprindashvili/no, pending core
