Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-11, with the labels that each got.

#4831 Filter tenants and groups in Access Control by current region
  app/controllers/ops_controller/ops_rbac.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: bug, hammer/yes, settings

#4850 dashboard widget specs - fix codeclimate issues
  app/javascript/spec/dashboards/widget-empty.spec.js
  app/javascript/spec/dashboards/widget-wrapper.spec.js
Labels: technical debt

#4856 No need to load default search when user is on tagging screen.
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes, tagging

#4817 Fix rubocop warnings in InfraNetworkingController
  app/controllers/infra_networking_controller.rb
Labels: technical debt

#4849 Show only servers in current region in Diagnostics
  app/controllers/ops_controller/diagnostics.rb
Labels: bug, hammer/yes, settings

#4846 [HAMMER] Add translations for hammer
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
  locale/es/ManageIQ_UI_Classic.po
  locale/fr/ManageIQ_UI_Classic.po
  locale/ja/ManageIQ_UI_Classic.po
  locale/pt_BR/ManageIQ_UI_Classic.po
  locale/zh_CN/ManageIQ_UI_Classic.po
Labels: internationalization

#4844 GTL - use miqSparkle-style spinner when loading
  app/assets/javascripts/controllers/report_data_controller.js
  app/assets/javascripts/miq_application.js
  app/helpers/gtl_helper.rb
Labels: gaprindashvili/yes, gtls, hammer/yes

#4838 Turn off 'open_url' if the button is to be displayed for a list
  app/controllers/application_controller/buttons.rb
Labels: automation/automate, bug

#4782 Add any product product feature for Customization in menu
  app/presenters/menu/default_menu.rb
  spec/presenters/menu/default_menu_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes, menus

#4861 Fix rubocop warnings in OrchestrationStackController
  app/controllers/orchestration_stack_controller.rb
Labels: technical debt

#4863 Fix rubocop warnings in PlanningController
  app/controllers/planning_controller.rb
Labels: technical debt

#4864 Fix rubocop warnings in ProviderForemanController
  app/controllers/provider_foreman_controller.rb
Labels: technical debt

#4865 Enable Dialog only for "Display for" set to "Single"
  app/controllers/application_controller/buttons.rb
  app/views/shared/buttons/_ab_options_form.html.haml
Labels: automation/automate, bug, hammer/no

#4854 Stop spinner from spinning forever when creating a new key pair
  app/controllers/auth_key_pair_cloud_controller.rb
Labels: bug, compute/cloud, fine/yes, gaprindashvili/yes, hammer/yes

#4803 [GAPRINDASHVILI] Hide disabled tabs
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: blocker, bug, compute/containers

#4872 [GAPRINDASHVILI] Updated spec for setting the server name in the settings form
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: test

#4873 Display Tags info on Job Template summary view.
  app/controllers/mixins/manager_controller_mixin.rb
  app/helpers/automation_manager_helper.rb
  app/views/automation_manager/_configuration_script.html.haml
Labels: automation/ansible tower, bug, hammer/yes

#4875 Fixed to show grouping in drop down only for Ansible Tower type item.
  app/views/catalog/_form_basic_info.html.haml
Labels: blocker, bug, hammer/yes, services

#4877 Replace grapql explorer react mounter with react macro.
  app/assets/stylesheets/graphql_explorer.scss
  app/views/graphql_explorer/index.html.haml
Labels: react, refactoring, technical debt

#4876 [GAPRINDASHVILI] - Made changes to save server name only if it is not blank
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: blocker, bug

#4882 Add getJSONFixture helper to jest config.
  app/javascript/spec/.eslintrc.json
  app/javascript/spec/helpers/getJSONFixtures.js
  config/jest.setup.js
  jest.config.js
Labels: test

#4885 Enabled password editing if log protocol has changed.
  app/assets/javascripts/components/auth-credentials.js
Labels: bug, gaprindashvili/yes, hammer/yes, settings

#4871 [GAPRINDASHVILI] Fix vm_cloud image custom button return and cancel endpoints
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: blocker, bug

#4888 Add babel-polyfill
  config/webpack/shared.js
Labels: bug, hammer/yes, javascript infrastructure

#4891 [Changelog] Update for Sprint 98, H-B2, and G6
  CHANGELOG.md
Labels: documentation

#4887 Corrected logic for rendering custom buttons
  app/helpers/application_helper/toolbar_builder.rb
Labels: bug, button actions, gaprindashvili/yes, hammer/yes, toolbars

#4883 Added missing gettext into Dialog Editor controller
  app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
Labels: internationalization, technical debt

#4899 Replaced missing timeline attributes in performance controller.
  app/controllers/application_controller/performance.rb
Labels: bug, hammer/yes

#4900 Allow apostrophes in custom button names
  app/views/shared/dialogs/_dialog_user.html.haml
Labels: automation/automate, bug, gaprindashvili/yes, hammer/yes

#4837 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation

#4901 Reset session on failed CSRF token verification
  app/controllers/application_controller.rb
Labels: bug, compute/infrastructure, hammer/yes

#4898 Update PatternFly to v3.57
  manageiq-ui-classic.gemspec
Labels: dependencies, hammer/no

#4902 Fixed JS error, bottlenecks timeline does not have group levels.
  app/assets/javascripts/miq_timeline.js
Labels: bug, hammer/yes, timelines

#4881 Fix rubocop warnings in ServiceController
  app/controllers/service_controller.rb
Labels: technical debt

#4879 Fix rubocop warningsin ResourcePoolController
  app/controllers/resource_pool_controller.rb
Labels: hammer/no, technical debt

#4903 Fixed code to show Bottlenecks report download buttons.
  app/controllers/bottlenecks_controller.rb
  app/controllers/planning_controller.rb
  app/helpers/application_helper/button/utilization_download.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/optimize_helper.rb
  app/views/bottlenecks/_bottlenecks_tabs.html.haml
  config/routes.rb
  spec/helpers/application_helper/buttons/utilization_download_spec.rb
  spec/helpers/application_helper/toolbar_chooser_spec.rb
  spec/routing/bottlenecks_routing_spec.rb
Labels: bug, hammer/yes, optimize

#4886 Removed old react mounter.
  app/helpers/reactjs_helper.rb
  app/javascript/packs/application-common.js
  app/javascript/react/componentRegistry.js
  app/javascript/react/mounter.js
  app/javascript/spec/react/compontentRegistry.spec.js
Labels: refactoring, technical debt

#4907 Update react version to 16.6.x.
  package.json
Labels: dependencies

#4893 [GAPRINDASHVILI] - Custom button thru relationships
  app/controllers/application_controller.rb
  app/controllers/application_controller/buttons.rb
  app/controllers/mixins/custom_buttons.rb
  app/helpers/application_helper/toolbar/mixins/custom_button_toolbar_mixin.rb
  app/helpers/application_helper/toolbar_builder.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_container_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/ems_network_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/shared/controllers/shared_example_for_custom_buttons.rb
Labels: blocker, bug, button actions, toolbars

#4925 Fixed reading of ems_refresh_threshold memory_threshold value
  app/views/ops/_settings_workers_tab.html.haml
Labels: bug, gaprindashvili/yes, hammer/yes, settings

#4926 Remove S3 and Swift From List of Log Collection Types
  app/controllers/ops_controller/diagnostics.rb
Labels: bug, hammer/yes, settings

#4919 [GAPRINDASHVILI] Fix editing tags for VMs, Hosts and others
  app/controllers/application_controller/tags.rb
  spec/controllers/application_controller/tags_spec.rb
Labels: blocker, bug, tagging

#4867 Move form buttons reducer to separate file.
  app/javascript/forms/form-buttons-reducer.js
  app/javascript/forms/form-buttons-redux.jsx
  app/javascript/packs/application-common.js
Labels: react, refactoring

#4911 Fix GCE validation
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/mixins/ems_common_angular.rb
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Labels: bug, compute/cloud, hammer/yes

#4892 [GAPRINDASHVILI] Use a valid tab name for the Metrics tab in the Container form
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
Labels: blocker, bug

#4851 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#4914 [HAMMER] Update ui-components to 1.1.18 for hammer
  package.json
  yarn.lock
Labels: dependencies

#4933 Fix compliance travis - save records after changing compliances
  spec/helpers/compliance_summary_helper_spec.rb
Labels: test

#4922 Removed an extra observer from Edit Selected Element type drop down
  app/views/layouts/exp_atom/_editor.html.haml
Labels: bug, expressions/filters, hammer/yes

#4929 Fixed if condition to prevent undefined js error
  app/assets/javascripts/controllers/host/host_form_controller.js
  spec/javascripts/controllers/host/host_form_controller_spec.js
Labels: bug, compute/infrastructure, hammer/yes

#4934 Fixed to enable the download buttons on Utilization Report tab
  app/helpers/application_helper/button/utilization_download.rb
  spec/helpers/application_helper/buttons/utilization_download_spec.rb
Labels: blocker, bug, hammer/yes, optimize

#4874 Rescue error messages when executing retire action
  app/controllers/mixins/actions/vm_actions/retire.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes, services

#4906 Remove allow_message_expectations_on_nil
  spec/helpers/application_helper_spec.rb
Labels: technical debt, test

#4923 Use v_total_vms for HostDecorator
  app/decorators/host_decorator.rb
Labels: compute/infrastructure, hammer/no, performance

#4927 Remove invalid views
  product/views/CimBaseStorageExtent.yaml
  product/views/CimStorageExtent.yaml
  product/views/ManageIQ_Providers_Hawkular_MiddlewareManager_MiddlewareDiagnosticReport.yaml
  product/views/ManageIQ_Providers_MiddlewareManager.yaml
  product/views/SniaLocalFileSystem.yaml
  product/views/StorageManager.yaml
Labels: hammer/yes, technical debt

#4928 Fixed required description for snapshot if vendor is openstack.
  app/javascript/components/vm-snapshot-form-component.jsx
  app/views/vm_common/_snap.html.haml
Labels: bug, compute/cloud, hammer/yes

#4932 Fixed disabled password input.
  app/assets/javascripts/components/auth-credentials.js
Labels: bug, gaprindashvili/yes, hammer/yes, settings

#4935 Rails 5.1: each_with_object was deprecated / removed on params
  app/controllers/mixins/checked_id_mixin.rb
Labels: hammer/no, technical debt

#4937 Rails 5.1: Non-kwargs support in AC::TestCase#post is gone
  spec/controllers/dashboard_controller_spec.rb
Labels: hammer/no, technical debt, test

#4936 Rails 5.1: find using AR::Base instance was deprecated/removed
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
Labels: hammer/no, technical debt

#4939 [GAPRINDASHVILI] Update ui-components to 1.0.37 for gaprindashvili
  bower-locker.bower.json
  bower.json
Labels: dependencies

#4920 fix icon font family class
  app/decorators/miq_action_decorator.rb
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/container_project_view.rb
  app/helpers/application_helper/toolbar/dashboard_summary_toggle_view.rb
  app/helpers/application_helper/toolbar/ems_container_center.rb
  app/helpers/application_helper/toolbar/ems_containers_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
  app/helpers/application_helper/toolbar/physical_server_center.rb
  app/helpers/application_helper/toolbar/stack_orchestration_template_center.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/views/layouts/_header.html.haml
  app/views/layouts/_user_options.html.haml
Labels: bug, hammer/no

#4880 Fix rubocop warnings in SecurityGroupController
  app/controllers/security_group_controller.rb
Labels: hammer/no, technical debt

#4941 Load ui-components for printing with asset pipeline require
  app/assets/stylesheets/print.scss
Labels: bug, graphics, hammer/yes

#4938 Make print button consistent on VM infra and cloud screens
  app/controllers/vm_common.rb
  app/helpers/application_helper/toolbar_chooser.rb
Labels: bug, compute/infrastructure, hammer/yes

#4940 Add missing quadicon definition for generic object definitions
  app/decorators/generic_object_definition_decorator.rb
Labels: blocker, bug, gaprindashvili/yes, generic objects, hammer/yes

#4942 Configuration - notify backend when `quad_truncate` gets changed
  app/views/configuration/_ui_1.html.haml
Labels: blocker, bug, gaprindashvili/no, hammer/yes, settings

#4944 VM CLoud: floating ips to associate must be a list
  app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb
Labels: bug, compute/cloud, gaprindashvili/yes, hammer/yes

#4924 Adds authentication_status to Host.yaml
  product/views/Host.yaml
Labels: enhancement, hammer/no

#4948 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#4946 Add X-UA-Compatible header
  app/views/layouts/application.html.haml
Labels: bug, cloud intel/dashboard, hammer/yes

#4954 Add delete_flavors method to EmsCloudController
  app/controllers/application_controller/ci_processing.rb
  app/controllers/flavor_controller.rb
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: bug, compute/cloud, hammer/yes

#4947 Adds email validation for schedule and alerts forms
  app/controllers/miq_policy_controller/alerts.rb
  app/controllers/report_controller/schedules.rb
  spec/controllers/miq_policy_controller/alerts_spec.rb
Labels: bug, cloud intel/reporting, hammer/yes

#4955 Add a shared example and tests for nested lists under EmsCloudControl…
  spec/controllers/ems_cloud_controller_spec.rb
  spec/shared/controllers/shared_examples_for_nested_lists.rb
Labels: hammer/no, test

#4956 Fixed saving of custom button role visibility
  app/controllers/application_controller/buttons.rb
  spec/controllers/application_controller/buttons_spec.rb
Labels: automation/automate, blocker, bug, hammer/yes

#4957 Remove include pointing in invalid
  product/views/GuestDevice.yaml
  product/views/PhysicalNetworkPort.yaml
  product/views/ServiceTemplate.yaml
Labels: technical debt

#4949 Remove unnecessary styling for backend-generated PDF reports
  app/assets/stylesheets/pdf/_fontawesome.scss
  app/assets/stylesheets/pdf/_patternfly.scss
  app/assets/stylesheets/pdf/_report.scss
  app/assets/stylesheets/pdf_report.css
Labels: cloud intel/reporting, pending core

#4961 EmsInfraController test speed.
  spec/controllers/ems_infra_controller_spec.rb
Labels: hammer/no, test

#4959 EmsCloudController test speed.
  spec/controllers/ems_cloud_controller_spec.rb
Labels: hammer/no, test

#4945 Do not store download_summary_pdf using remember tab
  app/controllers/application_controller.rb
Labels: bug, gaprindashvili/no, hammer/yes

#4964 Spec: Do not call MiqProductFeature.seed - speedup of 1m
  spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
  spec/controllers/ops_controller/ops_rbac_user_spec.rb
Labels: hammer/no, test

#4868 Fix rubocop warnings in PxeController
  app/controllers/pxe_controller.rb
  app/controllers/pxe_controller/iso_datastores.rb
  app/controllers/pxe_controller/pxe_customization_templates.rb
  app/controllers/pxe_controller/pxe_servers.rb
Labels: gaprindashvili/no, hammer/no, technical debt

#4968 Remove unnecessary before(:all) call from a button spec
  spec/helpers/application_helper/buttons/iso_datastore_new_spec.rb
Labels: technical debt, test

#4976 Restful redirect: test speedup by not seeding all dialogs.
  spec/requests/restful_redirect_spec.rb
Labels: hammer/no, test

#4878 Fix rubocop warnings in report controller
  app/controllers/report_controller.rb
  app/controllers/report_controller/dashboards.rb
  app/controllers/report_controller/menus.rb
  app/controllers/report_controller/reports.rb
  app/controllers/report_controller/reports/editor.rb
  app/controllers/report_controller/saved_reports.rb
  app/controllers/report_controller/schedules.rb
Labels: technical debt

#4974 Speedup OpsController spec by removing MiqProductFeature.seed.
  app/presenters/tree_builder_ops_rbac_features.rb
  spec/controllers/ops_controller_spec.rb
Labels: hammer/no, test

#4973 Timeline spec speedup
  lib/report_formatter/timeline.rb
  spec/lib/report_formater/timeline_spec.rb
Labels: hammer/no, test

#4952 Don't translate audit messages
  app/controllers/ems_common_helper.rb
  app/controllers/ops_controller.rb
Labels: bug, hammer/yes, settings

#4969 Increase caching timeout for travis to speed up env setup
  .travis.yml
Labels: hammer/no, test

#4819 Fix rubocop warnings in MiqAeCustomization controller
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/miq_ae_customization_controller/custom_buttons.rb
  app/controllers/miq_ae_customization_controller/dialogs.rb
  app/controllers/miq_ae_customization_controller/old_dialogs.rb
Labels: technical debt

#4827 Fix rubocop warnings in MiqPolicyController
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_controller/alert_profiles.rb
  app/controllers/miq_policy_controller/alerts.rb
  app/controllers/miq_policy_controller/conditions.rb
  app/controllers/miq_policy_controller/events.rb
  app/controllers/miq_policy_controller/miq_actions.rb
  app/controllers/miq_policy_controller/policies.rb
  app/controllers/miq_policy_controller/policy_profiles.rb
  app/controllers/miq_policy_controller/rsop.rb
Labels: technical debt

#4975 AnsibleRepositoryController: speed up tests.
  spec/controllers/ansible_repository_controller_spec.rb
Labels: hammer/no, test

#4965 Don't webpack:compile for TEST_SUITE=spec
  config/initializers/webpacker.rb
  lib/tasks/manageiq/ui_tasks.rake
Labels: hammer/no, test

#4971 Travis - remove sudo:false
  .travis.yml
Labels: test

#4981 Add coveralls badge
  README.md
Labels: developer, hammer/no

#4979 VmCloudController spec speedup.
  spec/controllers/vm_cloud_controller_spec.rb
Labels: hammer/no, test

#4980 Minor spec fixes and speedups.
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_playbook_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/ems_physical_infra_controller_spec.rb
  spec/controllers/pxe_controller_spec.rb
  spec/controllers/resource_pool_controller_spec.rb
Labels: hammer/no, test

#4908 Cloud Volume creation fixes
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/controllers/cloud_volume_controller.rb
  app/controllers/ems_common.rb
  app/helpers/application_helper/button/cloud_volume_backup_create.rb
  app/helpers/application_helper/button/cloud_volume_backup_restore.rb
  app/helpers/application_helper/button/cloud_volume_new.rb
  app/views/cloud_volume/_common_new_edit.html.haml
  app/views/cloud_volume/new.html.haml
  spec/controllers/cloud_volume_controller_spec.rb
Labels: bug, compute/cloud, hammer/yes, storage

#4953 [GAPRINDASHVILI] - Fixed an issue introduced in cherry-pick conflict
  app/controllers/ops_controller/settings/common.rb
Labels: blocker, bug, settings

#4982 Fix rubocop warnings in StorageController
  app/controllers/storage_controller.rb
  app/controllers/storage_controller/storage_d.rb
  app/controllers/storage_controller/storage_pod.rb
Labels: hammer/no, technical debt

#4983 Fix rubocop warnings in TopologyController
  app/controllers/topology_controller.rb
Labels: hammer/no, technical debt

#4984 Fix rubocop warnings in UtilizationController
  app/controllers/utilization_controller.rb
Labels: hammer/no, technical debt

#4978 Rename deprecated towhat attribute to resource_type in miq schedules
  app/controllers/ops_controller/diagnostics.rb
  app/controllers/ops_controller/settings/schedules.rb
  app/controllers/report_controller/reports.rb
  app/controllers/report_controller/schedules.rb
  app/controllers/report_controller/widgets.rb
  app/presenters/tree_builder_report_schedules.rb
  app/services/widget_import_service.rb
  app/views/ops/_schedule_show.html.haml
  spec/controllers/ops_controller_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/services/widget_import_service_spec.rb
Labels: technical debt

#4930 Fix Delete message to display the entity type - "Generic Object Class"
  app/assets/javascripts/components/generic_object/generic-object-definition-toolbar.js
Labels: bug, generic objects, hammer/yes

#4990 Stop spinner after rendering flash message
  app/controllers/miq_ae_class_controller.rb
Labels: automation/automate, bug, hammer/yes

#4950 Remove open_url from GOD's custom buttons
  app/assets/javascripts/components/generic_object/main-custom-button-form-component.js
  app/views/static/generic_object/main_custom_button_form.html.haml
Labels: automation/automate, bug, generic objects, hammer/no, technical debt

#4977 Fix save in region replication form
  app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
  spec/javascripts/controllers/ops/pglogical_replication_form_controller_spec.js
Labels: blocker, bug, hammer/yes, settings

#4992 Rakefile - drop unused spec:*:setup tasks
  Rakefile
Labels: developer

#4998 Fix rubocop warnings in VmOrTemplateController
  app/controllers/vm_or_template_controller.rb
Labels: technical debt

#4997 Fix rubocop warnings in VmController
  app/controllers/vm_controller.rb
Labels: technical debt

#4996 Fix rubocop warnings in VmInfraController
  app/controllers/vm_infra_controller.rb
Labels: technical debt

#4995 Fix rubocop warnings in VmCloudController
  app/controllers/vm_cloud_controller.rb
Labels: technical debt

#5001 Replace `virtualization_tab` references with `kubevirt_tab`
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: bug, compute/containers, hammer/yes

#4986 Fix js tests that have SPEC HAS NO EXPECTATIONS
  spec/javascripts/components/verify-button_spec.js
  spec/javascripts/controllers/containers/container_project_dashboard_controller_spec.js
  spec/javascripts/controllers/ems_infra/aggregate_status_card_controller_spec.js
  spec/javascripts/controllers/toolbar_controller_spec.js
  spec/javascripts/fixtures/json/toolbar_middleware_server_list.json
Labels: hammer/no, test

#4509 Let Select Provision Template screen use GTL
  app/assets/javascripts/controllers/report_data_controller.js
  app/controllers/application_controller.rb
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/application_controller/report_data_additional_options.rb
  app/javascript/packs/provisioning-actions-common.js
  app/views/miq_request/_pre_prov.html.haml
  app/views/miq_request/_pre_prov_images.html.haml
  app/views/miq_request/_pre_prov_volumes_snapshots.html.haml
  app/views/miq_request/pre_prov.html.haml
  product/views/ProvisionCloudTemplates.yaml
  product/views/ProvisionInfraTemplates.yaml
  spec/controllers/application_controller/report_data_spec.rb
  spec/controllers/vm_cloud_controller_spec.rb
  spec/javascripts/support/jasmine.yml
  spec/support/controller_helper.rb
Labels: blocker, bug, gtls, hammer/yes

#5000 Reset `exp_tag` key when discard button is pressed.
  app/controllers/application_controller/filter.rb
  spec/controllers/application_controller/filter_spec.rb
Labels: bug, expressions/filters, hammer/yes

#5003 ReportDataController - fix a few style issues
  app/assets/javascripts/controllers/report_data_controller.js
Labels: technical debt

#5004 When redirecting to a specific storage, RBAC check storage_show
  app/controllers/storage_controller.rb
Labels: bug, gaprindashvili/yes, hammer/yes, storage

#5005 Show widget's title as page title when editing widget
  app/controllers/report_controller.rb
Labels: bug, cloud intel/reporting, gaprindashvili/yes, hammer/yes

#5006 spec - fix eslint warnings in report & toolbar specs
  spec/javascripts/.eslintrc.json
  spec/javascripts/controllers/report_data_controller_spec.js
  spec/javascripts/controllers/toolbar_controller_spec.js
Labels: technical debt, test

#5008 Fix rubocop warnings in app/services/a*
  app/services/ansible_tower_job_template_dialog_service.rb
  app/services/auto_placement_visibility_service.rb
  app/services/automate_import_service.rb
Labels: technical debt

#5002 Fix rubocop warnings in VmCommon module
  app/controllers/vm_common.rb
Labels: technical debt

#5010 Allow apostrophes in custom button names
  app/views/shared/dialogs/_dialog_user.html.haml
Labels: automation/automate, bug, gaprindashvili/yes, hammer/yes

#5011 VmCommon: add missing gettext
  app/controllers/vm_common.rb
Labels: hammer/no, internationalization

#4895 Replace cloud tenant form with React component
  app/assets/javascripts/controllers/cloud_tenant/cloud_tenant_form_controller.js
  app/javascript/.eslintrc.js
  app/javascript/components/cloud-tenant-form/cloud-tenant-form.jsx
  app/javascript/components/cloud-tenant-form/create-form-schema.js
  app/javascript/forms/data-driven-form.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/.eslintrc.json
  app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap
  app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
  app/views/cloud_tenant/edit.html.haml
  app/views/cloud_tenant/new.html.haml
  config/jest.setup.js
  package.json
  spec/javascripts/controllers/cloud/cloud_tenant_form_controller_spec.js
Labels: react, refactoring

#5012 Fix referrer -> referer
  app/controllers/vm_common.rb
  app/views/miq_request/_prov_field.html.haml
  spec/controllers/vm_common_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: hammer/no, technical debt

#5015 [GAPRINDASHVILI] - Check for Appliance name only when validating settings tab.
  app/controllers/ops_controller/settings/common.rb
Labels: blocker, bug, settings

#5009 Remove deprecated toplevel constants from the codebase
  app/controllers/flavor_controller.rb
  app/controllers/physical_server_controller.rb
  app/helpers/application_helper/button/new_flavor.rb
  spec/helpers/application_helper/buttons/new_flavor_spec.rb
  spec/services/dialog_local_service_spec.rb
Labels: gaprindashvili/no, hammer/no

#4985 Replace service form
  app/assets/javascripts/controllers/service/service_form_controller.js
  app/javascript/components/service-form/index.jsx
  app/javascript/components/service-form/schema.js
  app/javascript/forms/data-driven-form.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/service-form/service-form.spec.js
  app/views/service/_service_form.html.haml
  package.json
  spec/javascripts/controllers/service/service_form_controller_spec.js
Labels: hammer/no, react, services

#5018 ServiceForm spec - fix by disabling disableSubmit and making sure the validator can pass
  app/javascript/forms/data-driven-form.jsx
  app/javascript/spec/service-form/service-form.spec.js
Labels: test
