Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-10, with the labels that each got.

#4677 Fix variable name and extra semicolon in VMDB summary view
  app/views/ops/_db_summary.html.haml
Labels: bug, gaprindashvili/no, settings

#4580 Fix the way that switch card is being displayed on the dashboard
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, compute/physical infrastructure

#4685 Refactored cloud_object_store_object_spec with using let variables and removing classification mocking
  spec/controllers/cloud_object_store_object_spec.rb
Labels: gaprindashvili/no, refactoring, test

#4683 Refactored cloud_network_controller_spec with using let variables and removing classification mocking
  spec/controllers/cloud_network_controller_spec.rb
Labels: gaprindashvili/no, refactoring, test

#4689 Refactored cloud_subnet_controller_spec with using let variables and removing classification mocking
  spec/controllers/cloud_subnet_controller_spec.rb
Labels: gaprindashvili/no, refactoring, test

#4697 Refactored cloud_tenant_controller_spec with using let variables and removing classification mocking
  spec/controllers/cloud_tenant_controller_spec.rb
Labels: gaprindashvili/no, refactoring, test

#4688 Use bool instead of a string that needs to be translated
  app/controllers/application_controller/compare.rb
Labels: bug, gaprindashvili/no, internationalization

#4713 Removed reference to condition modifier
  app/controllers/miq_policy_controller/conditions.rb
Labels: blocker, bug, control, hammer/yes

#4698 Refactored cloud_volume_backup_controller_spec with using let variables and removing classification mocking
  spec/controllers/cloud_volume_backup_controller_spec.rb
Labels: gaprindashvili/no, refactoring, test

#4718 Fix wrapping switch
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, formatting/styling, gaprindashvili/yes, hammer/yes

#4700 Change flash after submit to have green color
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
Labels: angular dialogs, gaprindashvili/no

#4709 Removed extra horizontal line
  app/views/vm_common/_reconfigure.html.haml
Labels: bug, compute/infrastructure, formatting/styling, hammer/no

#4706 Pass normalized_state into textual summaries for consistency
  app/helpers/textual_mixins/textual_power_state.rb
Labels: bug, gaprindashvili/no, hammer/yes, textual summaries

#4676 Refactored auth_key_pair_cloud_controller_spec with using let variables and removing classification mocking
  spec/controllers/auth_key_pair_cloud_controller_spec.rb
Labels: gaprindashvili/no, refactoring, test

#4666 ApplicationController::CiProcessing: fix rubocop warnings
  app/controllers/application_controller/ci_processing.rb
Labels: technical debt, unmergeable

#4672 Fix UI error when migrating virtual machine
  app/controllers/application_controller/miq_request_methods.rb
Labels: blocker, bug, compute/infrastructure, gaprindashvili/no

#4671 Don't use if/unless inside a string interpolation
  app/controllers/application_controller.rb
  app/controllers/report_controller/reports/editor.rb
  app/helpers/vm_helper/textual_summary.rb
Labels: hammer/no, technical debt

#4705 Add Physical Chassis link to default menu
  app/presenters/menu/default_menu.rb
Labels: bug, compute/physical infrastructure, hammer/yes

#4711 Put background under archived/orphaned tree node icons in VMs
  app/presenters/tree_builder_archived.rb
  spec/presenters/tree_builder_archived_spec.rb
  spec/presenters/tree_builder_images_spec.rb
  spec/presenters/tree_builder_instances_spec.rb
Labels: gaprindashvili/no, graphics, hammer/yes

#4722 Corrected flash message rendering after submitting VM reconfigure request
  app/views/miq_request/show_list.html.haml
  app/views/static/miq-request-options.html.haml
Labels: bug, compute/infrastructure, hammer/yes

#4536 Allow selecting an optional volume type when creating an Openstack cloud volume
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/controllers/cloud_volume_controller.rb
  app/views/cloud_volume/_common_new_edit.html.haml
  spec/controllers/cloud_volume_controller_spec.rb
Labels: compute/cloud, enhancement, gaprindashvili/no, ux/approved

#4727 Remove full_ids from infra networking tree to fix error in selection
  app/presenters/tree_builder_infra_networking.rb
Labels: bug, hammer/yes, trees

#4725 Removed dead code for toolbar class toggle
  app/assets/javascripts/miq_application.js
  spec/javascripts/miq_application_spec.js
Labels: hammer/no, technical debt, toolbars

#3592 Converted retirementForm controller to component
  app/assets/javascripts/components/retirement-form.js
  app/assets/javascripts/controllers/retirement/retirement_form_controller.js
  app/views/shared/views/_retire.html.haml
  app/views/static/retirement-form.html.haml
  spec/javascripts/components/retirement/retirement-form_spec.js
  spec/javascripts/controllers/retirement/retirement_form_controller_spec.js
Labels: angular dialogs, gaprindashvili/no, refactoring

#4408 [GAPRINDASHVILI] Update gettext catalog for gaprindashvili update release
  locale/ManageIQ_UI_Classic.pot
Labels: internationalization

#4643 Remove deprecated VMDB::Config class
  app/controllers/ops_controller/settings.rb
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/help_menu.rb
  app/views/ops/_settings_workers_tab.html.haml
  spec/controllers/miq_request_controller_spec.rb
  spec/controllers/ops_controller/settings/common_spec.rb
  spec/controllers/ops_controller_spec.rb
  spec/controllers/ops_settings_spec.rb
Labels: technical debt

#4731 Cleaned up logic of deleting a Widget
  app/controllers/report_controller/widgets.rb
Labels: cloud intel/reporting, refactoring

#4732 initiate_wait_for_task - support :flash => true to flash while waiting
  app/controllers/application_controller/wait_for_task.rb
Labels: enhancement, tasks

#4734 Fixes disabled 'Show full screen report' button on Saved Reports page
  app/helpers/application_helper/toolbar/saved_reports_center.rb
Labels: bug, cloud intel/reporting, gaprindashvili/no, hammer/yes

#4737 Fixed CPU value display on VM summary
  app/helpers/vm_helper/textual_summary.rb
Labels: blocker, bug, compute/infrastructure, hammer/yes

#4690 bower to npm: patternfly-timeline (@pf3/timeline)
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/javascript/packs/globals.js
  bower.json
  package.json
  spec/javascripts/globals_pack_spec.js
Labels: dependencies, hammer/yes

#4710 Show correct VMs upon Service retirement
  app/controllers/application_controller/miq_request_methods.rb
  app/views/miq_request/_request.html.haml
  app/views/miq_request/_service_retire_show.html.haml
  spec/controllers/miq_request_controller_spec.rb
Labels: blocker, bug, compute/infrastructure, gaprindashvili/yes, hammer/yes

#4739 Fixed links for vm/templates to instances/images on cloud dashboard
  app/services/ems_cloud_dashboard_service.rb
Labels: blocker, bug, compute/cloud, hammer/yes

#4695 Replaced obsolete 'find_checked_records_with_rbac' method
  app/controllers/application_controller.rb
  app/controllers/cloud_tenant_controller.rb
  app/controllers/mixins/checked_id_mixin.rb
  app/controllers/ops_controller/ops_rbac.rb
  app/controllers/report_controller/schedules.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: rbac, technical debt

#4736 Add validation for cloud_networks and subnets
  app/helpers/host_helper/textual_summary.rb
Labels: blocker, bug, compute/infrastructure, hammer/yes

#4740 Fix delayed translation test
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: hammer/yes, internationalization, test

#4694 bower to npm: manageiq-ui-components
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/print.scss
  bower.json
  package.json
  tools/ci/setup_js_env.sh
Labels: dependencies, hammer/yes

#4682 Fix FTP credentials for log depot
  app/assets/javascripts/services/miq_db_backup_service.js
  app/views/ops/_log_collection.html.haml
Labels: blocker, bug, settings

#4742 [GAPRINDASHVILI] Update ui-components to 1.0.36 for gaprindashvili
  bower.json
Labels: dependencies

#4735 Remove bower
  .bowerrc
  .eslintignore
  .eslintrc.json
  .gitignore
  .travis.yml
  bower.json
  config/initializers/assets.rb
  lib/tasks/manageiq/ui_tasks.rake
  tools/ci/setup_js_env.sh
Labels: dependencies, hammer/yes

#4741 Removing button for showing fullscreen report from list view
  app/helpers/application_helper/toolbar/saved_reports_center.rb
Labels: bug, cloud intel/reporting, hammer/yes

#4744 Fix dynamic reducers
  app/javascript/forms/form-buttons-redux.jsx
  app/javascript/miq-component/react-blueprint.tsx
  app/javascript/miq-redux/index.js
  app/javascript/miq-redux/middleware.js
  app/javascript/miq-redux/reducer.js
  app/javascript/miq-redux/reducer.ts
  app/javascript/miq-redux/redux-router-actions.test.js
  app/javascript/miq-redux/redux-typings.ts
  app/javascript/miq-redux/store.js
  app/javascript/packs/application-common.js
Labels: bug, hammer/yes

#4750 Fix adding a new Service Catalog Item for Vmware Catalog Item Type
  app/controllers/catalog_controller.rb
Labels: blocker, bug, hammer/yes, services

#4752 Default menu - fix all menu items to use full url
  app/presenters/menu/default_menu.rb
Labels: bug, hammer/yes, menus

#4754 [GAPRINDASHVILI] Fix failing specs
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: test

#4755 [GAPRINDASHVILI] Add listicon parameter for child stack display
  app/controllers/orchestration_stack_controller.rb
Labels: blocker, bug, compute/cloud

#4758 Travis - change postgresql to 9.5
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes, test

#4759 Fix for javascript error when attempting to edit a service dialog based on orchestration template
  app/views/miq_ae_customization/_dialog_sample.html.haml
Labels: angular dialogs, bug, hammer/yes

#4476 Convert Log collection controller to component
  app/assets/javascripts/components/ops/log-collection-form-component.js
  app/assets/javascripts/services/miq_service.js
  app/views/ops/_log_collection.html.haml
  app/views/static/ops/log_collection/log_collection.html.haml
  spec/javascripts/components/ops/log_collection_form_spec.js
  spec/javascripts/controllers/ops/log_collection_form_controller_spec.js
Labels: angular dialogs, gaprindashvili/no, hammer/no, refactoring

#4747 [HAMMER] yarn: lock by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies

#4768 Fix multi-tab endpoint credential validation by passing the right credential type when user hits "Enter"
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Labels: blocker, bug, compute/infrastructure, hammer/yes

#4771 Remove code that is commented out
  app/controllers/application_controller/buttons.rb
  app/controllers/miq_ae_customization_controller/custom_buttons.rb
Labels: hammer/no, technical debt

#4749 Use report default options for Report screens
  app/controllers/application_controller.rb
  spec/controllers/application_controller/report_data_spec.rb
Labels: bug, hammer/yes, settings

#4777 ApplicationController::Performance: fix rubocop warnings
  app/controllers/application_controller/performance/options.rb
Labels: technical debt

#4766 Fix rubocop warnings in ApplicationController::Filter
  app/controllers/application_controller/filter/expression_edit_history.rb
Labels: technical debt

#4765 Fix rubocop warning in ApplicationContoller::Feature
  app/controllers/application_controller/feature.rb
Labels: technical debt

#4764 Fix rubocop warning in ApplicationController::ExpressionHtml
  app/controllers/application_controller/expression_html.rb
Labels: technical debt

#4763 Fix rubocop warnings in ApplicationController::Explorer
  app/controllers/application_controller/explorer.rb
Labels: technical debt

#4762 Fix rubocop warnings in ApplicationController::DialogRunner
  app/controllers/application_controller/dialog_runner.rb
  spec/controllers/application_controller/dialog_runner_spec.rb
Labels: technical debt

#4767 Add dashboard for cloud tenant
  app/controllers/cloud_tenant_controller.rb
  app/controllers/cloud_tenant_dashboard_controller.rb
  app/helpers/application_helper/toolbar/cloud_tenant_center.rb
  app/services/cloud_tenant_dashboard_service.rb
  app/services/ems_cloud_dashboard_service.rb
  app/services/ems_dashboard_service.rb
  app/views/cloud_tenant/_recent-images-line-chart.html.haml
  app/views/cloud_tenant/_recent-instances-line-chart.html.haml
  app/views/cloud_tenant/_show_dashboard.html.haml
  app/views/cloud_tenant/show_dashboard.html.haml
  config/routes.rb
  spec/controllers/cloud_tenant_controller_spec.rb
Labels: ux/approved

#4770 Remove OpenShift deployment wizard
  app/assets/javascripts/controllers/container_deployment/deploy-provider-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-config-auth-settings-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-config-settings-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-details-cdn-channel-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-details-create-vms-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-details-existing-vms-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-details-general-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-details-no-provider-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-master-nodes-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-review-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-review-progress-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-review-summary-controller.js
  app/assets/javascripts/controllers/container_deployment/dialogs.module.js
  app/assets/javascripts/controllers/container_deployment/modal_dialog/modal-dialog-directive.js
  app/assets/javascripts/controllers/container_deployment/wizard.js
  app/assets/javascripts/controllers/container_deployment/wizard/wizard-buttons.js
  app/assets/javascripts/controllers/container_deployment/wizard/wizard-directive.js
  app/assets/javascripts/controllers/container_deployment/wizard/wizard-review-page-directive.js
  app/assets/javascripts/controllers/container_deployment/wizard/wizard-step-directive.js
  app/assets/javascripts/controllers/container_deployment/wizard/wizard-substep-directive.js
  app/assets/javascripts/services/miq_service.js
  app/assets/stylesheets/application.css
  app/assets/stylesheets/wizard.scss
  app/helpers/application_helper/toolbar/ems_containers_center.rb
  app/views/ems_container/_deploy.html.haml
  app/views/ems_container/show_list.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-add-roles-popover.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-auth-mode-review.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-auth-settings-review.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-config-auth-mode.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-config-auth-settings.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-config-settings-review.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-config-settings.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-cdn-channel.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-cdn-review.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-create-vms.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-existing-vms.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-general-review.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-general.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-details-no-provider.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-master-nodes-review-create-vms.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-master-nodes-review-tables.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-master-nodes-review.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-masters-nodes.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-review-progress.html.haml
  app/views/static/deploy_containers_provider/deploy-provider-review-summary.html.haml
  app/views/static/modal-dialog.html
  app/views/static/wizard-review-page.html
  app/views/static/wizard-step.html
  app/views/static/wizard-substep.html
  app/views/static/wizard.html.haml
Labels: technical debt

#4778 Make physical network visible only for FLAT and VLAN
  app/assets/javascripts/components/cloud_network/cloud-network-form.js
  app/views/static/cloud_network/cloud-network-form.html.haml
Labels: bug, fine/yes, gaprindashvili/yes, hammer/yes, networks

#4769 [HAMMER] [Changelog] Add updates for beta1.1
  CHANGELOG.md
Labels: documentation

#4773 Disable Open URL for all models that don't have remote_console_url
  app/controllers/application_controller/buttons.rb
  app/views/shared/buttons/_ab_options_form.html.haml
  spec/controllers/application_controller/buttons_spec.rb
Labels: automation/automate, enhancement, hammer/no, ux/approved

#4783 Move connected physical servers to the Relationships table
  app/controllers/physical_switch_controller.rb
  app/helpers/physical_switch_helper/textual_summary.rb
  spec/helpers/physical_switch_helper/textual_summary_spec.rb
Labels: compute/physical infrastructure, refactoring

#4793 Render the notification drawer footer synchronously, remove its haml
  app/assets/javascripts/controllers/notifications/notification-drawer.directive.js
  app/views/layouts/_notifications_drawer.html.haml
  app/views/static/notification_drawer/notification-drawer.html.haml
  app/views/static/notification_drawer/notification-footer.html.haml
Labels: bug, gaprindashvili/no, hammer/yes

#4794 Fix Ansible Playbook 'New Catalog Item' styling issue
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: bug, formatting/styling, hammer/yes

#4792 Display notifications in the expanded notification drawer
  app/views/static/notification_drawer/notification-body.html.haml
Labels: bug, gaprindashvili/no, hammer/yes, notifications

#4796 [Gaprindashvili] - Make sure @edit[:current].config[:server][:zone] is set
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: blocker, bug, settings

#4745 Fix error for Datastore custom button
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/controllers/application_controller/buttons.rb
  app/views/shared/dialogs/_dialog_provision.html.haml
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
Labels: automation/automate, blocker, bug, gaprindashvili/yes, hammer/yes

#4789 Remove catching flash messages in report_data_controller.js
  app/assets/javascripts/controllers/report_data_controller.js
Labels: bug, gaprindashvili/no, gtls, hammer/yes

#4802 Fix rubocop warnings in EmsContainerController
  app/controllers/ems_container_controller.rb
Labels: technical debt

#4801 Fix rubocop warnings in EmsCommonHelper
  app/controllers/ems_common_helper.rb
Labels: technical debt

#4800 Fix rubocop warnings in EmsClusterController
  app/controllers/ems_cluster_controller.rb
Labels: technical debt

#4799 Fix rubocop warnings in EmsCloudController
  app/controllers/ems_cloud_controller.rb
Labels: technical debt

#4798 Fix rubocop warnings in DashboardController
  app/controllers/dashboard_controller.rb
Labels: technical debt

#4797 Fix rubocop warnings in ApplicationController::Timelines
  app/controllers/application_controller/timelines.rb
Labels: technical debt

#4788 Fix rubocop warings in ApplicationController::Tags
  app/controllers/application_controller/tags.rb
Labels: technical debt

#4787 Fix rubocop warnings in ApplicationController::SysprepAnswerFile
  app/controllers/application_controller/sysprep_answer_file.rb
Labels: technical debt

#4786 Fix rubocop warnings in ApplicationController::ReportDownloads
  app/controllers/application_controller/report_downloads.rb
Labels: technical debt

#4785 ApplicationController::PolicySupport: fix rubocop warnings
  app/controllers/application_controller/policy_support.rb
Labels: technical debt

#4774 Fix rubocop warnings in ApplicationController:MiqRequestMethods
  app/controllers/application_controller/miq_request_methods.rb
Labels: technical debt

#4757 Fix rubocop warnings in ApplicationController::Compare
  app/controllers/application_controller/compare.rb
Labels: technical debt

#4726 Replace about modal with a react component that feeds on the API
  app/javascript/components/miq-about-modal.jsx
  app/javascript/packs/component-definitions-common.js
  app/presenters/menu/default_menu.rb
  app/presenters/menu/item.rb
  app/views/layouts/_about_modal.html.haml
  app/views/layouts/_header.html.haml
  app/views/ops/_settings_help_menu_tab.html.haml
Labels: bug, performance

#4779 Fix rubocop warnings in ApplicationController::Performance
  app/controllers/application_controller/performance.rb
Labels: technical debt

#4805 Fix rubocop warnings in FloatingIpController
  app/controllers/floating_ip_controller.rb
Labels: technical debt

#4806 Removed dead code in performance controller
  app/controllers/application_controller/performance.rb
  app/controllers/application_controller/performance/options.rb
Labels: technical debt

#4804 Fix rubocop warnings in EmsInfraController
  app/controllers/ems_infra_controller.rb
Labels: technical debt

#4760 Fixed links to point to correct provider controller based upon type.
  app/assets/javascripts/services/alerts_center_service.js
  app/controllers/restful_redirect_controller.rb
  spec/controllers/restful_redirect_controller_spec.rb
Labels: blocker, bug, hammer/yes, monitor

#4807 Fix rubocop warnings in GenericObjectController
  app/controllers/generic_object_controller.rb
Labels: technical debt

#4808 Fix rubocop warnings in GenericObjectDefinitionController
  app/controllers/generic_object_definition_controller.rb
Labels: technical debt

#4810 [RFE] Display current zone name and region number in the about modal
  app/javascript/components/miq-about-modal.jsx
Labels: enhancement, settings

#4812 Upgrade spice-html5-bower to 1.7.3
  package.json
Labels: dependencies, hammer/yes

#4795 Fix vm_cloud image custom button return and cancel endpoints
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: blocker, bug, compute/cloud, gaprindashvili/yes, hammer/yes

#4790 Allow Service retirement over Centralized Administration
  app/controllers/application_controller/ci_processing.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes, services

#4821 Fix bottom tooltip placement for notifications in the drawer
  app/views/static/notification_drawer/_notification-body.html.haml
Labels: bug, hammer/yes, notifications

#4823 Styling cleanup
  app/assets/stylesheets/patternfly_overrides.scss
Labels: formatting/styling, hammer/no, technical debt

#4824 Only update report name in group reports menu when editing a report
  app/controllers/report_controller/reports/editor.rb
Labels: blocker, bug, cloud intel/reporting, gaprindashvili/yes, hammer/yes

#4825 Setting `@in_a_form`
  app/controllers/catalog_controller.rb
Labels: bug, hammer/yes, services

#4822 Fix removing catalog items from Catalog Bundle resource list
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: bug, hammer/yes, services

#4811 Add physical switches to the Physical Server page Relationships table
  app/controllers/physical_server_controller.rb
  app/helpers/physical_server_helper/textual_summary.rb
  app/views/physical_server/show.html.haml
  spec/helpers/physical_server_helper/textual_summary_spec.rb
Labels: compute/physical infrastructure, enhancement

#4835 Load correct Mixins::CustomButtons::Result when browser is refreshed
  app/controllers/ops_controller.rb
Labels: blocker, bug, hammer/yes, settings

#4836 Rename tabs in the haml to match current tab in the controller scope
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/mixins/ems_common_angular.rb
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Labels: blocker, bug, hammer/yes

#4840 Move reducer initialization out of the buttons component.
  app/javascript/forms/form-buttons-redux.jsx
Labels: bug

#4834 Code climate and eslint js rules
  .codeclimate.yml
  app/javascript/.eslintrc.js
  app/javascript/spec/.eslintrc.json
  app/javascript/spec/miq-component/helpers.spec.jsx
  app/javascript/spec/miq-component/miq-component.spec.js
  app/javascript/spec/miq-redux/redux-router-actions.test.js
  app/javascript/spec/react/compontentRegistry.test.js
Labels: cleanup, test

#4843 Fixed feature id when checking assert_privileges.
  app/controllers/application_controller/tags.rb
  spec/controllers/application_controller/tags_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes, tagging

#4845 ReportDataController - remove dead scrollElement
  app/assets/javascripts/controllers/report_data_controller.js
Labels: hammer/yes, technical debt

#4847 Advanced search - use the right spinner
  app/views/layouts/exp_atom/_editor.html.haml
Labels: bug, configuration management, hammer/yes

#4842 Js specs - more naming consistency
  app/javascript/spec/dashboards/widget-empty.spec.js
  app/javascript/spec/dashboards/widget-wrapper.spec.js
  app/javascript/spec/miq-component/helpers.spec.js
  app/javascript/spec/miq-redux/redux-router-actions.spec.js
  app/javascript/spec/react/compontentRegistry.spec.js
  app/javascript/spec/toolbar-actions/toolbar-actions-delete.spec.js
  app/javascript/spec/toolbar-actions/toolbar-actions-generic.spec.js
  spec/javascripts/controllers/dialog_user/dialog_user_controller_spec.js
  spec/javascripts/services/dialog_user_submit_error_handling_service_spec.js
Labels: technical debt, test

#4833 Fix rubocop warnings in controller mixins/actions
  app/controllers/mixins/actions/vm_actions/add_security_group.rb
  app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb
  app/controllers/mixins/actions/vm_actions/disassociate_floating_ip.rb
  app/controllers/mixins/actions/vm_actions/evacuate.rb
  app/controllers/mixins/actions/vm_actions/live_migrate.rb
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/controllers/mixins/actions/vm_actions/policy_simulation.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/controllers/mixins/actions/vm_actions/remove_security_group.rb
  app/controllers/mixins/actions/vm_actions/resize.rb
  app/controllers/mixins/actions/vm_actions/retire.rb
  app/controllers/mixins/actions/vm_actions/right_size.rb
Labels: technical debt

#4830 Fix rubocop warnings in MiqTemplateController
  app/controllers/miq_template_controller.rb
Labels: technical debt

#4815 Fix rubocop warnings in HostAggregateController
  app/controllers/host_aggregate_controller.rb
Labels: technical debt

#4775 Display custom buttons after comming from relationship table
  app/controllers/application_controller.rb
  app/controllers/application_controller/buttons.rb
  app/controllers/mixins/custom_buttons.rb
  app/helpers/application_helper/toolbar/mixins/custom_button_toolbar_mixin.rb
  app/helpers/application_helper/toolbar_builder.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_container_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/ems_network_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/shared/controllers/shared_example_for_custom_buttons.rb
Labels: blocker, bug, button actions, gaprindashvili/yes, hammer/yes, toolbars

#4829 Fix rubocop warnings in MiqTaskController
  app/controllers/miq_task_controller.rb
Labels: technical debt

#4820 Fix rubocop warnings in MiqAeToolsController
  app/controllers/miq_ae_tools_controller.rb
Labels: technical debt

#4818 Fix rubocop warnings in MiqAeClassController
  app/controllers/miq_ae_class_controller.rb
Labels: technical debt

#4816 Fix rubocop warnings in HostController
  app/controllers/host_controller.rb
Labels: technical debt

#4848 [GAPRINDASHVILI] Fixed action order field name to be consistent with observer
  app/views/catalog/_form_resources_info.html.haml
Labels: blocker, bug, services

#4855 Rescue error when canceling job
  app/controllers/miq_task_controller.rb
  spec/controllers/miq_task_controller_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#4852 Fix rubocop warnings in controller mixins
  app/controllers/mixins/containers_common_mixin.rb
  app/controllers/mixins/ems_common_angular.rb
  app/controllers/mixins/explorer_show.rb
  app/controllers/mixins/generic_form_mixin.rb
  app/controllers/mixins/generic_list_mixin.rb
  app/controllers/mixins/generic_session_mixin.rb
  app/controllers/mixins/generic_show_mixin.rb
  app/controllers/mixins/manager_controller_mixin.rb
  app/controllers/mixins/more_show_actions.rb
  app/controllers/mixins/time_helper.rb
  app/controllers/mixins/vm_show_mixin.rb
Labels: technical debt

#4853 Fix rubocop warnings in NetworkRouterController
  app/controllers/network_router_controller.rb
Labels: technical debt

#4858 Fix CI After Dynamic Product Features
  spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
Labels: hammer/yes, test

#4809 [RFE] Display Vm power state in the related grid views
  product/views/ManageIQ_Providers_CloudManager_Vm-all_vms_and_templates.yaml
  product/views/ManageIQ_Providers_CloudManager_Vm-vms.yaml
  product/views/ManageIQ_Providers_CloudManager_Vm.yaml
  product/views/ManageIQ_Providers_InfraManager_Vm.yaml
  product/views/Vm-all_vms.yaml
  product/views/Vm.yaml
  product/views/VmOrTemplate-all_vms_and_templates.yaml
  product/views/VmOrTemplate.yaml
  product/views/Vm__restricted.yaml
  spec/controllers/application_controller/report_data_spec.rb
Labels: enhancement, gtls
