Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-07, with the labels that each got.

#4234 Don't create create schedule if already created
  app/controllers/report_controller/schedules.rb
Labels: bug, cloud intel/reporting, gaprindashvili/no

#4237 Add spec for dialogUserSubmitErrorHandlingService
  spec/javascripts/services/dialog_user_submit_error_handling_service.spec.js
Labels: gaprindashvili/no, test

#4233 Fix the EMS fallback decorator's single_quad definition
  app/decorators/ext_management_system_decorator.rb
Labels: gaprindashvili/no, gtls

#4232 Show and allow the server name to be saved in the settings/server screen
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#4228 Add single_quad definition for embedded ansible credentials
  app/decorators/manageiq/providers/embedded_automation_manager/authentication_decorator.rb
Labels: bug, gaprindashvili/no

#4223 Fix toolbar switching for Buttons accord and Add a new Button action
  app/controllers/application_controller/buttons.rb
  app/controllers/miq_ae_customization_controller/custom_buttons.rb
Labels: bug, toolbars

#4214 Don't allow user to create a repository if he has no rights to EA provider
  app/helpers/application_helper/button/embedded_ansible.rb
Labels: automation/ansible, bug, gaprindashvili/yes, toolbars

#4173 Move setting toolbar filename to Ansible Playbook/Repository/Credential controllers
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_playbook_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/toolbar_chooser.rb
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_playbook_controller_spec.rb
  spec/controllers/ansible_repository_controller_spec.rb
  spec/helpers/application_helper/toolbar_chooser_spec.rb
Labels: gaprindashvili/no, technical debt, toolbars

#4224 Add guidance text for new <<reset>> magic word
  app/helpers/ops_helper.rb
  app/views/ops/_settings_advanced_tab.html.haml
Labels: bug, settings

#4164 Fixing showtype error
  app/controllers/mixins/generic_list_mixin.rb
Labels: bug, compute/physical infrastructure

#3240 Move common initialization steps of topologies to topology service
  app/assets/javascripts/controllers/topology/cloud_topology_controller.js
  app/assets/javascripts/controllers/topology/container_topology_controller.js
  app/assets/javascripts/controllers/topology/infra_topology_controller.js
  app/assets/javascripts/controllers/topology/network_topology_controller.js
  app/assets/javascripts/controllers/topology/physical_infra_topology_controller.js
  app/assets/javascripts/services/topology_service.js
  app/views/container_topology/show.html.haml
  app/views/network_topology/show.html.haml
  spec/javascripts/controllers/containers/container_topology_controller_spec.js
  spec/javascripts/services/topology_service_spec.js
Labels: gaprindashvili/no, refactoring, topology

#4240 Fixed variable name
  app/controllers/miq_request_controller.rb
  spec/controllers/miq_request_controller_spec.rb
Labels: bug, gaprindashvili/yes, requests

#4241 Refactoring provision method to use new rbac call
  app/controllers/mixins/actions/host_actions/misc.rb
  spec/controllers/mixins/actions/host_actions/misc_spec.rb
Labels: gaprindashvili/no, rbac, refactoring

#4242 Pass in id of selected record correctly.
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: bug, gaprindashvili/yes, services

#4245 Passing capacity hash to values broke PV screen
  app/helpers/persistent_volume_helper/textual_summary.rb
Labels: bug, gaprindashvili/no, textual summaries

#4247 Replaced fileicons with fonticons in alerts.
  app/assets/javascripts/controllers/alerts/alerts_list_controller.js
  app/assets/javascripts/services/alerts_center_service.js
  app/controllers/alerts_list_controller.rb
  app/views/shared/views/_alerts_list.html.haml
Labels: bug, gaprindashvili/no, graphics

#4186 NOR to use right values
  app/helpers/vm_helper/textual_summary.rb
Labels: bug, cloud intel/reporting, gaprindashvili/no

#3799 Adding connections between servers and switches on topology page
  app/assets/stylesheets/topology.css
  app/services/physical_infra_topology_service.rb
Labels: compute/physical infrastructure, pending core, ux/approved

#4212 Unify openstack toolbar
  app/helpers/application_helper/button/cockpit_console.rb
  app/helpers/application_helper/button/instance_associate_floating_ip.rb
  app/helpers/application_helper/button/instance_attach.rb
  app/helpers/application_helper/button/instance_detach.rb
  app/helpers/application_helper/button/instance_disassociate_floating_ip.rb
  app/helpers/application_helper/toolbar/openstack_vm_cloud_center.rb
  app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
Labels: gaprindashvili/no, technical debt, toolbars

#4252 Use onchange as well as onfocus for radio buttons
  app/assets/javascripts/miq_ujs_bindings.js
Labels: blocker, bug, gaprindashvili/yes

#4256 Fixes page header when displaying Cloud Networks list
  app/controllers/vm_common.rb
Labels: blocker, bug, compute/cloud, gaprindashvili/yes

#4257 Fixed to make Reload button visible on list view.
  app/helpers/application_helper/button/miq_request.rb
Labels: bug, gaprindashvili/no, requests

#4249 Adding physical switches card to physical infra dashboard
  app/services/ems_physical_infra_dashboard_service.rb
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#4141 Extracting physical ports of a switch to a new page
  app/controllers/physical_network_port_controller.rb
  app/controllers/physical_switch_controller.rb
  app/decorators/physical_network_port_decorator.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/physical_network_port_helper.rb
  app/helpers/physical_network_port_helper/textual_summary.rb
  app/helpers/physical_switch_helper/textual_summary.rb
  app/views/physical_network_port/show.html.haml
  app/views/physical_switch/show.html.haml
  config/routes.rb
  product/views/PhysicalNetworkPort.yaml
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#3634 Rack page toolbar
  app/helpers/application_helper/toolbar/physical_rack_center.rb
  app/helpers/application_helper/toolbar/physical_racks_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/views/physical_rack/show.html.haml
Labels: compute/physical infrastructure, enhancement

#4254 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#4258 Textual summary spec
  spec/helpers/persistent_volume_helper/textual_summary_spec.rb
  spec/helpers/security_group_helper/textual_summary_spec.rb
Labels: gaprindashvili/no, test, textual summaries

#4259 Report menu style fixes.
  app/controllers/report_controller/menus.rb
Labels: cloud intel/reporting, gaprindashvili/no, technical debt

#4260 Makes Git URL field bigger
  app/views/miq_ae_tools/_import_export.html.haml
Labels: automation/automate, bug, enhancement

#4253 Update patternfly-sass to 3.52.0
  manageiq-ui-classic.gemspec
Labels: dependencies

#4246 Style fixes.
  app/controllers/application_controller/buttons.rb
  app/controllers/catalog_controller.rb
Labels: gaprindashvili/no, technical debt

#4266 Removed labels props from vm-snapshot-form-component.
  app/javascript/components/vm-snapshot-form-component.jsx
  package.json
Labels: gaprindashvili/no, react, refactoring

#4265 Add single_quad definition for ansible tower jobs
  app/decorators/manageiq/providers/ansible_tower/automation_manager/job_decorator.rb
Labels: bug, gaprindashvili/no, graphics

#4218 Move plugin logic for inflections into Vmdb::Plugins
  lib/tasks/manageiq/ui_tasks.rake
Labels: refactoring

#4276 Update gettext catalog for master
  locale/ManageIQ_UI_Classic.pot
Labels: gaprindashvili/no, internationalization, test

#4206 Fix Manage policies and Check compliance buttons for Container Images and others
  app/controllers/ems_common.rb
  spec/controllers/ems_common_controller_spec.rb
Labels: bug, gaprindashvili/yes

#4272 Add security protocol to physical infra form data
  app/controllers/ems_physical_infra_controller.rb
Labels: bug, compute/physical infrastructure, gaprindashvili/no

#4270 Fixed visible memory switch while adding snapshot for turned off vm.
  app/views/vm_common/_snap.html.haml
  package.json
Labels: bug, compute/infrastructure, gaprindashvili/no

#4250 Adjusting the grid definitions for physical infra provider dashboard
  app/views/static/ems_physical_infra/aggregate-status-card.html.haml
Labels: bug, compute/physical infrastructure

#4279 add GenericSessionMixin to PXE Controller
  app/controllers/pxe_controller.rb
  spec/controllers/pxe_controller_spec.rb
Labels: gaprindashvili/no, technical debt

#4281 add GeneralMixin test to reportcontroller
  spec/controllers/report_controller_spec.rb
Labels: gaprindashvili/no, test

#4283 Increase upper limit of the range for daily chargeback report to 5 weeks
  app/views/report/_form_filter_chargeback.html.haml
Labels: bug, cloud intel/chargeback, enhancement

#4169 Remove references to host provisioning
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/host_controller.rb
  app/controllers/miq_request_controller.rb
  app/decorators/miq_event_definition_decorator.rb
  app/helpers/application_helper/button/host_miq_request_new.rb
  app/helpers/application_helper/button/miq_request_copy.rb
  app/helpers/application_helper/toolbar/host_center.rb
  app/helpers/application_helper/toolbar/hosts_center.rb
  app/presenters/menu/default_menu.rb
  app/views/miq_request/_prov_host_dialog.html.haml
  app/views/miq_request/_prov_host_grid.html.haml
  app/views/miq_request/_request.html.haml
  locale/ManageIQ_UI_Classic.pot
  spec/helpers/application_helper/buttons/host_miq_request_new_spec.rb
  spec/helpers/application_helper/buttons/miq_request_approval_spec.rb
  spec/helpers/application_helper/buttons/miq_request_copy_spec.rb
  spec/helpers/application_helper/buttons/miq_request_edit_spec.rb
  spec/presenters/menu/default_menu_spec.rb
Labels: compute/infrastructure, gaprindashvili/no, technical debt

#4286 Fix asset pipeline for remote consoles when loading jquery
  app/assets/stylesheets/print.scss
Labels: bug, gaprindashvili/no

#4285 Remove Snapshot field from EC2 Instance summary screen
  app/helpers/vm_cloud_helper/textual_summary.rb
Labels: bug, compute/cloud, gaprindashvili/yes

#4282 Fix date/time display on request screen
  app/views/shared/dialogs/_dialog_field_date_and_date_time_control.html.haml
Labels: blocker, bug, gaprindashvili/yes, services

#2855 Add OpenID-Connect authentication support
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/ops_controller/settings/common.rb
  app/views/dashboard/login.html.haml
  app/views/dashboard/oidc_login.html.haml
  app/views/ops/_settings_authentication_tab.html.haml
  config/routes.rb
  spec/controllers/dashboard_controller_spec.rb
Labels: enhancement, gaprindashvili/no

#4288 Set Status of Physical Servers and Physical Switches in Topology View
  app/assets/javascripts/services/topology_service.js
  app/services/physical_infra_topology_service.rb
Labels: compute/physical infrastructure, enhancement, topology

#4262 Implement toolbar extension mechanism for providers
  app/helpers/application_helper/toolbar/base.rb
  app/helpers/application_helper/toolbar/basic.rb
  app/helpers/application_helper/toolbar/override.rb
  app/helpers/application_helper/toolbar_builder.rb
Labels: enhancement, gaprindashvili/no

#4290 Add shared example that tests textual summary has given methods
  spec/helpers/ansible_repository_helper/textual_summary_spec.rb
  spec/shared/helpers/textual_summaty_helper_methods.rb
Labels: gaprindashvili/no, test

#4297 Refactoring method in policy_support.rb to use new RBAC call
  app/controllers/application_controller/policy_support.rb
  spec/controllers/application_controller/policy_support_spec.rb
Labels: gaprindashvili/no, rbac, technical debt

#4264 Replace vendor SVG references in textual summaries with decorators
  app/helpers/automation_manager_helper.rb
  app/helpers/configuration_job_helper/textual_summary.rb
  app/helpers/container_group_helper/textual_summary.rb
  app/helpers/container_node_helper/textual_summary.rb
  app/helpers/provider_configuration_manager_helper.rb
  app/helpers/provider_foreman_helper.rb
  app/helpers/textual_mixins/textual_vmm_info.rb
  app/helpers/vm_helper/textual_summary.rb
Labels: gaprindashvili/no, refactoring, textual summaries

#4289 Use decorator to determine the root node icon in a provider tree
  app/presenters/tree_builder_vat.rb
  spec/presenters/tree_builder_vat_spec.rb
Labels: cleanup, gaprindashvili/no

#4307 Add missing single_quad definition for ansible tower provider
  app/decorators/manageiq/providers/automation_manager_decorator.rb
Labels: bug, gaprindashvili/no

#4111 Textual summary fixes
  app/helpers/physical_server_helper/textual_summary.rb
  app/helpers/textual_multilabel.rb
  app/javascript/react/textual_summary_click.js
  spec/helpers/physical_server_helper/textual_summary_spec.rb
Labels: bug, compute/physical infrastructure, gaprindashvili/no, textual summaries

#4308 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#2828 CloudSubnet: Convert Controller to Component
  app/assets/javascripts/components/cloud_subnet/cloud-subnet-form.js
  app/assets/javascripts/controllers/cloud_subnet/cloud_subnet_form_controller.js
  app/controllers/cloud_subnet_controller.rb
  app/views/cloud_subnet/_common_new_edit.haml
  app/views/cloud_subnet/edit.html.haml
  app/views/cloud_subnet/new.html.haml
  app/views/static/cloud_subnet/cloud-subnet-form.html.haml
  spec/controllers/cloud_subnet_controller_spec.rb
  spec/javascripts/components/cloud_subnet/cloud_subnet_form_spec.js
Labels: networks, refactoring

#4312 Minor fixes in Cloud Subnet
  app/assets/javascripts/components/cloud_subnet/cloud-subnet-form.js
  app/controllers/cloud_subnet_controller.rb
  spec/javascripts/components/cloud_subnet/cloud_subnet_form_spec.js
Labels: gaprindashvili/no, networks, refactoring

#4314 Make sure that react helper always closes the div tag
  app/helpers/reactjs_helper.rb
Labels: bug, gaprindashvili/no

#4305 [GAPRINDASHVILI] Update .json gettext catalogs (javascript) for Gaprindashvili update
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
Labels: blocker, bug, internationalization

#4303 [GAPRINDASHVILI] ui-components 1.0.32
  bower-locker.bower.json
  bower.json
Labels: blocker, dependencies

#4317 Fix link in textual_region
  app/helpers/textual_mixins/textual_region.rb
Labels: blocker, bug, gaprindashvili/no

#2422 Network Router: Use API; Fix fixed IPs subnet
  app/assets/javascripts/controllers/network_router/network_router_form_controller.js
  app/controllers/network_router_controller.rb
  app/views/network_router/_common_new_edit.haml
  config/routes.rb
  spec/controllers/network_router_controller_spec.rb
Labels: networks, refactoring

#3509 FormButtons component, with redux
  app/javascript/forms/form-buttons-redux.jsx
  app/javascript/forms/form-buttons.jsx
  app/javascript/forms/miq-button.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/provider-dialogs/modal.js
  package.json
Labels: enhancement, gaprindashvili/no, javascript infrastructure

#4323 Add angular gettext and make translation directive working
  app/assets/javascripts/application.js
  app/assets/javascripts/gettextCatalog.js
  app/assets/javascripts/miq_angular_application.js
  package.json
Labels: blocker, bug, gaprindashvili/yes, internationalization

#4112 Add new Cumulative Rate Calculation checkbox to Report editing screen
  app/controllers/report_controller/reports/editor.rb
  app/views/report/_form_filter_chargeback.html.haml
Labels: blocker, bug, cloud intel/chargeback, enhancement, gaprindashvili/yes

#4309 Changing Host icons
  app/decorators/miq_event_definition_decorator.rb
  app/helpers/application_helper/toolbar/host_aggregate_center.rb
  app/helpers/application_helper/toolbar/host_aggregates_center.rb
  app/helpers/ems_cluster_helper/textual_summary.rb
  app/helpers/ems_infra_helper/textual_summary.rb
  app/helpers/host_aggregate_helper/textual_summary.rb
  app/helpers/infra_networking_helper/textual_summary.rb
  app/helpers/miq_ae_class_helper.rb
  app/helpers/network_port_helper/textual_summary.rb
  app/helpers/resource_pool_helper/textual_summary.rb
  app/helpers/storage_helper/textual_summary.rb
  app/presenters/tree_builder_automate_simulation_results.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_condition.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_network.rb
  app/presenters/tree_builder_policy.rb
  app/presenters/tree_builder_protect.rb
  app/presenters/tree_builder_smartproxy_affinity.rb
  app/presenters/tree_builder_storage_adapters.rb
  app/services/ems_infra_dashboard_service.rb
  app/services/ui_service_mixin.rb
  app/views/container_topology/show.html.haml
  app/views/infra_topology/show.html.haml
  app/views/physical_infra_topology/show.html.haml
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/presenters/tree_builder_network_spec.rb
  spec/presenters/tree_builder_smartproxy_affinity_spec.rb
  spec/presenters/tree_builder_storage_adapters_spec.rb
Labels: gaprindashvili/no, graphics

#4324 Hide Driving Event field for Containers.
  app/controllers/miq_policy_controller/alerts.rb
  app/views/miq_policy/_alert_details.html.haml
  spec/controllers/miq_policy_controller/alerts_spec.rb
Labels: blocker, bug, control, gaprindashvili/yes

#4293 add GenericSessionMixin to Chargeback Controller
  app/controllers/chargeback_controller.rb
  spec/controllers/chargeback_controller_spec.rb
Labels: gaprindashvili/no, technical debt

#4294 add GenericSessionMixin to ems cluster controller
  app/controllers/ems_cluster_controller.rb
  spec/controllers/ems_cluster_controller_spec.rb
Labels: gaprindashvili/no, technical debt

#4295 add Generic Session Mixin to guest device controller
  app/controllers/guest_device_controller.rb
  spec/controllers/guest_device_controller_spec.rb
Labels: gaprindashvili/no, technical debt

#4296 Add GenericSessionMixin to Miq_policy controller
  app/controllers/miq_policy_controller.rb
  spec/controllers/miq_policy_controller_spec.rb
Labels: gaprindashvili/no, technical debt

#4327 Remove the unnecessary view_to_hash call from Foreman controller
  app/controllers/provider_foreman_controller.rb
Labels: configuration management, gaprindashvili/no, gtls, technical debt

#4329 Fix path to jQuery when loading it separately for remote consoles
  app/views/layouts/remote_console.html.haml
  app/views/vm_common/console_vmrc.html.haml
  app/views/vm_common/console_webmks.html.haml
  config/initializers/assets.rb
Labels: bug, gaprindashvili/no

#4328 Fixed rbac feature id being passed in to assert_privileges method
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: bug, gaprindashvili/yes, tagging

#4333 Fix a wrong paramenter being inject into infra dashboard
  app/assets/javascripts/controllers/ems_infra_dashboard/utilization_trend_chart_controller.js
Labels: bug, compute/physical infrastructure, dashboards, gaprindashvili/no

#4287 Fix search text on non gtl screens
  app/controllers/application_controller.rb
  spec/controllers/flavor_controller_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes, textual summaries

#4291 Event Details for notification emails
  app/views/generic_mailer/policy_action_email.html.haml
  app/views/generic_mailer/policy_action_email.text.haml
Labels: enhancement, settings

#4331 Display "FloatingIp belongs to NetworkRouter" relation
  app/controllers/network_router_controller.rb
  app/helpers/floating_ip_helper/textual_summary.rb
  app/helpers/network_router_helper/textual_summary.rb
  app/views/network_router/show.html.haml
Labels: enhancement, networks

#4332 Make name and description visible on CloudTenant details page
  app/controllers/cloud_tenant_controller.rb
  app/helpers/cloud_tenant_helper/textual_summary.rb
Labels: enhancement, networks

#4335 Fixing display of subcollections of physical components
  app/controllers/physical_chassis_controller.rb
  app/controllers/physical_rack_controller.rb
Labels: bug, compute/physical infrastructure

#4343 Fix path to jQuery in application.js
  app/assets/javascripts/application.js
Labels: bug, gaprindashvili/no

#4167 Adding PhysicalStorages list and summary pages
  app/controllers/ems_common.rb
  app/controllers/physical_chassis_controller.rb
  app/controllers/physical_rack_controller.rb
  app/controllers/physical_storage_controller.rb
  app/decorators/physical_storage_decorator.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/toolbar/physical_storage_center.rb
  app/helpers/application_helper/toolbar/physical_storages_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_physical_infra_helper/textual_summary.rb
  app/helpers/physical_rack_helper/textual_summary.rb
  app/helpers/physical_storage_helper.rb
  app/helpers/physical_storage_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/services/ems_physical_infra_dashboard_service.rb
  app/services/ui_service_mixin.rb
  app/views/layouts/listnav/_ems_physical_infra.html.haml
  app/views/layouts/listnav/_physical_storage.html.haml
  app/views/physical_rack/show.html.haml
  app/views/physical_storage/show.html.haml
  app/views/physical_storage/show_list.html.haml
  config/routes.rb
  product/views/PhysicalStorage.yaml
  spec/controllers/physical_storage_controller_spec.rb
  spec/helpers/physical_storage_helper/textual_summary_spec.rb
Labels: compute/physical infrastructure, enhancement, pending core, ux/review

#4321 Fix custom button without dialog
  app/controllers/application_controller/buttons.rb
  spec/controllers/application_controller/buttons_spec.rb
Labels: automation/automate, blocker, bug, gaprindashvili/no

#4338 Fix find in expression editor
  app/views/layouts/exp_atom/_edit_find.html.haml
Labels: bug, control, gaprindashvili/no

#4342 Display "CloudSubnet has many NetworkPorts" relation
  app/controllers/cloud_subnet_controller.rb
  app/helpers/cloud_subnet_helper/textual_summary.rb
  app/views/cloud_subnet/show.html.haml
Labels: enhancement, networks

#4346 Fixing link for physical switches ports
  app/helpers/physical_switch_helper/textual_summary.rb
Labels: bug, compute/physical infrastructure, gaprindashvili/no

#4347 Set the Status of some topology nodes
  app/services/physical_infra_topology_service.rb
Labels: compute/physical infrastructure, enhancement, topology

#4337 Display "FloatingIp belongs to CloudNetwork" relation
  app/controllers/cloud_network_controller.rb
  app/helpers/cloud_network_helper/textual_summary.rb
  app/helpers/floating_ip_helper/textual_summary.rb
  app/views/cloud_network/show.html.haml
Labels: enhancement, networks

#4348 Fix the health_state quadicon
  app/helpers/quadicon_helper.rb
Labels: bug, compute/physical infrastructure

#4345 Add missing gettext into angular controllers
  app/assets/javascripts/components/cloud_subnet/cloud-subnet-form.js
  app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
  app/assets/javascripts/controllers/cloud_tenant/cloud_tenant_form_controller.js
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/assets/javascripts/controllers/cloud_volume_backup/cloud_volume_backup_form_controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-details-no-provider-controller.js
  app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-master-nodes-controller.js
  app/assets/javascripts/controllers/ems_infra_dashboard/heatmap_controller.js
  app/assets/javascripts/controllers/ems_infra_dashboard/utilization_trend_chart_controller.js
  app/assets/javascripts/controllers/ems_physical_infra_dashboard/server_health_pie_chart_controller.js
  app/assets/javascripts/controllers/host_aggregate/host_aggregate_form_controller.js
  app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
  app/assets/javascripts/controllers/security_group/security_group_form_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_attach_form_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_detach_form_controller.js
Labels: bug, gaprindashvili/no, internationalization

#4350 Fix capitalization: Floating Ip -> Floating IP
  app/controllers/floating_ip_controller.rb
  app/helpers/network_router_helper/textual_summary.rb
  app/views/network_topology/show.html.haml
  product/views/FloatingIp.yaml
Labels: bug, gaprindashvili/no, networks

#4322 [GAPRINDASHVILI] remove `use_broker` expectations to fix the spec
  spec/controllers/mixins/ems_common_angular_spec.rb
Labels: test

#4353 Use ui lookup for model name in listnav
  app/helpers/application_helper/listnav.rb
  spec/views/layouts/listnav/_floating_ip.html.haml_spec.rb
Labels: gaprindashvili/no, technical debt

#4336 Remove VM Transform buttons
  app/helpers/application_helper/toolbar/vm_infras_center.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
Labels: blocker, gaprindashvili/yes, transformation

#4341 Remove Redux environment warning in production
  app/assets/javascripts/application.js
  app/javascript/packs/application-common.js
  config/webpack/shared.js
Labels: bug, developer, gaprindashvili/no

#4340 Disable ruby-scrutinizer-run to prevent time out of Scrutinizer
  .scrutinizer.yml
Labels: developer, gaprindashvili/no

#4361 Added helper that clears all unused react components from virtual DOM.
  app/javascript/miq-component/helpers.js
  app/javascript/miq-component/helpers.spec.jsx
  app/javascript/miq-component/react-blueprint.tsx
Labels: bug, react

#4299 Service AnsibleTower and EmbeddedAnsible UI parity
  app/controllers/service_controller.rb
  app/helpers/service_helper/textual_summary.rb
  app/views/layouts/_textual_groups_tabs.html.haml
  app/views/service/_svcs_show.html.haml
Labels: automation/ansible tower, enhancement, gaprindashvili/no, services

#4362 Display the correct quadicon for NTFS datastore entities
  app/decorators/storage_decorator.rb
Labels: bug, gaprindashvili/no, graphics

#4357 VM: associate only unused floating IPs
  app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb
Labels: enhancement, networks

#4369 GO Edit Screen: Add buttonText to file input button
  app/views/static/generic_object/custom-image-component.html.haml
Labels: bug, gaprindashvili/no, generic objects, internationalization

#4359 Add missing gettext into patternfly charts
  app/assets/javascripts/components/pf_charts/donut-pct-chart.component.js
  app/assets/javascripts/components/pf_charts/utilization-trend-chart.component.js
Labels: bug, gaprindashvili/no, internationalization

#4360 Fix sprintf with gettext in genericObjectTableComponent
  app/assets/javascripts/components/generic_object/generic-object-table-component.js
Labels: bug, gaprindashvili/no, internationalization

#4370 Corrected typo in miqSparkle function name
  app/controllers/miq_ae_class_controller.rb
Labels: bug, compute/infrastructure

#4371 Jest - fix "SecurityError: localStorage is not available for opaque origins"
  jest.config.js
Labels: bug, test

#4365 New Group Screen: use variable for placeholder texts
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, gaprindashvili/no, internationalization, settings

#4373 Ensure Look up groups checkbox is not shown when OIDC is enabled.
  app/views/ops/_rbac_group_details.html.haml
  spec/views/ops/_rbac_group_details.html.haml_spec.rb
Labels: bug, gaprindashvili/no, settings

#4320 Added configuration to enable redux routing for react components.
  app/javascript/miq-component/react-history.ts
  app/javascript/miq-redux/middleware.ts
  app/javascript/miq-redux/store.ts
  package.json
Labels: react

#4366 Fix indentation in prov_iso_img_grid
  app/views/miq_request/_prov_iso_img_grid.html.haml
Labels: bug, gaprindashvili/no, requests

#4306 Add shared_examples tests for helpers/textual_summary
  spec/helpers/ansible_credential_helper/textual_summary_spec.rb
  spec/helpers/ansible_playbook_helper/textual_summary_spec.rb
  spec/helpers/ansible_repository_helper/textual_summary_spec.rb
  spec/helpers/auth_key_pair_cloud_helper/textual_summary_spec.rb
  spec/helpers/availability_zone_helper/textual_summary_spec.rb
  spec/helpers/cloud_network_helper/textual_summary_spec.rb
  spec/helpers/cloud_object_store_container_helper/textual_summary_spec.rb
  spec/helpers/cloud_object_store_object_helper/textual_summary_spec.rb
  spec/helpers/cloud_subnet_helper/textual_summary_spec.rb
  spec/helpers/cloud_tenant_helper/textual_summary_spec.rb
  spec/helpers/cloud_volume_backup_helper/textual_summary_spec.rb
  spec/helpers/cloud_volume_helper/textual_summary_spec.rb
  spec/helpers/cloud_volume_snapshot_helper/textual_summary_spec.rb
  spec/helpers/configuration_job_helper/textual_summary_spec.rb
  spec/helpers/container_build_helper/textual_summary_spec.rb
  spec/helpers/container_group_helper/textual_summary_spec.rb
  spec/helpers/container_helper/textual_summary_spec.rb
  spec/helpers/container_image_helper/textual_summary_spec.rb
  spec/helpers/container_image_registry_helper/textual_summary_spec.rb
  spec/helpers/container_node_helper/textual_summary_spec.rb
  spec/helpers/container_project_helper/textual_summary_spec.rb
  spec/helpers/container_replicator_helper/textual_summary_spec.rb
  spec/helpers/container_route_helper/textual_summary_spec.rb
  spec/helpers/container_template_helper/textual_summary_spec.rb
  spec/helpers/ems_cloud_helper/textual_summary_spec.rb
  spec/helpers/ems_cluster_helper/textual_summary_spec.rb
  spec/helpers/ems_cotainer_helper/textual_summary_spec.rb
  spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb
  spec/shared/helpers/textual_summary_helper_methods.rb
  spec/shared/helpers/textual_summaty_helper_methods.rb
Labels: gaprindashvili/no, test

#4354 Adding Physical Storages to Physical Chassis summary page
  app/helpers/physical_chassis_helper/textual_summary.rb
  app/views/physical_chassis/show.html.haml
  spec/helpers/physical_chassis_helper/textual_summary_spec.rb
Labels: compute/physical infrastructure, enhancement

#4217 adding support to filter events by new group levels
  app/assets/javascripts/controllers/timeline/timeline_options_controller.js
  app/assets/javascripts/miq_timeline.js
  app/controllers/application_controller/timelines.rb
  app/controllers/application_controller/timelines/options.rb
  app/views/layouts/_tl_options.html.haml
  lib/report_formatter/timeline.rb
  spec/controllers/application_controller/timelines_spec.rb
  spec/lib/report_formater/timeline_spec.rb
Labels: enhancement, gaprindashvili/no, timelines

#4381 Adding some required config to charts-mixin
  app/assets/javascripts/controllers/mixins/charts-mixin.js
Labels: bug

#4387 Depend on patternfly 3.52.3 - do not upgrade
  package.json
Labels: dependencies, gaprindashvili/no

#4389 Fix unresponsive Save button while editing VM
  app/controllers/vm_common.rb
Labels: bug, compute/infrastructure, gaprindashvili/yes
