Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2018-04, with the labels that each got.

#3693 Validation of new provider with http_proxy settings
  app/controllers/mixins/ems_common_angular.rb
Labels: blocker, bug, compute/cloud, gaprindashvili/yes

#3700 [GAPRINDASHVILI] update ui-components to 1.0.21
  bower-locker.bower.json
  bower.json
Labels: blocker, dependencies

#3679 Enable WebMKS console access for VMware vCloud's VMs
  app/controllers/vm_remote.rb
  app/helpers/application_helper/button/vm_webmks_console.rb
  app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
  app/views/vm_common/console_webmks.html.haml
  config/routes.rb
  spec/helpers/application_helper/buttons/vm_webmks_console_spec.rb
Labels: enhancement, gaprindashvili/yes

#3686 Check dialog-user for info on valid inputs
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
Labels: blocker, bug, gaprindashvili/yes, services

#3712 Fix for Template Custom Button Dialog Not Displaying Submit or Cancel Buttons
  app/controllers/vm_common.rb
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: angular dialogs, blocker, bug, gaprindashvili/yes

#3716 Render flash partial even for an empty report list
  app/views/report/_report_list.html.haml
Labels: blocker, bug, cloud intel/reporting, gaprindashvili/yes

#3714 Get all user form data before validating for errors per field
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, gaprindashvili/yes, settings

#3719 package.json - remove Angular 2+ dependencies
  package.json
Labels: dependencies, gaprindashvili/no

#3723 Fix query to fetch more widgets
  app/controllers/report_controller/dashboards.rb
Labels: blocker, bug, cloud intel/dashboard, gaprindashvili/yes

#3635 Fix for the feature tree role selection in the Add User Role form
  app/controllers/ops_controller/ops_rbac.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: bug, gaprindashvili/no, settings

#3725 Changed title for adding / editing automate class for consistency
  app/controllers/miq_ae_class_controller.rb
Labels: automation/automate, gaprindashvili/no, technical debt

#3718 Update Rx.js to version 5.6
  app/assets/javascripts/application.js
  app/assets/javascripts/components/generic_object/generic-object-definition-toolbar.js
  app/assets/javascripts/components/physical_infrastructures/physical-server-toolbar.js
  app/assets/javascripts/controllers/container_deployment/deploy-provider-controller.js
  app/assets/javascripts/controllers/error_modal_controller.js
  app/assets/javascripts/controllers/header/header_controller.js
  app/assets/javascripts/controllers/middleware_server/middleware_server_controller.js
  app/assets/javascripts/controllers/report_data_controller.js
  app/assets/javascripts/controllers/toolbar_controller.js
  app/assets/javascripts/controllers/topology/network_topology_controller.js
  app/assets/javascripts/controllers/tree_view_controller.js
  app/assets/javascripts/miq_angular_application.js
  app/assets/javascripts/miq_debug.js
  app/assets/javascripts/miq_explorer.js
  app/assets/javascripts/miq_toolbar.js
  app/assets/javascripts/services/event_notifications_service.js
  app/assets/javascripts/services/subscription_service.js
  app/assets/javascripts/services/topology_service.js
  app/javascript/miq_observable.js
  app/javascript/packs/application-common.js
  bower.json
  package.json
  spec/javascripts/controllers/toolbar_controller_spec.js
  spec/javascripts/services/subscription_service_spec.js
Labels: dependencies, gaprindashvili/no

#3720 Fix displaying user detail page
  app/views/ops/_rbac_user_details.html.haml
Labels: bug, gaprindashvili/yes

#3681 Improve VM Chargeback Preview Report table formatting
  app/assets/stylesheets/patternfly_overrides.scss
  app/controllers/mixins/chargeback_preview.rb
Labels: bug

#3121 Reconfigure VM: Add / Remove Network Adapters
  app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/views/miq_request/_reconfigure_show.html.haml
  app/views/vm_common/_reconfigure.html.haml
  spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js
Labels: compute/infrastructure, enhancement

#3696 Container dashboard charts: send datapoints as full timestamps
  app/services/container_dashboard_service.rb
  app/services/container_service_mixin.rb
  spec/services/container_dashboard_service_spec.rb
Labels: blocker, bug, charts, compute/containers, fine/yes, gaprindashvili/yes

#3710 Fix SecurityGroup -> FirewallRules table port range display
  app/helpers/security_group_helper/textual_summary.rb
  config/initializers/range_formats.rb
Labels: bug, gaprindashvili/yes

#3728 Restrict the Help->Documentation screen based on RBAC rules only
  app/controllers/support_controller.rb
  app/views/support/show.html.haml
Labels: bug, gaprindashvili/yes

#3707 Add Oracle images.
  app/assets/images/svg/vendor-oracle.svg
  app/assets/images/svg/vendor-oracle_cloud.svg
  app/assets/images/svg/vendor-oracle_cloud_network.svg
Labels: graphics

#3369 Add a physical rack to the topology
  app/services/physical_infra_topology_service.rb
  app/services/topology_service.rb
  app/services/ui_service_mixin.rb
  app/views/physical_infra_topology/show.html.haml
Labels: compute/physical infrastructure, enhancement, topology

#2917 Update menu icons
  app/presenters/menu/default_menu.rb
Labels: enhancement, graphics, ux/approved

#3676 Fix saving changes after editing Satellite Provider
  app/controllers/provider_foreman_controller.rb
Labels: blocker, bug, configuration management

#3673 Fix editing of Default Container Image Rate
  app/controllers/chargeback_controller.rb
  app/helpers/application_helper/button/chargeback_rate_remove.rb
Labels: bug, gaprindashvili/yes, pending core

#3701 Include api_version when calling raw_connect for vCloud
  app/controllers/mixins/ems_common_angular.rb
Labels: enhancement, gaprindashvili/yes

#2978 Improve per provider settings ui
  app/assets/stylesheets/icon_customizations.scss
  app/views/static/provider_option_field_input.html.haml
  app/views/static/provider_option_section.html.haml
Labels: gaprindashvili/no, ux/approved

#3711 [FINE] API - use a utf-8 aware btoa implementation (base64encode)
  app/assets/javascripts/application.js
  app/assets/javascripts/miq_api.js
  bower.json
Labels: blocker, bug, dependencies

#3738 [FINE] Fix params for populate_reports_menu
  app/controllers/dashboard_controller.rb
Labels: blocker, bug, cloud intel/timelines

#3499 Ae resolve options component
  app/assets/javascripts/components/ae_resolve_options/ae-resolve-options-component.js
  app/assets/javascripts/controllers/schedule/schedule_form_controller.js
  app/views/ops/_schedule_form_filter.html.haml
  app/views/static/ae_resolve_options/ae-resolve-options-component.html.haml
Labels: angular dialogs, gaprindashvili/no, refactoring

#3729 Webpack pack priority
  app/helpers/application_helper.rb
  app/helpers/application_helper/webpack.rb
  app/views/layouts/application.html.haml
  app/views/layouts/login.html.haml
Labels: dependencies, gaprindashvili/no

#3665 [GAPRINDASHVILI] Updated translations for next gaprindashvili update
  locale/es/ManageIQ_UI_Classic.po
  locale/fr/ManageIQ_UI_Classic.po
  locale/ja/ManageIQ_UI_Classic.po
  locale/pt_BR/ManageIQ_UI_Classic.po
  locale/zh_CN/ManageIQ_UI_Classic.po
Labels: internationalization

#3706 [FINE] Fix for Role Tree Features check display
  app/controllers/ops_controller/ops_rbac.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: blocker

#1651 Regulate encryption when creating new volume from snapshot
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/views/cloud_volume/_common_new_edit.html.haml
Labels: bug, compute/cloud, fine/no

#3747 Fixed Secondary filter to be added/edited correctly.
  app/views/report/_form_expression_buttons.html.haml
  app/views/report/_form_filter.html.haml
  spec/views/report/_form_expression_buttons.html.haml_spec.rb
Labels: blocker, bug, cloud intel/reporting, gaprindashvili/yes

#2530 CloudNetwork: Convert controller to component
  app/assets/javascripts/components/cloud_network/cloud-network-form.js
  app/assets/javascripts/controllers/cloud_network/cloud_network_form_controller.js
  app/controllers/cloud_network_controller.rb
  app/views/cloud_network/_common_new_edit.html.haml
  app/views/cloud_network/change.html.haml
  app/views/cloud_network/edit.html.haml
  app/views/cloud_network/new.html.haml
  app/views/static/cloud_network/cloud-network-form.html.haml
  spec/controllers/cloud_network_controller_spec.rb
  spec/javascripts/components/cloud_network/cloud_network_form_spec.js
Labels: networks, refactoring

#3736 Networks > * forms - use the API to retrieve the list of network managers
  app/assets/javascripts/components/cloud_network/cloud-network-form.js
  app/assets/javascripts/controllers/cloud_subnet/cloud_subnet_form_controller.js
  app/assets/javascripts/controllers/floating_ip/floating_ip_form_controller.js
  app/assets/javascripts/controllers/network_router/network_router_form_controller.js
  app/assets/javascripts/controllers/security_group/security_group_form_controller.js
  app/assets/javascripts/services/miq_service.js
  app/controllers/application_controller.rb
  app/controllers/application_controller/network.rb
  app/controllers/cloud_network_controller.rb
  app/controllers/cloud_subnet_controller.rb
  app/controllers/floating_ip_controller.rb
  app/controllers/network_router_controller.rb
  app/controllers/security_group_controller.rb
  app/views/cloud_subnet/new.html.haml
  app/views/floating_ip/new.html.haml
  app/views/network_router/_common_new_edit.haml
  app/views/security_group/new.html.haml
  app/views/static/cloud_network/cloud-network-form.html.haml
Labels: gaprindashvili/no, networks, unmergeable

#3748 [FINE] Fix failing specs
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/views/shared/views/_ownership.html.haml_spec.rb
Labels: test

#3749 Swap the save/cancel buttons on the dialog editor to be consistent
  app/views/miq_ae_customization/editor.html.haml
Labels: automation/automate, bug, gaprindashvili/no

#3752 [Changelog] Update for Sprint 83
  CHANGELOG.md
Labels: documentation

#3755 Update bower.json resolutions with bootstrap-switch
  bower.json
Labels: dependencies, gaprindashvili/no

#3705 Skip re-validation when non-required fields are cleared
  app/assets/javascripts/directives/validation/reset_validation_status.js
  spec/javascripts/directives/validation/reset_validation_status_spec.js
Labels: bug, gaprindashvili/yes

#3765 update react to 16.3
  package.json
Labels: dependencies, gaprindashvili/no

#3656 Fix title in service details page when searching text
  app/controllers/service_controller.rb
Labels: bug, gaprindashvili/no, services

#3281 Add wrapper for widget in Dashboard
  app/assets/javascripts/components/widget-chart.js
  app/assets/javascripts/components/widget-empty.js
  app/assets/javascripts/components/widget-error.js
  app/assets/javascripts/components/widget-footer.js
  app/assets/javascripts/components/widget-menu.js
  app/assets/javascripts/components/widget-report.js
  app/assets/javascripts/components/widget-rss.js
  app/assets/javascripts/components/widget-spinner.js
  app/assets/javascripts/components/widget-wrapper.js
  app/helpers/dashboard_helper.rb
  app/javascript/spec/dashboards/mocks.js
  app/javascript/spec/dashboards/widget-empty.test.js
  app/javascript/spec/dashboards/widget-wrapper.test.js
  app/views/dashboard/_widget.html.haml
  app/views/dashboard/_widget_blank.html.haml
  app/views/dashboard/_widget_footer.html.haml
  app/views/dashboard/_zoomed_chart.html.haml
  app/views/layouts/_header.html.haml
Labels: dashboards, gaprindashvili/no

#3750 Remove unnecessary gettext from tests
  spec/helpers/generic_object_helper/textual_summary_spec.rb
  spec/helpers/vmware_console_helper_spec.rb
  spec/presenters/menu/custom_loader_spec.rb
  spec/views/report/_form_expression_buttons.html.haml_spec.rb
Labels: technical debt, test

#3767 Fix user edit
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, gaprindashvili/yes, settings

#3751 Remove 'Include C&U metrics' option for Metering Reports
  app/views/report/_form_filter_chargeback.html.haml
Labels: bug, cloud intel/chargeback, gaprindashvili/yes

#3766 [FINE] - Reset field_entry_point when new field is added.
  app/controllers/miq_ae_customization_controller/dialogs.rb
Labels: blocker, bug, old dialogs

#3763 [FINE]Restore the Delete button for server in diagnostics
  app/controllers/ops_controller/diagnostics.rb
  app/helpers/application_helper/toolbar/diagnostics_zone_center.rb
  app/presenters/tree_builder_roles_by_server.rb
  spec/helpers/application_helper/toolbar/diagnostics_zone_center_spec.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
Labels: blocker, bug, settings

#3746 [FINE] - Show message when trying to edit item with missing Provisioning request
  app/controllers/catalog_controller.rb
  app/views/catalog/_sandt_tree_show.html.haml
  spec/controllers/catalog_controller_spec.rb
Labels: blocker, bug, services

#3690 Add button in toolbar for remotely accessing a physical server
  app/controllers/physical_server_controller.rb
  app/helpers/application_helper/toolbar/physical_infrastructure/operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/physical_server_center.rb
  config/routes.rb
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#3534 Convert MIQ Request filtering to the client (javascript)
  app/assets/javascripts/components/miq-request-options.js
  app/assets/javascripts/controllers/report_data_controller.js
  app/controllers/miq_request_controller.rb
  app/helpers/miq_request_helper.rb
  app/views/miq_request/_prov_options.html.haml
  app/views/miq_request/show_list.html.haml
  app/views/static/miq-request-options.html.haml
  config/routes.rb
  spec/controllers/miq_request_controller_spec.rb
  spec/routing/miq_request_routing_spec.rb
  spec/views/miq_request/_prov_options.html.haml_spec.rb
Labels: angular dialogs, bug, gaprindashvili/no, technical debt

#3773 [GAPRINDASHVILI] Update ui-components to 1.0.22 for gaprindashvili
  bower-locker.bower.json
  bower.json
Labels: dependencies

#3768 Fix generic object show in services
  app/controllers/service_controller.rb
  spec/controllers/service_controller_spec.rb
Labels: blocker, bug, gaprindashvili/yes, generic objects

#3775 save/render flash message after Network Router delete is initiated.
  app/controllers/network_router_controller.rb
  spec/controllers/network_router_controller_spec.rb
Labels: bug, gaprindashvili/yes, networks

#3770 Use fonticons with color in quadicons' powerstate quadrants
  app/decorators/host_decorator.rb
  app/decorators/manageiq/providers/container_manager_decorator.rb
  app/decorators/miq_template_decorator.rb
  app/decorators/physical_server_decorator.rb
  app/decorators/vm_or_template_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, gtls

#3769 Mark CloudSubnet.cidr as required
  app/views/cloud_subnet/_common_new_edit.haml
Labels: bug, gaprindashvili/yes, networks

#3780 Remove old quadicon styling from patternfly-overrides
  app/assets/stylesheets/patternfly_overrides.scss
Labels: cleanup, gaprindashvili/no

#3745 Fix Control explorer policies Search clear button
  app/controllers/miq_policy_controller.rb
  spec/controllers/miq_policy_controller_spec.rb
Labels: bug

#3737 Fix url for service / vm / instance / stack retirement
  app/assets/javascripts/controllers/retirement/retirement_form_controller.js
  spec/javascripts/controllers/retirement/retirement_form_controller_spec.js
Labels: bug, fine/yes, gaprindashvili/yes, services

#3758 meaningful openscap report filenames
  app/controllers/container_image_controller.rb
Labels: blocker, bug, compute/containers, gaprindashvili/yes

#3774 Update decorators to use fonticons for single quads
  app/assets/stylesheets/patternfly_overrides.scss
  app/decorators/auth_private_key_decorator.rb
  app/decorators/availability_zone_decorator.rb
  app/decorators/cloud_network_decorator.rb
  app/decorators/cloud_object_store_container_decorator.rb
  app/decorators/cloud_object_store_object_decorator.rb
  app/decorators/cloud_subnet_decorator.rb
  app/decorators/cloud_tenant_decorator.rb
  app/decorators/cloud_volume_backup_decorator.rb
  app/decorators/cloud_volume_decorator.rb
  app/decorators/cloud_volume_snapshot_decorator.rb
  app/decorators/container_build_decorator.rb
  app/decorators/container_decorator.rb
  app/decorators/container_group_decorator.rb
  app/decorators/container_image_decorator.rb
  app/decorators/container_image_registry_decorator.rb
  app/decorators/container_node_decorator.rb
  app/decorators/container_project_decorator.rb
  app/decorators/container_replicator_decorator.rb
  app/decorators/container_route_decorator.rb
  app/decorators/container_template_decorator.rb
  app/decorators/container_volume_decorator.rb
  app/decorators/ems_cluster_decorator.rb
  app/decorators/ext_management_system_decorator.rb
  app/decorators/flavor_decorator.rb
  app/decorators/floating_ip_decorator.rb
  app/decorators/host_aggregate_decorator.rb
  app/decorators/host_decorator.rb
  app/decorators/load_balancer_decorator.rb
  app/decorators/manageiq/providers/cloud_manager/auth_key_pair_decorator.rb
  app/decorators/miq_policy_decorator.rb
  app/decorators/network_port_decorator.rb
  app/decorators/network_router_decorator.rb
  app/decorators/orchestration_stack_decorator.rb
  app/decorators/persistent_volume_decorator.rb
  app/decorators/security_group_decorator.rb
  spec/controllers/auth_key_pair_cloud_controller_spec.rb
  spec/presenters/tree_node/host_spec.rb
Labels: gaprindashvili/no, graphics, refactoring

#3783 Add custom attributes to playbook summary
  app/controllers/service_controller.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, gaprindashvili/yes, services

#3790 Add direct redux npm dependency, redux 4.0.0 breaks
  package.json
Labels: bug, dependencies, fine/no, gaprindashvili/no

#3785 Send the tree data for explorer trees as an object instead of JSON
  app/views/layouts/listnav/_explorer.html.haml
  app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml
Labels: bug

#3697 Azure labeling and tagging support
  app/controllers/ops_controller/settings/label_tag_mapping.rb
Labels: bug, gaprindashvili/yes, pending core, tagging

#3792 CiProcessing specs - stub user for failing retirement specs
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: gaprindashvili/no, test

#3789 Deduplicate AuthPrivateKeyPair decorator
  app/decorators/manageiq/providers/cloud_manager/auth_key_pair_decorator.rb
Labels: cleanup, gaprindashvili/no

#3793 Render new dialog runner for all service types.
  app/controllers/service_controller.rb
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: blocker, bug, gaprindashvili/yes, services

#3781 Update typescript to 2.8.0
  config/webpack/loaders/angular.js
  package.json
Labels: developer, gaprindashvili/no

#3787 Clear the request field when switching the button type to 'Default'
  app/controllers/mixins/playbook_options.rb
  spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb
Labels: automation/automate, bug, gaprindashvili/yes

#3771 Fix enabling/disabling Add button when creating new user
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, gaprindashvili/yes, settings

#3795 [GAPRINDASHVILI] Update manageiq-ui-components to 1.0.23 for gaprindashvili
  bower-locker.bower.json
  bower.json
Labels: dependencies

#3754 Server summary page changes
  app/controllers/physical_server_controller.rb
  app/helpers/physical_server_helper/textual_summary.rb
  spec/helpers/physical_server_helper/textual_summary_spec.rb
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no

#3510 Fix the setting for the retirement_remove_resources flag
  app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: bug, gaprindashvili/yes, services

#3805 Added setting of `@ems` to fix the nilclass error.
  app/controllers/ems_storage_controller.rb
  spec/controllers/ems_storage_controller_spec.rb
  spec/views/shared/views/ems_common/_show.html.haml_spec.rb
Labels: blocker, bug, gaprindashvili/yes, storage

#3812 Adding myself as a code owner for the app/decorators folder
  .github/CODEOWNERS
Labels: developer, gaprindashvili/no

#3409 Add redirect to request show_list page
  app/controllers/application_controller/ci_processing.rb
  app/controllers/orchestration_stack_controller.rb
  app/controllers/service_controller.rb
  spec/controllers/orchestration_stack_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: compute/infrastructure, enhancement, gaprindashvili/no

#3815 Use fonticons for alert profile folders
  app/views/miq_policy/_alert_profile_folders.html.haml
Labels: gaprindashvili/no, graphics, refactoring

#3816 Remove unnecessary template-no-host image and its only reference
  app/assets/images/svg/currentstate-template-no-host.svg
  app/helpers/textual_mixins/textual_power_state.rb
Labels: gaprindashvili/no, graphics, refactoring

#3818 Use the QuadiconHelper.machine_state for miq_template too
  app/decorators/miq_template_decorator.rb
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, gtls, refactoring

#3819 Fix title in Config Settings page to match the accordion
  app/controllers/ops_controller/settings.rb
  app/controllers/ops_controller/settings/common.rb
Labels: bug, gaprindashvili/yes, settings

#3820 Bump to ruby 2.3.6
  .travis.yml
Labels: dependencies

#3821 Renames network method according to label at physical server summary page
  app/controllers/physical_server_controller.rb
  app/helpers/physical_server_helper/textual_summary.rb
Labels: compute/physical infrastructure, gaprindashvili/no, technical debt

#3794 Remove unnecessary fonticon definitions from decorators and delete the related PNGs
  app/assets/images/100/auth_key_pair.png
  app/assets/images/100/availability_zone.png
  app/assets/images/100/cloud_network.png
  app/assets/images/100/cloud_object_store_container.png
  app/assets/images/100/cloud_subnet.png
  app/assets/images/100/cloud_tenant.png
  app/assets/images/100/cloud_volume.png
  app/assets/images/100/cloud_volume_snapshot.png
  app/assets/images/100/container.png
  app/assets/images/100/container_build.png
  app/assets/images/100/container_group.png
  app/assets/images/100/container_image.png
  app/assets/images/100/container_image_registry.png
  app/assets/images/100/container_node.png
  app/assets/images/100/container_project.png
  app/assets/images/100/container_replicator.png
  app/assets/images/100/container_route.png
  app/assets/images/100/container_service.png
  app/assets/images/100/container_template.png
  app/assets/images/100/ems_cluster.png
  app/assets/images/100/flavor.png
  app/assets/images/100/floating_ip.png
  app/assets/images/100/load_balancer.png
  app/assets/images/100/network_port.png
  app/assets/images/100/network_router.png
  app/assets/images/100/persistent_volume.png
  app/assets/images/100/security_group.png
  app/decorators/auth_private_key_decorator.rb
  app/decorators/availability_zone_decorator.rb
  app/decorators/cloud_network_decorator.rb
  app/decorators/cloud_object_store_container_decorator.rb
  app/decorators/cloud_object_store_object_decorator.rb
  app/decorators/cloud_subnet_decorator.rb
  app/decorators/cloud_tenant_decorator.rb
  app/decorators/cloud_volume_backup_decorator.rb
  app/decorators/cloud_volume_decorator.rb
  app/decorators/cloud_volume_snapshot_decorator.rb
  app/decorators/configuration_script_source_decorator.rb
  app/decorators/container_build_decorator.rb
  app/decorators/container_decorator.rb
  app/decorators/container_group_decorator.rb
  app/decorators/container_image_decorator.rb
  app/decorators/container_image_registry_decorator.rb
  app/decorators/container_node_decorator.rb
  app/decorators/container_project_decorator.rb
  app/decorators/container_replicator_decorator.rb
  app/decorators/container_route_decorator.rb
  app/decorators/container_service_decorator.rb
  app/decorators/container_template_decorator.rb
  app/decorators/ems_cluster_decorator.rb
  app/decorators/flavor_decorator.rb
  app/decorators/floating_ip_decorator.rb
  app/decorators/load_balancer_decorator.rb
  app/decorators/manageiq/providers/embedded_automation_manager/configuration_script_source_decorator.rb
  app/decorators/network_port_decorator.rb
  app/decorators/network_router_decorator.rb
  app/decorators/orchestration_stack_decorator.rb
  app/decorators/persistent_volume_decorator.rb
  app/decorators/security_group_decorator.rb
Labels: cleanup, gaprindashvili/no, graphics

#3786 Some Physical Servers params should be accessed through asset_detail
  app/helpers/physical_server_helper/textual_summary.rb
  product/views/PhysicalServer.yaml
Labels: compute/physical infrastructure, gaprindashvili/no, refactoring

#3759 Fix bugs on set ownership screen
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/views/shared/views/_ownership.html.haml
  spec/controllers/vm_cloud_controller_spec.rb
Labels: bug, compute/infrastructure, gaprindashvili/yes

#3788 Fix using old options for calculating
  app/assets/javascripts/miq_application.js
  app/assets/javascripts/miq_c3.js
Labels: bug, charts

#3811 [FINE] Add an optional argument for handling RBAC based on a boolean value
  app/controllers/application_controller.rb
Labels: bug

#3436 Add delete button to network router list and detail screen
  app/helpers/application_helper/toolbar/network_router_center.rb
  app/helpers/application_helper/toolbar/network_routers_center.rb
  app/javascript/miq_observable.js
  app/javascript/packs/toolbar-actions.js
  app/javascript/tests/toolbar-actions-delete.test.js
  app/javascript/toolbar-actions/delete.js
  app/javascript/typings/globals.d.ts
  app/views/cloud_tenant/show.html.haml
  app/views/layouts/_toolbar_actions.html.haml
  app/views/network_router/show.html.haml
  app/views/network_router/show_list.html.haml
  config/jest.setup.js
Labels: enhancement, gaprindashvili/no

#3809 Fixes Service Catalog Item Custom subtype display
  app/views/catalog/_sandt_tree_show.html.haml
Labels: bug, fine/yes, gaprindashvili/yes, services

#3810 Enable Compilance button for list of VMs
  app/helpers/application_helper/button/instance_check_compare.rb
Labels: bug, fine/yes, gaprindashvili/yes, toolbars

#3782 Add specs for saving widgets for #3723
  spec/controllers/miq_report_controller/dashboards_spec.rb
Labels: test

#3814 Apply gettext on catalog types & subtypes
  app/views/catalog/_form_basic_info.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
Labels: gaprindashvili/no, internationalization, services, technical debt

#3823 Fixed disabled report editor treeview styling regression
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, gaprindashvili/yes, graphics

#3828 optionally WEBPACK_EXCLUDE_NODE_MODULES
  config/webpack/configuration.js
  config/webpack/loaders.js
  config/webpack/loaders/angular.js
  config/webpack/loaders/assets.js
  config/webpack/loaders/babel.js
  config/webpack/loaders/react.js
  config/webpack/loaders/sass.js
  config/webpack/shared.js
Labels: developer, gaprindashvili/no

#3838 Remove Search from Switch summary page
  app/controllers/infra_networking_controller.rb
Labels: bug, fine/yes, gaprindashvili/yes, networks

#2925 Update toolbar icons
  app/assets/images/toolbars/automation.png
  app/assets/images/toolbars/blank_button.png
  app/assets/images/toolbars/custom_group.png
  app/assets/images/toolbars/enter_maint_mode.png
  app/assets/images/toolbars/exit_maint_mode.png
  app/assets/images/toolbars/guest_choice.png
  app/assets/images/toolbars/guest_restart.png
  app/assets/images/toolbars/guest_shutdown.png
  app/assets/images/toolbars/guest_startup.png
  app/assets/images/toolbars/power_choice.png
  app/assets/images/toolbars/power_off.png
  app/assets/images/toolbars/power_on.png
  app/assets/images/toolbars/power_pause.png
  app/assets/images/toolbars/power_reset.png
  app/assets/images/toolbars/power_resume.png
  app/assets/images/toolbars/power_shelve.png
  app/assets/images/toolbars/power_shelve_offload.png
  app/assets/images/toolbars/power_suspend.png
  app/assets/images/toolbars/reset.png
  app/assets/images/toolbars/restart.png
  app/assets/images/toolbars/resume.png
  app/assets/images/toolbars/standby.png
  app/assets/images/toolbars/start.png
  app/assets/images/toolbars/suspend.png
  app/assets/stylesheets/icon_customizations.scss
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/diagnostics_server_center.rb
  app/helpers/application_helper/toolbar/host_center.rb
  app/helpers/application_helper/toolbar/hosts_center.rb
  app/helpers/application_helper/toolbar/middleware_domain_center.rb
  app/helpers/application_helper/toolbar/middleware_server_center.rb
  app/helpers/application_helper/toolbar/middleware_server_group_center.rb
  app/helpers/application_helper/toolbar/middleware_servers_center.rb
  app/helpers/application_helper/toolbar/physical_server_center.rb
  app/helpers/application_helper/toolbar/physical_servers_center.rb
  app/helpers/application_helper/toolbar/vm_clouds_center.rb
  app/helpers/application_helper/toolbar/vm_infras_center.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
Labels: enhancement, gaprindashvili/no, graphics, ux/approved

#3847 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation

#3843 Change Service 'Order' button to blue color to look active
  app/views/catalog/_svccat_tree_show.html.haml
Labels: bug, gaprindashvili/yes, services

#3851 Decorator w/fonticon for VmdbDatabaseConnection and VmdbDatabaseSetting
  app/decorators/vmdb_database_connection_decorator.rb
  app/decorators/vmdb_database_setting_decorator.rb
Labels: gaprindashvili/no, graphics, refactoring

#3827 Timeline menu
  app/controllers/ems_common.rb
  app/controllers/mixins/ems_common_angular.rb
  app/controllers/mixins/more_show_actions.rb
  app/helpers/application_helper/toolbar_chooser.rb
Labels: bug, fine/yes, gaprindashvili/yes, timelines

#3840 Disable credential / repository form when embedded ansible is unavailable
  app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
  app/assets/javascripts/controllers/ansible_repository/repository_form_controller.js
  app/views/ansible_credential/_credential_form.html.haml
  app/views/ansible_repository/_repository_form.html.haml
Labels: automation/ansible, bug, gaprindashvili/yes

#3858 Add a unique random DOM ID for each quadicon and use it in miq_bootstrap
  app/views/shared/_quadicon.html.haml
Labels: bug, gaprindashvili/no

#3807 [FINE] - Removed specific buttons for Network Routers
  app/helpers/application_helper/toolbar/network_router_center.rb
  app/helpers/application_helper/toolbar/network_routers_center.rb
Labels: blocker, bug, networks

#3865 Fix for certain tag categories being unable to be saved as dialog field elements
  app/assets/javascripts/services/dialog_editor_http_service.js
  spec/javascripts/services/dialog_editor_http_service_spec.js
Labels: angular dialogs, bug, gaprindashvili/yes

#3845 [GAPRINDASHVILI] Update ui-components to 1.0.24 for gaprindashvili
  bower.json
Labels: dependencies

#3863 Change fa-cog to pficon-settings in VmdbDatabaseSettingDecorator
  app/decorators/vmdb_database_setting_decorator.rb
Labels: gaprindashvili/no, graphics

#3861 Performance: style fixes.
  app/controllers/application_controller/performance.rb
Labels: gaprindashvili/no, technical debt

#3860 Extract QuadiconHelper.machine_state case to a hash and freeze it
  app/helpers/quadicon_helper.rb
Labels: gaprindashvili/no, refactoring

#3764 [FINE] Add rbac to report definition on users and tenants
  app/controllers/report_controller/reports/editor.rb
  app/helpers/report_helper/editor.rb
  spec/controllers/miq_report_controller/reports/editor_spec.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
  spec/controllers/ops_controller_spec.rb
  spec/helpers/application_helper/views_shared_spec.rb
  spec/presenters/tree_builder_ops_rbac_spec.rb
Labels: blocker, bug, cloud intel/chargeback

#3876 Update physical server toolbar buttons
  app/helpers/application_helper/toolbar/physical_infrastructure/operations_button_group_mixin.rb
Labels: compute/physical infrastructure, enhancement, gaprindashvili/no, graphics

#3874 [GAPRINDASHVILI] Update ui-components to 1.0.25 for gaprindashvili
  bower.json
Labels: dependencies

#3877 Fixes display of VM Retirement State label
  app/helpers/vm_helper/textual_summary.rb
Labels: bug, compute/infrastructure, gaprindashvili/yes

#3866 Clear tag expression field when editing group tag expression
  app/controllers/application_controller/filter.rb
  app/views/layouts/exp_atom/_edit_tags.html.haml
Labels: automation/automate, bug, gaprindashvili/yes

#3879 Do not force exp_key to be limited to "CONTAINS" for date type fields.
  app/controllers/application_controller/filter/expression.rb
Labels: bug, cloud intel/reporting, gaprindashvili/yes
