Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-07, with the labels that each got.

#5766 Fix overrided color for disabled Timelines link
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, changelog/yes, hammer/yes, textual summaries

#5769 Ensure replication related flash messages show task name
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: bug, changelog/yes, hammer/no, settings

#5774 Fix error viewing Customize tab on Requests
  app/views/shared/views/_prov_dialog.html.haml
Labels: bug, changelog/yes, hammer/yes, requests

#5719 Added Price to Catalog Items.
  app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
  app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
  app/controllers/catalog_controller.rb
  app/views/catalog/_form_basic_info.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/catalog/_st_angular_form.html.haml
  app/views/catalog/_svccat_tree_show.html.haml
  spec/controllers/catalog_controller_spec.rb
  spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
Labels: changelog/yes, enhancement, hammer/no, services, ux/review

#5754 Remove deprecated Networks Load Balancer menu
  app/controllers/load_balancer_controller.rb
  app/helpers/application_helper/toolbar/load_balancer_center.rb
  app/helpers/application_helper/toolbar/load_balancers_center.rb
  app/helpers/load_balancer_helper.rb
  app/helpers/load_balancer_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/load_balancer/show.html.haml
  app/views/load_balancer/show_list.html.haml
  spec/controllers/ems_network_controller_spec.rb
  spec/controllers/load_balancer_controller_spec.rb
  spec/helpers/load_balancer_helper/textual_summary_spec.rb
  spec/helpers/load_balancer_helper_spec.rb
  spec/services/dialog_local_service_spec.rb
  spec/shared/controllers/shared_examples_for_ems_network_controller.rb
  spec/shared/controllers/shared_examples_for_load_balancer_controller.rb
  spec/shared/controllers/shared_network_manager_context.rb
  spec/views/layouts/listnav/_load_balancer.html.haml_spec.rb
Labels: changelog/yes, enhancement, hammer/no, networks, technical debt

#5744 Ids in specs
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_common_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/guest_device_controller_spec.rb
  spec/controllers/miq_ae_tools_controller_spec.rb
  spec/controllers/miq_policy_controller_spec.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
  spec/controllers/ops_controller/diagnostics_spec.rb
  spec/controllers/ops_controller/settings/automate_schedules_spec.rb
  spec/controllers/ops_controller/settings/schedules_spec.rb
  spec/controllers/physical_chassis_controller_spec.rb
  spec/controllers/physical_rack_controller_spec.rb
  spec/controllers/physical_server_controller_spec.rb
  spec/controllers/physical_storage_controller_spec.rb
  spec/controllers/physical_switch_controller_spec.rb
  spec/controllers/picture_controller_spec.rb
  spec/helpers/compliance_summary_helper_spec.rb
  spec/helpers/vm_helper/textual_summary_spec.rb
  spec/helpers/vm_helper_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
  spec/views/layouts/list_grid.html.haml_spec.rb
Labels: technical debt, test

#5764 The factory handles this
  spec/controllers/application_controller/compare_spec.rb
Labels: technical debt, test

#5781 These are all unnecessary
  spec/controllers/auth_key_pair_cloud_controller_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5770 Handle nil options and missing keys in ansible credentials
  app/helpers/ansible_credential_helper/textual_summary.rb
  spec/helpers/ansible_credential_helper/textual_summary_spec.rb
Labels: automation/ansible, bug

#5771 Fixed deleting users
  app/controllers/ops_controller/ops_rbac.rb
Labels: blocker, bug, changelog/no, settings

#5757 [Changelog] Update for Hammer-8
  CHANGELOG.md
Labels: documentation, hammer/yes

#5773 Removing more of the extra attributes set by factories
  spec/controllers/application_controller/explorer_spec.rb
  spec/controllers/application_controller/tags_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5782 Add a rubocop channel to the codeclimate config
  .codeclimate.yml
Labels: test

#5778 Revert the sandbox variable refactoring on Settings/Diagnostics trees
  app/controllers/ops_controller/diagnostics.rb
  app/presenters/tree_builder_diagnostics.rb
  app/presenters/tree_builder_roles_by_server.rb
  app/presenters/tree_builder_servers_by_role.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
Labels: bug, hammer/no, trees

#5730 [RFE] Add Clone dashboard form
  app/controllers/report_controller.rb
  app/controllers/report_controller/dashboards.rb
  app/helpers/application_helper/toolbar/miq_widget_set_center.rb
  app/javascript/components/copy-dashboard-form/copy-dashboard-form.jsx
  app/javascript/components/copy-dashboard-form/copy-dashboard-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/copy-dashboard-form/copy-dashboard-form.spec.js
  app/views/report/_copy_dashboard.html.haml
  app/views/report/_db_show.html.haml
  config/routes.rb
  spec/controllers/miq_report_controller/dashboards_spec.rb
Labels: changelog/yes, cloud intel/dashboard, dashboards, enhancement, hammer/no, react, ux/review

#5750 Fix catalog item delete when part of catalog bundle
  app/javascript/components/remove-catalog-item-modal.jsx
Labels: bug, changelog/yes, hammer/no, services

#5788 [HAMMER] Update ui-components to 1.1.29 for hammer
  package.json
  yarn.lock
Labels: dependencies

#5779 Adjust the test against the accordion name at saved reports
  app/controllers/report_controller/saved_reports.rb
  spec/controllers/report_controller_spec.rb
Labels: bug, changelog/yes, cloud intel/reporting, hammer/no

#5768 Revert faster services PR 5366
  product/views/Service.yaml
Labels: bug, hammer/yes, services

#5772 Remove duplicate tagging edit buttons for Services
  app/controllers/service_controller.rb
Labels: bug, services

#5767 fix miq task conditions
  product/views/MiqTask.yaml
Labels: automation/ansible tower, changelog/no, hammer/no, technical debt

#5787 Update ui-components to 1.2.7
  package.json
Labels: dependencies

#5784 Show affected servers on PhysicalServerFirmwareUpdateRequest
  app/controllers/application_controller/miq_request_methods.rb
  app/views/miq_request/_request.html.haml
Labels: compute/physical infrastructure, enhancement

#5786 vm_common#reload spec - prevent sporadic failure when folder id matches vm id
  spec/controllers/vm_common_spec.rb
Labels: bug/sporadic test failure, test

#5760 Add missing gettexts to Tagging
  app/javascript/components/taggingWrapper.jsx
  package.json
Labels: bug, dependencies, internationalization

#5627 Migrate service dialog from orchestration template from to data driven forms
  app/controllers/catalog_controller.rb
  app/javascript/components/orchestration-template/service-dialog-from-ot.jsx
  app/javascript/components/orchestration-template/service-dialog-from-ot.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/orchestration-template/service-dialog-from-ot.spec.js
  app/views/catalog/_service_dialog_from_ot.html.haml
  config/routes.rb
  spec/controllers/catalog_controller_spec.rb
  spec/routing/catalog_routing_spec.rb
Labels: hammer/no, react

#5765 Removes AnsibleTowerJobTemplateDialogService from UI
  app/controllers/automation_manager_controller.rb
  app/services/ansible_tower_job_template_dialog_service.rb
  spec/services/ansible_tower_job_template_dialog_service_spec.rb
Labels: automation/ansible tower, changelog/no, hammer/no, technical debt

#5789 Set value of hash to be deleted from saved data.
  app/controllers/ops_controller/settings/analysis_profiles.rb
  spec/controllers/ops_controller/settings/analysis_profiles_spec.rb
Labels: bug, changelog/yes, hammer/no, settings

#5790 Names and zones are set by the factory
  spec/controllers/automation_manager_controller_spec.rb
Labels: technical debt, test

#5686 Restore the service tree hiearachy and implement lazy loading for nested services
  app/presenters/tree_builder_services.rb
  spec/presenters/tree_builder_services_spec.rb
Labels: bug, hammer/no, services, trees

#5616 Hide columns in GTL lists for non-admin users(not only)
  app/controllers/application_controller.rb
  app/controllers/catalog_controller.rb
  lib/gtl_formatter.rb
  product/views/ServiceTemplate.yaml
  spec/controllers/catalog_controller_spec.rb
Labels: enhancement

#5792 Reverted changes to git import form.
  app/helpers/miq_ae_tools_helper.rb
  app/views/miq_ae_tools/_import_export.html.haml
  spec/helpers/miq_ae_tools_spec.rb
Labels: automation/automate, bug, changelog/yes, hammer/no

#5794 Update ui-components to 1.2.8
  package.json
Labels: dependencies

#5777 Expand the node in DialogEditor/TreeSelector with prefix included
  app/controllers/tree_controller.rb
Labels: bug, hammer/no, trees

#5791 Removed Zone selection from bundle add/edit/details screen
  app/views/catalog/_form_basic_info.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
Labels: bug, changelog/yes, hammer/no, services

#5796 Fix the wording Job -> Task.
  app/helpers/application_helper/toolbar/tasks_center.rb
Labels: bug, changelog/yes, hammer/no, tasks

#5797 Request columns order
  product/views/MiqRequest.yaml
Labels: changelog/yes, hammer/no, requests, technical debt

#5793 Don't set unnecessary attributes with FactoryBot in specs
  spec/controllers/catalog_controller_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5795 [Changelog] Update for Sprint 115
  CHANGELOG.md
Labels: documentation

#5799 Don't set name and description of tags in specs
  spec/controllers/cloud_network_controller_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5783 Fix displaying 'Add a Provider' page on a fresh appliance
  app/services/user_validation_service.rb
  spec/controllers/dashboard_controller_spec.rb
Labels: blocker, bug, cloud intel/dashboard, hammer/no

#5780 Fix Object Attribute Type selection for Group and Tenant
  app/controllers/miq_ae_tools_controller.rb
  app/controllers/ops_controller/settings/automate_schedules.rb
  app/helpers/application_helper.rb
  spec/controllers/miq_ae_tools_controller_spec.rb
Labels: automation/automate, bug, changelog/yes, hammer/yes

#5800 Fix the title/tooltip attribute setting for TreeNode::Menu::Item
  app/presenters/tree_node/menu/item.rb
Labels: bug, hammer/no, trees

#5801 Hide Tenant Name for Infra and Cloud providers in list views for non-admin users
  app/controllers/ems_cloud_controller.rb
  app/controllers/ems_infra_controller.rb
  product/views/ManageIQ_Providers_CloudManager.yaml
  product/views/ManageIQ_Providers_InfraManager.yaml
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
Labels: enhancement

#5803 Adjust the test against accordion name in saved reports (part 2)
  app/controllers/report_controller/saved_reports.rb
Labels: bug, changelog/yes, cloud intel/reporting, hammer/no

#5804 Remove whitespace from attribute name
  app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml
Labels: automation/automate, bug, hammer/no

#5805 [HAMMER] Update ui-components to 1.1.30 for hammer
  package.json
  yarn.lock
Labels: dependencies

#5806 Update ui-components to 1.2.9
  package.json
Labels: dependencies

#5809 Rename the "Cloud Intel" menu item to "Overview"
  app/controllers/chargeback_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/report_controller.rb
  app/presenters/menu/default_menu.rb
  app/presenters/tree_builder.rb
  spec/presenters/menu/custom_loader_spec.rb
Labels: changelog/yes, enhancement, hammer/no, ux/approved

#5763 Mark items for translation on Settings Server tab
  app/views/ops/_settings_server_tab.html.haml
Labels: bug, internationalization, settings

#5811 Don't use string interpolation inside gettext strings
  app/controllers/ems_physical_infra_controller.rb
  app/controllers/ops_controller/settings/upload.rb
  app/controllers/security_group_controller.rb
Labels: bug, internationalization

#5619 Read-only pages for browsing firmware repository
  app/controllers/firmware_binary_controller.rb
  app/controllers/firmware_registry_controller.rb
  app/controllers/firmware_target_controller.rb
  app/helpers/application_helper/toolbar/firmware_registry_center.rb
  app/helpers/firmware_binary_helper.rb
  app/helpers/firmware_binary_helper/textual_summary.rb
  app/helpers/firmware_registry_helper.rb
  app/helpers/firmware_registry_helper/textual_summary.rb
  app/helpers/firmware_target_helper.rb
  app/helpers/firmware_target_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/firmware_binary/show.html.haml
  app/views/firmware_registry/show.html.haml
  app/views/firmware_registry/show_list.html.haml
  app/views/firmware_target/show.html.haml
  app/views/layouts/listnav/_firmware_binary.html.haml
  app/views/layouts/listnav/_firmware_registry.html.haml
  app/views/layouts/listnav/_firmware_target.html.haml
  app/views/miq_request/_physical_server_firmware_update_show.html.haml
  app/views/miq_request/_request.html.haml
  config/routes.rb
  product/views/FirmwareBinary.yaml
  product/views/FirmwareRegistry.yaml
  product/views/FirmwareTarget.yaml
  spec/presenters/menu/default_menu_spec.rb
Labels: enhancement

#5357 Add scopes for filtering Archived/Orphaned VMs based on RBAC
  app/controllers/vm_common.rb
  app/presenters/tree_builder_archived.rb
  spec/presenters/tree_builder_archived_spec.rb
  spec/presenters/tree_builder_images_spec.rb
  spec/presenters/tree_builder_instances_spec.rb
Labels: changelog/yes, compute/cloud, compute/infrastructure, enhancement, hammer/no

#5816 The factory sets the names
  spec/controllers/ansible_repository_controller_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5818 Raise flash message for blank dialog import
  app/controllers/miq_ae_customization_controller.rb
  spec/controllers/miq_ae_customization_controller_spec.rb
Labels: automation/automate, bug

#5684 Introduce AzureStack cloud provider
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/ems_common/angular.rb
  app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  app/views/shared/views/ems_common/angular/_form.html.haml
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Labels: enhancement, graphics

#5820 Allow loading of main.scss from outside this repository
  app/assets/stylesheets/application.css
Labels: bug, hammer/no

#5761 Unify the HTML5 canvas-based remote consoles under a single endpoint
  app/assets/javascripts/remote_consoles/webmks.js
  app/controllers/ops_controller/settings/common.rb
  app/controllers/vm_remote.rb
  app/helpers/application_helper/button/vm_console.rb
  app/helpers/application_helper/button/vm_html5_console.rb
  app/helpers/application_helper/button/vm_vmrc_console.rb
  app/helpers/application_helper/button/vm_vnc_console.rb
  app/helpers/application_helper/button/vm_webmks_console.rb
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/helpers/vmware_console_helper.rb
  app/views/ops/_settings_server_tab.html.haml
  config/routes.rb
  spec/helpers/application_helper/buttons/vm_html5_console_spec.rb
  spec/helpers/application_helper/buttons/vm_vnc_console_spec.rb
  spec/helpers/application_helper/buttons/vm_webmks_console_spec.rb
  spec/helpers/vmware_console_helper_spec.rb
  spec/routing/vm_infra_routing_spec.rb
  spec/support/examples_group/shared_examples_for_vm_console.rb
Labels: changelog/yes, consoles, enhancement, hammer/no

#5821 Remove additional deprecated Load Balancers code in UI
  app/controllers/mixins/ems_common.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_network_helper/textual_summary.rb
  app/helpers/vm_helper/textual_summary.rb
  app/services/network_topology_service.rb
  config/routes.rb
  spec/helpers/ems_network_helper/textual_summary_spec.rb
  spec/helpers/vm_helper/textual_summary_spec.rb
Labels: changelog/yes, enhancement, hammer/no, networks, technical debt

#5667 Add Copy option to Catalog Item/Bundle
  app/controllers/catalog_controller.rb
  app/helpers/application_helper/button/catalog_item_copy_button.rb
  app/helpers/application_helper/toolbar/servicetemplate_center.rb
  app/helpers/application_helper/toolbar/servicetemplates_center.rb
  app/javascript/components/copy-catalog-form/copy-catalog-form.jsx
  app/javascript/components/copy-catalog-form/copy-catalog-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/views/catalog/_copy_catalog.html.haml
  config/routes.rb
Labels: changelog/yes, enhancement, hammer/no, react, services

#5727 Display container Map Tag delete confirmation message
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  app/views/ops/_label_tag_mapping_form.html.haml
Labels: bug, changelog/yes, hammer/yes, settings

#5823 The factory sets name and description.
  spec/controllers/application_controller/build_audit_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5822 Show item's description when edit/copy in Requests
  app/controllers/miq_request_controller.rb
  spec/controllers/miq_request_controller_spec.rb
Labels: breadcrumbs, changelog/no, hammer/no, requests

#5827 Fixed select component in forms
  package.json
Labels: bug, react

#5833 Added styled table react components and data driven variant.
  app/javascript/components/simple-table/simple-table.jsx
  app/javascript/spec/simple-table/__snapshots__/simple-table.spec.js.snap
  app/javascript/spec/simple-table/simple-table.spec.js
Labels: enhancement, react

#5829 Update Font Fabulous to 1.0.5
  manageiq-ui-classic.gemspec
Labels: dependencies

#5832 Fix missing flash message when adding first Container Provider
  app/views/ems_container/show_list.html.haml
  app/views/layouts/_empty.html.haml
Labels: bug, compute/containers, hammer/no

#5828 Added determine_api_endpoints for ContainerVolume
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: bug, changelog/yes, hammer/yes, services

#5838 The factory sets all these again
  spec/controllers/automation_manager_controller_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5171 Sorting, filtering and design of report result tables.
  app/controllers/application_controller.rb
  app/controllers/mixins/controller_constants.rb
  app/controllers/report_controller.rb
  app/controllers/report_controller/saved_reports.rb
  app/helpers/application_helper/button/view_ght_always.rb
  app/helpers/application_helper/toolbar/report_view.rb
  app/javascript/components/report-data-table.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/report-data-table.spec.js
  app/views/layouts/_report_html.html.haml
  app/views/layouts/_saved_report_paging_bar.html.haml
  app/views/layouts/report_only.html.haml
  package.json
Labels: cloud intel/reporting, enhancement, ux/approved

#5819 Overview > Optimization - new screen
  app/controllers/optimization_controller.rb
  app/helpers/application_helper/toolbar/optimizations_center.rb
  app/javascript/components/simple-table/simple-table.jsx
  app/javascript/optimization/listen.js
  app/javascript/optimization/optimization_list.js
  app/javascript/optimization/refresh.js
  app/javascript/optimization/transform.js
  app/javascript/packs/application-common.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/simple-table/__snapshots__/simple-table.spec.js.snap
  app/presenters/menu/default_menu.rb
  app/views/optimization/show.html.haml
  app/views/optimization/show_list.html.haml
  config/routes.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/optimization_controller_spec.rb
  spec/controllers/provider_foreman_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/support/controller_helper.rb
Labels: changelog/yes, cloud intel/reporting, enhancement, hammer/no

#5845 Update ui-components to 1.2.10
  package.json
Labels: dependencies

#5844 We don't need these
  spec/controllers/cloud_object_store_container_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5846 Add release info to About screen title
  app/javascript/components/miq-about-modal.jsx
Labels: enhancement

#5843 Automate method editing bugz
  app/controllers/miq_ae_class_controller.rb
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: automation/automate, bug, changelog/yes, hammer/yes

#5840 AzureStack orchestration template provisioning
  app/controllers/catalog_controller.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/javascript/components/orchestration-template/orchestration-template-form.schema.js
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_orchestration_templates.rb
  product/views/ManageIQ_Providers_AzureStack_CloudManager_OrchestrationTemplate.yaml
  spec/controllers/catalog_controller_spec.rb
Labels: enhancement

#5688 Opening URLs through automate
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/assets/javascripts/services/dialog_field_refresh_service.js
  app/controllers/application_controller/buttons.rb
  app/controllers/application_controller/wait_for_task.rb
  app/services/dialog_local_service.rb
  app/views/shared/buttons/_ab_options_form.html.haml
  app/views/shared/dialogs/_dialog_provision.html.haml
  app/views/shared/dialogs/_dialog_user.html.haml
  spec/javascripts/controllers/dialog_user/dialog_user_controller_spec.js
  spec/services/dialog_local_service_spec.rb
Labels: automation/automate, enhancement

#5848 Remove Embedded Ansible repository unsused attributes
  app/assets/javascripts/controllers/ansible_repository/repository_form_controller.js
  app/controllers/mixins/embedded_ansible_refresh_mixin.rb
  app/helpers/ansible_repository_helper/textual_summary.rb
  app/views/ansible_repository/_repository_form.html.haml
  spec/helpers/ansible_repository_helper/textual_summary_spec.rb
  spec/javascripts/controllers/ansible_repository/ansible_repository_form_controller_spec.js
Labels: automation/ansible

#5807 Fix Chargeback tree for report
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_chargeback_reports.rb
  spec/presenters/tree_builder_spec.rb
Labels: bug, cloud intel/chargeback, cloud intel/reporting

#5849 Fix Embedded Ansible Respository refresh
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/controllers/mixins/embedded_ansible_refresh_mixin.rb
Labels: bug, changelog/yes, embedded ansible, hammer/no

#5842 Make create dialog from template reusable
  app/javascript/components/service-dialog-from-form/service-dialog-from.jsx
  app/javascript/components/service-dialog-from-form/service-dialog-from.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/service-dialog-from-form/service-dialog-from-form.spec.js
  app/views/catalog/_service_dialog_from_ot.html.haml
Labels: changelog/no, enhancement, hammer/no, react

#5836 Override pf class for chart tooltip background
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, charts

#5785 [HAMMER] Improve the performance the lazy-loading of services tree by caching
  app/presenters/tree_builder_services.rb
Labels: bug, performance, trees

#5855 Handle network managers in the dialog local service
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: bug, hammer/no

#5841 [Changelog] Update for Hammer-9
  CHANGELOG.md
Labels: documentation, hammer/yes

#5852 These are set by the factory
  spec/controllers/cloud_tenant_controller_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5857 Fix custom button group `Display on Button` option
  app/controllers/application_controller/buttons.rb
Labels: automation/automate, bug, ivanchuk/yes

#5858 Select the features tree items when 'everything' is allowed
  app/presenters/tree_node/menu/item.rb
  app/presenters/tree_node/miq_product_feature.rb
Labels: bug, hammer/no, ivanchuk/yes, rbac, trees

#5865 [IVANCHUK] yarn: lock by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies

#5868 [Changelog] Update for Sprint 116
  CHANGELOG.md
Labels: documentation

#5870 Permission store: fix specs.
  spec/helpers/application_helper_spec.rb
Labels: ivanchuk/yes, test

#5866 Do not build the regex for embedded method when there's no fqname
  app/controllers/miq_ae_class_controller.rb
Labels: automation/automate, bug, hammer/yes, ivanchuk/yes

#5856 Dialog copy - remove ids pointing to the original dialog
  app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
Labels: angular dialogs, bug, hammer/yes, ivanchuk/yes

#5850 Use React component to create service dialog from ansible tower
  app/controllers/automation_manager_controller.rb
  app/controllers/mixins/manager_controller_mixin.rb
  app/views/automation_manager/_configscript_service_dialog.html.haml
  config/routes.rb
  spec/controllers/automation_manager_controller_spec.rb
Labels: changelog/no, hammer/no, react

#5861 These are all set by the factory
  spec/controllers/automation_manager_controller_spec.rb
Labels: changelog/no, hammer/no, refactoring, test

#5869 Fixed container provider custom button dialog redirect.
  app/services/dialog_local_service.rb
Labels: bug, compute/containers, hammer/yes, ivanchuk/yes

#5839 Allow returning back to the previous controller, after clicking on Back button and to cancel policy sim properly
  app/controllers/mixins/actions/vm_actions/policy_simulation.rb
  app/views/layouts/_x_edit_buttons.html.haml
  config/routes.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/views/layouts/_x_edit_buttons.html.haml_spec.rb
Labels: bug, compute/infrastructure, hammer/yes, ivanchuk/yes

#5872 Remove delimiter for Request ID
  app/views/miq_request/_request.html.haml
Labels: enhancement, ivanchuk/yes

#5874 Fix resizer blocking paginator elements
  app/assets/stylesheets/patternfly_overrides.scss
Labels: blocker, bug, formatting/styling, hammer/yes, ivanchuk/yes

#5871 These are set by the factory, again
  spec/controllers/cloud_object_store_object_spec.rb
Labels: changelog/no, hammer/no, ivanchuk/no, refactoring, test

#5859 Removed gettext changing value for Analysis Profiles
  app/views/ops/_ap_form_set.html.haml
Labels: bug, ivanchuk/yes, settings

#5814 Fix Policy breadcrumbs when coming from GTL page
  app/controllers/mixins/breadcrumbs_mixin.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: bug, hammer/no

#5614 Migrated PXE servers forms to react
  app/assets/stylesheets/dynamic_prefix_form_input.scss
  app/assets/stylesheets/main.scss
  app/controllers/pxe_controller.rb
  app/controllers/pxe_controller/pxe_servers.rb
  app/javascript/components/async-credentials/async-credentials.jsx
  app/javascript/components/async-credentials/edit-secret-field.jsx
  app/javascript/components/async-credentials/secret-switch-field.jsx
  app/javascript/components/pxe-servers-form/pxe-server-form.jsx
  app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
  app/javascript/forms/input-with-dynamic-prefix.jsx
  app/javascript/forms/mappers/formsFieldsMapper.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/async-credentials/__snapshots__/secret-switch-field.spec.js.snap
  app/javascript/spec/async-credentials/secret-switch-field.spec.js
  app/javascript/spec/dual-list-select/__snapshots__/dual-list-select.spec.js.snap
  app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
  app/javascript/spec/forms/input-with-dynamic-prefix.spec.js
  app/javascript/spec/helpers/fieldProvider.js
  app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
  app/javascript/spec/pxe-servers-form/pxe-server-form.spec.js
  app/views/pxe/_pxe_form.html.haml
  config/routes.rb
  spec/controllers/pxe_controller_spec.rb
  spec/routing/pxe_routing_spec.rb
Labels: hammer/no, ivanchuk/no, react

#5883 [HAMMER] Add spec:jest, spec:javascript and spec:compile back
  .travis.yml
Labels: developer

#5837 Generalized check for accordion in params when selecting (saved)reports
  app/controllers/report_controller/saved_reports.rb
  spec/controllers/report_controller_spec.rb
Labels: bug, changelog/yes, cloud intel/reporting, hammer/no, ivanchuk/yes

#5887 Fixed JS snapshot test mismatch.
  app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
Labels: bug, test

#5880 The factory sets all these again
  spec/controllers/cloud_volume_backup_controller_spec.rb
Labels: changelog/no, hammer/no, ivanchuk/no, refactoring, test

#5888 Fixed rubocop standard error warning in pxe_servers.rb
  app/controllers/pxe_controller/pxe_servers.rb
Labels: compute/infrastructure, technical debt

#5885 Update travis spec for corner cases
  spec/other/travis_spec.rb
Labels: ivanchuk/yes, test

#5890 These are all set by the factory again
  spec/controllers/cloud_subnet_controller_spec.rb
Labels: changelog/no, hammer/no, ivanchuk/no, refactoring, test

#5886 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#5875 user_input_filter - don't send Cancel on Apply
  app/assets/javascripts/miq_application.js
  app/controllers/application_controller/filter.rb
  app/views/layouts/_user_input_filter.html.haml
Labels: bug, compute/infrastructure, hammer/yes, ivanchuk/yes

#5894 [HAMMER] Update ui-components to 1.1.31 for hammer
  package.json
  yarn.lock
Labels: dependencies

#5882 [IVANCHUK] Update travis.yml for ivanchuk
  .travis.yml
Labels: developer

#5891 Removed antipatterns from the spec for BreadcrumbsMixin
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: breadcrumbs, hammer/no, ivanchuk/no, technical debt, test

#5879 [IVANCHUK] Add json i18n catalogs for ivanchuk
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
Labels: internationalization

#5889 Store the nodes as objects in the TreeBuilder instead of JSON
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_automation_manager_configuration_scripts.rb
  app/presenters/tree_builder_configured_systems.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
  spec/controllers/provider_foreman_controller_spec.rb
  spec/presenters/tree_builder_ae_class_spec.rb
  spec/presenters/tree_builder_automate_catalog_spec.rb
  spec/presenters/tree_builder_automate_spec.rb
  spec/presenters/tree_builder_chargeback_assignments_spec.rb
  spec/presenters/tree_builder_chargeback_rates_spec.rb
  spec/presenters/tree_builder_menu_roles_spec.rb
  spec/presenters/tree_builder_ops_rbac_spec.rb
  spec/presenters/tree_builder_report_roles_spec.rb
  spec/presenters/tree_builder_report_saved_reports_spec.rb
  spec/presenters/tree_builder_spec.rb
Labels: changelog/yes, hammer/no, ivanchuk/no, refactoring, trees

#5893 Add title for clone_to_template edit action
  app/controllers/application_controller/miq_request_methods.rb
  spec/controllers/miq_request_controller_spec.rb
Labels: changelog/no, compute/infrastructure, ivanchuk/yes, requests

#5898 Added missing argument in function definition
  app/controllers/application_controller/compare.rb
  spec/controllers/application_controller/compare_spec.rb
Labels: bug, changelog/yes, compute/infrastructure, hammer/yes, ivanchuk/yes

#5900 Show value of Locked/Reset fields when value is false or not set.
  app/views/report/_db_show.html.haml
Labels: bug, changelog/yes, cloud intel/dashboard, ivanchuk/yes

#5899 Filter out Maintenance zone from the drop down
  app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
Labels: bug, changelog/yes, ivanchuk/yes, services

#5878 Fixed issues with 'Back' button on right size screen
  app/controllers/vm_common.rb
  app/views/vm_common/_right_size.html.haml
  spec/controllers/vm_controller_spec.rb
Labels: bug, changelog/yes, compute/infrastructure, hammer/yes, ivanchuk/yes

#5472 Make Add button respond properly on changes while adding Catalog Item
  app/controllers/catalog_controller.rb
  app/helpers/params_helper.rb
  spec/controllers/catalog_controller_spec.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes, services

#5903 We don't need to set urls here
  spec/controllers/automation_manager_controller_spec.rb
Labels: changelog/no, hammer/no, ivanchuk/no, refactoring, test

#5897 Allow to copy from 'read only' CodeMirror editor
  app/assets/javascripts/miq_application.js
Labels: bug, services

#5830 Fixed Error in Restore Cloud Volume Backup
  app/controllers/cloud_volume_backup_controller.rb
Labels: blocker, bug, ivanchuk/yes, storage

#5908 Make the check against Satellite organization safe to fix RHSM issues
  app/controllers/ops_controller/settings/rhn.rb
Labels: bug, hammer/yes, ivanchuk/yes

#5826 Make editing schedule with EVM Group/Tenant type work
  app/controllers/ops_controller/settings/automate_schedules.rb
  spec/controllers/ops_controller/settings/automate_schedules_spec.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes, networks

#5902 Propagate parent model into GTLs on InfraNetwork switches 🖵 🐞
  app/controllers/infra_networking_controller.rb
  app/presenters/tree_builder_infra_networking.rb
Labels: bug, compute/infrastructure, explorers, hammer/yes, ivanchuk/yes

#5905 Filters header renamed to Global Filters
  app/views/layouts/listnav/_show_list.html.haml
Labels: bug, compute/infrastructure, hammer/yes, ivanchuk/yes

#5906 user_input_filter: Don't autofocus selects
  app/views/layouts/_user_input_filter.html.haml
Labels: bug, expressions/filters, hammer/yes, ivanchuk/yes

#5909 Clear modal after Applying advanced search
  app/views/layouts/_adv_search_footer.html.haml
Labels: bug, compute/cloud, hammer/yes, ivanchuk/yes

#5775 Remove password fields from ansible credentials details page
  app/helpers/ansible_credential_helper/textual_summary.rb
  spec/helpers/ansible_credential_helper/textual_summary_spec.rb
Labels: automation/ansible, bug, ux/review
