Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-01, with the labels that each got.

#5113 set_ownership - use miq_template (not vm) for images
  app/controllers/mixins/actions/vm_actions/ownership.rb
Labels: bug, compute/cloud, hammer/yes

#4958 Remove invalid compliances references
  product/views/PhysicalChassis.yaml
  product/views/PhysicalRack.yaml
  product/views/PhysicalServer.yaml
Labels: technical debt

#5118 Stop spinner after rednering flash message
  app/controllers/miq_ae_class_controller.rb
Labels: automation/automate, bug, hammer/yes

#5119 Fixed saving of role/group visibility for a widget
  app/controllers/report_controller/widgets.rb
  spec/controllers/report_controller/widget_spec.rb
Labels: bug, cloud intel/reporting, hammer/yes

#5120 PhysicalInfraTopologyService spec - expect manager to have Valid status, not nil
  spec/services/physical_infra_topology_service_spec.rb
Labels: hammer/no, test

#5124 Updated right cell header
  app/controllers/service_controller.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, hammer/yes, services

#5112 [HAMMER] set_ownership - use miq_template (not vm) for images
  app/controllers/mixins/actions/vm_actions/ownership.rb
Labels: blocker, bug

#5125 Add missing gettext into exp_editor.html.haml
  app/views/layouts/_exp_editor.html.haml
Labels: bug, hammer/no, internationalization

#5122 Add missing gettext to zone dropdown in My Tasks screen
  app/views/miq_task/_tasks_options.html.haml
Labels: bug, hammer/no, internationalization

#5114 Cluster textual summary: add translatable label
  app/helpers/ems_cluster_helper/textual_summary.rb
Labels: bug, hammer/no, internationalization

#5115 Add missing gettext into ems_common/angular/_form.html.haml
  app/views/shared/views/ems_common/angular/_form.html.haml
Labels: hammer/no, internationalization

#5116 Add translatable labels to Host textual summary
  app/helpers/host_helper/textual_summary.rb
Labels: bug, hammer/no, internationalization

#5127 Bug 1650484: Update misleading form label for new Cloud Tenant form
  app/javascript/components/cloud-tenant-form/create-form-schema.js
  app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap
Labels: bug, compute/cloud, hammer/yes

#5130 Fixed regression on schedules screen due to bad towhat refactoring
  app/controllers/report_controller/schedules.rb
Labels: bug, cloud intel/reporting, hammer/no

#5126 Remove logic for request screen dialogs
  app/views/miq_request/_request_dialog_details.html.haml
  app/views/miq_request/_st_prov_show.html.haml
Labels: bug, gaprindashvili/yes, hammer/yes

#5134 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#5106 Update patternfly to 3.59.1
  manageiq-ui-classic.gemspec
  package.json
Labels: dependencies, hammer/no

#5129 Add spec for button tenant manage quota in OpsController
  spec/helpers/application_helper/buttons/basic_spec.rb
Labels: test

#4896 Bug 1480819: Fix labels for Scale Infrastructure Provider form
  app/helpers/ems_infra_helper.rb
  app/views/ems_infra/scaling.html.haml
Labels: bug, hammer/yes

#5055 Flavor add form converted to data-driven-forms
  app/assets/javascripts/controllers/flavor/flavor_form_controller.js
  app/javascript/components/flavor-form/add-form-schema.js
  app/javascript/components/flavor-form/flavor-form.jsx
  app/javascript/helpers/miq-redirect-back.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap
  app/javascript/spec/flavor-form/flavor-form.spec.js
  app/javascript/spec/helpers/miqFlashLater.js
  app/views/flavor/_flavor_form.html.haml
  app/views/flavor/new.html.haml
  package.json
Labels: compute/cloud, hammer/no, react, refactoring

#5121 Adds dual list react component
  app/javascript/components/dual-list-select/helpers.jsx
  app/javascript/components/dual-list-select/index.jsx
  app/javascript/components/dual-list-select/list.jsx
  app/javascript/forms/data-driven-form.jsx
  app/javascript/forms/mappers/formsFieldsMapper.jsx
  app/javascript/spec/dual-list-select/__snapshots__/dual-list-select.spec.js.snap
  app/javascript/spec/dual-list-select/dual-list-select.spec.js
  app/javascript/spec/dual-list-select/helpers.spec.js
  app/javascript/spec/helpers/fieldProvider.js
Labels: hammer/no, react, refactoring

#5142 Fix usage of TreeBuilder.extract_node_model_and_id in OpcControler
  app/controllers/ops_controller/ops_rbac.rb
  spec/helpers/application_helper/buttons/basic_spec.rb
Labels: blocker, bug, hammer/yes

#5143 Send button_order via API
  app/assets/javascripts/components/generic_object/main-custom-button-group-form.js
Labels: automation/automate, bug, gaprindashvili/yes, generic objects, hammer/yes

#5149 Fix missing paging in provisioning template selection
  app/controllers/application_controller/miq_request_methods.rb
Labels: bug, hammer/yes

#5150 remove outdated IE properties
  app/assets/stylesheets/miq_tree.scss
  app/assets/stylesheets/patternfly_overrides.scss
Labels: formatting/styling, hammer/no, technical debt

#5146 Unify sorting in GOD page
  app/views/generic_object_definition/_show_actions.html.haml
  app/views/generic_object_definition/_show_custom_button_group.html.haml
  app/views/generic_object_definition/_table_button.html.haml
Labels: automation/automate, bug, bugzilla needed, gaprindashvili/yes, generic objects, hammer/yes

#5144 Dont show gtl checkbox when display list from chart click
  app/controllers/application_controller/performance.rb
  app/controllers/host_controller.rb
  app/controllers/vm_controller.rb
  app/helpers/application_helper.rb
Labels: bug, charts, compute/infrastructure, hammer/yes

#5136 Rename WebsocketWorker to RemoteConsoleWorker
  app/controllers/ops_controller/settings/common.rb
  app/views/ops/_settings_workers_tab.html.haml
Labels: consoles, hammer/no

#5161 Properly handle non-existent hash key
  app/controllers/pxe_controller.rb
Labels: bug, compute/infrastructure, hammer/no

#5060 Added "Preserve owner?" checkbox on Import report screen
  app/controllers/report_controller.rb
  app/views/report/_export_custom_reports.html.haml
Labels: cloud intel/reporting, enhancement, hammer/yes

#5156 Make policy export strings fully translatable
  app/views/miq_policy/_export.html.haml
Labels: bug, hammer/no, internationalization

#5162 Dashboard (under Reports) - fix broken accordion_select; use @dashboard, not @db
  app/controllers/dashboard_controller.rb
  app/controllers/report_controller.rb
  app/controllers/report_controller/dashboards.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/dashboard_delete.rb
  app/helpers/application_helper/button/db_delete.rb
  app/helpers/application_helper/toolbar/miq_widget_set_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/views/report/_db_form.html.haml
  app/views/report/_db_list.html.haml
  app/views/report/_db_widget_remove.html.haml
  app/views/report/_db_widgets.html.haml
  spec/controllers/miq_report_controller/dashboards_spec.rb
  spec/helpers/application_helper/buttons/dashboard_delete_spec.rb
  spec/views/report/_db_widget_remove.html.haml_spec.rb
Labels: bug, cloud intel/dashboard, hammer/no

#5148 Show breadcrumbs when redirected from another controller
  app/controllers/ems_cloud_controller.rb
  app/controllers/ems_container_controller.rb
  app/controllers/ems_infra_controller.rb
  spec/controllers/ems_infra_controller_spec.rb
Labels: bug, hammer/yes, monitor

#5160 Add Status Attribute to Cloud Volume Detail screen
  app/helpers/cloud_volume_helper/textual_summary.rb
  spec/helpers/cloud_volume_helper/textual_summary_spec.rb
Labels: enhancement, storage

#5169 Add translatable label to auth key pair textual summary
  app/helpers/auth_key_pair_cloud_helper/textual_summary.rb
Labels: bug, hammer/no, internationalization

#5168 Add translatable labels to orchestration stack textual summary
  app/helpers/orchestration_stack_helper/textual_summary.rb
Labels: bug, hammer/no, internationalization

#5154 [GAPRINDASHVILI] Fix editing tags from container provider page
  app/controllers/application_controller/tags.rb
Labels: blocker, bug

#5174 [GAPRINDASHVILI] [WIP] Change datastores to data_stores
  spec/services/dialog_local_service_spec.rb
Labels: test

#4753 Do not allow to embed a method into itself in automate
  app/assets/javascripts/controllers/miq_ae_class/ae_inline_method_selection_controller.js
  app/controllers/miq_ae_class_controller.rb
  app/views/miq_ae_class/_embedded_methods.html.haml
  spec/controllers/miq_ae_class_controller_spec.rb
Labels: automation/automate, bug, hammer/yes

#5175 rake yarn:clobber - an easy way to remove node_modules & yarn.lock from all engines
  lib/tasks/manageiq/ui_tasks.rake
Labels: developer, hammer/no

#5184 Fixed typo in textual_zone spec filename
  spec/helpers/textual_mixins/textual_zone_spec.rb
Labels: hammer/no, test

#5183 [Changelog] Update for Sprint 103
  CHANGELOG.md
Labels: documentation

#5176 Fixed check in if condition
  app/controllers/application_controller/filter/expression.rb
  spec/controllers/application_controller/filter/expression_spec.rb
Labels: bug, expressions/filters, hammer/yes

#5189 Fixed display of worker memory threshold settings
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: bug, hammer/yes, settings

#5191 Exclude form schemas
  .codeclimate.yml
  app/javascript/components/cloud-tenant-form/cloud-tenant-form.jsx
  app/javascript/components/cloud-tenant-form/create-form.schema.js
  app/javascript/components/flavor-form/flavor-form.jsx
  app/javascript/components/flavor-form/flavor-form.schema.js
  app/javascript/components/service-form/index.jsx
  app/javascript/components/service-form/service-form.schema.js
  app/javascript/components/set-service-ownership-form/index.jsx
  app/javascript/components/set-service-ownership-form/ownership-form.schema.js
  app/javascript/spec/set-service-ownership-form/set-service-ownership-form.spec.js
Labels: developer

#5195 Added missing unit label
  app/services/container_dashboard_service.rb
  spec/services/container_dashboard_service_spec.rb
Labels: bug, compute/containers, hammer/yes

#5199 Make LDAP Users searchable
  app/views/ops/_ldap_auth_users.html.haml
Labels: blocker, enhancement, gaprindashvili/yes, hammer/yes

#5201 Add create-react-context dependency to fix react-bootstrap-typeahead failure
  package.json
Labels: dependencies, hammer/no

#5186 Allow `blob:` type in img-src CSP for WebMKS remote consoles
  app/controllers/vm_remote.rb
Labels: bug, consoles, gaprindashvili/yes, hammer/yes

#5202 Allow the user to upload a custom favicon image in Custom Logos
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/upload.rb
  app/helpers/application_helper.rb
  app/views/dashboard/oidc_login.html.haml
  app/views/dashboard/saml_login.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/login.html.haml
  app/views/layouts/print.html.haml
  app/views/layouts/remote_console.html.haml
  app/views/layouts/report_only.html.haml
  app/views/ops/_settings_custom_logos_tab.html.haml
  app/views/vm_common/console_vmrc.html.haml
  config/routes.rb
Labels: enhancement, graphics

#5209 Fixed labels that should not be links
  app/helpers/host_helper/textual_summary.rb
Labels: bug, compute/infrastructure, hammer/no

#5203 API/http - explicitly send cookie for api requests
  app/javascript/http_api/api.js
  app/javascript/http_api/fetch.js
  app/javascript/http_api/http.js
  spec/javascripts/components/physical_infrastructures/physical-server-toolbar_spec.js
  spec/javascripts/helpers/toolbar.js
Labels: bug, hammer/no

#5206 sync_from_file is deprecated in favor of seed_dialog
  spec/requests/restful_redirect_spec.rb
Labels: technical debt, test

#5205 Fix travis failure caused by ManageIQ/manageiq#18378
  spec/services/topology_service_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes, test

#5208 Add missing styling to user input filter modal
  app/views/layouts/_user_input_filter.html.haml
Labels: bug, formatting/styling

#5198 Cloud Volume textual summary: add translatable labels
  app/helpers/cloud_volume_helper/textual_summary.rb
Labels: bug, hammer/no, internationalization

#5192 Fix displaying selected dashboard while clicking on its tab
  app/controllers/dashboard_controller.rb
  spec/controllers/dashboard_controller_spec.rb
Labels: bug, cloud intel/dashboard, hammer/yes

#5213 Require yarn>=1.0.0
  package.json
Labels: dependencies, hammer/no

#5200 Bug 1664888: Allow OpenStack infra providers without ironic
  app/controllers/mixins/ems_common_angular.rb
  app/helpers/application_helper/button/ems_infra_scale.rb
Labels: compute/infrastructure, enhancement

#5212 Delete the "report_menus" instead of :report_menus when resetting
  app/controllers/report_controller/menus.rb
  spec/controllers/miq_report_controller/menus_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes
