Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-10, with the labels that each got.

#6250 Use active scope for vms in VmCommon
  app/controllers/vm_common.rb
Labels: technical debt

#6219 Switch find_by_* to lookup_by_*
  app/controllers/application_controller/current_user.rb
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/application_controller/performance.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_policy_controller/miq_actions.rb
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  app/controllers/ops_controller/settings/tags.rb
  app/controllers/report_controller/reports/editor.rb
  app/controllers/report_controller/schedules.rb
  app/services/user_validation_service.rb
  spec/controllers/application_controller/performance_spec.rb
  spec/controllers/report_controller_spec.rb
Labels: ivanchuk/no, refactoring

#6257 [Changelog] Update for Sprint 121
  CHANGELOG.md
Labels: documentation

#6251 consolidate topology styling
  app/assets/stylesheets/application.css
  app/assets/stylesheets/container_topology.css
  app/assets/stylesheets/physical_infra_topology.scss
  app/assets/stylesheets/topology.scss
Labels: cleanup, formatting/styling, ivanchuk/no

#6237 Provider validate - don't attempt to directly connect from the UI
  app/controllers/mixins/ems_common/angular.rb
  spec/controllers/ems_cloud_controller_spec.rb
Labels: bug, compute/infrastructure, ivanchuk/no

#6217 Allow resetting changes while editing Zone's Password or Verify Password fields
  app/controllers/ops_controller/settings/zones.rb
  spec/controllers/ops_controller/settings/zones_spec.rb
Labels: bug, ivanchuk/yes, settings

#6255 Remove the possibility to chose of quadicon/single quad in GTLs
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/helpers/configuration_helper.rb
  app/views/configuration/_ui_1.html.haml
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_container_controller_spec.rb
  spec/controllers/host_controller_spec.rb
Labels: cleanup, ivanchuk/no

#6266 [Changelog] Add missing PRs from Sprint 121
  CHANGELOG.md
Labels: documentation

#6265 Update Access Restriction to current state in role detail
  app/views/ops/_rbac_role_details.html.haml
Labels: technical debt

#6254 Correctly apply gettext to MiqDialog::DIALOG_TYPES
  app/controllers/miq_ae_customization_controller/old_dialogs.rb
  app/presenters/tree_builder_provisioning_dialogs.rb
  app/views/miq_ae_customization/_old_dialogs_form.html.haml
Labels: bug, internationalization, ivanchuk/yes

#5997 Toolbar: React rewrite and simplification.
  app/assets/javascripts/controllers/toolbar_controller.js
  app/assets/javascripts/miq_application.js
  app/assets/javascripts/miq_explorer.js
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/topology-toolbar.scss
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/basic.rb
  app/helpers/application_helper/toolbar/base.rb
  app/helpers/application_helper/toolbar/catalogitem_button_center.rb
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/container_node_center.rb
  app/helpers/application_helper/toolbar/custom.rb
  app/helpers/application_helper/toolbar/custom_button_center.rb
  app/helpers/application_helper/toolbar/dashboard_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
  app/helpers/application_helper/toolbar/logs_center.rb
  app/helpers/application_helper/toolbar/physical_server_center.rb
  app/helpers/application_helper/toolbar/report_view.rb
  app/helpers/application_helper/toolbar/topology_center.rb
  app/helpers/application_helper/toolbar/vm_performance.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/helpers/application_helper/toolbar/x_vm_performance.rb
  app/helpers/application_helper/toolbar_builder.rb
  app/helpers/toolbar_helper.rb
  app/javascript/components/dashboard_toolbar.jsx
  app/javascript/components/miq-toolbar.jsx
  app/javascript/components/topology_toolbar.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/toolbar/__snapshots__/dashboard_toolbar.spec.jsx.snap
  app/javascript/spec/toolbar/__snapshots__/miq-generic-toolbar.spec.jsx.snap
  app/javascript/spec/toolbar/__snapshots__/topology_toolbar.spec.jsx.snap
  app/javascript/spec/toolbar/dashboard_toolbar.spec.jsx
  app/javascript/spec/toolbar/miq-generic-toolbar.spec.jsx
  app/javascript/spec/toolbar/miq-toolbar.spec.jsx
  app/javascript/spec/toolbar/topology_toolbar.spec.jsx
  app/views/dashboard/_widgets_menu.html.haml
  app/views/layouts/_center_div_dashboard_no_listnav.html.haml
  app/views/layouts/_center_div_no_listnav.html.haml
  app/views/layouts/_center_div_with_listnav.html.haml
  app/views/layouts/_content.html.haml
  app/views/layouts/angular/_toolbar.html.haml
  app/views/shared/_topology_header_toolbar.html.haml
  config/jest.setup.js
  jest.config.js
  package.json
  spec/javascripts/controllers/toolbar_controller_spec.js
  spec/javascripts/miq_application_spec.js
Labels: enhancement, ivanchuk/no, toolbars

#6259 Refactor optimization_controller to use default breadcrumbs methods
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/controllers/optimization_controller.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
  spec/controllers/optimization_controller_spec.rb
Labels: breadcrumbs, changelog/no, ivanchuk/no, optimize, technical debt

#6198 Fix error on Cloud Provider Dashboard
  app/services/ems_dashboard_service.rb
  spec/services/ems_dashboard_service_spec.rb
Labels: bug, changelog/yes, compute/cloud, ivanchuk/yes

#6264 Fixed low z-index on ddf select menu.
  app/assets/stylesheets/application.css
  app/assets/stylesheets/data_driven_forms_overrides.scss
  app/javascript/forms/mappers/formsFieldsMapper.jsx
Labels: bug, changelog/yes, ivanchuk/yes, react, services

#6269 Completely remove the records2table method as its obsolete
  app/controllers/application_controller/policy_support.rb
  app/controllers/application_controller/tags.rb
  app/controllers/host_controller.rb
  app/controllers/mixins/actions/vm_actions/evacuate.rb
  app/controllers/mixins/actions/vm_actions/live_migrate.rb
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/controllers/mixins/actions/vm_actions/retire.rb
  lib/report_formatter/converter.rb
Labels: cleanup, cloud intel/reporting, ivanchuk/no, technical debt

#6248 Convert part of Infra Provider dashboard to React, add Quadicon.
  app/assets/stylesheets/aggregate_status_card.scss
  app/assets/stylesheets/application.css
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/javascript/components/aggregate_status_card.jsx
  app/javascript/components/pf_aggregate_status_card.jsx
  app/javascript/packs/component-definitions-common.js
  app/services/ems_cloud_dashboard_service.rb
  app/services/ems_dashboard_service.rb
  app/services/ems_infra_dashboard_service.rb
  app/services/ems_physical_infra_dashboard_service.rb
  app/views/cloud_tenant/_show_dashboard.html.haml
  app/views/ems_cloud/_show_dashboard.html.haml
  app/views/ems_infra/_show_dashboard.html.haml
  app/views/ems_physical_infra/_show_dashboard.html.haml
  app/views/physical_infra_overview/show.html.haml
Labels: dashboards, enhancement, ivanchuk/no, ux/approved

#6176 Update react version to 16.9.x
  app/javascript/components/miq-about-modal.jsx
  config/webpack/shared.js
  package.json
Labels: react

#6262 styling cleanup
  app/assets/stylesheets/application.css
  app/assets/stylesheets/main.scss
Labels: cleanup, formatting/styling, ivanchuk/no, unmergeable, wip

#6270 Set grid type in GTLs on migrate, retire and evacuate screens
  app/controllers/mixins/actions/vm_actions/evacuate.rb
  app/controllers/mixins/actions/vm_actions/live_migrate.rb
  app/controllers/mixins/actions/vm_actions/retire.rb
Labels: ivanchuk/no, technical debt, ux/review

#6274 Fixed jest tests after React update
  app/javascript/spec/automate-import-export-form/__snapshots__/import-datastore-via-git.spec.js.snap
  app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js
  app/javascript/spec/catalog-form/catalog-form.spec.js
  app/javascript/spec/cloud-network-form/cloud-network-form.spec.js
  app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
  app/javascript/spec/flavor-form/flavor-form.spec.js
  app/javascript/spec/pxe-servers-form/pxe-server-form.spec.js
Labels: react, technical debt, test

#6276 fix styling issue in header
  app/assets/images/layout/navbar.png
  app/assets/stylesheets/header_background.scss
  app/assets/stylesheets/main.scss
Labels: bug, changelog/yes, cleanup, formatting/styling, graphics, ivanchuk/no

#6275 Async jest tests
  app/javascript/components/report-data-table.jsx
  app/javascript/spec/async-credentials/async-credentials.spec.js
  app/javascript/spec/copy-dashboard-form/copy-dashboard-form.spec.js
  app/javascript/spec/flavor-form/flavor-form.spec.js
  app/javascript/spec/forms/input-with-dynamic-prefix.spec.js
  app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js
  app/javascript/spec/orchestration-template/orchestration-template-form.spec.js
  app/javascript/spec/pxe-servers-form/pxe-server-form.spec.js
  app/javascript/spec/report-data-table.spec.js
  app/javascript/spec/set-ownership-form/set-ownership-form.spec.js
  app/javascript/spec/workers-form/workers-form.spec.js
  config/jest.setup.js
Labels: react, technical debt, test

#6277 Fix loading of Network Port details screen
  app/helpers/network_port_helper/textual_summary.rb
  spec/shared/controllers/shared_network_manager_context.rb
Labels: bug, ivanchuk/yes, networks

#6272 Apply gettext to MiqReport::Generator model constant
  app/controllers/report_controller/reports/editor.rb
  app/views/report/_form_sort.html.haml
Labels: bug, internationalization, ivanchuk/yes

#6280 VmCommon: split get_node_info.
  app/controllers/vm_common.rb
Labels: explorers, ivanchuk/no, refactoring, technical debt, trees

#6281 Automate explorer: split get_node_info, make variables more readable.
  app/controllers/miq_ae_class_controller.rb
  spec/controllers/miq_ae_class_controller_spec.rb
Labels: automation/automate, ivanchuk/no, refactoring, technical debt, trees

#6285 Test against the right accor when switching to chargeback reports
  app/controllers/chargeback_controller.rb
Labels: bug, changelog/yes, cloud intel/chargeback, ivanchuk/yes

#6144 Make Automate Domains and Providers clickable from the list displayed through Tenant's Relationships
  app/controllers/automation_manager_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/ops_controller.rb
  app/controllers/provider_foreman_controller.rb
  app/controllers/restful_redirect_controller.rb
  app/helpers/application_helper.rb
  app/views/miq_ae_class/show.html.haml
  app/views/provider_foreman/show.html.haml
  config/routes.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/miq_ae_class_controller_spec.rb
  spec/controllers/ops_controller_spec.rb
  spec/controllers/provider_foreman_controller_spec.rb
  spec/controllers/restful_redirect_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/views/miq_ae_class/show.html.haml_spec.rb
  spec/views/provider_foreman/show.html.haml_spec.rb
Labels: enhancement, settings

#6284 Display only one Cancel button for Compare action
  app/controllers/application_controller/compare.rb
Labels: bug, compute/infrastructure

#6235 Fix tagging for Edit Group and Provisioning screens
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/ops_controller/ops_rbac.rb
  app/javascript/components/taggingWrapper.jsx
  package.json
Labels: bug, tagging

#6283 Add Provider to List view of Infra/Hosts and Infra/Datastores
  product/views/Host.yaml
  product/views/Storage.yaml
Labels: compute/infrastructure, enhancement

#6211 Upgrade to babel 7 and jest 24
  .babelrc
  .babelrc.js
  app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
  app/javascript/spec/async-credentials/__snapshots__/edit-secret-field.spec.js.snap
  app/javascript/spec/dual-list-select/__snapshots__/dual-list-select.spec.js.snap
  app/javascript/spec/orchestration-template/orchestration-template-form.spec.js
  app/javascript/spec/simple-table/__snapshots__/simple-table.spec.js.snap
  app/javascript/spec/toolbar/__snapshots__/miq-generic-toolbar.spec.jsx.snap
  config/jest.setup.js
  config/webpack/shared.js
  jest.config.js
  package.json
Labels: dependencies

#6233 Do not update breadcrumbs when ops/change_tab
  app/controllers/ops_controller.rb
  spec/controllers/ops_controller_spec.rb
Labels: breadcrumbs, bug, ivanchuk/yes

#6289 Fix toolbar button with function
  app/controllers/network_router_controller.rb
  app/helpers/application_helper/toolbar/base.rb
  app/helpers/application_helper/toolbar/firmware_registries_center.rb
  app/helpers/application_helper/toolbar/firmware_registry_center.rb
  app/helpers/application_helper/toolbar/generic_object_definition_center.rb
  app/helpers/application_helper/toolbar/generic_object_definitions_center.rb
  app/helpers/application_helper/toolbar/network_router_center.rb
  app/helpers/application_helper/toolbar/network_routers_center.rb
  app/helpers/application_helper/toolbar/optimizations_center.rb
  app/helpers/application_helper/toolbar/physical_storage_center.rb
  app/helpers/application_helper/toolbar/physical_storages_center.rb
  app/helpers/application_helper/toolbar/servicetemplate_center.rb
  app/helpers/application_helper/toolbar/servicetemplates_center.rb
  app/javascript/components/miq-toolbar.jsx
  spec/controllers/network_router_controller_spec.rb
Labels: ivanchuk/no, toolbars

#6294 Fixed error when saving replication subscription with params[:subscriptions]been nil
  app/controllers/ops_controller/settings/common.rb
Labels: bug, ivanchuk/yes, settings

#6293 Add Refresh button to Ansible Tower Jobs page
  app/controllers/configuration_job_controller.rb
  app/helpers/application_helper/toolbar/configuration_jobs_center.rb
Labels: changelog/no, enhancement, ivanchuk/no, toolbars

#6297 Check button.data isn't null
  app/javascript/components/miq-toolbar.jsx
Labels: bug, ivanchuk/no, toolbars

#6278 Disable "Apply" button when all sections are deselected.
  app/controllers/application_controller/compare.rb
  app/views/layouts/listnav/_compare_sections.html.haml
  spec/controllers/application_controller/compare_spec.rb
  spec/views/layouts/listnav/_compare_sections.html.haml_spec.rb
Labels: bug, compute/cloud, compute/infrastructure, ivanchuk/yes

#6302 Remove dead layouts/angular-bootstrap/_ae_resolve_options
  app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml
Labels: cleanup

#6299 Add missing ui-lookup to make Object Attribute consistent
  app/views/shared/buttons/_ab_show.html.haml
Labels: bug, ivanchuk/yes, services

#6273 Move node expandedness evaluation into TreeNode::Node
  app/presenters/tree_builder.rb
  app/presenters/tree_node/hash.rb
  app/presenters/tree_node/node.rb
Labels: ivanchuk/no, refactoring, trees

#6304 Remove zanata from README
  README.md
Labels: cleanup, internationalization, ivanchuk/no

#6301 Toolbar Simplification follow-up
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/diagnostics_server_center.rb
  app/helpers/application_helper/toolbar/ems_cloud_center.rb
  app/helpers/application_helper/toolbar/ems_clouds_center.rb
  app/helpers/application_helper/toolbar/ems_container_center.rb
  app/helpers/application_helper/toolbar/ems_containers_center.rb
  app/helpers/application_helper/toolbar/ems_infra_center.rb
  app/helpers/application_helper/toolbar/ems_infras_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
  app/helpers/application_helper/toolbar/firmware_registries_center.rb
  app/helpers/application_helper/toolbar/firmware_registry_center.rb
  app/helpers/application_helper/toolbar/physical_servers_center.rb
  app/helpers/application_helper/toolbar/physical_switch_center.rb
  app/helpers/application_helper/toolbar/physical_switches_center.rb
  app/helpers/application_helper/toolbar/tasks_center.rb
  app/helpers/application_helper/toolbar/template_clouds_center.rb
Labels: formatting/styling, ivanchuk/no

#6286 Renamed 'Generic Object Classes' to 'Generic Object Definitions'
  app/assets/javascripts/components/generic_object/generic-object-definition.js
  app/controllers/generic_object_definition_controller.rb
  app/helpers/application_helper/toolbar/generic_object_definition_center.rb
  app/helpers/application_helper/toolbar/generic_object_definitions_center.rb
  app/presenters/tree_builder_generic_object_definition.rb
  app/views/generic_object_definition/_show_god.html.haml
  app/views/generic_object_definition/_show_list.html.haml
  app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml
  product/views/GenericObjectDefinition.yaml
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: generic objects

#6267 Allow editing and other actions on selected Host Aggregate
  app/controllers/host_aggregate_controller.rb
  app/controllers/mixins/ems_common.rb
  config/routes.rb
  spec/controllers/host_aggregate_controller_spec.rb
  spec/controllers/mixins/ems_common_spec.rb
Labels: bug, compute/cloud

#6315 Toolbar update - topology
  app/javascript/components/topology_toolbar.jsx
  app/javascript/spec/toolbar/__snapshots__/topology_toolbar.spec.jsx.snap
Labels: formatting/styling, ivanchuk/no

#6319 Fix toolbar initialization.
  app/javascript/components/miq-toolbar.jsx
Labels: bug, ivanchuk/no, toolbars

#6288 ChargebackRateDetail: Apply gettext to model constants
  app/controllers/chargeback_controller.rb
  app/views/chargeback/_tier_first_row.haml
Labels: bug, internationalization, ivanchuk/yes

#6321 Toolbar: pass keepSpinner to the toolbar.
  app/helpers/application_helper/toolbar_builder.rb
Labels: bug, ivanchuk/no, toolbars

#6322 Fix edit of GOD custom button
  app/assets/javascripts/components/generic_object/main-custom-button-form.js
Labels: bug, generic objects, ivanchuk/yes

#6325 Fix logout on group change
  app/assets/javascripts/miq_application.js
  app/assets/javascripts/miq_global.js
  app/views/layouts/_user_options.html.haml
Labels: bug, ivanchuk/yes, settings

#6256 Fix cancel buttons and some history cleanup
  app/controllers/application_controller/compare.rb
  app/controllers/application_controller/explorer.rb
  app/controllers/catalog_controller.rb
  app/controllers/generic_object_definition_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/mixins/manager_controller_mixin.rb
  app/controllers/pxe_controller.rb
  app/controllers/report_controller.rb
  app/controllers/service_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/toolbar_chooser.rb
Labels: bug, cleanup, ivanchuk/no

#6316 Display only one Back button for Policy simulation
  app/controllers/vm_common.rb
  spec/controllers/vm_common_spec.rb
Labels: bug, compute/infrastructure, ivanchuk/no

#6326 Fix password input length
  app/views/ops/_rbac_user_details.html.haml
Labels: formatting/styling, ivanchuk/yes, settings

#6324 Toolbar view separation
  app/javascript/components/miq-toolbar.jsx
Labels: bug, ivanchuk/no, toolbars

#6331 Update ui-components to 1.3.2
  package.json
Labels: dependencies

#6330 Dropbox removed, in exchange for using support tool
  app/views/static/ops/log_collection/log_collection.html.haml
Labels: enhancement, settings

#6341 Re adding RH dropbox support, and making it readonly along with support
  app/views/static/ops/log_collection/log_collection.html.haml
Labels: enhancement, ivanchuk/no, settings

#6340 [HAMMER] Dropbox removed, in exchange for using support tool
  app/views/ops/_log_collection.html.haml
Labels: enhancement, settings

#6343 [HAMMER] Fix hammer/master difference problem with backport of #6330 and #6341
  app/views/ops/_log_collection.html.haml
Labels: bug, settings

#6353 Update toolbar snapshots
  app/javascript/spec/toolbar/__snapshots__/miq-toolbar.spec.jsx.snap
Labels: changelog/no, ivanchuk/no, react, test

#6359 Fix eslint
  .eslintrc.json
  app/javascript/.eslintrc.json
  package.json
Labels: developer, ivanchuk/no
