Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-12, with the labels that each got.

#6467 Fix rubocop in EmsNetworkController
  app/controllers/ems_network_controller.rb
Labels: technical debt

#6461 Fix rubocop in EmsInfraController
  app/controllers/ems_infra_controller.rb
Labels: changelog/yes, technical debt

#6460 Fix rubocop in EmsContainerController
  app/controllers/ems_container_controller.rb
Labels: changelog/no, technical debt

#6459 Fix rubocop in EmsClusterController
  app/controllers/ems_cluster_controller.rb
Labels: changelog/no, technical debt

#6454 Fix rubocop warnings in ConfigurationController
  app/controllers/configuration_controller.rb
Labels: changelog/no, technical debt

#6455 Fix rubocop warning in ContainerDashboardController
  app/controllers/container_dashboard_controller.rb
Labels: changelog/no, technical debt

#6456 Fix rubocop warning in EmsCloudController
  app/controllers/ems_cloud_controller.rb
Labels: changelog/no, technical debt

#6466 Machine Credential: don't access options hash when null
  app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
Labels: bug, embedded ansible, ivanchuk/yes

#6470 Fix rubocop in ApplicationController
  app/controllers/application_controller.rb
Labels: changelog/no, technical debt

#6468 Fix rubocop in EmsPhysicalInfraController
  app/controllers/ems_physical_infra_controller.rb
Labels: changelog/no, technical debt

#6482 Generalize queue matching.
  spec/controllers/cloud_volume_controller_spec.rb
Labels: test

#6471 Fix rubocop in ApplicationController::AdvancedSearch
  app/controllers/application_controller/advanced_search.rb
Labels: changelog/no, technical debt

#6472 Fix rubocop in ApplicationController::Buttons
  app/controllers/application_controller/buttons.rb
Labels: changelog/no, technical debt

#6473 Fix rubocop in ApplicationController::CiProcessing
  app/controllers/application_controller/ci_processing.rb
Labels: changelog/no, technical debt

#6474 Fix rubocop in ApplicationController::Compare
  app/controllers/application_controller/compare.rb
Labels: changelog/no, technical debt

#6476 Fix rubocop in ApplicationController::DialogRunner
  app/controllers/application_controller/dialog_runner.rb
Labels: changelog/no, technical debt

#6483 Fix rubocop in ApplicationController::MiqRequestMethods
  app/controllers/application_controller/miq_request_methods.rb
Labels: changelog/no, technical debt

#6484 Fix rubocop in ApplicationController::Performance::ChartClickData
  app/controllers/application_controller/performance/chart_click_data.rb
Labels: changelog/no, technical debt

#6485 Fix rubocop in ApplicationController::Performance::Options
  app/controllers/application_controller/performance/options.rb
Labels: changelog/no, technical debt

#6477 Fix rubocop in ApplicationController::Explorer
  app/controllers/application_controller/explorer.rb
Labels: changelog/no, technical debt

#6479 Fix rubocop in ApplicationController::Filter
  app/controllers/application_controller/filter.rb
Labels: changelog/no, technical debt

#6478 Fix rubocop in ApplicationController::Filter::Expression
  app/controllers/application_controller/filter/expression.rb
Labels: changelog/no, technical debt

#6369 Make Save button respond properly on changes in User's Available Groups
  app/controllers/ops_controller/ops_rbac.rb
  app/views/ops/_rbac_group_selected.html.haml
  spec/controllers/ops_controller/ops_rbac_spec.rb
  spec/views/ops/_rbac_group_selected.html.haml_spec.rb
Labels: bug, settings

#6469 Reconfigure: use detailed RBAC features.
  app/controllers/miq_request_controller.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/helpers/application_helper/button/vm_reconfigure.rb
  app/helpers/application_helper/button/vm_reconfigure_multiple.rb
  app/helpers/application_helper/toolbar/template_clouds_center.rb
  app/helpers/application_helper/toolbar/vm_infras_center.rb
  app/helpers/application_helper/toolbar/x_template_cloud_center.rb
  app/views/vm_common/_reconfigure.html.haml
  spec/helpers/application_helper/buttons/vm_reconfigure_spec.rb
  spec/shared/helpers/application_helper_buttons.rb
Labels: changelog/yes, compute/infrastructure, enhancement

#6490 fixes service#display deprecation msg
  spec/presenters/tree_builder_services_spec.rb
Labels: technical debt, test

#6492 compare cleanup follow-up
  app/assets/stylesheets/patternfly_overrides.scss
Labels: changelog/no, cleanup, formatting/styling, ivanchuk/no

#6463 Move $().setupVerticalNavigation(...) logic to React
  app/assets/javascripts/miq_application.js
  app/assets/stylesheets/vertical_navigation.scss
  app/javascript/components/main-menu/helpers.js
  app/javascript/components/main-menu/main-menu.jsx
  app/javascript/components/main-menu/second-level.jsx
  app/javascript/components/main-menu/third-level.jsx
  app/javascript/components/main-menu/top-level.jsx
  app/javascript/components/top-navbar/index.js
  app/javascript/components/top-navbar/navbar-header.jsx
  app/javascript/miq-redux/menu-reducer.js
  app/javascript/miq-redux/store.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/main-menu/__snapshots__/main-menu.spec.js.snap
  app/javascript/spec/main-menu/main-menu.spec.js
  app/views/layouts/_header.html.haml
  app/views/layouts/_navbar-header.html.haml
Labels: react, refactoring, technical debt

#6292 Disable Save/Reset buttons after discarding changes for Subscription
  app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
Labels: bug, ivanchuk/yes, settings

#6499 Multiple issues fixed on action edit screen
  app/controllers/miq_policy_controller/miq_actions.rb
  spec/controllers/miq_policy_controller/miq_actions_spec.rb
Labels: bug, changelog/yes, control

#6503 Fix cloud_object_store and cloud_tenant queue_opts
  spec/controllers/cloud_object_store_container_spec.rb
  spec/controllers/cloud_tenant_controller_spec.rb
Labels: test

#6502 miq_qe - support debounced.cancel, debounced.flush
  app/assets/javascripts/miq_qe.js
Labels: developer

#6505 Don't test exact queue_options when testing operations
  spec/controllers/cloud_network_controller_spec.rb
  spec/controllers/cloud_subnet_controller_spec.rb
  spec/controllers/cloud_volume_controller_spec.rb
  spec/controllers/cloud_volume_snapshot_controller_spec.rb
  spec/controllers/floating_ip_controller_spec.rb
  spec/controllers/host_aggregate_controller_spec.rb
  spec/controllers/network_router_controller_spec.rb
  spec/controllers/security_group_controller_spec.rb
  spec/services/git_based_domain_import_service_spec.rb
Labels: test

#6511 Entry Point modal styling fix
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, formatting/styling, ivanchuk/yes

#6512 Remove custom "table-borderless" class
  app/assets/stylesheets/patternfly_overrides.scss
Labels: cleanup, formatting/styling, ivanchuk/no

#6514 Update specs for storage belonging to an EMS
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: test

#6517 Fix rubocop in CloudVolumeBackupController
  app/controllers/cloud_volume_backup_controller.rb
Labels: technical debt

#6486 Fix rubocop in ApplicationController::Performance
  app/controllers/application_controller/performance.rb
Labels: changelog/no, technical debt

#6495 Fix rubocop in ApplicationController::PolicySupport
  app/controllers/application_controller/policy_support.rb
Labels: changelog/no, technical debt

#6496 Fix rubocop in ApplicationController::ReportDownloads
  app/controllers/application_controller/report_downloads.rb
Labels: changelog/no, technical debt

#6508 Fix rubocop in ApplicationController::Timelines
  app/controllers/application_controller/timelines.rb
Labels: changelog/no, technical debt

#6507 Fix rubocop in ApplicationController::Timelines::Options
  app/controllers/application_controller/timelines/options.rb
Labels: changelog/no, technical debt

#6501 Fix rubocop in ApplicationController::Tags
  app/controllers/application_controller/tags.rb
Labels: changelog/no, technical debt

#6500 Fix rubocop in ApplicationController::SysprepAnswerFile
  app/controllers/application_controller/sysprep_answer_file.rb
Labels: changelog/no, technical debt

#6497 Fix rubocop in ApplicationController::SessionSize
  app/controllers/application_controller/session_size.rb
Labels: changelog/no, technical debt

#6516 Remove unnecessary code from GenericObjectDefinitionController
  app/controllers/generic_object_definition_controller.rb
Labels: changelog/no, technical debt

#6515 Fix rubocop in GenericObjectController
  app/controllers/generic_object_controller.rb
Labels: changelog/no, technical debt

#6518 Remove unnecessary one-liner from cloudVolumeBackupForm
  app/assets/javascripts/components/cloud_volume_backup/cloud-volume-backup-form.js
Labels: technical debt

#6525 Fix rubocop warnings in DashboardController
  app/controllers/dashboard_controller.rb
Labels: changelog/no, technical debt

#6526 Fix rubocop in HostController
  app/controllers/host_controller.rb
Labels: changelog/no, technical debt

#6527 Fix rubocop in HostAggregateController
  app/controllers/host_aggregate_controller.rb
Labels: changelog/no, technical debt

#6528 Fix rubocop in InfraNetworkingController
  app/controllers/infra_networking_controller.rb
Labels: changelog/no, technical debt

#6491 Allow performing Shelve Offload operation for Instances in a nested list
  app/controllers/application_controller/ci_processing.rb
  app/controllers/orchestration_stack_controller.rb
  spec/controllers/cloud_tenant_controller_spec.rb
  spec/controllers/mixins/ems_common_spec.rb
  spec/controllers/orchestration_stack_controller_spec.rb
Labels: bug, compute/cloud

#6522 Reimplement token generation for cockpit webconsole proxy
  app/controllers/dashboard_controller.rb
Labels: blocker, bug, ivanchuk/yes

#6531 Updates for Ivanchuk-2
  CHANGELOG.md
Labels: documentation

#6524 webpack - merge sharedPackages and resolve.alias
  config/webpack/RailsEnginesPlugin.js
  config/webpack/shared.js
  package.json
Labels: developer

#6530 Automate Ansible: host+input params for playbooks, input params for workflows
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
  app/views/miq_ae_class/_angular_inputs_form.html.haml
Labels: automation/automate, enhancement

#6529 Toolbars: use kebabLimit to set number of visible custom buttons.
  app/helpers/application_helper.rb
  app/javascript/components/miq-toolbar.jsx
  app/javascript/spec/toolbar/miq-toolbar.spec.jsx
  app/views/layouts/_center_div_dashboard_no_listnav.html.haml
  app/views/layouts/_center_div_no_listnav.html.haml
  app/views/layouts/_center_div_with_listnav.html.haml
  app/views/layouts/_content.html.haml
  config/settings.yml
  package.json
Labels: changelog/yes, enhancement, toolbars

#6532 Replace "action" class in Chargeback with "action-cell"
  app/assets/stylesheets/patternfly_overrides.scss
  app/views/chargeback/_cb_rate_edit_table.html.haml
  app/views/chargeback/_tier_first_row.haml
  app/views/chargeback/_tier_row.haml
Labels: cleanup, formatting/styling, ivanchuk/no

#6535 Fix rubocop in MiqAeClassController
  app/controllers/miq_ae_class_controller.rb
Labels: changelog/no, technical debt

#6536 Fix rubocop in MiqAeCustomizationController::CustomButtons
  app/controllers/miq_ae_customization_controller/custom_buttons.rb
Labels: changelog/no, technical debt

#6537 Fix rubocop in MiqAeCustomizationController::Dialogs
  app/controllers/miq_ae_customization_controller/dialogs.rb
Labels: changelog/no, technical debt

#6538 Fix rubocop in MiqAeCustomizationController
  app/controllers/miq_ae_customization_controller.rb
Labels: changelog/no, technical debt

#6541 Fixed right cell title to show missing info for Policy record.
  app/controllers/miq_policy_controller/policies.rb
Labels: bug, changelog/yes, control

#6533 Fixed code to pass in `service_template` in ae_attributes hash
  app/assets/javascripts/components/generic_object/main-custom-button-form.js
  spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js
Labels: bug, changelog/yes, generic objects, services

#6426 Enable Check Compliance toolbar button for nested list of VMs and make it work
  app/controllers/application_controller/ci_processing.rb
  app/controllers/ems_cluster_controller.rb
  app/controllers/host_controller.rb
  app/controllers/resource_pool_controller.rb
  app/helpers/application_helper/toolbar/vm_clouds_center.rb
  app/helpers/application_helper/toolbar/vm_infras_center.rb
  spec/controllers/auth_key_pair_cloud_controller_spec.rb
  spec/controllers/availability_zone_controller_spec.rb
  spec/controllers/cloud_tenant_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_cluster_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/flavor_controller_spec.rb
  spec/controllers/host_aggregate_controller_spec.rb
  spec/controllers/host_controller_spec.rb
  spec/controllers/resource_pool_controller_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_cloud_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: bug

#6458 Allow performing operations on Instances of a chosen Cloud Network
  app/controllers/cloud_network_controller.rb
  config/routes.rb
  spec/controllers/cloud_network_controller_spec.rb
Labels: bug

#6498 Allow performing operations on Instances of a chosen Network Router
  app/controllers/application_controller/ci_processing.rb
  app/controllers/network_router_controller.rb
  config/routes.rb
  spec/controllers/network_router_controller_spec.rb
Labels: bug, changelog/yes

#6547 Fix rubocop in MiqPolicyController::Alerts
  app/controllers/miq_policy_controller/alerts.rb
Labels: changelog/no, technical debt

#6546 Fix rubocop in MiqPolicyController::AlertProfiles
  app/controllers/miq_policy_controller/alert_profiles.rb
Labels: technical debt

#6545 Fix rubocop in MiqAeToolsController
  app/controllers/miq_ae_tools_controller.rb
Labels: changelog/no, technical debt

#6550 Toolbars: remove unused variable.
  app/helpers/application_helper/toolbar/compare_center.rb
  app/helpers/application_helper/toolbar/drift_center.rb
Labels: changelog/no, technical debt

#6520 Allow performing operations on Instances of a chosen Security Group
  app/controllers/application_controller/ci_processing.rb
  app/controllers/security_group_controller.rb
  config/routes.rb
  spec/controllers/security_group_controller_spec.rb
Labels: bug, unmergeable

#6548 Remove Middleware* from Performance and MiqPolicy controller
  app/controllers/application_controller/performance.rb
  app/controllers/miq_policy_controller/alert_profiles.rb
  app/controllers/miq_policy_controller/alerts.rb
  app/helpers/term_of_service_helper.rb
  app/views/layouts/_perf_options.html.haml
  product/views/MiddlewareDeployment.yaml
  product/views/MiddlewareDomain.yaml
  product/views/MiddlewareServer.yaml
  product/views/MiddlewareServerGroup.yaml
Labels: bug, technical debt

#6539 Display Search box in Infra Networking page
  app/controllers/infra_networking_controller.rb
  app/views/infra_networking/explorer.html.haml
  spec/controllers/infra_networking_controller_spec.rb
Labels: bug, changelog/yes

#6557 Fix rubocop in MiqRequestController
  app/controllers/miq_request_controller.rb
Labels: changelog/no, technical debt

#6552 Fix rubocop in MiqPolicyController::Events
  app/controllers/miq_policy_controller/events.rb
Labels: changelog/no, technical debt

#6551 Fix rubocop in MiqPolicyController::Conditions
  app/controllers/miq_policy_controller/conditions.rb
Labels: changelog/no, technical debt

#6553 Fix rubocop in MiqPolicyController::MiqActions
  app/controllers/miq_policy_controller/miq_actions.rb
Labels: changelog/no, technical debt

#6554 Fix rubocop in MiqPolicyController::Policies
  app/controllers/miq_policy_controller/policies.rb
Labels: changelog/no, technical debt

#6556 Fix rubocop in MiqPolicyController
  app/controllers/miq_policy_controller.rb
Labels: changelog/no, technical debt

#6555 Fix rubocop in MiqPolicyController::PolicyProfiles
  app/controllers/miq_policy_controller/policy_profiles.rb
Labels: changelog/no, technical debt

#6558 Update patternfly-react to get rid of warnings with new react
  config/webpack/shared.js
  package.json
Labels: changelog/yes, javascript infrastructure

#6488 Allow performing operations on Instances of a chosen Cloud Subnet
  app/controllers/application_controller/ci_processing.rb
  app/controllers/cloud_subnet_controller.rb
  config/routes.rb
  spec/controllers/cloud_subnet_controller_spec.rb
Labels: bug, changelog/yes

#6560 Split out masthead styling
  app/assets/stylesheets/application.css
  app/assets/stylesheets/masthead.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/patternfly_overrides.scss
Labels: cleanup, formatting/styling, ivanchuk/no

#6565 Prevent rendering User to Look Up form field twice and with same id
  app/views/ops/_rbac_group_details.html.haml
Labels: bug

#6562 Fix rubocop in MiqTaskController
  app/controllers/miq_task_controller.rb
Labels: technical debt

#6563 Fix rubocop in MiqTemplateController
  app/controllers/miq_template_controller.rb
Labels: technical debt

#6564 Fix rubocop in HostActions::Discover mixin
  app/controllers/mixins/actions/host_actions/discover.rb
Labels: technical debt

#6567 Fix rubocop in Mixins::Actions::VmActions::AssociateFloatingIp
  app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb
Labels: technical debt

#6568 Fix rubocop in Mixins::Actions::VmActions::DisassociateFloatingIp
  app/controllers/mixins/actions/vm_actions/disassociate_floating_ip.rb
Labels: technical debt

#6569 Fix rubocop in Mixins::Actions::VmActions::Evacuate
  app/controllers/mixins/actions/vm_actions/evacuate.rb
Labels: technical debt

#6566 Fix rubocop in Mixins::Actions::HostAction::Misc
  app/controllers/mixins/actions/host_actions/misc.rb
Labels: technical debt

#6571 Remove useless toolbar button for Container Build scan (SSA)
  app/helpers/application_helper/toolbar/container_build_center.rb
  app/helpers/application_helper/toolbar/container_builds_center.rb
Labels: cleanup
