Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-03, with the labels that each got.

#5291 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes

#5289 Fixes value of validate_id in host form
  app/assets/javascripts/controllers/host/host_form_controller.js
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  spec/javascripts/controllers/host/host_form_controller_spec.js
Labels: bug, compute/infrastructure, hammer/yes

#5271 Remove Timelines and RSS UI
  app/controllers/alert_controller.rb
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/report_controller/dashboards.rb
  app/controllers/report_controller/widgets.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/title.rb
  app/javascript/angular/dashboard/index.js
  app/javascript/angular/dashboard/widget-rss.js
  app/javascript/angular/dashboard/widget-wrapper.js
  app/javascript/spec/dashboard/widget-wrapper.spec.js
  app/presenters/menu/default_menu.rb
  app/presenters/tree_builder_report_widgets.rb
  app/presenters/tree_builder_timelines.rb
  app/services/widget_import_service.rb
  app/views/alert/_rss_list.html.haml
  app/views/alert/show_list.html.haml
  app/views/dashboard/timeline.html.haml
  app/views/layouts/listnav/_timeline.html.haml
  app/views/report/_db_widget.html.haml
  app/views/report/_widget_form_rss.html.haml
  app/views/report/_widget_show.html.haml
  config/routes.rb
  spec/controllers/miq_report_controller/widgets_spec.rb
  spec/helpers/application_helper/title_spec.rb
  spec/presenters/tree_builder_report_widgets_spec.rb
  spec/presenters/tree_builder_timelines_spec.rb
  spec/routing/alert_routing_spec.rb
  spec/services/widget_import_service_spec.rb
Labels: cloud intel/timelines, technical debt

#5193 Fix sumary screen for catalog item with deleted provider template
  app/controllers/catalog_controller.rb
  app/views/catalog/explorer.html.haml
Labels: bug, hammer/yes, services

#5292 Fixed wrong keyword for selected nodes in TreeBuilderAlertProfileObj
  app/presenters/tree_builder_alert_profile_obj.rb
  spec/presenters/tree_builder_alert_profile_obj_spec.rb
Labels: bug, hammer/no, trees

#5283 [Performance] Remove compliance from VmOrTemplate includes
  product/views/VmOrTemplate.yaml
Labels: bug, compute/infrastructure, fine/yes, gaprindashvili/yes, hammer/yes, performance

#5265 Add error when clicking upload image without selecting a file
  app/assets/javascripts/components/generic_object/custom-image.js
  app/views/static/generic_object/custom-image.html.haml
Labels: automation/automate, bug, generic objects, hammer/yes, ux/approved

#5294 Remove the obsolete assert_type method from TreeBuilder
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_alert_profile.rb
  app/presenters/tree_builder_condition.rb
  app/presenters/tree_builder_policy.rb
  app/presenters/tree_builder_report_dashboards.rb
Labels: cleanup, hammer/no, trees

#5267 Dialog Editor - rework tree params, *don't* pre-initialize the tree
  app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
  app/assets/javascripts/services/dialog_editor_http_service.js
  app/views/miq_ae_customization/editor.html.haml
Labels: automation/automate, enhancement

#5255 Allow Approver user to deny the request
  app/helpers/application_helper/button/miq_request.rb
  app/helpers/application_helper/toolbar/miq_request_center.rb
  spec/helpers/application_helper/buttons/miq_request_approval_spec.rb
Labels: bug, hammer/yes, requests

#5301 Rename and refactor miqOnCheckMenuRoles in miq_tree.js
  app/assets/javascripts/miq_tree.js
  app/presenters/tree_builder_menu_roles.rb
  spec/presenters/tree_builder_menu_roles_spec.rb
Labels: hammer/no, refactoring, trees

#5298 Catalog trees: move the unassigned node add into the ServiceCatalogs
  app/presenters/tree_builder_catalog_items.rb
  app/presenters/tree_builder_catalogs_class.rb
Labels: hammer/no, refactoring, trees

#5296 Move common parts of CBA and CBR trees into TreeBuilderChargeback
  app/presenters/tree_builder_chargeback.rb
  app/presenters/tree_builder_chargeback_assignments.rb
  app/presenters/tree_builder_chargeback_rates.rb
Labels: hammer/no, refactoring, trees

#5299 Operate with open_nodes through options instead of TreeState
  app/presenters/tree_builder_iso_datastores.rb
  app/presenters/tree_builder_ops_vmdb.rb
  app/presenters/tree_builder_pxe_servers.rb
  app/presenters/tree_builder_report_reports.rb
Labels: hammer/no, refactoring, trees

#5307 Update ui-components to 1.2.2
  package.json
Labels: dependencies

#5304 Drop the default onclick handler from TreeBuilder as it's not used
  app/assets/javascripts/miq_tree.js
  app/presenters/tree_builder.rb
Labels: cleanup, hammer/no, trees

#5312 styling fix for vm edit screen
  app/views/vm_common/_form.html.haml
Labels: compute/infrastructure, formatting/styling, hammer/no

#5313 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#5187 CustomButtonSet - don't touch children/members directly, set button_order
  app/controllers/application_controller/buttons.rb
  app/controllers/generic_object_definition_controller.rb
Labels: enhancement, pending core, toolbars

#5302 Fix highlighting the condition in accordion after creating it
  app/controllers/miq_policy_controller/conditions.rb
  spec/controllers/miq_policy_controller/conditions_spec.rb
  spec/controllers/miq_policy_controller_spec.rb
Labels: bug, control, hammer/yes

#5306 When activating a tree node, make it visible by scrolling onto it
  app/assets/javascripts/miq_tree.js
Labels: bug, hammer/no, trees

#5317 Remove unused variable from infra networking controller
  app/controllers/infra_networking_controller.rb
  spec/controllers/infra_networking_controller_spec.rb
Labels: bug, compute/infrastructure, gaprindashvili/yes, hammer/yes

#5310 Container trends chart - wait for loadingDone before displaying pf-trends-chart
  app/views/ems_container/_trends-chart.html.haml
Labels: bug, compute/containers, gaprindashvili/no, hammer/yes

#5319 Fix failing travis - stub my_server when dealing with custom button sets
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: test

#5308 Fix unhandled promise catch in catalog form
  app/javascript/components/catalog-form/catalog-form.jsx
Labels: hammer/no, react, services

#5309 Unify the signature of TreeBuilder#initialize to 4+1 arguments
  app/controllers/application_controller/automate.rb
  app/controllers/application_controller/compare.rb
  app/controllers/application_controller/policy_support.rb
  app/controllers/configuration_controller.rb
  app/controllers/host_controller.rb
  app/controllers/miq_policy_controller/rsop.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/generic_show_mixin.rb
  app/controllers/mixins/more_show_actions.rb
  app/controllers/ops_controller/diagnostics.rb
  app/controllers/ops_controller/settings/cap_and_u.rb
  app/controllers/ops_controller/settings/common.rb
  app/controllers/vm_common.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_alert_profile_obj.rb
  app/presenters/tree_builder_automate.rb
  app/presenters/tree_builder_automate_simulation_results.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_compliance_history.rb
  app/presenters/tree_builder_datacenter.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_default_filters.rb
  app/presenters/tree_builder_diagnostics.rb
  app/presenters/tree_builder_genealogy.rb
  app/presenters/tree_builder_menu_roles.rb
  app/presenters/tree_builder_miq_action_category.rb
  app/presenters/tree_builder_network.rb
  app/presenters/tree_builder_ops_rbac_features.rb
  app/presenters/tree_builder_policy_simulation_results.rb
  app/presenters/tree_builder_protect.rb
  app/presenters/tree_builder_report_reports.rb
  app/presenters/tree_builder_sections.rb
  app/presenters/tree_builder_smartproxy_affinity.rb
  app/presenters/tree_builder_storage_adapters.rb
  app/presenters/tree_builder_tags.rb
  app/presenters/tree_builder_vat.rb
  spec/presenters/tree_builder_automate_simulation_results_spec.rb
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_compliance_history_spec.rb
  spec/presenters/tree_builder_datacenter_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/presenters/tree_builder_default_filters_spec.rb
  spec/presenters/tree_builder_genealogy_spec.rb
  spec/presenters/tree_builder_miq_action_category_spec.rb
  spec/presenters/tree_builder_network_spec.rb
  spec/presenters/tree_builder_policy_simulation_results_spec.rb
  spec/presenters/tree_builder_protect_spec.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
  spec/presenters/tree_builder_sections_spec.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
  spec/presenters/tree_builder_smartproxy_affinity_spec.rb
  spec/presenters/tree_builder_storage_adapters_spec.rb
  spec/presenters/tree_builder_vat_spec.rb
  spec/views/ops/_settings_cu_collection_tab.html.haml_spec.rb
Labels: hammer/no, refactoring, trees

#5311 [HAMMER] Update ui-components to 1.1.20 for hammer
  package.json
  yarn.lock
Labels: dependencies

#5330 Fix 'Tried to load angular more than once'
  config/webpack/shared.js
Labels: dependencies

#5327 Automate import service fix.
  app/services/automate_import_service.rb
Labels: automation/automate, bug

#5284 Added promise debounce library (with updated typescript) and async validation in Catalog form
  app/javascript/components/catalog-form/catalog-form.schema.js
  app/javascript/helpers/promise-debounce.js
  app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
  app/javascript/spec/catalog-form/validator.spec.js
  package.json
  tsconfig.json
Labels: enhancement, hammer/no, react, services

#5270 Added hostname fallback fields for openstack amqp events.
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
Labels: compute/infrastructure, enhancement, hammer/no

#5336 Lock enzyme adapter version to stop failing travis.
  package.json
Labels: bug

#5333 Clean up the ApplicationController::Features structure a little
  app/controllers/application_controller.rb
  app/controllers/application_controller/feature.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/mixins/sandbox.rb
  app/controllers/mixins/vm_show_mixin.rb
  app/controllers/ops_controller.rb
  app/controllers/report_controller.rb
  spec/controllers/application_controller/feature_spec.rb
Labels: explorers, hammer/no, refactoring, trees

#5337 Upgrade version of react-ui-components
  package.json
Labels: dependencies

#5303 Make hakiri stop complaining about the controller param in trees
  app/views/layouts/_tree.html.haml
Labels: developer

#5335 Hide services from the Services tree as its redundant and slow
  app/presenters/tree_builder_services.rb
  spec/presenters/tree_builder_services_spec.rb
Labels: bug, hammer/yes, services, trees, ux/approved

#5338 Drop the unnecessary accords instance variable from some controllers
  app/controllers/application_controller/automate.rb
  app/controllers/miq_policy_controller/rsop.rb
  app/controllers/planning_controller.rb
Labels: cleanup, explorers, hammer/no, technical debt, trees

#5348 Remove constants ALLOWED_FIELD_SUFFIXES from Reports::Editor
  app/controllers/report_controller/reports/editor.rb
Labels: refactoring

#5346 Use supports_volume_resizing? to toggle the Volume size field
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
Labels: enhancement, hammer/no, storage

#5350 Remove unnecessary `:onclick => false` local from TreeBuilders
  app/presenters/tree_builder_alert_profile_obj.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_smartproxy_affinity.rb
  app/presenters/tree_builder_tags.rb
  spec/presenters/tree_builder_belongs_to_hac_spec.rb
  spec/presenters/tree_builder_belongs_to_vat_spec.rb
  spec/presenters/tree_builder_smartproxy_affinity_spec.rb
Labels: cleanup, hammer/no, trees

#5351 Drop the click_url from TreeBuilder locals for miqOnClickHostNet
  app/presenters/tree_builder_network.rb
  app/presenters/tree_builder_storage_adapters.rb
Labels: cleanup, hammer/no, trees

#5353 Remove references to MiqPassword
  app/controllers/mixins/ems_common/angular.rb
  app/controllers/mixins/ems_common_angular.rb
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ops_controller/settings/common_spec.rb
  spec/spec_helper.rb
Labels: technical debt

#5355 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#5354 Fix creating a group after validation message 'already exists'
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, hammer/yes, settings

#5345 Don't throw exception when template is not found in Provisioning
  app/controllers/application_controller/miq_request_methods.rb
Labels: bug, compute/infrastructure, hammer/yes

#5340 Enforce RBAC roles on Control -> Explorer accordions consistently with other explorers
  app/controllers/miq_policy_controller.rb
Labels: control, hammer/no, rbac, refactoring

#5360 Unify the code style of features hashes in controllers
  app/controllers/automation_manager_controller.rb
  app/controllers/bottlenecks_controller.rb
  app/controllers/catalog_controller.rb
  app/controllers/chargeback_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/ops_controller.rb
  app/controllers/provider_foreman_controller.rb
  app/controllers/pxe_controller.rb
  app/controllers/report_controller.rb
  app/controllers/service_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/utilization_controller.rb
  app/controllers/vm_cloud_controller.rb
  app/controllers/vm_infra_controller.rb
  app/controllers/vm_or_template_controller.rb
Labels: hammer/no, refactoring

#5318 Clean up the add_root option in TreeBuilders and use root_options without it
  app/controllers/mixins/sandbox.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_automate_simulation_results.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_compliance_history.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_default_filters.rb
  app/presenters/tree_builder_diagnostics.rb
  app/presenters/tree_builder_menu_roles.rb
  app/presenters/tree_builder_ops_rbac_features.rb
  app/presenters/tree_builder_protect.rb
  app/presenters/tree_builder_region.rb
  app/presenters/tree_builder_sections.rb
  app/presenters/tree_builder_services.rb
  app/presenters/tree_builder_smartproxy_affinity.rb
  app/presenters/tree_builder_tags.rb
  app/presenters/tree_builder_utilization.rb
  spec/helpers/application_helper_spec.rb
  spec/presenters/tree_builder_ae_customization_spec.rb
  spec/presenters/tree_builder_automate_simulation_results_spec.rb
  spec/presenters/tree_builder_belongs_to_hac_spec.rb
  spec/presenters/tree_builder_belongs_to_vat_spec.rb
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_compliance_history_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/presenters/tree_builder_default_filters_spec.rb
  spec/presenters/tree_builder_protect_spec.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
  spec/presenters/tree_builder_sections_spec.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
  spec/presenters/tree_builder_smartproxy_affinity_spec.rb
  spec/presenters/tree_builder_tags_spec.rb
Labels: cleanup, hammer/no, refactoring, trees

#5352 Unify onselect with oncheck across trees with checkboxes
  app/assets/javascripts/miq_tree.js
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_sections.rb
  app/views/layouts/_tree.html.haml
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/presenters/tree_builder_sections_spec.rb
Labels: hammer/no, refactoring, trees

#5359 Subscription ID is required when adding, readOnly when editing (Azure)
  app/views/shared/views/ems_common/angular/_form.html.haml
Labels: bug, compute/cloud, hammer/yes

#5363 Delete unused method find_or_new
  app/controllers/mixins/checked_id_mixin.rb
Labels: hammer/no, technical debt

#5362 Fixed condition to use correct feature id
  app/controllers/application_controller/tags.rb
  spec/controllers/application_controller/tags_spec.rb
Labels: bug, hammer/yes, tagging

#5358 Add spec for the fix for creating group after validation message
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: gaprindashvili/yes, hammer/yes, test

#5366 Services use turbo button
  product/views/Service.yaml
Labels: bug, hammer/yes, performance

#5370 [Failing Travis - Breadcrumbs] Fix container > role and x_active_tree in breadcrumbs
  app/controllers/miq_policy_controller.rb
  app/controllers/mixins/breadcrumbs_mixin.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: bug, hammer/no, trees

#5339 Add safeguard for VMs without ext_management_system
  app/services/network_topology_service.rb
Labels: bug, gaprindashvili/yes, hammer/yes, topology

#5344 Add Enable/Disable button to Schedule summary page
  app/controllers/ops_controller/settings/schedules.rb
  app/helpers/application_helper/toolbar/miq_report_schedule_center.rb
  app/helpers/application_helper/toolbar/miq_schedule_center.rb
Labels: bug, enhancement, hammer/no, settings

#5364 Fixes segmentation_id and physical_network required (in Cloud Network form)
  app/assets/javascripts/components/cloud_network/cloud-network-form.js
  app/views/static/cloud_network/cloud-network-form.html.haml
Labels: bug, hammer/yes, networks

#5376 Fix missed argument change for compliance history tree
  app/controllers/vm_common.rb
Labels: bug, compute/infrastructure

#5365 Move event handling settings from locals to options in TreeBuilder
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_alert_profile_obj.rb
  app/presenters/tree_builder_automate.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_datacenter.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_default_filters.rb
  app/presenters/tree_builder_diagnostics.rb
  app/presenters/tree_builder_genealogy.rb
  app/presenters/tree_builder_menu_roles.rb
  app/presenters/tree_builder_miq_action_category.rb
  app/presenters/tree_builder_network.rb
  app/presenters/tree_builder_ops_rbac_features.rb
  app/presenters/tree_builder_protect.rb
  app/presenters/tree_builder_sections.rb
  app/presenters/tree_builder_smartproxy_affinity.rb
  app/presenters/tree_builder_snapshots.rb
  app/presenters/tree_builder_storage_adapters.rb
  app/presenters/tree_builder_tags.rb
  spec/presenters/tree_builder_alert_profile_obj_spec.rb
  spec/presenters/tree_builder_belongs_to_hac_spec.rb
  spec/presenters/tree_builder_belongs_to_vat_spec.rb
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/presenters/tree_builder_genealogy_spec.rb
  spec/presenters/tree_builder_protect_spec.rb
  spec/presenters/tree_builder_sections_spec.rb
  spec/presenters/tree_builder_smartproxy_affinity_spec.rb
  spec/presenters/tree_builder_tags_spec.rb
Labels: refactoring, trees

#5356 Highlight changes from default on all trees with checkboxes
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_default_filters.rb
  app/presenters/tree_builder_protect.rb
  app/presenters/tree_builder_tags.rb
  app/views/layouts/_tree.html.haml
  spec/presenters/tree_builder_belongs_to_hac_spec.rb
  spec/presenters/tree_builder_belongs_to_vat_spec.rb
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/presenters/tree_builder_protect_spec.rb
  spec/presenters/tree_builder_tags_spec.rb
Labels: hammer/no, question, trees, unmergeable, ux/approved

#5372 Update supported ruby versions on Travis
  .travis.yml
Labels: developer

#5379 [Changelog] Update for Hammer-4
  CHANGELOG.md
Labels: documentation, hammer/yes

#5377 Permanently hide the VMs where it was possible to optionally display them
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/controllers/vm_common.rb
  app/controllers/vm_infra_controller.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_archived.rb
  app/presenters/tree_builder_images.rb
  app/presenters/tree_builder_instances.rb
  app/presenters/tree_builder_vandt.rb
  app/presenters/tree_builder_vms_and_templates.rb
  app/views/configuration/_ui_2.html.haml
  spec/controllers/vm_common_spec.rb
  spec/presenters/tree_builder_archived_spec.rb
  spec/presenters/tree_builder_images_spec.rb
  spec/presenters/tree_builder_instances_spec.rb
  spec/presenters/tree_builder_spec.rb
  spec/presenters/tree_builder_vms_and_templates_spec.rb
Labels: cleanup, hammer/no, trees, ux/approved

#5380 Add missing fonticons in the host and vm summary screens
  app/helpers/host_helper/textual_summary.rb
  app/helpers/vm_helper/textual_summary.rb
Labels: graphics, technical debt

#5381 Adjust accordion height calculation hack to the new breadcrumbs
  app/assets/javascripts/miq_application.js
Labels: bug, hammer/no

#5103 bug 1614567: Allow user to select Network Port for provisioning
  app/views/miq_request/_prov_field.html.haml
  app/views/shared/views/_prov_dialog.html.haml
Labels: bug, compute/cloud

#5382 Fix preselect node in servers by roles tree under diagnostics
  app/presenters/tree_builder_servers_by_role.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
Labels: bug, trees

#3570 Add tagging component
  app/assets/stylesheets/application.css
  app/controllers/application_controller/tags.rb
  app/controllers/catalog_controller.rb
  app/javascript/components/taggingWrapper.jsx
  app/javascript/packs/application-common.js
  app/javascript/packs/component-definitions-common.js
  app/views/layouts/_tag_edit.html.haml
  app/views/layouts/_tag_edit_assignments.html.haml
  app/views/layouts/_tagging.html.haml
  app/views/layouts/_x_edit_buttons.html.haml
  config/webpack/loaders.js
  spec/controllers/application_controller/tags_spec.rb
  spec/controllers/auth_key_pair_cloud_controller_spec.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/cloud_network_controller_spec.rb
  spec/controllers/cloud_object_store_container_spec.rb
  spec/controllers/cloud_object_store_object_spec.rb
  spec/controllers/cloud_subnet_controller_spec.rb
  spec/controllers/cloud_tenant_controller_spec.rb
  spec/controllers/cloud_volume_backup_controller_spec.rb
  spec/controllers/cloud_volume_controller_spec.rb
  spec/controllers/cloud_volume_snapshot_controller_spec.rb
  spec/controllers/cloud_volume_type_controller_spec.rb
  spec/controllers/configuration_job_controller_spec.rb
  spec/controllers/floating_ip_controller_spec.rb
  spec/controllers/generic_object_controller_spec.rb
  spec/controllers/infra_networking_controller_spec.rb
  spec/controllers/network_router_controller_spec.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
  spec/controllers/provider_foreman_controller_spec.rb
  spec/controllers/security_group_controller_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/spec_helper.rb
  spec/support/tagging_helper.rb
Labels: react

#5341 Add Cancel button to policy simulation page
  app/controllers/application_controller/policy_support.rb
  app/views/layouts/_policy_sim.html.haml
  app/views/layouts/_x_edit_buttons.html.haml
  config/routes.rb
  spec/controllers/application_controller/policy_support_spec.rb
Labels: bug, hammer/yes

#5386 Fix room display in physical infra summary views
  app/helpers/physical_server_helper/textual_summary.rb
  app/helpers/physical_storage_helper/textual_summary.rb
  spec/helpers/physical_server_helper/textual_summary_spec.rb
  spec/helpers/physical_storage_helper/textual_summary_spec.rb
Labels: bug, compute/physical infrastructure

#5384 Fix the access to child services from parents under My Services
  app/assets/javascripts/miq_tree.js
  app/views/service/_svcs_show.html.haml
Labels: bug, hammer/yes, services, trees

#5387 Add missing fonticons in the containers area summary screens
  app/helpers/container_node_helper/textual_summary.rb
  app/helpers/container_replicator_helper/textual_summary.rb
  app/helpers/ems_container_helper/textual_summary.rb
Labels: graphics, technical debt

#5389 Extract the sandbox variables from the Roles/Servers TreeBuilders under Diagnostics
  app/assets/javascripts/miq_tree.js
  app/controllers/ops_controller/diagnostics.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_diagnostics.rb
  app/presenters/tree_builder_roles_by_server.rb
  app/presenters/tree_builder_servers_by_role.rb
  app/views/layouts/_tree.html.haml
  spec/presenters/tree_builder_roles_by_server_spec.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
Labels: hammer/no, refactoring, trees

#5394 Fixed display of default memory threshold correctly on new appliance
  app/controllers/ops_controller/settings/common.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: bug, hammer/yes, settings
