Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-08, with the labels that each got.

#5912 Drop random data-whatever from modals
  app/views/layouts/_searchbar.html.haml
  app/views/layouts/_x_adv_searchbox.html.haml
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: technical debt

#5913 We don't need to set these, again...
  spec/controllers/chargeback_controller_spec.rb
Labels: changelog/no, hammer/no, ivanchuk/no, refactoring, test

#5919 views: remove unneeded compliances join
  product/views/ManageIQ_Providers_CloudManager_Template-all_vms_and_templates.yaml
  product/views/MiqTemplate.yaml
  product/views/ProvisionCloudTemplates.yaml
  product/views/Vm-all_vms.yaml
  product/views/VmOrTemplate-all_archived.yaml
Labels: bug, cloud intel/reporting, hammer/yes, ivanchuk/yes

#5914 Fix button sets order in tree
  app/presenters/tree_builder_generic_object_definition.rb
Labels: bug, generic objects, hammer/yes, ivanchuk/yes

#5847 Refactor spec for hiding tenant column for non admin users
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/shared/controllers/shared_examples_for_hiding_column_non_admin.rb
Labels: refactoring, test

#5915 Catalog item removal modal: disable delete button if API data incomplete
  app/javascript/components/remove-catalog-item-modal.jsx
  app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js
Labels: bug, ivanchuk/yes, services

#5834 Add '<No Depot>' option to Collect Logs form
  app/assets/javascripts/components/ops/log-collection-form.js
  app/assets/javascripts/services/miq_db_backup_service.js
  app/controllers/ops_controller/diagnostics.rb
  app/views/static/ops/log_collection/log_collection.html.haml
Labels: bug, changelog/yes, ivanchuk/yes, settings

#5918 Remove Load Balancer button from Network Topology page
  app/views/network_topology/show.html.haml
  config/routes.rb
Labels: bug, hammer/no, ivanchuk/yes

#5925 Changed model name when showing list of Tower Templates.
  app/controllers/automation_manager_controller.rb
  product/views/ManageIQ_Providers_AnsibleTower_AutomationManager_ConfigurationScript.yaml
  spec/controllers/automation_manager_controller_spec.rb
Labels: automation/ansible tower, bug, changelog/yes, hammer/yes, ivanchuk/yes

#5921 The factory sets these, again...
  spec/controllers/provider_foreman_controller_spec.rb
Labels: changelog/no, hammer/no, ivanchuk/no, refactoring, test

#5926 Circling back and removing compliance join for all
  product/views/InstanceOrImage.yaml
  product/views/ManageIQ_Providers_CloudManager_Template.yaml
  product/views/ManageIQ_Providers_CloudManager_Vm-all_vms_and_templates.yaml
  product/views/ManageIQ_Providers_CloudManager_Vm-vms.yaml
  product/views/ManageIQ_Providers_CloudManager_Vm.yaml
  product/views/ManageIQ_Providers_InfraManager_Template.yaml
  product/views/ManageIQ_Providers_InfraManager_Vm.yaml
  product/views/MiqTemplate-all_miq_templates.yaml
  product/views/ProvisionInfraTemplates.yaml
  product/views/Vm.yaml
  product/views/VmOrTemplate-all_orphaned.yaml
  product/views/VmOrTemplate-all_vms_and_templates.yaml
Labels: bug, cloud intel/reporting, hammer/yes, ivanchuk/yes

#5927 Fix display of Container Project Compliance Policies
  app/views/miq_policy/_policy_folders.html.haml
Labels: bug, control, hammer/yes, ivanchuk/yes

#4913 GOD's button group can have buttons assign/unassign during create/edit
  app/assets/javascripts/components/generic_object/assign-buttons.js
  app/assets/javascripts/components/generic_object/main-custom-button-group-form.js
  app/assets/javascripts/directives/form_changed.js
  app/assets/javascripts/miq_global.js
  app/controllers/generic_object_definition_controller.rb
  app/javascript/helpers/move.js
  app/javascript/packs/application-common.js
  app/views/static/generic_object/assign-buttons.html.haml
  app/views/static/generic_object/main_custom_button_group_form.html.haml
  config/routes.rb
  spec/javascripts/components/generic_object_definition/assign-buttons_spec.js
Labels: automation/automate, bug, changelog/yes, dependencies, gaprindashvili/yes, generic objects, hammer/yes, ivanchuk/yes

#5930 Report results: fix toolbar button display when in "filter".
  app/helpers/application_helper/button/view_ght.rb
Labels: bug, cloud intel/reporting, ivanchuk/yes

#5928 Add formatting to report data filter display.
  app/javascript/components/report-data-table.jsx
  app/javascript/spec/report-data-table.spec.js
Labels: cloud intel/reporting, enhancement, react

#5931 Fix double id in GOD
  app/views/generic_object_definition/_show_list.html.haml
Labels: changelog/no, ivanchuk/no, technical debt

#5207 Provider edit - move message about a username near the field, fix everything
  app/assets/javascripts/components/auth-credentials.js
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/views/configuration_manager/_shared_form.html.haml
  app/views/layouts/angular-bootstrap/_auth_credentials_angular_bootstrap.html.haml
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  app/views/static/auth-credentials.html.haml
Labels: bug, compute/cloud, compute/infrastructure, ivanchuk/yes

#5867 Get proper record class while performing operations on Managed VMs of a chosen Datastore
  app/controllers/application_controller/ci_processing.rb
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: blocker, bug, compute/infrastructure, hammer/yes, ivanchuk/yes

#5550 Replace provision Tagging tree by component
  app/assets/javascripts/miq_tree.js
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/vm_common.rb
  app/javascript/components/taggingWrapper.jsx
  app/javascript/miq-redux/middleware.js
  app/javascript/spec/miq-redux/middleware.spec.js
  app/views/miq_request/_prov_edit.html.haml
  app/views/miq_request/_prov_field.html.haml
  package.json
Labels: ivanchuk/no, react, tagging, trees, ux/review

#5932 Fix error when canceling addition of new schedule
  app/controllers/ops_controller/settings/schedules.rb
Labels: bug, ivanchuk/yes, settings

#5940 Mark the options argument in TreeBuilder methods unnecessary with _
  app/presenters/tree_builder_alert_profile.rb
  app/presenters/tree_builder_automation_manager_configuration_scripts.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_condition.rb
  app/presenters/tree_builder_policy.rb
  app/presenters/tree_builder_report_dashboards.rb
  app/presenters/tree_builder_storage.rb
Labels: hammer/no, ivanchuk/no, technical debt, trees

#5920 Update datepicker when start date changed
  app/controllers/report_controller/schedules.rb
Labels: bug, cloud intel/reporting, hammer/yes, ivanchuk/yes

#5936 Get record class while performing operations on VMs of chosen Cluster
  app/controllers/application_controller/ci_processing.rb
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: blocker, bug, compute/infrastructure, hammer/yes, ivanchuk/yes

#5952 Fixed call that build list of Storages to build Host file drop down
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  spec/controllers/mixins/actions/vm_actions/reconfigure_spec.rb
Labels: bug, changelog/yes, compute/infrastructure, hammer/yes, ivanchuk/yes

#5943 Fix load tags with multiple values in one category
  app/controllers/application_controller/tags.rb
Labels: bug, tagging

#5951 [Changelog] Update for Sprint 117
  CHANGELOG.md
Labels: documentation

#5955 Drop the MiqPolicyController#open_parent_nodes as it's never used
  app/controllers/miq_policy_controller.rb
Labels: cleanup, control, explorers, hammer/no, ivanchuk/no, trees

#5942 Fix main_div double id withour getting rid of <div id=main_div>
  app/controllers/generic_object_definition_controller.rb
  app/views/generic_object_definition/_list.html.haml
  app/views/generic_object_definition/_show_actions.html.haml
  app/views/generic_object_definition/_show_custom_button.html.haml
  app/views/generic_object_definition/_show_custom_button_group.html.haml
  app/views/generic_object_definition/_show_god.html.haml
  app/views/generic_object_definition/show.html.haml
  app/views/generic_object_definition/show_list.html.haml
Labels: changelog/no, ivanchuk/no, technical debt

#5825 Don't modify original model value for form submission
  app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
  app/views/ops/_settings_replication_tab.html.haml
Labels: bug, hammer/yes, ivanchuk/yes, settings

#5954 Drop the unnecessary _pid and _options args from TreeBuilder#override
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_alert_profile_obj.rb
  app/presenters/tree_builder_automate.rb
  app/presenters/tree_builder_automate_catalog.rb
  app/presenters/tree_builder_automate_entrypoint.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_belongs_to_vat.rb
  app/presenters/tree_builder_compliance_history.rb
  app/presenters/tree_builder_infra_networking.rb
  app/presenters/tree_builder_network.rb
  app/presenters/tree_builder_roles_by_server.rb
  app/presenters/tree_builder_servers_by_role.rb
  app/presenters/tree_builder_smartproxy_affinity.rb
  app/presenters/tree_builder_tenants.rb
  app/presenters/tree_builder_utilization.rb
  spec/presenters/tree_builder_alert_profile_obj_spec.rb
Labels: cleanup, hammer/no, ivanchuk/no, trees

#5945 Do not use the same 🌳🌳 for assignments for Alert Profiles and RBAC groups
  app/controllers/miq_policy_controller/alert_profiles.rb
  app/presenters/tree_builder_alert_profile_assign.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_ems_folders.rb
  app/presenters/tree_builder_resource_pools.rb
  spec/presenters/tree_builder_ems_folders_spec.rb
  spec/presenters/tree_builder_resource_pools_spec.rb
Labels: hammer/no, ivanchuk/no, refactoring, trees, unmergeable

#5959 Update ui-components to 1.3.0
  package.json
Labels: dependencies

#5917 Remove sandpaper styling around GTLs
  app/assets/javascripts/controllers/report_data_controller.js
  app/assets/javascripts/miq_explorer.js
  app/controllers/automation_manager_controller.rb
  app/controllers/provider_foreman_controller.rb
  app/controllers/service_controller.rb
  app/helpers/application_helper/page_layouts.rb
  app/presenters/explorer_presenter.rb
  app/views/layouts/_center_div_no_listnav.html.haml
  app/views/service/explorer.html.haml
Labels: formatting/styling, hammer/no, ivanchuk/no, technical debt

#5950 Remove report names from group settings hash when reports are deleted
  app/controllers/report_controller/reports.rb
  spec/controllers/miq_report_controller/reports_spec.rb
Labels: bug, changelog/yes, hammer/no, ivanchuk/yes

#5873 Switch to Advanced tab when only error is "Request is required"
  app/controllers/application_controller/buttons.rb
  app/views/shared/buttons/_ab_advanced_form.html.haml
  spec/controllers/application_controller/buttons_spec.rb
Labels: automation/automate, bug, changelog/yes, hammer/yes, ivanchuk/yes

#5933 Disable <Choose a Role> option to prevent error while adding Group
  app/views/ops/_rbac_group_details.html.haml
  spec/views/ops/_rbac_group_details.html.haml_spec.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes, settings

#5956 Drop the VmCommon#open_parent_nodes as we no longer display VMs
  app/controllers/vm_common.rb
Labels: cleanup, hammer/no, ivanchuk/no, trees

#5962 Add 'Service ID' to Service detail page
  app/helpers/service_helper/textual_summary.rb
  spec/helpers/service_helper/textual_summary_spec.rb
Labels: enhancement, services

#5966 Drop the pid/options arguments from AssignTo trees' override 🐞
  app/presenters/tree_builder_ems_folders.rb
  app/presenters/tree_builder_resource_pools.rb
Labels: bug, changelog/no, hammer/no, ivanchuk/no, trees

#5961 [Changelog] Update Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#5948 The dialog ems_network endpoint is wrong
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: bug, ivanchuk/yes, services

#5957 Drop the obsolete :full_ids from x_build_node_id in CatalogController
  app/controllers/application_controller/explorer.rb
  app/controllers/catalog_controller.rb
Labels: cleanup, hammer/no, ivanchuk/no, trees

#5934 Consume the URL for VMRC from the task result instead of building it
  app/controllers/vm_remote.rb
  app/views/vm_common/console_vmrc.html.haml
Labels: cleanup, hammer/no, technical debt

#5964 Do not remember tab when downloading report from list view.
  app/controllers/application_controller.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes, settings

#5975 Fix jest - react-test-renderer version must match react and react-dom versions
  package.json
Labels: dependencies, ivanchuk/yes

#5960 [IVANCHUK] Bump version of react-ui-components to 0.11.37
  package.json
  yarn.lock
Labels: dependencies

#5974 Build the selected node key from the session stored model in RBS 🌳🐞
  app/presenters/tree_builder_roles_by_server.rb
Labels: bug, changelog/yes, hammer/no, ivanchuk/yes, trees

#5979 Update react-ui-compoennts to 0.11.37
  package.json
Labels: dependencies, ivanchuk/no

#5968 Add the configuration toolbar button on Ansible/Templates screen
  app/controllers/automation_manager_controller.rb
  app/helpers/application_helper/toolbar/configuration_scripts_center.rb
  app/helpers/application_helper/toolbar/x_configuration_scripts_center.rb
Labels: automation/ansible tower, bug, changelog/yes, ivanchuk/no

#5969 Remove dead methods
  app/controllers/catalog_controller.rb
  app/controllers/chargeback_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_controller/alert_profiles.rb
Labels: changelog/no, ivanchuk/no, technical debt

#5980 [Changelog] Update for Hammer-10
  CHANGELOG.md
Labels: documentation, hammer/yes

#5981 NetworkRouter form_params should get tenant id from nested hash
  app/controllers/network_router_controller.rb
  spec/controllers/network_router_controller_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes, networks

#5983 Use the TreeBuilder#node_by_tree_id in compliance history 🌳
  app/presenters/tree_builder_compliance_history.rb
Labels: hammer/no, ivanchuk/no, refactoring, trees

#5984 Drop the unnecessary sandbox variable in storage adapters 🌳✂️✂️
  app/presenters/tree_builder_storage_adapters.rb
Labels: hammer/no, ivanchuk/no, technical debt, trees

#5985 Do not rely on the obsolete sandbox variable in ComplianceHistory🌳
  app/presenters/tree_builder_compliance_history.rb
Labels: cleanup, hammer/no, ivanchuk/no, technical debt, trees

#5986 Do not rely on the obsolete sandbox variable in Networks 🌳
  app/presenters/tree_builder_network.rb
Labels: cleanup, hammer/no, ivanchuk/no, technical debt, trees

#5987 Drop the unused options argument from TreeBuilder#x_get_tree_objects
  app/presenters/tree_builder.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/presenters/tree_builder_network_spec.rb
  spec/presenters/tree_builder_storage_adapters_spec.rb
Labels: cleanup, hammer/no, ivanchuk/no, technical debt, trees

#5988 Drop the options argument from TreeBuilder#x_build_single_node
  app/presenters/full_tree_builder.rb
  app/presenters/tree_builder.rb
Labels: cleanup, hammer/no, ivanchuk/no, trees

#5989 Drop the unused options argument from TreeBuilder#x_get_custom_kids
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_alert_profile.rb
  app/presenters/tree_builder_automation_manager_configuration_scripts.rb
  app/presenters/tree_builder_buttons.rb
  app/presenters/tree_builder_catalog_items.rb
  app/presenters/tree_builder_chargeback_rates.rb
  app/presenters/tree_builder_chargeback_reports.rb
  app/presenters/tree_builder_compliance_history.rb
  app/presenters/tree_builder_condition.rb
  app/presenters/tree_builder_configuration_manager.rb
  app/presenters/tree_builder_configured_systems.rb
  app/presenters/tree_builder_iso_datastores.rb
  app/presenters/tree_builder_ops_rbac.rb
  app/presenters/tree_builder_ops_settings.rb
  app/presenters/tree_builder_ops_vmdb.rb
  app/presenters/tree_builder_orchestration_templates.rb
  app/presenters/tree_builder_policy.rb
  app/presenters/tree_builder_provisioning_dialogs.rb
  app/presenters/tree_builder_pxe_customization_templates.rb
  app/presenters/tree_builder_pxe_servers.rb
  app/presenters/tree_builder_report_dashboards.rb
  app/presenters/tree_builder_report_reports.rb
  app/presenters/tree_builder_report_saved_reports.rb
  app/presenters/tree_builder_report_widgets.rb
  app/presenters/tree_builder_services.rb
  app/presenters/tree_builder_storage.rb
  app/presenters/tree_builder_storage_pod.rb
  app/presenters/tree_builder_utilization.rb
  app/presenters/tree_builder_vms_filter.rb
  app/presenters/tree_kids.rb
  spec/controllers/provider_foreman_controller_spec.rb
  spec/presenters/tree_builder_compliance_history_spec.rb
  spec/presenters/tree_builder_ops_rbac_spec.rb
  spec/presenters/tree_builder_report_dashboards_spec.rb
  spec/presenters/tree_builder_report_saved_reports_spec.rb
  spec/presenters/tree_builder_report_widgets_spec.rb
  spec/presenters/tree_builder_services_spec.rb
Labels: cleanup, hammer/no, ivanchuk/no, technical debt, trees

#5976 policy_sim - set @in_a_form to prevent adv_search_build
  app/controllers/application_controller/policy_support.rb
Labels: bug, ivanchuk/yes

#5982 Pass the conditional class to the About Modal instead of HTML body
  app/assets/stylesheets/about_modal_background.scss
  app/javascript/components/miq-about-modal.jsx
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
Labels: hammer/no, ivanchuk/no, react, technical debt

#5990 Switch the clickability between networks and storage trees
  app/assets/javascripts/miq_tree.js
  app/presenters/tree_builder_network.rb
  app/presenters/tree_builder_storage_adapters.rb
Labels: bug, changelog/yes, hammer/no, ivanchuk/no, trees

#5929 UI for basic CRUD operations re FirmwareRegistry
  app/controllers/firmware_registry_controller.rb
  app/helpers/application_helper/toolbar/firmware_registries_center.rb
  app/helpers/application_helper/toolbar/firmware_registry_center.rb
  app/helpers/firmware_registry_helper/textual_summary.rb
  app/javascript/components/firmware-registry/firmware-registry-form.jsx
  app/javascript/components/firmware-registry/firmware-registry-form.schema.js
  app/javascript/packs/component-definitions-common.js
Labels: enhancement, ivanchuk/yes

#5999 Completely get rid of the options argument from all TreeBuilder methods
  app/presenters/tree_builder.rb
Labels: cleanup, hammer/no, ivanchuk/no, technical debt, trees

#5996 Removed `Tenant` column from list view.
  product/views/ServiceTemplate.yaml
Labels: bug, changelog/yes, ivanchuk/yes, services

#5994 Drop the conversion of legacy options from TreeBuilder#convert_bs_tree
  app/presenters/tree_builder.rb
Labels: cleanup, hammer/no, ivanchuk/no, trees

#5992 Add missing gettext to HostController
  app/controllers/host_controller.rb
Labels: bug, internationalization, ivanchuk/yes

#5944 React-based trees for alert profile assigments
  app/javascript/components/tree-view/hierarchical-tree-view.jsx
  app/javascript/components/tree-view/index.js
  app/javascript/packs/component-definitions-common.js
  app/views/miq_policy/_alert_profile_assign.html.haml
Labels: hammer/no, ivanchuk/no, react, trees

#6000 Fix onclick setting for VMs on host/networks🌳 extend it to templates
  app/assets/javascripts/miq_tree.js
  app/presenters/tree_builder_network.rb
Labels: bug, trees

#5863 Change service-ownership-form to pull data from the API
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/javascript/components/set-ownership-form/index.jsx
  app/javascript/components/set-ownership-form/ownership-form.schema.js
  app/javascript/components/set-service-ownership-form/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/set-ownership-form/set-ownership-form.spec.js
  app/javascript/spec/set-service-ownership-form/set-service-ownership-form.spec.js
  app/views/shared/views/_ownership.html.haml
  spec/controllers/vm_infra_controller_spec.rb
  spec/views/shared/views/_ownership.html.haml_spec.rb
Labels: changelog/yes, enhancement, hammer/no, ivanchuk/no, react

#5998 Rename build_tags_tree to build_tags_for_provisioning
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/miq_request_controller.rb
Labels: hammer/no, ivanchuk/no, technical debt

#5991 [IVANCHUK] Update yarn.lock after backports
  yarn.lock
Labels: dependencies

#5973 Add Set Ownership to Key Pairs
  app/controllers/auth_key_pair_cloud_controller.rb
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/helpers/application_helper/toolbar/auth_key_pair_cloud_center.rb
  app/helpers/application_helper/toolbar/auth_key_pair_clouds_center.rb
  app/helpers/auth_key_pair_cloud_helper/textual_summary.rb
  app/views/auth_key_pair_cloud/show.html.haml
  config/routes.rb
Labels: changelog/yes, compute/cloud, enhancement, ivanchuk/yes

#5923 Queue up schedule/s to run now
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/settings/schedules.rb
  app/controllers/report_controller/schedules.rb
  spec/controllers/ops_controller/settings/schedules_spec.rb
Labels: enhancement, settings

#6001 Report results: Multiple fixes.
  app/javascript/components/report-data-table.jsx
Labels: bug, cloud intel/reporting, ivanchuk/yes

#6006 [IVANCHUK] Update ui-components to 1.2.13 for ivanchuk
  package.json
  yarn.lock
Labels: dependencies

#5963 Remove Host Discover and Add buttons
  app/assets/javascripts/controllers/host/host_form_controller.js
  app/controllers/host_controller.rb
  app/controllers/mixins/actions/host_actions/discover.rb
  app/helpers/application_helper/toolbar/hosts_center.rb
  app/views/host/_form.html.haml
  app/views/host/discover.html.haml
  app/views/host/new.html.haml
  spec/controllers/application_controller_spec.rb
  spec/controllers/host_controller_spec.rb
  spec/javascripts/controllers/host/host_form_controller_spec.js
Labels: bug, changelog/yes, compute/infrastructure

#6009 Determine if EmsFolder is a blue folder using a model method
  app/presenters/tree_builder_belongs_to_vat.rb
  app/presenters/tree_builder_ems_folders.rb
Labels: hammer/no, ivanchuk/no, technical debt, trees

#6008 Support node 12
  package.json
Labels: dependencies, ivanchuk/no

#6002 Drop the laziness of the Foreman/Ansible configured systems 🌳🌳
  app/presenters/tree_builder_automation_manager_configured_systems.rb
  app/presenters/tree_builder_configuration_manager_configured_systems.rb
  app/presenters/tree_builder_configured_systems.rb
Labels: hammer/no, ivanchuk/no, technical debt, trees

#5953 Drop the FullTreeBuilder as regular TreeBuilder can handle ancestry
  app/presenters/full_tree_builder.rb
  app/presenters/tree_builder_vandt.rb
  app/presenters/tree_builder_vms_and_templates.rb
  app/presenters/tree_node/ems_folder.rb
  spec/presenters/tree_builder_vms_and_templates_spec.rb
  spec/presenters/tree_node/ems_folder_spec.rb
Labels: hammer/no, ivanchuk/no, refactoring, trees

#6014 Display flash messages for report that has no data available
  app/views/report/_savedreports_list.html.haml
Labels: bug, cloud intel/reporting, hammer/no, ivanchuk/yes

#6013 Fix browser tabs for My/All Tasks text display in runtime language
  app/helpers/application_helper/title.rb
Labels: bug, hammer/yes, internationalization

#5876 Add missing routes to compare managed VMs of a Datastore
  config/routes.rb
Labels: bug, hammer/yes, ivanchuk/yes

#6024 Fix typo in chargeback breadcrumbs options
  app/controllers/chargeback_controller.rb
Labels: breadcrumbs, bug, ivanchuk/yes

#6020 Flatten the ConfigManagerProvider🌳 by dropping the single type
  app/presenters/tree_builder_configuration_manager.rb
  spec/controllers/provider_foreman_controller_spec.rb
Labels: cleanup, hammer/no, ivanchuk/no, technical debt, trees, ux/approved

#6026 Fix typo in PXE breadcrumbs_options
  app/controllers/pxe_controller.rb
Labels: breadcrumbs, bug, ivanchuk/yes

#6016 Fix manager typo in menu breadcrumbs
  app/controllers/ems_block_storage_controller.rb
Labels: breadcrumbs, bug, ivanchuk/no, storage

#6015 Do not require password verification for RHN subscription
  app/controllers/ops_controller.rb
  app/views/layouts/_auth_credentials2.html.haml
Labels: bug, hammer/no, ivanchuk/yes, technical debt, ux/approved

#6018 Make select in new cloud tenant always headed to bottom
  app/javascript/components/cloud-tenant-form/create-form.schema.js
  app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap
Labels: bug, changelog/yes, ivanchuk/yes

#6004 Fix breadcrumbs in control section
  app/controllers/miq_policy_controller.rb
  app/controllers/mixins/breadcrumbs_mixin.rb
  spec/controllers/miq_policy_controller_spec.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: breadcrumbs, bug, changelog/yes, control, ivanchuk/yes

#6033 Fix automate/simulation breadcrumbs
  app/controllers/miq_ae_tools_controller.rb
  app/controllers/mixins/breadcrumbs_mixin.rb
  spec/controllers/miq_ae_tools_controller_spec.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: automation/automate, breadcrumbs, bug, changelog/yes, ivanchuk/yes

#6003 Call miqCheckForChanges in breadcrumbs
  app/javascript/components/breadcrumbs/index.js
  app/javascript/components/breadcrumbs/on-click-functions.js
  app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
  app/javascript/spec/breadcrumbs/breadcrumbs.spec.js
  app/javascript/spec/breadcrumbs/on-click-functions.spec.js
Labels: breadcrumbs, bug, changelog/yes, ivanchuk/no

#6030 Use react-codemirror onChange event instead of onBeforeChange.
  app/javascript/components/code-editor/index.js
  app/javascript/spec/code-editor/__snapshots__/code-editor.spec.js.snap
  app/javascript/spec/code-editor/code-editor.spec.js
  app/javascript/spec/orchestration-template/orchestration-template-form.spec.js
Labels: bug, changelog/yes, ivanchuk/yes, react

#6028 Report data: add display of active filter. Add empty state.
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/report-data-table.scss
  app/javascript/components/report-data-table.jsx
  app/javascript/spec/report-data-table.spec.js
Labels: cloud intel/reporting, enhancement, ivanchuk/yes, ux/approved

#5995 Fixed correct setting of record to get counts of relationships
  app/controllers/cloud_tenant_dashboard_controller.rb
  app/services/cloud_tenant_dashboard_service.rb
  app/services/dashboard_service.rb
Labels: bug, changelog/yes, compute/cloud, ivanchuk/yes

#6045 Introduce breadcrumbs to utilization controller
  app/controllers/utilization_controller.rb
  spec/controllers/utilization_controller_spec.rb
Labels: breadcrumbs, bug, ivanchuk/yes

#6023 Allow Tagging for Floating Ip from CloudNetwork/NetworkRouter
  app/controllers/cloud_network_controller.rb
  app/controllers/network_router_controller.rb
  spec/controllers/cloud_network_controller_spec.rb
  spec/controllers/network_router_controller_spec.rb
Labels: bug, changelog/no, ivanchuk/yes, tagging

#6040 Automate url open fixes
  app/controllers/application_controller/buttons.rb
  config/routes.rb
Labels: automation/automate, bug, ivanchuk/yes

#6041 Optimization - don't deduplicate breadcrumbs when report definition and saved report have the same name
  app/controllers/optimization_controller.rb
  spec/controllers/optimization_controller_spec.rb
Labels: breadcrumbs, bug, ivanchuk/yes

#5993 Do not highlight Action node when deleting last Button Group
  app/controllers/application_controller/buttons.rb
Labels: bug, hammer/yes, ivanchuk/yes, services

#6034 Hide Additional Tenants of Catalog Item if role does not allow displaying them
  app/views/catalog/_form_basic_info.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/catalog/_st_angular_form.html.haml
  spec/views/catalog/_form_basic_info.html.haml_spec.rb
  spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
  spec/views/catalog/_st_angular_form.html.haml_spec.rb
Labels: bug, ivanchuk/yes, services

#6038 Angular - fix GTL i18n by including the angulars modules needed for translate, other modules too
  app/assets/javascripts/angular_modules/module_alerts_center.js
  app/assets/javascripts/angular_modules/module_automate_selector.js
  app/assets/javascripts/angular_modules/module_compat.js
  app/assets/javascripts/angular_modules/module_fonticon_picker.js
  app/assets/javascripts/angular_modules/module_helpers.js
  app/assets/javascripts/angular_modules/module_notifications.js
  app/assets/javascripts/angular_modules/module_report_data.js
  app/assets/javascripts/angular_modules/module_toolbar.js
  app/assets/javascripts/angular_modules/module_tree_view.js
  app/assets/javascripts/application.js
  app/assets/javascripts/components/sanitize.js
  app/assets/javascripts/components/tree.js
  app/assets/javascripts/controllers/alerts/alerts_list_controller.js
  app/assets/javascripts/controllers/alerts/alerts_most_recent_controller.js
  app/assets/javascripts/controllers/alerts/alerts_overview_controller.js
  app/assets/javascripts/controllers/alerts/edit_alert_dialog_controller.js
  app/assets/javascripts/controllers/container_dashboard/container_project_dashboard_controller.js
  app/assets/javascripts/controllers/ems_common/aggregate_status_card_controller.js
  app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js
  app/assets/javascripts/controllers/ems_container_dashboard/heatmap_controller.js
  app/assets/javascripts/controllers/ems_container_dashboard/recent_images_line_chart_controller.js
  app/assets/javascripts/controllers/ems_container_dashboard/recent_pods_line_chart_controller.js
  app/assets/javascripts/controllers/ems_container_dashboard/trends_chart_controller.js
  app/assets/javascripts/controllers/ems_infra_dashboard/heatmap_controller.js
  app/assets/javascripts/controllers/ems_physical_infra_dashboard/recent_servers_line_chart_controller.js
  app/assets/javascripts/controllers/fonticon_picker_controller.js
  app/assets/javascripts/controllers/header/header_controller.js
  app/assets/javascripts/controllers/live_metrics/ad_hoc_metrics_controller.js
  app/assets/javascripts/controllers/miq_ae_class/ae_inline_method_selection_controller.js
  app/assets/javascripts/controllers/notifications/notification-drawer.directive.js
  app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
  app/assets/javascripts/controllers/notifications/toast_list_controller.js
  app/assets/javascripts/controllers/report_data_controller.js
  app/assets/javascripts/controllers/toolbar_controller.js
  app/assets/javascripts/controllers/tree_view_controller.js
  app/assets/javascripts/directives/translate.js
  app/assets/javascripts/miq_angular_application.js
  app/assets/javascripts/services/alerts_center_service.js
  app/assets/javascripts/services/event_notifications_service.js
  app/helpers/gtl_helper.rb
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/catalog/_svccat_tree_show.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/angular/_toolbar.html.haml
  app/views/layouts/listnav/_explorer.html.haml
  app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml
  app/views/miq_ae_class/_embedded_methods.html.haml
  app/views/shared/buttons/_ab_options_form.html.haml
  app/views/shared/buttons/_group_form.html.haml
  app/views/shared/views/_show_alerts_list.html.haml
  app/views/shared/views/_show_alerts_most_recent.html.haml
  app/views/shared/views/_show_alerts_overview.html.haml
  spec/javascripts/controllers/alerts_center/alerts_list_controller_spec.js
  spec/javascripts/controllers/alerts_center/alerts_overview_controller_spec.js
  spec/javascripts/controllers/report_data_controller_spec.js
  spec/javascripts/controllers/toolbar_controller_spec.js
  spec/javascripts/controllers/tree_view_controller/tree_view_controller_spec.js
  spec/javascripts/services/alerts_center_service_spec.js
  spec/javascripts/services/event_notifications_service_spec.js
Labels: bug, internationalization, ivanchuk/yes

#5904 Do not append title to breadcrumbs on show_list pages
  app/controllers/cloud_network_controller.rb
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/cloud_object_store_object_controller.rb
  app/controllers/cloud_subnet_controller.rb
  app/controllers/cloud_tenant_controller.rb
  app/controllers/cloud_volume_backup_controller.rb
  app/controllers/cloud_volume_controller.rb
  app/controllers/cloud_volume_snapshot_controller.rb
  app/controllers/cloud_volume_type_controller.rb
  app/controllers/configuration_job_controller.rb
  app/controllers/container_dashboard_controller.rb
  app/controllers/container_group_controller.rb
  app/controllers/container_image_controller.rb
  app/controllers/container_image_registry_controller.rb
  app/controllers/container_node_controller.rb
  app/controllers/container_project_controller.rb
  app/controllers/container_replicator_controller.rb
  app/controllers/container_route_controller.rb
  app/controllers/container_service_controller.rb
  app/controllers/container_template_controller.rb
  app/controllers/ems_cloud_controller.rb
  app/controllers/ems_container_controller.rb
  app/controllers/ems_infra_controller.rb
  app/controllers/ems_network_controller.rb
  app/controllers/ems_object_storage_controller.rb
  app/controllers/ems_physical_infra_controller.rb
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/controllers/orchestration_stack_controller.rb
  app/controllers/persistent_volume_controller.rb
  app/controllers/physical_chassis_controller.rb
  app/controllers/physical_rack_controller.rb
  app/controllers/physical_server_controller.rb
  app/controllers/physical_storage_controller.rb
  app/controllers/physical_switch_controller.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: breadcrumbs, changelog/yes, ivanchuk/yes

#6053 Do not show unassigned buttons in My Service page
  app/helpers/application_helper/toolbar_builder.rb
Labels: bug, hammer/yes, ivanchuk/yes, services

#6052 Fixed API endpoint for GO object custom button dialogs.
  app/controllers/service_controller.rb
  app/services/dialog_local_service.rb
Labels: bug, changelog/yes, generic objects, ivanchuk/yes

#6054 Fix missing whitespace
  app/helpers/application_helper/toolbar_builder.rb
Labels: cleanup, ivanchuk/no

#6017 Mark the Indexes node as expanded instead of altering it in 🌳state
  app/presenters/tree_builder_ops_vmdb.rb
  app/presenters/tree_node/hash.rb
Labels: hammer/no, ivanchuk/no, refactoring, trees

#5864 Drop legacy dialog user
  app/controllers/catalog_controller.rb
  app/controllers/mixins/custom_button_dialog_form_mixin.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper/dialogs.rb
  app/services/dialog_local_service.rb
  app/views/shared/dialogs/_auto_refresh_javascript.html.haml
  app/views/shared/dialogs/_dialog_field.html.haml
  app/views/shared/dialogs/_dialog_field_check_box.html.haml
  app/views/shared/dialogs/_dialog_field_date_and_date_time_control.html.haml
  app/views/shared/dialogs/_dialog_field_drop_down_list.html.haml
  app/views/shared/dialogs/_dialog_field_radio_button.html.haml
  app/views/shared/dialogs/_dialog_field_text_area_box.html.haml
  app/views/shared/dialogs/_dialog_field_text_box.html.haml
  app/views/shared/dialogs/_dialog_group.html.haml
  app/views/shared/dialogs/_dialog_provision.html.haml
  app/views/shared/dialogs/_dialog_tab.html.haml
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/mixins/custom_button_dialog_form_mixin_spec.rb
  spec/helpers/application_helper/dialogs_spec.rb
  spec/services/dialog_local_service_spec.rb
  spec/views/shared/dialogs/_dialog_field_drop_down_list.html.haml_spec.rb
Labels: automation/automate, changelog/yes, cleanup, ivanchuk/no, old dialogs

#6021 Do not set load_children on the Active Services in the Services🌳
  app/presenters/tree_builder_services.rb
Labels: cleanup, hammer/no, ivanchuk/no, technical debt, trees

#6019 Make the Datastore Clusters 🌳 non-lazy as always loads its 🧒🧒
  app/presenters/tree_builder_storage_pod.rb
  app/views/storage/_storage_pod_folders.html.haml
Labels: hammer/no, refactoring, trees

#6022 Drop the load_children from 🌳Builder as it is no longer used
  app/presenters/tree_builder.rb
Labels: cleanup, hammer/no, ivanchuk/no, pending core, trees

#6057 Service - use x_node instead of accessing tree internals via @sb
  app/controllers/service_controller.rb
Labels: services, technical debt

#6035 Allow setting of fancy page titles (right_cell_text). Use it in Reports.
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/controllers/report_controller.rb
  app/helpers/application_helper.rb
  app/presenters/explorer_presenter.rb
  app/views/layouts/_content.html.haml
  app/views/layouts/_policy_sim.html.haml
  app/views/layouts/_tabs.html.haml
Labels: cloud intel/reporting, ivanchuk/yes, ux/approved

#6051 Fix spinner behavior when clicking redo/undo change buttons in Adv Search
  app/views/layouts/_exp_editor.html.haml
Labels: bug, configuration management

#6058 [IVANCHUK] Update breadcrumbs spec to match master
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: test

#6064 Hide Copy Widget for non-SuperAdmin users
  app/helpers/application_helper/button/miq_widget_set_copy.rb
  app/helpers/application_helper/toolbar/miq_widget_set_center.rb
Labels: blocker, bug, cloud intel/dashboard, ivanchuk/yes

#6068 [Changelog] Update for Sprint 118
  CHANGELOG.md
Labels: documentation

#6065 Prevent login redirect with ?timeout during logout
  app/assets/javascripts/miq_application.js
  app/assets/javascripts/miq_global.js
  app/views/layouts/_user_options.html.haml
Labels: bug, cloud intel/dashboard, ivanchuk/yes

#5935 Add offending Vm/Container Node/... to All Alerts Overview
  app/views/shared/views/_alerts_list.html.haml
Labels: enhancement, ivanchuk/yes

#6061 Revert "Do not show unassigned buttons"
  app/helpers/application_helper/toolbar_builder.rb
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: ivanchuk/no

#6074 Add translated report headers to PDF reports
  app/views/layouts/print/report.html.haml
Labels: bug, internationalization, ivanchuk/yes

#6070 Fix nilClass error
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  spec/controllers/mixins/actions/vm_actions/reconfigure_spec.rb
Labels: bug, changelog/yes, compute/infrastructure, ivanchuk/yes

#6067 Removed Pause & Resume Provider buttons from UI.
  app/helpers/application_helper/toolbar/automation_manager_provider_center.rb
  app/helpers/application_helper/toolbar/automation_manager_providers_center.rb
  app/helpers/application_helper/toolbar/configuration_manager_provider_center.rb
  app/helpers/application_helper/toolbar/configuration_manager_providers_center.rb
  app/helpers/application_helper/toolbar/ems_cloud_center.rb
  app/helpers/application_helper/toolbar/ems_clouds_center.rb
  app/helpers/application_helper/toolbar/ems_container_center.rb
  app/helpers/application_helper/toolbar/ems_containers_center.rb
  app/helpers/application_helper/toolbar/ems_infra_center.rb
  app/helpers/application_helper/toolbar/ems_infras_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
Labels: blocker, bug, changelog/yes, compute/cloud, compute/containers, compute/infrastructure, compute/physical infrastructure, ivanchuk/yes

#6043 Disable marking of translated strings in production
  app/views/layouts/_i18n_js.html.haml
Labels: internationalization, ivanchuk/no

#6077 Create docs section in settings for documentation links
  app/views/automation_manager/explorer.html.haml
  app/views/ems_cloud/show_list.html.haml
  app/views/ems_container/show_list.html.haml
  app/views/ems_infra/show_list.html.haml
  app/views/ems_network/show_list.html.haml
  app/views/ems_physical_infra/show_list.html.haml
  app/views/provider_foreman/explorer.html.haml
  config/settings.yml
Labels: blocker, bug, compute/cloud, ivanchuk/yes

#5938 Dialog Editor - show validation title when button is disabled
  app/views/miq_ae_customization/editor.html.haml
Labels: automation/automate, bug, hammer/yes, ivanchuk/yes

#6076 Report cleanup
  app/controllers/report_controller.rb
  app/controllers/report_controller/saved_reports.rb
  spec/controllers/report_controller_spec.rb
Labels: cloud intel/reporting, enhancement, ivanchuk/yes

#6085 Add titles for editor of service dialogs
  app/controllers/miq_ae_customization_controller.rb
  spec/controllers/miq_ae_customization_controller_spec.rb
Labels: bug, changelog/yes, ivanchuk/yes

#6081 VmReconfigure: convert ActionController::Parameters to hash.
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
Labels: bug, compute/infrastructure, ivanchuk/yes

#6080 Remove the `Actions` hash node from GOD and CatalogItem 🌳🌳
  app/controllers/application_controller/buttons.rb
  app/controllers/catalog_controller.rb
  app/controllers/generic_object_definition_controller.rb
  app/helpers/application_helper/button/catalog_item_button_reorder.rb
  app/helpers/application_helper/toolbar/catalogitem_button_set_center.rb
  app/helpers/application_helper/toolbar/servicetemplate_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/presenters/tree_builder_catalog_items.rb
  app/presenters/tree_builder_generic_object_definition.rb
  spec/controllers/generic_object_definition_controller_spec.rb
Labels: hammer/no, ivanchuk/no, refactoring, trees, ux/approved

#6088 Needed to pass in `action` to fix form button display in form
  app/controllers/application_controller/buttons.rb
Labels: bug, changelog/yes, ivanchuk/yes, services

#6087 [Changelog] Update for Ivanchuk RC1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#6086 Optimization - html title for saved reports
  app/controllers/optimization_controller.rb
  app/controllers/report_controller/saved_reports.rb
  spec/controllers/optimization_controller_spec.rb
Labels: cloud intel/reporting, enhancement, ivanchuk/yes

#6025 VmCommon: no string math in right_cell_text
  app/controllers/vm_common.rb
Labels: bug, internationalization, ivanchuk/yes

#6075 Allow Display in Catalog to stay checked for Catalog Bundle
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: blocker, bug, hammer/yes, ivanchuk/yes, services

#6097 Drop the node text override from AlertProfile assignment 🌳🌳
  app/presenters/tree_builder_alert_profile_obj.rb
Labels: cleanup, ivanchuk/no, trees

#6089 Clean up the building of my/global filters in TreeBuilders that contain them
  app/presenters/tree_builder_automation_manager_configuration_scripts.rb
  app/presenters/tree_builder_configured_systems.rb
  app/presenters/tree_builder_filters_mixin.rb
  app/presenters/tree_builder_services.rb
  app/presenters/tree_builder_storage.rb
  app/presenters/tree_builder_vms_filter.rb
Labels: hammer/no, ivanchuk/no, refactoring, trees

#6066 Do not use hash nodes for MiqReport records in Saved Reports 🌳
  app/controllers/report_controller.rb
  app/presenters/tree_builder_report_saved_reports.rb
  spec/presenters/tree_builder_report_saved_reports_spec.rb
Labels: hammer/no, ivanchuk/no, refactoring, technical debt, trees

#6094 Simplify TreeNode image definition by always using the decorators
  app/presenters/tree_node/ext_management_system.rb
  app/presenters/tree_node/generic_object_definition.rb
  app/presenters/tree_node/miq_ae_domain.rb
  app/presenters/tree_node/miq_ae_method.rb
  app/presenters/tree_node/node.rb
  app/presenters/tree_node/service.rb
  app/presenters/tree_node/service_template.rb
  app/presenters/tree_node/windows_image.rb
Labels: cleanup, ivanchuk/no, trees

#6101 Turbo mode for services
  product/views/Service.yaml
Labels: bug, ivanchuk/yes, services

#6107 Set the node as selected using the state hash directly
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_roles_by_server.rb
  app/presenters/tree_builder_servers_by_role.rb
Labels: ivanchuk/no, refactoring, trees

#6095 Remove some legacy 🌳node conversion code for CSS classes and lazy loading
  app/presenters/tree_builder.rb
  app/presenters/tree_node/node.rb
  spec/controllers/application_controller/explorer_spec.rb
  spec/controllers/miq_ae_class_controller_spec.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
  spec/presenters/tree_builder_spec.rb
Labels: cleanup, ivanchuk/no, refactoring, trees

#6113 Fixed to set saveable state regardless of number of items selected.
  app/assets/javascripts/components/retirement-form.js
Labels: bug, changelog/yes, ivanchuk/yes, services

#6114 Fixed to show a warning flash message.
  app/controllers/application_controller.rb
  app/controllers/cloud_volume_controller.rb
  spec/controllers/application_controller_spec.rb
Labels: bug, changelog/yes, ivanchuk/yes, storage

#6027 Delete resizer
  app/assets/javascripts/application.js
  app/assets/javascripts/resizable_sidebar.js
  app/assets/stylesheets/patternfly_overrides.scss
  app/controllers/dashboard_controller.rb
  app/views/layouts/_center_div_with_listnav.html.haml
  app/views/layouts/_content.html.haml
  app/views/miq_policy/_rsop_form.html.haml
  config/routes.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/javascripts/resizable_sidebar_spec.js
Labels: cleanup, formatting/styling, hammer/no, ivanchuk/no, technical debt, ux/approved

#6104 Expand the snapshots 🌳 with open_all instead of changing its state
  app/presenters/tree_builder_snapshots.rb
Labels: cleanup, ivanchuk/no, trees

#6115 Move text under Description to Chargeback Rate Details table
  app/views/chargeback/_cb_rate_show.html.haml
Labels: bug, cloud intel/chargeback, ivanchuk/yes

#6118 Update data driven forms to v1.15.6
  package.json
Labels: bug, ivanchuk/yes, react

#6112 Replace select attribute in tree nodes with the state/checked
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_alert_profile_obj.rb
  app/presenters/tree_builder_belongs_to_hac.rb
  app/presenters/tree_builder_belongs_to_vat.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_builder_default_filters.rb
  app/presenters/tree_builder_ems_folders.rb
  app/presenters/tree_builder_protect.rb
  app/presenters/tree_builder_resource_pools.rb
  app/presenters/tree_builder_sections.rb
  app/presenters/tree_builder_smartproxy_affinity.rb
  app/presenters/tree_builder_tenants.rb
  app/presenters/tree_node/hash.rb
  app/presenters/tree_node/menu/item.rb
  app/presenters/tree_node/miq_product_feature.rb
  app/presenters/tree_node/node.rb
  spec/presenters/tree_builder_alert_profile_obj_spec.rb
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_default_filters_spec.rb
  spec/presenters/tree_builder_protect_spec.rb
  spec/presenters/tree_builder_sections_spec.rb
  spec/presenters/tree_builder_smartproxy_affinity_spec.rb
Labels: cleanup, ivanchuk/no, technical debt, trees
