Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-02, with the labels that each got.

#5214 [Changelog] Update for Hammer-2
  CHANGELOG.md
Labels: documentation, hammer/yes

#5215 AR::QueryMethods uniq/distinct takes no block
  app/services/topology_service.rb
  spec/services/infra_topology_service_spec.rb
Labels: technical debt, topology

#5182 Use base_model name instead of demodulize
  app/services/dialog_local_service.rb
  spec/services/dialog_local_service_spec.rb
Labels: automation/automate, bug, hammer/yes

#5218 Use timeline listnav only for dashboard controller
  app/helpers/application_helper/listnav.rb
  spec/controllers/availability_zone_controller_spec.rb
  spec/controllers/container_controller_spec.rb
  spec/controllers/container_group_controller_spec.rb
  spec/controllers/container_node_controller_spec.rb
  spec/controllers/container_project_controller_spec.rb
  spec/controllers/container_replicator_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_cluster_controller_spec.rb
  spec/controllers/ems_container_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/host_controller_spec.rb
Labels: bug, hammer/yes

#5216 Report editor titles's tab unification
  app/controllers/report_controller/reports/editor.rb
  spec/controllers/miq_report_controller/reports/editor_spec.rb
Labels: cloud intel/reporting, refactoring

#5217 Report editor: add livesearch to timezone dropdown
  app/views/report/_form_filter_chargeback.html.haml
Labels: cloud intel/reporting, enhancement, hammer/no

#5223 Display missing checkboxes for workers under Diagnostics
  app/controllers/ops_controller/diagnostics.rb
  spec/controllers/ops_controller/diagnostics_spec.rb
Labels: blocker, bug, hammer/yes, settings

#5226 Ansible job launch confirmation message fix
  app/controllers/application_controller/buttons.rb
Labels: automation/automate, bug, hammer/yes

#5225 Ansible Tower & Foreman edit - explicitly warn when Zone.visible.empty?
  app/views/configuration_manager/_shared_form.html.haml
Labels: bug, configuration management

#5222 Add listnav to Embedded Ansible pages
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_playbook_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/controllers/mixins/listnav_mixin.rb
  app/views/layouts/listnav/_ansible_credential.html.haml
  app/views/layouts/listnav/_ansible_playbook.html.haml
  app/views/layouts/listnav/_ansible_repository.html.haml
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_playbook_controller_spec.rb
  spec/controllers/ansible_repository_controller_spec.rb
Labels: automation/ansible, enhancement

#5159 Display widget's title in full screen of widget result
  app/controllers/application_controller.rb
  app/views/layouts/_show_report.html.haml
  app/views/layouts/report_only.html.haml
  spec/controllers/application_controller_spec.rb
Labels: bug, cloud intel/dashboard, hammer/yes

#5229 Add back paging options
  app/assets/javascripts/controllers/report_data_controller.js
Labels: enhancement, hammer/yes

#5232 Container dashboard utilization metrics - fix hourly metrics
  app/assets/javascripts/components/pf_charts/line-chart.component.js
  app/assets/javascripts/controllers/ems_container_dashboard/utilization_trend_chart_controller.js
  app/services/container_dashboard_service.rb
Labels: blocker, bug, compute/containers, gaprindashvili/no, hammer/yes

#5237 Automate Datastore Schema Edit reset click message
  app/views/miq_ae_class/_fields_seq_form.html.haml
Labels: automation/automate, bug, hammer/yes

#5235 Fix database connections page
  app/controllers/ops_controller/db.rb
Labels: bug, settings

#5240 Fix rubocop warnings in ExplorerPresenter
  app/presenters/explorer_presenter.rb
Labels: hammer/no, technical debt

#5243 Fix missing flash message for Re-check Authentication Status
  app/views/ems_container/_show_dashboard.html.haml
Labels: blocker, bug, hammer/yes

#5241 Check button's inputs before looking for records
  app/controllers/application_controller/buttons.rb
Labels: automation/automate, bug, gaprindashvili/yes, hammer/yes

#5242 Remove not working stuff
  app/controllers/application_controller/buttons.rb
  app/views/static/generic_object/main_custom_button_form.html.haml
Labels: hammer/no, technical debt

#5236 Do not hide the spinner before the custom button simulate redirect
  app/assets/javascripts/miq_application.js
Labels: bug

#5244 AC::Parameters doesn't have each_value, use each
  app/controllers/security_group_controller.rb
Labels: technical debt

#5239 User Edit screen - link to button
  app/views/ops/_rbac_user_details.html.haml
Labels: enhancement, formatting/styling, gaprindashvili/yes, hammer/yes

#5221 Don't allow adding another svc bundle into an existing bundle
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: bug, hammer/yes, services

#5180 Added data-driven-form for automate import/export.
  app/javascript/components/automate-import-export-form/datastore-via-git.schema.js
  app/javascript/components/automate-import-export-form/import-datastore-via-git.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/automate-import-export-form/__snapshots__/import-datastore-via-git.spec.js.snap
  app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js
  app/views/miq_ae_tools/_import_export.html.haml
  package.json
Labels: react, ux/approved

#5247 Fix rubocop warnings in presenters #1
  app/presenters/full_tree_builder.rb
  app/presenters/menu/yaml_loader.rb
  app/presenters/tree_builder_region.rb
  app/presenters/tree_kids.rb
  app/presenters/widget_presenter.rb
Labels: technical debt

#5228 Rework dual list
  app/assets/stylesheets/dual_list.scss
  app/assets/stylesheets/main.scss
  app/javascript/.eslintrc.json
  app/javascript/components/dual-list-select/index.jsx
  app/javascript/components/dual-list-select/list.jsx
  app/javascript/spec/dual-list-select/__snapshots__/dual-list-select.spec.js.snap
  app/javascript/spec/dual-list-select/dual-list-select.spec.js
Labels: enhancement

#5248 Remove codeclimate-test-reported
  manageiq-ui-classic.gemspec
  tools/ci/after_install.sh
Labels: dependencies

#5249 Fix error during jasmine
  spec/javascripts/support/jasmine.yml
Labels: hammer/no, test

#5128 Fix enabling Power operations for a template
  app/controllers/application_controller/ci_processing.rb
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: blocker, bug, compute/infrastructure, hammer/yes

#5245 Fix Expression Builder to load page display only once per dropdown pick
  app/views/layouts/exp_atom/_edit_tag.html.haml
Labels: bug, expressions/filters, hammer/yes

#5251 Fix the label of Custom Button Events for infra providers
  app/helpers/ems_infra_helper/textual_summary.rb
Labels: bug, compute/infrastructure, hammer/yes

#5250 Fixed explanation of brand image positioning under Custom Logos
  app/views/ops/_settings_custom_logos_tab.html.haml
Labels: bug, settings

#5233 Converts server relationship form to DDR
  app/controllers/vm_common.rb
  app/javascript/components/vm-server-relationship-form/index.jsx
  app/javascript/components/vm-server-relationship-form/vm-server-relationship-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/vm-server-relationship-form/vm-server-relationship-form.spec.js
  app/views/vm_common/_evm_relationship.html.haml
  package.json
Labels: hammer/no, react, refactoring, services

#5252 Allow to print (export to PDF) the right size recommendations of a VM
  app/controllers/vm_common.rb
  app/helpers/application_helper/toolbar/right_size_view.rb
  app/views/vm_common/_right_size.html.haml
  config/routes.rb
Labels: compute/infrastructure, enhancement

#5256 Add Memory for Amazon Availability Zones
  app/controllers/application_controller/performance.rb
Labels: bug, charts, hammer/yes

#5254 Use ljust to left justify and pad strings
  lib/report_formatter/text.rb
  spec/lib/report_formater/text_formatter_spec.rb
  spec/support/report_helper.rb
Labels: bug, cloud intel/reporting, gaprindashvili/yes, hammer/yes

#5260 Fix wrong displayed elapsed time in the service
  app/helpers/service_helper/textual_summary.rb
  spec/helpers/service_helper/textual_summary_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes, services

#5262 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation

#5258 Do not show Refresh button on Monitoring page
  app/helpers/application_helper/button/summary_reload.rb
  spec/helpers/application_helper/buttons/summary_reload_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes, toolbars

#5266 Upgrade from FactoryGirl to FactoryBot
  spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
  spec/controllers/ops_controller_spec.rb
  spec/helpers/application_helper/buttons/basic_spec.rb
Labels: technical debt, test

#5269 Downgrade types/enzyme to fix Travis
  package.json
Labels: hammer/no, test

#5268 Remove unnecessary cases from Custom Button tree node name generation
  app/presenters/tree_builder_buttons.rb
Labels: cleanup, hammer/no

#5264 Remove the unused squash_toggle method/route from TreeSupport
  app/controllers/application_controller.rb
  app/controllers/application_controller/tree_support.rb
  config/routes.rb
  spec/routing/ems_cloud_routing_spec.rb
  spec/routing/ems_container_routing_spec.rb
  spec/routing/ems_infra_routing_spec.rb
  spec/routing/ems_physical_infra_routing_spec.rb
  spec/routing/host_routing_spec.rb
  spec/routing/shared_examples/vm_common_examples.rb
  spec/routing/vm_or_template_routing_spec.rb
Labels: cleanup, hammer/no, trees

#5272 Use @types/enzyme v3.1.17 to prevent error TS2314
  package.json
Labels: hammer/no, test

#5139 Converted Catalog form
  app/controllers/catalog_controller.rb
  app/javascript/components/catalog-form/catalog-form.jsx
  app/javascript/components/catalog-form/catalog-form.schema.js
  app/javascript/components/dual-list-select/helpers.jsx
  app/javascript/forms/mappers/formsFieldsMapper.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
  app/javascript/spec/catalog-form/catalog-form.spec.js
  app/javascript/spec/dual-list-select/helpers.spec.js
  app/views/catalog/_column_lists.html.haml
  app/views/catalog/_stcat_form.html.haml
Labels: hammer/no, react, refactoring, services, ux/approved

#5173 Allow pausing/resuming foreman and ansible tower providers
  app/assets/javascripts/controllers/configuration_manager_form_controller.js
  app/assets/javascripts/miq_explorer.js
  app/controllers/application_controller/explorer.rb
  app/controllers/automation_manager_controller.rb
  app/controllers/availability_zone_controller.rb
  app/controllers/ems_block_storage_controller.rb
  app/controllers/ems_cloud_controller.rb
  app/controllers/ems_common.rb
  app/controllers/ems_common_helper.rb
  app/controllers/ems_container_controller.rb
  app/controllers/ems_infra_controller.rb
  app/controllers/ems_network_controller.rb
  app/controllers/ems_object_storage_controller.rb
  app/controllers/ems_physical_infra_controller.rb
  app/controllers/ems_storage_controller.rb
  app/controllers/flavor_controller.rb
  app/controllers/host_aggregate_controller.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/ems_common/angular.rb
  app/controllers/mixins/ems_common/core.rb
  app/controllers/mixins/ems_common/metrics.rb
  app/controllers/mixins/ems_common/pause_resume.rb
  app/controllers/mixins/ems_common_angular.rb
  app/controllers/mixins/manager_controller_mixin.rb
  app/controllers/provider_foreman_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/toolbar/automation_manager_provider_center.rb
  app/helpers/application_helper/toolbar/automation_manager_providers_center.rb
  app/helpers/application_helper/toolbar/configuration_manager_provider_center.rb
  app/helpers/application_helper/toolbar/configuration_manager_providers_center.rb
  app/presenters/explorer_presenter.rb
  app/views/automation_manager/explorer.html.haml
  app/views/configuration_manager/_shared_form.html.haml
  app/views/provider_foreman/explorer.html.haml
  app/views/shared/_provider_paused.html.haml
  spec/controllers/mixins/ems_common/angular_spec.rb
  spec/helpers/application_helper_spec.rb
Labels: hammer/no

#5274 Remove sandbox variables from the trees on the diagnostics screens
  app/controllers/ops_controller/diagnostics.rb
  app/presenters/tree_builder_diagnostics.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
Labels: cleanup, trees

#5275 Webpack - add watchOptions to ignore vim swapfiles
  config/webpack/shared.js
Labels: developer

#5277 Add All Custom Button Events page to Cloud Network
  app/views/cloud_network/show.html.haml
Labels: bug, gaprindashvili/yes, hammer/yes, networks

#5278 TreeBuilderInfraNetworking - remove dead code, fix style
  app/presenters/tree_builder_infra_networking.rb
Labels: technical debt

#5273 Clean up some sandbox variables on the Custom Buttons screen
  app/controllers/application_controller/automate.rb
  app/controllers/application_controller/buttons.rb
  app/controllers/miq_ae_customization_controller/custom_buttons.rb
  app/helpers/custom_button_helper.rb
  app/presenters/tree_builder_buttons.rb
  app/presenters/tree_builder_catalog_items.rb
  app/views/layouts/_ae_resolve_options.html.haml
  app/views/shared/buttons/_ab_form.html.haml
  app/views/shared/buttons/_ab_list.html.haml
  spec/controllers/application_controller/automate_spec.rb
  spec/controllers/application_controller/buttons_spec.rb
  spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb
  spec/views/shared/buttons/_ab_form.html.haml_spec.rb
Labels: automation/automate, hammer/no, refactoring, trees

#5285 Fix specs to use ChargebackRateDetailCurrency#code
  spec/controllers/chargeback_controller_spec.rb
Labels: test

#5276 Split method process_emss.
  app/controllers/mixins/ems_common/core.rb
Labels: automation/ansible tower, hammer/no, technical debt

#5282 InfraNetworking & Storage - remove dead methods
  app/controllers/infra_networking_controller.rb
  app/controllers/storage_controller.rb
Labels: technical debt

#5286 Fix add new action
  app/controllers/miq_policy_controller/miq_actions.rb
Labels: bug, control

#4304 Add endpoint url for azure
  app/controllers/mixins/ems_common/angular.rb
  app/controllers/mixins/ems_common_angular.rb
  app/views/layouts/angular-bootstrap/_endpoints_for_url.html.haml
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  app/views/shared/views/ems_common/angular/_form.html.haml
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/mixins/ems_common/angular_spec.rb
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Labels: bug, compute/cloud, hammer/no

#5220 Advanced Search Save: don't create unnecessary flash message
  app/controllers/application_controller/advanced_search.rb
Labels: bug, expressions/filters, hammer/no
