Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2019-11, with the labels that each got.

#6362 Use widget_minimized? method to de-duplicate code
  app/controllers/dashboard_controller.rb
Labels: ivanchuk/no, technical debt

#6133 [IVANCHUK] Added a nil check.
  app/views/shared/views/_ownership.html.haml
Labels: bug, compute/cloud

#6345 Fix typo in #6341
  app/views/static/ops/log_collection/log_collection.html.haml
Labels: bug, ivanchuk/yes

#6342 Extract expression types
  app/controllers/application_controller/filter/expression.rb
  app/controllers/report_controller/reports/editor.rb
  app/helpers/exp_atom_helper.rb
  app/views/layouts/exp_atom/_edit_field.html.haml
  app/views/layouts/exp_atom/_edit_tag.html.haml
  app/views/layouts/exp_atom/_editor.html.haml
  app/views/report/_form_filter.html.haml
  spec/controllers/miq_report_controller/reports/editor_spec.rb
  spec/helpers/atom_helper_spec.rb
Labels: expressions/filters, refactoring

#6355 Remove deprecated factory_by_name
  spec/presenters/tree_node/availability_zone_spec.rb
  spec/presenters/tree_node/configured_system_spec.rb
  spec/presenters/tree_node/container_spec.rb
  spec/presenters/tree_node/customization_template_spec.rb
  spec/presenters/tree_node/ems_cluster_spec.rb
  spec/presenters/tree_node/ems_folder_spec.rb
  spec/presenters/tree_node/ext_management_system_spec.rb
  spec/presenters/tree_node/host_spec.rb
  spec/presenters/tree_node/pxe_image_spec.rb
  spec/presenters/tree_node/vm_or_template_spec.rb
Labels: technical debt, test

#6360 Enable babel-loader caching
  config/webpack/loaders.js
Labels: developer

#6371 Update ui-components to 1.3.3
  package.json
Labels: dependencies, ivanchuk/no

#6372 Fix node ID generation for MiqAeClassController#open_parent_nodes
  app/controllers/miq_ae_class_controller.rb
Labels: bug

#6291 DialogUser - use DialogData.outputConversion before submit and refresh
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/assets/javascripts/controllers/dialog_user/dialog_user_reconfigure_controller.js
  app/assets/javascripts/services/dialog_field_refresh_service.js
  spec/javascripts/controllers/dialog_user/dialog_user_controller_spec.js
  spec/javascripts/services/dialog_field_refresh_service_spec.js
Labels: bug, hammer/yes, ivanchuk/yes

#6373 [IVANCHUK] Update ui-components to 1.2.15 for ivanchuk
  package.json
  yarn.lock
Labels: dependencies

#6367 More report cleanup
  app/controllers/application_controller/report_downloads.rb
  app/views/layouts/print/report.html.haml
Labels: cloud intel/reporting, refactoring

#6374 Force user group reload after changing permissions so tree is correct
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, hammer/yes, settings

#6376 Disable clicking on Edit Tags without selecting Configured Systems
  app/helpers/application_helper/toolbar/configured_system/automation/policy_mixin.rb
Labels: bug, configuration management, ivanchuk/yes

#6352 Show name in success catalog form messages
  app/controllers/catalog_controller.rb
  app/javascript/components/catalog-form/catalog-form.jsx
  app/javascript/spec/catalog-form/catalog-form.spec.js
Labels: bug, changelog/yes, ivanchuk/yes

#5854 Vertical navbar
  app/assets/stylesheets/patternfly_overrides.scss
  app/helpers/application_helper/navbar.rb
  app/javascript/components/main-menu/helpers.js
  app/javascript/components/main-menu/main-menu.jsx
  app/javascript/components/main-menu/recursive-props.js
  app/javascript/components/main-menu/second-level.jsx
  app/javascript/components/main-menu/third-level.jsx
  app/javascript/components/main-menu/top-level.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/packs/globals.js
  app/javascript/spec/main-menu/__snapshots__/main-menu.spec.js.snap
  app/javascript/spec/main-menu/main-menu.spec.js
  app/javascript/spec/toolbar/__snapshots__/dashboard_toolbar.spec.jsx.snap
  app/views/layouts/_vertical_navbar.html.haml
Labels: hammer/no, ivanchuk/no, react

#6224 Refactor get_rec_cls to get proper record class for various items
  app/controllers/application_controller/ci_processing.rb
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/cloud_object_store_object_controller.rb
  app/controllers/ems_cluster_controller.rb
  app/controllers/ems_infra_controller.rb
  app/controllers/ems_storage_controller.rb
  app/controllers/host_controller.rb
  app/controllers/miq_template_controller.rb
  app/controllers/orchestration_stack_controller.rb
  app/controllers/resource_pool_controller.rb
  app/controllers/service_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_common.rb
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/cloud_object_store_container_spec.rb
  spec/controllers/ems_cluster_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/ems_storage_controller_spec.rb
  spec/controllers/host_controller_spec.rb
  spec/controllers/miq_template_controller_spec.rb
  spec/controllers/orchestration_stack_controller_spec.rb
  spec/controllers/resource_pool_controller_spec.rb
  spec/controllers/service_controller_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_common_spec.rb
Labels: refactoring

#6384 Fix CloudVolume constantization issues by using try/safe_constantize
  app/helpers/application_helper/button/cloud_volume_new.rb
Labels: bug, ivanchuk/no

#6383 Fix TreeNode selectability and checkboxes for alert profile assign
  app/presenters/tree_builder_alert_profile_obj.rb
Labels: bug, ivanchuk/no, trees

#6240 React tree view with redux store
  app/javascript/components/tree-view/hierarchical-tree-view.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/tree-view/tree-view.spec.js
Labels: ivanchuk/no, trees

#6385 Optimization - consistent date formats
  app/assets/javascripts/miq_global.js
  app/javascript/optimization/transform.js
  app/views/layouts/application.html.haml
Labels: bug, ivanchuk/yes, overview/optimization

#6386 ReportDataTable - fix error when data.report is null
  app/javascript/components/report-data-table.jsx
Labels: bug, overview/optimization

#6389 Unify the service catalog order button handling on list/single views
  app/views/catalog/_svccat_tree_show.html.haml
Labels: bug, ivanchuk/no, services

#6365 Make Save button disabled after canceling User's password changes
  app/assets/javascripts/miq_change_stored_password.js
  app/views/ops/_rbac_user_details.html.haml
Labels: bug, changelog/yes, ivanchuk/yes, settings

#6382 Fix double ng-if
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: automation/automate, changelog/no, cleanup, ivanchuk/no, services

#6399 Ping controller fix
  app/controllers/ping_controller.rb
  spec/controllers/ping_controller_spec.rb
Labels: bug, hammer/no, ivanchuk/yes

#6395 Remove old class
  app/assets/stylesheets/patternfly_overrides.scss
Labels: cleanup, formatting/styling, ivanchuk/no

#6398 Policy: simplify handling of @trees, make in an array.
  app/controllers/miq_policy_controller.rb
Labels: breadcrumbs, bug, trees

#6387 Add page title for custom menu items.
  app/helpers/application_helper/title.rb
Labels: enhancement, menus

#6407 Uncomment PingController spec
  spec/controllers/ping_controller_spec.rb
Labels: test

#6368 Set empty report submenus to empty arrays instead of empty strings
  app/controllers/report_controller/menus.rb
Labels: bug, hammer/yes, ivanchuk/yes, overview/reporting

#6403 Display name instead of [object Object] for the Host in Network Port's Relationships table
  app/helpers/network_port_helper/textual_summary.rb
  spec/helpers/network_port_helper/textual_summary_spec.rb
Labels: bug, ivanchuk/yes, networks

#6405 Service Catalog styling fix
  app/views/catalog/_svccat_tree_show.html.haml
Labels: bug, formatting/styling, ivanchuk/no

#6404 Remove custom "static" class
  app/assets/stylesheets/patternfly_overrides.scss
  app/views/catalog/_ot_tree_show.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/catalog/_stcat_tree_show.html.haml
  app/views/catalog/_svccat_tree_show.html.haml
  app/views/chargeback/_cb_rate_edit.html.haml
  app/views/chargeback/_cb_rate_show.html.haml
  app/views/generic_object_definition/_show_custom_button.html.haml
  app/views/generic_object_definition/_show_custom_button_group.html.haml
  app/views/host/_config.html.haml
  app/views/layouts/_adv_search_body.html.haml
  app/views/layouts/_group_filter_expression.html.haml
  app/views/miq_ae_class/_method_inputs.html.haml
  app/views/miq_ae_customization/_dialog_info.html.haml
  app/views/miq_ae_customization/_dialog_sample.html.haml
  app/views/miq_ae_customization/_old_dialogs_details.html.haml
  app/views/miq_ae_tools/_results_uri.html.haml
  app/views/miq_policy/_action_details.html.haml
  app/views/miq_policy/_alert_profile_details.html.haml
  app/views/miq_policy/_event_details.html.haml
  app/views/miq_policy/_policy_details.html.haml
  app/views/ops/_ap_show.html.haml
  app/views/ops/_db_info.html.haml
  app/views/ops/_logs_selected.html.haml
  app/views/ops/_rbac_tag_box.html.haml
  app/views/ops/_schedule_show.html.haml
  app/views/ops/_selected_by_roles.html.haml
  app/views/ops/_selected_by_servers.html.haml
  app/views/ops/_server_desc.html.haml
  app/views/ops/_settings_evm_servers_tab.html.haml
  app/views/ops/_settings_import_tags_tab.html.haml
  app/views/ops/rhn/_info_subscribed.html.haml
  app/views/report/_db_show.html.haml
  app/views/report/_report_info.html.haml
  app/views/report/_show_schedule.html.haml
  app/views/report/_widget_show.html.haml
  app/views/shared/buttons/_ab_list.html.haml
  app/views/shared/buttons/_ab_show.html.haml
  app/views/static/ansible-raw-stdout.html.haml
  app/views/vm_common/_snapshots_desc.html.haml
Labels: cleanup, formatting/styling, ivanchuk/no

#6412 Allow create Service Dialog from Template on Ansible/Templates screen, depending on navigation steps
  app/controllers/automation_manager_controller.rb
Labels: automation/ansible tower, bug, ivanchuk/no

#6410 Move vertical nav styling into a separate file
  app/assets/stylesheets/application.css
  app/assets/stylesheets/patternfly_overrides.scss
  app/assets/stylesheets/vertical_navigation.scss
Labels: cleanup, formatting/styling, ivanchuk/no

#6408 [HAMMER] Update ui-components to 1.1.35 for hammer
  package.json
  yarn.lock
Labels: dependencies

#6416 Try to create a dashboard without needed fields
  spec/controllers/miq_report_controller/dashboards_spec.rb
Labels: test

#6388 Dialog Editor, ExplorerPresenter - make sure all ids are strings in javascript
  app/controllers/infra_networking_controller.rb
  app/controllers/vm_common.rb
  app/helpers/miq_ae_customization_helper.rb
  app/presenters/explorer_presenter.rb
  spec/presenters/explorer_presenter_spec.rb
Labels: angular dialogs, bug, hammer/yes, ivanchuk/yes

#6411 Remove control-labelimage class
  app/assets/stylesheets/patternfly_overrides.scss
  app/views/catalog/_svccat_tree_show.html.haml
  app/views/ops/_selected_by_servers.html.haml
Labels: cleanup, formatting/styling, ivanchuk/no

#6391 Display user info after clicking on Lookup while provisioning VM
  app/controllers/miq_request_controller.rb
  spec/controllers/miq_request_controller_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes

#6396 Pretty print the webpack list
  lib/tasks/manageiq/ui_tasks.rake
Labels: developer

#6414 Add fallback for clicking on a section w/o permissions.
  app/controllers/dashboard_controller.rb
Labels: bug, menus

#6406 Sprints 122,123, and 124
  CHANGELOG.md
Labels: documentation

#6421 Display icons in GTLs on PXE screens
  app/controllers/application_controller.rb
Labels: bug, gtls

#6415 [HAMMER] DialogUser - use DialogData.outputConversion before submit and refresh
  app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
  app/assets/javascripts/controllers/dialog_user/dialog_user_reconfigure_controller.js
  app/assets/javascripts/services/dialog_field_refresh_service.js
  spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
  spec/javascripts/helpers/object.values.js
  spec/javascripts/services/dialog_field_refresh_service_spec.js
  spec/javascripts/support/jasmine.yml
Labels: bug

#6423 [HAMMER] Update ui-components to 1.1.36 for hammer
  package.json
  yarn.lock
Labels: dependencies

#6417 Compare Treegrid fix
  app/views/layouts/_compare.html.haml
Labels: bug, compute/infrastructure, ivanchuk/yes

#6424 Move compare/drift styling into a separate file
  app/assets/stylesheets/application.css
  app/assets/stylesheets/compare_drift.scss
  app/assets/stylesheets/patternfly_overrides.scss
Labels: changelog/no, cleanup, formatting/styling, ivanchuk/no

#6428 Fix VmInfra Reconfigure specs
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/helpers/application_helper/buttons/vm_reconfigure_spec.rb
Labels: test

#6429 Remove ems_ref_obj
  app/controllers/ems_infra_controller.rb
  spec/controllers/ems_infra_controller_spec.rb
Labels: compute/infrastructure, technical debt

#6379 Allow tagging or managing policies for Replicators, Pods, Nodes, Images
  app/controllers/mixins/ems_common.rb
  spec/controllers/mixins/ems_common_spec.rb
Labels: compute/containers, enhancement

#6427 Remove unnecessary one-liner alias functions from Compare/Drift
  app/controllers/application_controller/compare.rb
Labels: cleanup, ivanchuk/no, technical debt

#6334 Add Refresh button to individual Dashboard Widget
  app/controllers/dashboard_controller.rb
  app/javascript/angular/dashboard/dropdown-menu.js
  app/javascript/angular/dashboard/widget-wrapper.js
  app/javascript/spec/dashboard/widget-empty.spec.js
  app/javascript/spec/dashboard/widget-wrapper.spec.js
  app/presenters/widget_presenter.rb
  app/views/dashboard/_widget.html.haml
  config/routes.rb
Labels: enhancement, ivanchuk/no, overview/dashboard

#6432 Fix cancel/reset buttons' reaction to C&U collection checkboxes
  app/controllers/ops_controller/settings/cap_and_u.rb
Labels: bug, ivanchuk/yes, trees

#6431 Call `miqCheckForChanges` before changing tabs.
  app/assets/javascripts/miq_application.js
  app/views/miq_request/_prov_wf.html.haml
  app/views/ops/_ap_form.html.haml
Labels: bug

#6437 Remove custom "no-border" class
  app/assets/stylesheets/patternfly_overrides.scss
  app/views/ops/_settings_help_menu_tab.html.haml
Labels: cleanup, formatting/styling, ivanchuk/no

#6436 Compare/drift styling cleanup
  app/assets/stylesheets/compare_drift.scss
Labels: cleanup, formatting/styling, ivanchuk/no

#6438 Remove duplicate styling
  app/assets/stylesheets/patternfly_overrides.scss
Labels: cleanup, formatting/styling, ivanchuk/no

#6439 Fix rubocop warnings in CatalogController
  app/controllers/catalog_controller.rb
Labels: technical debt

#6440 Fix rubocop in AnsibleCredentialController
  app/controllers/ansible_credential_controller.rb
Labels: changelog/no, technical debt

#6441 Fix rubocop warnings in AnsibleRepositoryController
  app/controllers/ansible_repository_controller.rb
Labels: changelog/no, technical debt

#6442 Fix rubocop warnings in AutomationManagerController
  app/controllers/automation_manager_controller.rb
Labels: changelog/no, technical debt

#6443 Fix rubocop warnings in ChargebackController
  app/controllers/chargeback_controller.rb
Labels: changelog/no, technical debt

#6444 Fix rubocop warnings in CloudNetworkController
  app/controllers/cloud_network_controller.rb
Labels: changelog/no, technical debt

#6445 Fix rubocop warnings in CloudObjectStoreContainerController
  app/controllers/cloud_object_store_container_controller.rb
Labels: changelog/no, technical debt

#6446 Fix rubocop in CloudSubnetController
  app/controllers/cloud_subnet_controller.rb
Labels: changelog/no, technical debt

#6337 Prefer item name over item description
  app/controllers/application_controller.rb
  spec/controllers/miq_ae_class_controller_spec.rb
  spec/controllers/miq_ae_customization_controller/old_dialogs_spec.rb
  spec/controllers/ops_controller/settings/analysis_profiles_spec.rb
Labels: bug, ivanchuk/yes, services

#6351 Remove Tags from Network Topology View and others
  app/assets/javascripts/controllers/topology/cloud_topology_controller.js
  app/assets/javascripts/controllers/topology/infra_topology_controller.js
  app/assets/javascripts/controllers/topology/network_topology_controller.js
  app/assets/javascripts/controllers/topology/physical_infra_topology_controller.js
  app/assets/javascripts/services/topology_service.js
  app/services/cloud_topology_service.rb
  app/services/infra_topology_service.rb
  app/services/network_topology_service.rb
  app/services/physical_infra_topology_service.rb
  app/services/topology_service.rb
  app/views/cloud_topology/show.html.haml
  app/views/infra_topology/show.html.haml
  app/views/network_topology/show.html.haml
  app/views/physical_infra_topology/show.html.haml
  spec/services/topology_service_spec.rb
Labels: changelog/yes, topology

#6349 Allow performing SSA on Clusters of Infra provider
  app/controllers/application_controller/ci_processing.rb
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: bug, changelog/yes

#6447 Remove old "widthed" form class
  app/assets/stylesheets/patternfly_overrides.scss
  app/views/report/_form_styling.html.haml
Labels: cleanup, formatting/styling, ivanchuk/no

#6451 Fix rubocop warning in CloudTenantController
  app/controllers/cloud_tenant_controller.rb
Labels: changelog/no, technical debt

#6450 Customized fonticon cleanup
  app/assets/stylesheets/icon_customizations.scss
  app/assets/stylesheets/patternfly_overrides.scss
  app/controllers/miq_policy_controller.rb
  app/views/miq_policy/import.html.haml
Labels: cleanup, formatting/styling, ivanchuk/no

#6453 Don't query for an exact type
  app/controllers/storage_controller/storage_pod.rb
  app/presenters/tree_builder_storage_pod.rb
Labels: changelog/no, trees

#6433 Rename usage ChargebackRateDetailCurrency to Currency
  app/controllers/catalog_controller.rb
  app/controllers/chargeback_controller.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/chargeback_controller_spec.rb
Labels: technical debt, wip

#6462 Rename ChargebackRateDetailCurrency to Currency in haml
  app/views/catalog/_form_basic_info.html.haml
  app/views/chargeback/_cb_rate_edit.html.haml
Labels: technical debt

#6464 Remove failing miq-toolbar snapshot test
  app/javascript/spec/toolbar/__snapshots__/miq-toolbar.spec.jsx.snap
  app/javascript/spec/toolbar/miq-toolbar.spec.jsx
Labels: test
