Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-04, with the labels that each got.

#6809 Remove max value for resizing of a disk
  app/assets/javascripts/directives/reconfigure/validateMultiple.js
  app/views/vm_common/_reconfigure.html.haml
Labels: bug, compute/infrastructure, ivanchuk/no

#6806 subtree_arranged of_type is a string, not a Class
  app/presenters/tree_builder_alert_profile_assign.rb
Labels: bug

#6813 [IVANCHUK] Remove max value for resizing of a disk
  app/assets/javascripts/directives/reconfigure/validateMultiple.js
  app/views/vm_common/_reconfigure.html.haml
Labels: bug, compute/infrastructure

#6808 Fix duplicates in removal dialogs
  app/javascript/components/remove-catalog-item-modal.jsx
  app/javascript/components/remove-generic-item-modal.jsx
  app/javascript/spec/remove-catalog-item-modal/__snapshots__/remove-catalog-item-modal.spec.js.snap
  app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js
  config/jest.setup.js
Labels: bug

#6807 Catalog item removal dialog: fix unordered list markup
  app/javascript/components/remove-catalog-item-modal.jsx
  app/javascript/spec/remove-catalog-item-modal/__snapshots__/remove-catalog-item-modal.spec.js.snap
Labels: bug, services

#6812 AuthKeyPair to use remove modal for deletion
  app/controllers/auth_key_pair_cloud_controller.rb
  app/helpers/application_helper/toolbar/auth_key_pair_cloud_center.rb
  app/helpers/application_helper/toolbar/auth_key_pair_clouds_center.rb
Labels: enhancement

#6816 Consume actioncable from NPM, move notifications code to modern JS
  app/assets/javascripts/application.js
  app/assets/javascripts/cable.js
  app/assets/javascripts/miq_global.js
  app/javascript/components/notification-drawer/notification-drawer.jsx
  app/javascript/notifications/init.js
  app/javascript/packs/application-common.js
  app/javascript/spec/notification-drawer/notification-drawer.spec.js
  app/views/layouts/_header.html.haml
  app/views/layouts/_notifications_drawer.html.haml
  app/views/layouts/_toast_list.html.haml
  app/views/layouts/application.html.haml
  package.json
Labels: cleanup, react

#6620 POC Add debride
  .travis.yml
  Rakefile
  manageiq-ui-classic.gemspec
  tools/ci/dead_method_check.sh
Labels: dependencies, developer

#6952 Fix jest snapshot error
  app/javascript/spec/remove-catalog-item-modal/__snapshots__/remove-catalog-item-modal.spec.js.snap
Labels: test

#6955 Prefer stubbing permissions over modifying the backend
  spec/helpers/application_helper_spec.rb
Labels: cleanup, test

#6951 Clean up the header
  app/views/layouts/_header.html.haml
  app/views/layouts/_navbar-header.html.haml
  app/views/layouts/_right_section.html.haml
Labels: cleanup

#6815 Use removal modal for ansible tower provider removal
  app/assets/javascripts/controllers/report_data_controller.js
  app/controllers/mixins/manager_controller_mixin.rb
  app/helpers/application_helper/toolbar/automation_manager_provider_center.rb
  app/helpers/application_helper/toolbar/automation_manager_providers_center.rb
  app/helpers/application_helper/toolbar/configuration_manager_provider_center.rb
  app/helpers/application_helper/toolbar/configuration_manager_providers_center.rb
  app/javascript/components/remove-generic-item-modal.jsx
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/provider_foreman_controller_spec.rb
Labels: enhancement

#6957 Remove copy-pasted and possibly dead code from Infra Networking
  app/controllers/infra_networking_controller.rb
Labels: cleanup, compute/infrastructure, jansa/no

#6958 Always set node icon background explicitly instead of fallback CSS
  app/assets/stylesheets/patternfly_overrides.scss
  app/presenters/tree_builder_archived.rb
  app/presenters/tree_node/assigned_server_role.rb
  app/presenters/tree_node/hash.rb
  app/presenters/tree_node/vm_or_template.rb
  spec/presenters/tree_builder_archived_spec.rb
  spec/presenters/tree_builder_images_spec.rb
  spec/presenters/tree_builder_instances_spec.rb
  spec/presenters/tree_builder_roles_by_server_spec.rb
  spec/presenters/tree_builder_servers_by_role_spec.rb
Labels: jansa/no, technical debt, trees

#6960 Remove unnecessary post_check from tenants tree under catalogs
  app/presenters/tree_builder_tenants.rb
Labels: cleanup, jansa/no, trees

#6961 Move TreeBuilder.group_id under TreeBuilderBelongsToHac
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_belongs_to_hac.rb
Labels: cleanup, trees

#6966 Get rid of the no longer used @miq_after_onload
  app/controllers/mixins/manager_controller_mixin.rb
  app/controllers/mixins/vm_show_mixin.rb
  app/views/layouts/_header.html.haml
Labels: cleanup, technical debt

#6969 Fix snapshot toolbar button always disabled
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
  app/helpers/application_helper/toolbar/x_vm_snapshot_center.rb
Labels: bug, compute/infrastructure, jansa/yes?

#6962 Remove obsolete lines from CODEOWNERS
  .github/CODEOWNERS
Labels: cleanup

#6970 [Rails52] Use arel to fix "Dangerous query method"
  app/controllers/application_controller.rb
  app/controllers/application_controller/ci_processing.rb
  app/controllers/catalog_controller.rb
  app/controllers/mixins/actions/host_actions/misc.rb
  app/controllers/mixins/containers_common_mixin.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/ems_common/core.rb
  app/controllers/mixins/manager_controller_mixin.rb
  app/presenters/tree_builder_automation_manager_configuration_scripts.rb
  app/presenters/tree_builder_infra_networking.rb
  spec/presenters/tree_builder_spec.rb
Labels: cleanup

#6971 [Rails52] Fixes deprecated rack helpers
  spec/controllers/ops_controller_spec.rb
  spec/controllers/report_controller_spec.rb
Labels: cleanup

#6964 Reimplemented 🌳🌳 post_check in Ruby from JavaScript
  app/assets/javascripts/miq_tree.js
  app/javascript/spec/old_js/miq_tree.spec.js
  app/presenters/tree_builder.rb
  app/views/layouts/_tree.html.haml
  spec/presenters/tree_builder_spec.rb
Labels: technical debt, trees

#6686 Use Net::SSH:HostKeyMistmatch instead of MiqSshUtilHostKeyMismatch
  app/controllers/host_controller.rb
Labels: refactoring

#6975 Simplified checkedness of 🌳🌳 on compare screens, enabled post_check
  app/presenters/tree_builder_sections.rb
  spec/presenters/tree_builder_sections_spec.rb
Labels: bug, cleanup, trees

#6956 Allow chaining method calls built from report columns in layouts/item
  app/views/layouts/_item.html.haml
Labels: bug

#6972 Redirect to proper screen after succesful update of a Cloud Tenant in a list
  app/controllers/cloud_tenant_controller.rb
  spec/controllers/cloud_tenant_controller_spec.rb
Labels: bug, compute/cloud, jansa/yes

#6974 Delete Cloud Tenants selected in a nested list
  app/controllers/cloud_tenant_controller.rb
  app/controllers/mixins/ems_common.rb
  config/routes.rb
  spec/controllers/cloud_tenant_controller_spec.rb
  spec/controllers/mixins/ems_common_spec.rb
Labels: bug, compute/cloud, jansa/yes

#6759 Display buttons for Evacuate Instances in a nested list, remove pagingDivButtonGroupController
  app/assets/javascripts/components/vm_cloud/vm_cloud_evacuate_form.js
  app/assets/javascripts/controllers/buttons/paging_div_button_group_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_associate_floating_ip_form_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_attach_form_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_detach_form_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_disassociate_floating_ip_form_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_live_migrate_form_controller.js
  app/assets/javascripts/controllers/vm_cloud/vm_cloud_resize_form_controller.js
  app/controllers/ops_controller.rb
  app/controllers/service_controller.rb
  app/controllers/vm_common.rb
  app/views/layouts/angular/_paging_div_buttons.html.haml
  app/views/static/evacuate-form.html.haml
  app/views/vm_common/_associate_floating_ip.html.haml
  app/views/vm_common/_attach.html.haml
  app/views/vm_common/_detach.html.haml
  app/views/vm_common/_disassociate_floating_ip.html.haml
  app/views/vm_common/_live_migrate.html.haml
  app/views/vm_common/_resize.html.haml
  spec/javascripts/controllers/buttons/paging_div_button_group_controller_spec.js
Labels: bug

#6965 Redirect to proper screen after reconfiguring, migrating, evacuating Instances in a nested list
  app/controllers/mixins/actions/vm_actions/evacuate.rb
  app/controllers/mixins/actions/vm_actions/live_migrate.rb
  app/controllers/mixins/actions/vm_actions/resize.rb
  spec/controllers/mixins/actions/vm_actions/evacuate_spec.rb
  spec/controllers/mixins/actions/vm_actions/live_migrate_spec.rb
  spec/controllers/mixins/actions/vm_actions/resize_spec.rb
Labels: bug

#6797 Remove extra flash message after attaching/detaching Cloud Volume from Instance
  app/controllers/cloud_network_controller.rb
  app/controllers/cloud_subnet_controller.rb
  app/controllers/vm_cloud_controller.rb
  spec/controllers/cloud_network_controller_spec.rb
  spec/controllers/cloud_subnet_controller_spec.rb
  spec/controllers/host_aggregate_controller_spec.rb
  spec/controllers/vm_cloud_controller_spec.rb
Labels: bug, jansa/yes?

#6979 Fix TreeBuilder#post_check to actually reverse! the nodes
  app/presenters/tree_builder.rb
Labels: bug, trees

#6981 [IVANCHUK] - Enable Check Compliance toolbar button for nested list of VMs and make it work
  app/controllers/application_controller/ci_processing.rb
  app/controllers/ems_cluster_controller.rb
  app/controllers/host_controller.rb
  app/controllers/resource_pool_controller.rb
  app/helpers/application_helper/toolbar/vm_clouds_center.rb
  app/helpers/application_helper/toolbar/vm_infras_center.rb
  spec/controllers/auth_key_pair_cloud_controller_spec.rb
  spec/controllers/availability_zone_controller_spec.rb
  spec/controllers/cloud_tenant_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_cluster_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/flavor_controller_spec.rb
  spec/controllers/host_aggregate_controller_spec.rb
  spec/controllers/host_controller_spec.rb
  spec/controllers/resource_pool_controller_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_cloud_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: bug

#6984 remove-generic-item-modal: fix typeof==undefined bug
  .eslintrc.json
  app/javascript/.eslintrc.json
  app/javascript/components/remove-generic-item-modal.jsx
Labels: bug, jansa/yes

#6994 Menu - sort Providers menu together, singular
  app/presenters/menu/default_menu.rb
Labels: enhancement

#6985 Replace angular-based fonticon picker with a react component
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/fonticon_picker.scss
  app/javascript/components/fonticon-picker/icon-list.jsx
  app/javascript/components/fonticon-picker/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/views/shared/buttons/_ab_options_form.html.haml
  app/views/shared/buttons/_group_form.html.haml
Labels: enhancement, react

#6992 Make sure custom button doesn't need to be checked when on summary page
  app/helpers/application_helper/toolbar_builder.rb
Labels: bug, jansa/yes?, services

#6953 prov_dialog customize - don't fail when no :sysprep_enabled
  app/views/shared/views/_prov_dialog.html.haml
Labels: bug, ivanchuk/yes

#7003 Merge default button labels properly with the custom ones in DDF
  app/javascript/forms/data-driven-form.jsx
Labels: bug, internationalization, react
