Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-06, with the labels that each got.

#7092 Remove duplicated FieldArray component from the component mapper
  app/javascript/forms/mappers/formFieldsMapper.jsx
Labels: technical debt

#7093 MiqTask to get stdout for Ansible should be owned by user who requested view
  app/views/service/_svcs_show.html.haml
Labels: bug, ivanchuk/yes, jansa/yes?, services

#7097 CustomLoader - load from all Engines' .menu
  app/presenters/menu/custom_loader.rb
  spec/presenters/menu/custom_loader_spec.rb
Labels: developer, enhancement, jansa/yes?

#7095 Disable privilege escalation when machine credential doesn't support it
  app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
  app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
  app/views/layouts/angular/_ansible_form_options_angular.html.haml
Labels: bug, ivanchuk/yes, jansa/yes, services

#7102 Remove the no longer used ownership_field_changed route
  spec/routing/service_routing_spec.rb
  spec/routing/shared_examples/vm_common_examples.rb
  spec/routing/vm_or_template_routing_spec.rb
  spec/routing/vm_routing_spec.rb
Labels: cleanup

#7103 Drop the unused ownership_form_fields method/route
  app/controllers/mixins/actions/vm_actions/ownership.rb
  config/routes.rb
Labels: cleanup

#7077 Fix broken select in PXE server form
  app/javascript/forms/input-with-dynamic-prefix.jsx
  app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
Labels: bug, jansa/yes?, react

#7086 Fix missing partial for GOD page
  app/controllers/generic_object_definition_controller.rb
  app/helpers/application_helper/page_layouts.rb
  app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml
Labels: bug, jansa/no

#7088 Remove maintab, rembember_tab, session[:tab_url] functionality
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/mixins/menu_update_mixin.rb
  app/helpers/application_helper/navbar.rb
  app/presenters/menu/section.rb
  config/routes.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/mixins/menu_update_mixin_spec.rb
  spec/requests/auth_spec.rb
  spec/routing/dashboard_routing_spec.rb
Labels: cleanup, jansa/yes?

#7107 I18N for strings on Utilization screen
  app/controllers/application_controller/performance.rb
Labels: bug, internationalization, jansa/yes

#7108 Remove not existing route prov_show_option
  config/routes.rb
  spec/routing/miq_request_routing_spec.rb
Labels: cleanup, jansa/no

#7104 Fixed `.find` call in Profile remove_member call
  app/controllers/miq_policy_controller/policy_profiles.rb
  spec/controllers/miq_policy_controller/policy_profiles_spec.rb
Labels: bug, control, jansa/yes

#7085 Add Firefox cypress helper
  cypress/README.md
  package.json
Labels: cypress, dependencies, test

#7110 Don't render empty cd-rom table in VM reconfigure screen
  app/views/vm_common/_reconfigure.html.haml
Labels: bug, compute/infrastructure

#7100 Change to support simplified direct link for assignments
  app/controllers/chargeback_assignment_controller.rb
Labels: enhancement, jansa/yes?, overview/chargeback

#7112 Add noreferrer noopener to external links
  app/javascript/react/textual_summary_click.js
  app/views/layouts/_empty.html.haml
  app/views/shared/views/_alerts_list.html.haml
Labels: bug, jansa/yes?

#7106 [JANSA] Added translations for 9 languages
  app/assets/javascripts/locale/de/app.js
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/it/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/ko/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
  app/assets/javascripts/locale/zh_TW/app.js
Labels: enhancement, internationalization

#7113 Remove unused routes for catalog controller
  app/views/layouts/_tag_edit.html.haml
  config/routes.rb
  spec/routing/catalog_routing_spec.rb
Labels: cleanup

#7114 Remove unused routes from auth_key_pair cloud_controller
  config/routes.rb
Labels: cleanup

#7115 Drop the unused tag_edit_form_field_changed route
  config/routes.rb
  spec/routing/ems_configuration_routing_spec.rb
  spec/routing/ems_infra_routing_spec.rb
  spec/routing/ems_physical_infra_routing_spec.rb
  spec/routing/ops_routing_spec.rb
  spec/routing/orchestration_stack_routing_spec.rb
  spec/routing/security_group_routing_spec.rb
  spec/routing/service_routing_spec.rb
  spec/routing/shared_examples/tagging_examples.rb
Labels: cleanup

#7109 Clean up non-existing host routes.
  config/routes.rb
  spec/helpers/application_helper_spec.rb
  spec/routing/host_routing_spec.rb
  spec/routing/shared_examples/crud_examples.rb
Labels: cleanup, jansa/yes?

#7116 Fix to translate string in UI
  app/views/miq_policy/_alert_builtin_exp.html.haml
  app/views/miq_policy/_alert_details.html.haml
Labels: bug, internationalization, jansa/yes

#7119 Clean up dashboard routes.
  config/routes.rb
  spec/routing/dashboard_routing_spec.rb
Labels: cleanup, jansa/yes?

#7111 Hawkular & Middleware cleanup
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/application_controller.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/ems_common/angular.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
  app/views/layouts/angular/_multi_auth_credentials.html.haml
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
  spec/javascripts/fixtures/json/toolbar_middleware_server_detail.json
  spec/javascripts/fixtures/json/toolbar_middleware_server_list.json
  spec/javascripts/services/topology_service_spec.js
  spec/presenters/tree_node/ext_management_system_spec.rb
Labels: cleanup

#7122 Menu - update collapsed user icon
  app/javascript/menu/username.jsx
  app/stylesheet/menu-colors.scss
  app/stylesheet/menu.scss
Labels: enhancement, jansa/no

#7094 Display a validation success message upon DDF credential validation
  app/javascript/components/async-credentials/async-credentials.jsx
Labels: bug

#7125 Do not allow the users to switch to a group that they don't belong to
  app/controllers/dashboard_controller.rb
Labels: bug, jansa/yes?, settings

#7127 Rename the features_tree when not in edit mode under Access Control
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, react, trees

#7121 Allow to select whole hour in dialog sample screen
  app/views/miq_ae_customization/_dialog_sample.html.haml
Labels: automation/automate, bug, ivanchuk/yes, jansa/yes?

#7123 Massively delete some dead routes that have no matching methods
  app/views/vm_common/_evm_relationship.html.haml
  config/routes.rb
  spec/routing/configuration_routing_spec.rb
  spec/routing/ems_cloud_routing_spec.rb
  spec/routing/ems_cluster_routing_spec.rb
  spec/routing/ems_configuration_routing_spec.rb
  spec/routing/ems_container_routing_spec.rb
  spec/routing/ems_infra_routing_spec.rb
  spec/routing/ems_physical_infra_routing_spec.rb
  spec/routing/ems_storage_routing_spec.rb
  spec/routing/host_routing_spec.rb
  spec/routing/miq_ae_customization_routing_spec.rb
  spec/routing/miq_request_routing_spec.rb
  spec/routing/miq_task_routing_spec.rb
  spec/routing/report_routing_spec.rb
  spec/routing/shared_examples/utilization_examples.rb
  spec/routing/shared_examples/vm_common_examples.rb
  spec/routing/vm_infra_routing_spec.rb
  spec/routing/vm_or_template_routing_spec.rb
  spec/routing/vm_routing_spec.rb
  spec/views/layouts/_auth_credentials.html.haml_spec.rb
Labels: cleanup, jansa/yes?

#7129 Translate title of entries under Add a Widget button
  app/controllers/dashboard_controller.rb
Labels: bug, internationalization, jansa/yes?

#7128 Translate title of Dashboard widgets
  app/views/dashboard/_widget.html.haml
Labels: bug, internationalization, jansa/yes?

#7132 Remove extra *_xen reference from specs
  spec/presenters/tree_node/vm_or_template_spec.rb
Labels: cleanup

#7117 Remove unused routes from ops_controller
  app/views/layouts/_edit_log_depot_settings.html.haml
  app/views/ops/_category_form.html.haml
  config/routes.rb
  spec/routing/ops_routing_spec.rb
Labels: cleanup, jansa/yes?, technical debt

#7134 Delete unused *DashboardController#show methods and routes
  app/controllers/cloud_tenant_dashboard_controller.rb
  app/controllers/container_dashboard_controller.rb
  app/controllers/ems_cloud_dashboard_controller.rb
  app/controllers/ems_infra_dashboard_controller.rb
  app/controllers/ems_physical_infra_dashboard_controller.rb
  config/routes.rb
Labels: cleanup, dashboards, jansa/no

#7131 Clean up dead index routes
  app/controllers/catalog_controller.rb
  app/controllers/consumption_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/service_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_cloud_controller.rb
  app/controllers/vm_infra_controller.rb
  app/controllers/vm_or_template_controller.rb
  config/routes.rb
Labels: cleanup, jansa/no

#7135 Remove unused route identify_catalog in OpsController
  config/routes.rb
  spec/routing/catalog_routing_spec.rb
Labels: cleanup

#7130 Remove some additional dead routes from the application
  app/controllers/report_controller/schedules.rb
  config/routes.rb
  spec/routing/report_routing_spec.rb
Labels: cleanup

#7139 Do not mount the index route on ContainerDashboardController
  config/routes.rb
Labels: cleanup, jansa/no

#7138 Introducing a new test suite that checks the aliveness of routes
  .travis.yml
  Rakefile
  spec/routes_spec.rb
Labels: jansa/no, test

#7143 Remove old navbar styling from brand.scss
  vendor/assets/stylesheets/brand.scss
Labels: cleanup

#7136 nix the all_vm_or_templates callers
  app/controllers/application_controller.rb
  app/controllers/vm_common.rb
Labels: bug, jansa/yes?

#7142 Catalog Item: allow for selecting / deselecting whole tenant subtree
  app/controllers/catalog_controller.rb
  app/presenters/tree_builder_tenants.rb
  spec/controllers/catalog_controller_spec.rb
Labels: enhancement, services

#7146 Remove form action in report editor forms
  app/views/report/_form.html.haml
  app/views/report/_form_columns.html.haml
Labels: bug, jansa/no

#7140 [IVANCHUK] Allow selecting whole tenant subtree in catalog item creation
  app/controllers/catalog_controller.rb
  app/presenters/tree_builder_tenants.rb
  spec/controllers/catalog_controller_spec.rb
Labels: enhancement, services

#7133 Don't use the cloud_volume ems.parent_manager
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
Labels: bug, pending core

#7124 Add autocomplete=off to all rails, angular and react password fields
  app/assets/javascripts/components/ansible-credential-options.js
  app/helpers/application_helper/form_tags.rb
  app/javascript/components/async-credentials/edit-password-field.jsx
  app/javascript/components/async-credentials/password-field.jsx
  app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
  app/views/dashboard/_login_more.html.haml
  app/views/dashboard/login.html.haml
  app/views/layouts/angular-bootstrap/_auth_credentials_angular_bootstrap.html.haml
  app/views/miq_ae_class/_angular_inputs_form.html.haml
  app/views/ops/_rbac_user_details.html.haml
  app/views/ops/_settings_replication_tab.html.haml
  app/views/static/auth-credentials.html.haml
  app/views/static/ems_physical_infra/change_password.html.haml
  app/views/static/evacuate-form.html.haml
Labels: bug, jansa/yes?

#7149 Pre-provisioning: fix button collision in explorers and missing hide deprecated in nested
  app/controllers/application_controller.rb
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/vm_common.rb
  app/helpers/hide_partial_helper.rb
  app/views/miq_request/_pre_prov.html.haml
  app/views/miq_request/pre_prov.html.haml
  spec/controllers/application_controller_spec.rb
Labels: bug, compute/cloud, compute/infrastructure

#7091 Replace the physical infra provider forms with the DDF-based new one
  app/helpers/ems_physical_infra_helper.rb
  app/views/ems_physical_infra/edit.html.haml
  app/views/ems_physical_infra/new.html.haml
Labels: enhancement, jansa/no, react

#7090 Replace the old network provider forms with the DDF-based ProviderForm
  app/helpers/ems_network_helper.rb
  app/views/ems_network/edit.html.haml
  app/views/ems_network/new.html.haml
Labels: enhancement, jansa/no, react

#7152 [Gemfile] Remove "second" source
  Gemfile
Labels: dependencies

#7157 Moved common code to a method to reset tier details when switching Type.
  app/controllers/chargeback_rate_controller.rb
Labels: bug, jansa/yes?

#7159 render_exception: use error modal
  app/assets/javascripts/controllers/error_modal_controller.js
  app/controllers/application_controller.rb
Labels: bug

#7160 Added `Back` button and locked sidebar on Chargeback Preview screen.
  app/controllers/vm_common.rb
  app/views/layouts/_x_edit_buttons.html.haml
Labels: bug, compute/infrastructure, jansa/yes
