Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-03, with the labels that each got.

#6728 An ExtManagementSystem requires a zone
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/helpers/application_helper_spec.rb
Labels: test

#6725 [IVANCHUK] Update CHANGELOG.md for Ivanchuk-3
  CHANGELOG.md
Labels: documentation

#6709 Make Advanced Search in Services screen reactive also in other tabs
  app/controllers/service_controller.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes, jansa/yes, services

#6729 Allow editing Groups from the list view
  app/helpers/application_helper/toolbar/miq_groups_center.rb
Labels: bug, ivanchuk/yes, jansa/yes?, settings

#6705 GTL SearchBox Helpers for Cypress tests
  cypress/integration/ui/gtl.spec.js
  cypress/integration/ui/searchbox.spec.js
  cypress/support/commands.js
Labels: test

#6726 Fix rubocop in OpsController::Settings::Zones
  app/controllers/ops_controller/settings/zones.rb
Labels: technical debt

#6730 Display all of the following, not just Foreman
  app/controllers/provider_foreman_controller.rb
  app/presenters/tree_builder_configuration_manager.rb
  app/presenters/tree_builder_configuration_manager_configured_systems.rb
  spec/controllers/provider_foreman_controller_spec.rb
Labels: configuration management, enhancement

#6736 Remove invalid tagdata stub
  spec/shared/controllers/shared_example_for_download_summary_pdf.rb
Labels: refactoring, test

#6737 [JANSA] yarn: lock versions by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies

#6739 Remove invalid partials from login specs that aren't used
  spec/views/dashboard/login.html.haml_spec.rb
Labels: refactoring, test

#6740 Remove invalid partials from cloud topology service specs
  spec/services/cloud_topology_service_spec.rb
Labels: refactoring, test

#6723 Allow add/delete of global filters based upon user's allowed features
  app/controllers/application_controller/advanced_search.rb
  app/presenters/tree_builder_ops_rbac_features.rb
  app/views/layouts/_adv_search_body.html.haml
  app/views/layouts/_adv_search_footer.html.haml
  spec/presenters/tree_builder_ops_rbac_features_spec.rb
Labels: enhancement, expressions/filters, pending core

#6744 Do not display disabled domains in automate entrypoint selections
  app/presenters/tree_builder_automate_catalog.rb
Labels: automation/automate, bug

#6747 Remove invalid partials from catalog controller specs
  spec/controllers/catalog_controller_spec.rb
Labels: refactoring, test

#6741 Remove unused layouts
  app/views/layouts/_auth_credentials_keypair.html.haml
  app/views/layouts/_discover_azure_credentials.html.haml
  app/views/layouts/_miq_vnc_plugin.html.haml
  app/views/layouts/_pdf_styles.html.haml
  app/views/layouts/_show_statistics.html.haml
  app/views/layouts/_tag_edit_cat_tags.html.haml
  app/views/layouts/angular/_edit_log_depot_settings_angular.html.haml
Labels: cleanup

#6745 Set patternfly-react to 2.39.14 exactly
  package.json
Labels: bug, dependencies

#6749 Do not include switches into VMs and Templates tree
  app/presenters/tree_builder_vandt.rb
Labels: bug, jansa/yes?

#6746 [JANSA] Set patternfly-react to 2.39.14 exactly
  package.json
  yarn.lock
Labels: bug, dependencies

#6727 Display newly saved expression in Advanced Search in My Services
  app/controllers/service_controller.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, services

#6743 Fix vm factory in prov_vm_grid haml spec
  spec/views/miq_request/_prov_vm_grid.html.haml_spec.rb
Labels: refactoring, test

#6750 Mixin the TextualSummaryHelper to fix invalid partials
  spec/helpers/host_helper/textual_summary_spec.rb
Labels: refactoring, test

#6752 Clean up login test a bit
  cypress/integration/ui/login.spec.js
Labels: technical debt, test

#6754 Mixin the TextualSummaryHelper to fix invalid partials, part 2
  spec/helpers/vm_helper/textual_summary_spec.rb
Labels: refactoring, test

#6755 Remove invalid partial from EmsPhysicalInfraController specs
  spec/controllers/ems_physical_infra_controller_spec.rb
Labels: refactoring, test

#6760 Remove invalid partials, refactor unused factories in CheckedIdMixin
  spec/controllers/mixins/checked_id_mixin_spec.rb
Labels: refactoring, test

#6751 Make the password-field component context-free and usable without validation
  app/javascript/components/async-credentials/async-credentials.jsx
  app/javascript/components/async-credentials/async-provider-credentials.jsx
  app/javascript/components/async-credentials/password-field.jsx
  app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
  app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
  app/javascript/spec/async-credentials/async-credentials.spec.js
  app/javascript/spec/async-credentials/password-field.spec.js
Labels: react

#6762 Mixin the TextualSummaryHelper to fix invalid partials, part 3
  spec/helpers/cloud_tenant_helper/textual_summary_spec.rb
  spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb
Labels: refactoring, test

#6733 Make GTL helpers more generic and update README
  cypress/README.md
  cypress/integration/ui/gtl.spec.js
  cypress/integration/ui/settings.spec.js
  cypress/support/commands.js
Labels: cypress, test

#6761 Remove openstack naming logic for Hosts & Clusters
  app/controllers/application_controller/ci_processing.rb
  app/controllers/ems_cluster_controller.rb
  app/controllers/host_controller.rb
  app/controllers/miq_policy_controller/miq_actions.rb
  app/controllers/mixins/actions/host_actions/discover.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/ops_controller/settings/schedules.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/title.rb
  app/helpers/ems_cluster_helper/textual_summary.rb
  app/helpers/ems_infra_helper/textual_summary.rb
  app/helpers/host_helper/textual_summary.rb
  app/helpers/infra_networking_helper/textual_summary.rb
  app/helpers/resource_pool_helper/textual_summary.rb
  app/helpers/storage_helper/textual_summary.rb
  app/helpers/term_of_service_helper.rb
  app/helpers/vm_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/presenters/tree_node/ems_cluster.rb
  app/presenters/tree_node/host.rb
  app/services/ems_infra_dashboard_service.rb
  app/views/ems_physical_infra/discover.html.haml
  app/views/layouts/_discover.html.haml
  app/views/layouts/_form_buttons_verify.html.haml
  app/views/layouts/_perf_options.html.haml
  app/views/layouts/angular/_form_buttons_verify_angular.html.haml
  app/views/layouts/listnav/_ems_cluster.html.haml
  app/views/layouts/listnav/_ems_infra.html.haml
  app/views/layouts/listnav/_host.html.haml
  app/views/layouts/listnav/_physical_server.html.haml
  app/views/layouts/listnav/_resource_pool.html.haml
  app/views/layouts/listnav/_storage.html.haml
  app/views/miq_policy/_action_details.html.haml
  app/views/miq_policy/_action_options.html.haml
  app/views/miq_policy/_alert_details.html.haml
  app/views/miq_policy/_alert_snmp.html.haml
  app/views/miq_policy/_rsop_form.html.haml
  app/views/miq_request/_prov_vm_migrate_dialog.html.haml
  app/views/ops/_ldap_verify_button.html.haml
  app/views/ops/_rbac_group_details.html.haml
  app/views/ops/_settings_cu_collection_tab.html.haml
  app/views/ops/_settings_import_tab.html.haml
  app/views/shared/views/_prov_dialog.html.haml
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/ems_cluster_controller_spec.rb
  spec/controllers/miq_policy_controller_spec.rb
  spec/controllers/utilization_controller_spec.rb
  spec/helpers/application_helper/title_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/compliance_summary_helper_spec.rb
  spec/helpers/ems_cluster_helper/textual_summary_spec.rb
  spec/helpers/host_helper/textual_summary_spec.rb
  spec/helpers/term_of_service_helper_spec.rb
  spec/presenters/menu/default_menu_spec.rb
  spec/presenters/tree_builder_smartproxy_affinity_spec.rb
  spec/presenters/tree_node/ems_cluster_spec.rb
  spec/presenters/tree_node/host_spec.rb
Labels: cleanup

#6764 Add role_allows? interface to TextualSummaryHelper
  spec/helpers/ems_cloud_helper/textual_summary_spec.rb
Labels: refactoring, test

#6767 workers-form: remove vim_broker_worker
  app/javascript/components/workers-form/workers-form.jsx
  app/javascript/components/workers-form/workers.schema.js
  app/javascript/spec/workers-form/workers-form.spec.js
Labels: bug, jansa/yes?

#6766 Fix rubocop in OpsController::Settings
  app/controllers/ops_controller/settings.rb
Labels: technical debt

#6710 Show also external vlans in nic reconf
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
Labels: compute/infrastructure, enhancement

#6769 Allow optional custom form field mapping for MiqFormRenderer
  app/javascript/forms/data-driven-form.jsx
Labels: enhancement

#6771 Remove timeline license as that code no longer exists
  LICENSE.txt
  README.md
Labels: documentation

#6774 Correct typo and allow adding new and displaying details page of a Group
  app/controllers/ops_controller/ops_rbac.rb
Labels: bug, ivanchuk/yes, settings

#6777 MiqFormRenderer: fix proptype error
  app/javascript/forms/data-driven-form.jsx
Labels: bug

#6773 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#6779 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#6781 Use onCheckGeneric for handling checked nodes in the policies tree
  app/assets/javascripts/miq_tree.js
  app/controllers/application_controller/policy_support.rb
  app/presenters/tree_builder_protect.rb
  spec/presenters/tree_builder_protect_spec.rb
Labels: ivanchuk/no, refactoring, technical debt, trees

#6757 Add required interface methods for BreadcrumbsMixin specs
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: refactoring, test

#6731 Redirect to proper screen after editing selected Hosts in a nested list
  app/controllers/host_controller.rb
  spec/controllers/host_controller_spec.rb
Labels: bug, compute/infrastructure, ivanchuk/no

#6636 Update the page after clearing Search text, for non-explorer screens
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
Labels: bug, expressions/filters, ivanchuk/no

#6631 Toolbars batch update
  app/assets/javascripts/miq_toolbar.js
  app/controllers/application_controller/compare.rb
  app/controllers/application_controller/performance.rb
  app/helpers/application_helper/button/utilization_download.rb
  app/javascript/components/miq-toolbar.jsx
  app/javascript/spec/old_js/miq_toolbar.spec.js
Labels: bug, toolbars

#6784 Update webpack & babel
  .babelrc.js
  config/jest.setup.js
  config/webpack/loaders.js
  config/webpack/shared.js
  package.json
  tools/ci/before_install.sh
Labels: dependencies

#6776 [JANSA] Add json catalogs for jansa branch
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
Labels: internationalization

#6775 [IVANCHUK] Add json catalogs for ivanchuk update
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
Labels: internationalization

#6787 Get rid of unnecessary double quotes
  app/controllers/mixins/actions/vm_actions/rename.rb
  app/controllers/vm_common.rb
Labels: bug, compute/infrastructure, jansa/yes

#6788 Display success flash message after canceling adding/removing Security Group
  app/assets/javascripts/components/vm_cloud/vm-cloud-add-security-group.js
  app/assets/javascripts/components/vm_cloud/vm-cloud-remove-security-group.js
Labels: bug, compute/cloud

#6795 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#6794 Webpack - remove settings we no longer need, fix production build
  config/webpack/development.js
  config/webpack/production.js
  config/webpack/shared.js
Labels: dependencies

#6790 Clean up the capacity and utilization selection trees
  app/assets/javascripts/miq_tree.js
  app/controllers/ops_controller/settings/cap_and_u.rb
  app/presenters/tree_builder_clusters.rb
  app/presenters/tree_builder_datastores.rb
  app/presenters/tree_node/node.rb
  app/presenters/tree_node/storage.rb
  app/views/ops/_settings_cu_collection_tab.html.haml
  spec/presenters/tree_builder_clusters_spec.rb
  spec/presenters/tree_builder_datastores_spec.rb
  spec/views/ops/_settings_cu_collection_tab.html.haml_spec.rb
Labels: refactoring, trees

#6800 Test against all possible subclasses for checkedness in VAT tree
  app/controllers/ops_controller/ops_rbac.rb
  app/presenters/tree_builder_belongs_to_vat.rb
Labels: bug, jansa/yes, settings

#6801 Use miqOnCheckGeneric for handling checks on HAC and VAT trees
  app/assets/javascripts/miq_tree.js
  app/controllers/ops_controller/ops_rbac.rb
  app/presenters/tree_builder_belongs_to_hac.rb
Labels: cleanup, jansa/yes, refactoring, trees

#6763 move git based domain import to core
  app/services/git_based_domain_import_service.rb
  spec/services/git_based_domain_import_service_spec.rb
Labels: refactoring

#6792 Remove Generic Item Modal
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/helpers/application_helper/toolbar/ansible_credential_center.rb
  app/helpers/application_helper/toolbar/ansible_credentials_center.rb
  app/helpers/application_helper/toolbar/ansible_repositories_center.rb
  app/helpers/application_helper/toolbar/ansible_repository_center.rb
  app/javascript/components/remove-generic-item-modal.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/packs/provider-dialogs-common.js
  app/javascript/spec/remove-generic-item-modal/__snapshots__/remove-generic-item-modal.spec.js.snap
  app/javascript/spec/remove-generic-item-modal/remove-generic-item-modal.spec.js
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_repository_controller_spec.rb
Labels: enhancement, react

#6793 Move core settings from ui
  config/settings.yml
Labels: technical debt

#6803 Skip dynamic vm_cloud specs where the method isn't supported
  spec/controllers/vm_cloud_controller_spec.rb
Labels: test

#6799 Fix rubocop in OrchestrationStackController
  app/controllers/orchestration_stack_controller.rb
Labels: technical debt

#6804 Remove edit tags button from the genealogy screen
  app/helpers/application_helper/toolbar/x_vm_vmtree_center.rb
Labels: cleanup, compute/infrastructure

#6805 Skip dynamic vm_or_template specs where the method isn't supported
  spec/controllers/vm_or_template_controller_spec.rb
Labels: cleanup, test

#6789 Remove listnav from Ansible Credentials/Playbooks/Repositories list screens
  app/helpers/application_helper/page_layouts.rb
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_playbook_controller_spec.rb
  spec/controllers/ansible_repository_controller_spec.rb
  spec/helpers/application_helper/page_layouts_spec.rb
Labels: automation/ansible
