Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-09, with the labels that each got.

#7281 Fix html5 console button identifier
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
Labels: bug, consoles, ivanchuk/yes, jansa/yes?

#7288 Fix popover hiding under menu
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug

#7287 Display relationship between Configured System and VM.
  app/helpers/configured_system_helper/textual_summary.rb
Labels: enhancement

#7292 Update ui-components to 1.4.3
  package.json
Labels: dependencies

#7294 [IVANCHUK] Update ui-components to 1.2.22
  package.json
  yarn.lock
Labels: dependencies

#7293 [JANSA] Update ui components to 1.3.7
  package.json
  yarn.lock
Labels: dependencies

#7291 Cross reference the webpack manifest with the actual node_modules
  config/webpack/production.js
Labels: enhancement, jansa/yes?

#7295 Fix non-unique keys error inside pf_aggregate_status_card
  app/javascript/components/pf_aggregate_status_card.jsx
Labels: bug, react, storage

#7298 Void @sb[:action] before accordion_switch()
  app/controllers/application_controller/explorer.rb
Labels: bug, compute/cloud, ivanchuk/yes, jansa/yes?

#7300 Round GB Tenant Quota to compensate precision loss
  app/assets/javascripts/controllers/ops/tenant_quota_form_controller.js
  app/helpers/ops_helper/textual_summary.rb
Labels: enhancement

#7290 [JANSA] yarn upgrade: upgrade JS dependencies
  package.json
  yarn.lock
Labels: dependencies, jansa/yes

#7302 Added gettext calls to MiqReport::GROUPINGS for options select
  app/views/report/_form_sort.html.haml
Labels: bug, internationalization

#7306 Fixed width of Action type select component width to fix truncation
  app/views/miq_policy/_action_details.html.haml
Labels: bug, internationalization

#7301 [JANSA] Translated "choose" string in URL selector in PXE server form
  app/javascript/forms/input-with-dynamic-prefix.jsx
  app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
Labels: bug, internationalization, jansa/yes

#7283 [JANSA] Correctly set x_node for generic_object_definition_controller show_list()
  app/controllers/generic_object_definition_controller.rb
Labels: bug, generic objects, ivanchuk/yes, jansa/yes

#7317 Add description/target platform to Config Profile
  app/helpers/configuration_profile_helper/textual_summary.rb
Labels: enhancement

#7316 Fix issue during return from Set Ownership Screen to summary page of Service
  app/controllers/mixins/actions/vm_actions/ownership.rb
  spec/controllers/mixins/actions/vm_actions/ownership_spec.rb
Labels: bug, jansa/yes?

#7322 Added gettext calls for Provider Label in playbook and repository views
  app/helpers/ansible_playbook_helper/textual_summary.rb
  app/helpers/ansible_repository_helper/textual_summary.rb
Labels: internationalization

#7321 Translated Credential type list
  app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
Labels: internationalization

#7315 a11y: Make the main menu items accessible using the keyboard
  app/javascript/menu/side-nav-menu-link.jsx
Labels: accessibility, enhancement, react

#7319 Include modules manifest
  config/webpack/production.js
Labels: enhancement, jansa/yes?

#7308 Fix the validation of dependent fields in async credentials component
  app/javascript/components/async-credentials/async-credentials.jsx
  app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
  app/javascript/spec/async-credentials/async-credentials.spec.js
Labels: bug, react

#7330 RemoveGenericItemModal: fix display_field handling
  app/javascript/components/remove-generic-item-modal.jsx
Labels: bug

#7332 Sort the webpack modules for consistent output
  config/webpack/production.js
Labels: bug, jansa/yes?

#7311 Add onChange functionality to our DDF select fields
  app/javascript/components/provider-form/index.jsx
  app/javascript/components/provider-form/provider-select-field.jsx
  app/javascript/components/select/index.jsx
  app/javascript/forms/mappers/componentMapper.jsx
Labels: enhancement, react

#7188 React version of List view
  app/assets/javascripts/components/miq-request-options.js
  app/assets/javascripts/controllers/report_data_controller.js
  app/assets/javascripts/miq_angular_application.js
  app/assets/javascripts/miq_explorer.js
  app/helpers/application_helper.rb
  app/helpers/gtl_helper.rb
  app/javascript/components/gtl-view.jsx
  app/javascript/components/gtl/DataTable.jsx
  app/javascript/components/gtl/StaticGTLView.jsx
  app/javascript/components/gtl/data/gtl-small.json
  app/javascript/components/gtl/index.js
  app/javascript/components/gtl/styles.scss
  app/javascript/components/gtl/utils.js
  app/javascript/components/miq-toolbar.jsx
  app/javascript/components/remove-generic-item-modal.jsx
  app/javascript/packs/component-definitions-common.js
  app/presenters/explorer_presenter.rb
  app/views/layouts/_gtl.html.haml
  app/views/layouts/_x_gtl.html.haml
  app/views/layouts/react/_gtl.html.haml
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/container_build_controller_spec.rb
  spec/controllers/container_template_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/infra_networking_controller_spec.rb
  spec/controllers/orchestration_stack_controller_spec.rb
  spec/controllers/persistent_volume_controller_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_cloud_controller/trees_spec.rb
  spec/controllers/vm_infra_controller/trees_spec.rb
  spec/controllers/vm_or_template_controller_spec.rb
  spec/javascripts/controllers/report_data_controller_spec.js
  spec/shared/controllers/shared_examples_for_nested_lists.rb
  spec/support/controller_helper.rb
Labels: enhancement, gtls, react

#7323 Rename ContainerLabelTagMapping to be more generic
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
Labels: refactoring

#7318 Display labels for Infra VMs
  app/controllers/vm_common.rb
Labels: enhancement

#7339 Display the buttons' labels on DDF forms properly
  app/javascript/forms/data-driven-form.jsx
  app/javascript/spec/forms/__snapshots__/data-driven-form.spec.js.snap
Labels: bug, react

#7337 Show the helperText on the password-field component properly
  app/javascript/components/async-credentials/edit-password-field.jsx
  app/javascript/components/async-credentials/password-field.jsx
Labels: bug, react

#7320 Fix translation for consolidation column dropdown
  app/helpers/report_helper.rb
  app/views/report/_form_consolidate.html.haml
  app/views/report/_form_sort.html.haml
  app/views/report/_widget_columns.html.haml
Labels: bug, internationalization

#7297 Added new provisioning fields for the "IBM Power Virtual Servers" Provider
  app/controllers/application_controller.rb
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/application_controller/user_script_file.rb
  app/controllers/mixins/vm_show_mixin.rb
  app/views/miq_request/_prov_field.html.haml
  app/views/shared/views/_prov_dialog.html.haml
  app/views/vm_cloud/explorer.html.haml
Labels: enhancement

#7347 Allow the async-credentials component and its children to be not required
  app/javascript/components/async-credentials/async-credentials.jsx
  app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
  app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
  app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
Labels: bug, react

#7340 Hide empty properties for Configuration Profiles
  app/helpers/configuration_profile_helper/textual_summary.rb
Labels: enhancement, jansa/yes?

#7341 Display vendor for configured systems
  app/helpers/configured_system_helper/textual_summary.rb
Labels: enhancement, jansa/yes?

#7326 [JANSA] Add scrollbar to automate entrypoint dialog
  app/views/shared/_tree.html.haml
Labels: automation/automate, bug, ivanchuk/yes, jansa/yes

#7336 Implemented missing `onItemButtonClick` method for Order Service button
  app/javascript/components/gtl-view.jsx
  app/javascript/components/gtl/DataTable.jsx
  app/javascript/components/gtl/StaticGTLView.jsx
Labels: bug

#7338 Customized 'volumes' tab for IBM PVS in '_prov_dialog.html.haml'
  app/views/shared/views/_prov_dialog.html.haml
Labels: enhancement

#7351 Add IBM PowerVS to Cloud Volume create form
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/controllers/cloud_volume_controller.rb
  app/views/cloud_volume/_common_new_edit.html.haml
Labels: enhancement
