Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-07, with the labels that each got.

#7161 Remove unused grid_rows_json, grid_cols_json
  app/controllers/application_controller/compare.rb
Labels: cleanup

#7163 Fixed code to load correct toolbar on list/summary screens.
  app/helpers/application_helper/toolbar_chooser.rb
Labels: bug, compute/infrastructure, jansa/yes

#7165 Fixed button text to be consistent with others in the toolbar
  app/helpers/application_helper/toolbar/generic_object_definition_button_center.rb
  app/helpers/application_helper/toolbar/generic_object_definition_button_group_center.rb
Labels: bug, internationalization, jansa/yes

#7164 Display title on nested Policy Simulation screen.
  app/controllers/vm_common.rb
  app/helpers/application_helper/page_layouts.rb
  app/views/vm_common/_policy_options.html.haml
Labels: bug, compute/cloud, compute/infrastructure, jansa/yes

#7169 Check for container template instantiation support
  app/helpers/application_helper/toolbar/container_template_center.rb
Labels: compute/containers, enhancement, jansa/yes?

#7166 [JANSA] Add support for Service Telemetry Framework
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/mixins/ems_common/angular.rb
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: compute/cloud, enhancement

#7172 [JANSA] Updated translations for 9 languages
  app/assets/javascripts/locale/de/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/it/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/ko/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
  app/assets/javascripts/locale/zh_TW/app.js
Labels: bug, internationalization

#7171 Added a "Note" field mapping to React forms.
  app/javascript/components/orchestration-template/orchestration-template-form.schema.js
  app/javascript/forms/mappers/formFieldsMapper.jsx
Labels: bug, jansa/yes?, services

#7047 Replace old angular config provider form with the new ProviderForm
  app/controllers/mixins/manager_controller_mixin.rb
  app/helpers/ems_configuration_helper.rb
  app/views/ems_configuration/edit.html.haml
  app/views/ems_configuration/new.html.haml
Labels: enhancement, react

#7173 Rename term to disabled_types for clarity
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
Labels: technical debt

#7120 [JANSA] Fix GOD breadcrumbs
  app/controllers/generic_object_definition_controller.rb
Labels: breadcrumbs, bug, ivanchuk/yes

#7168 Enable / disable policy move buttons as needed
  app/views/miq_policy/_policy_details.html.haml
Labels: control, enhancement

#7175 Correctly render orch. template after content after page refresh
  app/views/catalog/_ot_tree_show.html.haml
Labels: bug, hammer/yes, ivanchuk/yes, jansa/yes?, services

#7177 Added missing `download_summary_pdf` route for physical chasis/racks
  config/routes.rb
Labels: bug, compute/physical infrastructure, jansa/yes

#7158 [IVANCHUK] Add support for Service Telemetry Framework
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/mixins/ems_common/angular.rb
  app/views/layouts/angular/_multi_auth_credentials.html.haml
Labels: compute/cloud, enhancement

#7098 [IVANCHUK] package.json: explicitly fail on node 12+
  package.json
Labels: bug, dependencies

#6990 [IVANCHUK] header fix
  app/assets/stylesheets/main.scss
Labels: bug

#7153 Fix missing tags on Group form
  app/controllers/ops_controller/ops_rbac.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: bug, jansa/yes?, settings

#7183 only set `object_ids` if in a form.
  app/controllers/application_controller.rb
Labels: bug, compute/infrastructure, jansa/yes

#7184 Show hover text correctly on Copy catalog item button
  app/helpers/application_helper/button/catalog_item_copy_button.rb
  app/helpers/application_helper/toolbar/servicetemplate_center.rb
Labels: bug, jansa/yes, services

#7185 Container project dashboard - add missing dataAvailable
  app/services/container_service_mixin.rb
  app/services/dashboard_service.rb
  spec/services/container_dashboard_service_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes

#7180 Add webpack-stats-plugin for use in auditing modules usage
  config/webpack/production.js
  package.json
  tools/ci/before_install.sh
Labels: dependencies, enhancement, jansa/yes?

#7190 Network controller breadcrumbs: fix menu section name: Networks -> Networks, helper
  app/controllers/cloud_network_controller.rb
  app/controllers/cloud_subnet_controller.rb
  app/controllers/ems_network_controller.rb
  app/controllers/floating_ip_controller.rb
  app/controllers/miq_request_controller.rb
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/controllers/mixins/menu_section.rb
  app/controllers/network_port_controller.rb
  app/controllers/network_router_controller.rb
  app/controllers/network_service_controller.rb
  app/controllers/network_topology_controller.rb
  app/controllers/security_group_controller.rb
  app/controllers/security_policy_controller.rb
  app/controllers/security_policy_rule_controller.rb
Labels: bug, jansa/yes?, networks

#7182 Deleted dead routes
  config/routes.rb
Labels: compute/physical infrastructure, jansa/yes, technical debt

#7195 [JANSA] Updated Translation Files from 2020-07-11
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/it/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/ko/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
  app/assets/javascripts/locale/zh_TW/app.js
Labels: bug, internationalization

#7193 [IVANCHUK] Update ui components to 1.2.19
  package.json
  yarn.lock
Labels: dependencies

#7154 bump more core extensions
  manageiq-ui-classic.gemspec
Labels: dependencies

#7200 Fixed to translate strings in UI
  app/controllers/miq_policy_controller/alerts.rb
  app/controllers/miq_policy_controller/policies.rb
  app/helpers/application_helper/toolbar/miq_policies_center.rb
  app/views/miq_policy/_policy_details.html.haml
Labels: bug, internationalization, jansa/yes?

#7197 Update ui-components to 1.4.2
  package.json
Labels: dependencies

#7196 [JANSA] Update ui-components to 1.3.6
  package.json
  yarn.lock
Labels: dependencies

#7205 Fix to retirement date in retirement form.
  app/assets/javascripts/components/retirement-form.js
Labels: bug, internationalization, jansa/yes

#7204 Fixed to translate menu titles in Navbar
  app/javascript/menu/first-level.jsx
  app/javascript/menu/second-level.jsx
Labels: bug, internationalization, jansa/no

#7203 copy catalog - add info notice about copy not being in catalog by default
  app/javascript/components/copy-catalog-form/copy-catalog-form.jsx
  config/jest.setup.js
Labels: bug

#7209 [JANSA] Fixed to translate menu titles in Navbar
  app/javascript/components/main-menu/second-level.jsx
  app/javascript/components/main-menu/third-level.jsx
  app/javascript/components/main-menu/top-level.jsx
Labels: bug

#7214 Fix failing tree_builder_sections_spec
  spec/presenters/tree_builder_sections_spec.rb
Labels: jansa/yes, test

#7210 Added missing route
  config/routes.rb
Labels: bug, jansa/yes, networks

#7212 Add I18N support to expression type in alerts.
  app/views/miq_policy/_alert_details.html.haml
Labels: bug, internationalization, jansa/yes?

#7208 [JANSA] Merge default button labels properly with the custom ones in DDF
  app/javascript/forms/data-driven-form.jsx
Labels: bug

#7211 Moved 'Firmware Registries' under 'Physical Infrastructure' menu
  app/controllers/firmware_registry_controller.rb
  app/presenters/menu/default_menu.rb
  spec/presenters/menu/default_menu_spec.rb
Labels: bug, compute/physical infrastructure, jansa/yes?, menus

#7219 Delete the unused users route form AutomationManagerController
  config/routes.rb
Labels: cleanup

#7192 Fix menu.spec.js
  cypress/integration/ui/menu.spec.js
  cypress/support/commands.js
Labels: bug, cypress, test

#7220 Remove the unused show_association/show_details routes
  config/routes.rb
  spec/routing/host_routing_spec.rb
  spec/routing/storage_routing_spec.rb
Labels: cleanup

#7221 Fix a string typo
  app/javascript/components/remove-generic-item-modal.jsx
Labels: bug, jansa/yes

#7223 Fix to Policy's I18N strings.
  app/controllers/miq_policy_controller.rb
Labels: bug, internationalization, jansa/yes?

#7224 Add I18N support to Orchestration Template string Draft.
  app/javascript/components/orchestration-template/orchestration-template-form.schema.js
Labels: bug, internationalization, jansa/yes?

#7222 [JANSA] Add missing routes for OpsController actions
  config/routes.rb
Labels: bug

#7231 Check that yarn is installed when updating
  lib/tasks/manageiq/ui_tasks.rake
Labels: developer, enhancement

#7232 [IVANCHUK] Update ui components to 1.2.20
  package.json
  yarn.lock
Labels: dependencies

#7207 Control > Explorer - use RemoveGenericItemModal + API for deletions
  app/controllers/application_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_controller/alert_profiles.rb
  app/controllers/miq_policy_controller/alerts.rb
  app/controllers/miq_policy_controller/conditions.rb
  app/controllers/miq_policy_controller/miq_actions.rb
  app/controllers/miq_policy_controller/policies.rb
  app/controllers/miq_policy_controller/policy_profiles.rb
  app/helpers/application_helper/button/condition.rb
  app/helpers/application_helper/button/condition_delete.rb
  app/helpers/application_helper/button/policy_delete.rb
  app/helpers/application_helper/toolbar/condition_center.rb
  app/helpers/application_helper/toolbar/miq_action_center.rb
  app/helpers/application_helper/toolbar/miq_alert_center.rb
  app/helpers/application_helper/toolbar/miq_alert_profile_center.rb
  app/helpers/application_helper/toolbar/miq_policy_center.rb
  app/helpers/application_helper/toolbar/miq_policy_profile_center.rb
  app/javascript/components/remove-generic-item-modal.jsx
  app/javascript/spec/remove-generic-item-modal/remove-generic-item-modal.spec.js
  config/routes.rb
  spec/controllers/miq_policy_controller/alert_profiles_spec.rb
  spec/controllers/miq_policy_controller/alerts_spec.rb
  spec/helpers/application_helper/buttons/condition_delete_spec.rb
  spec/presenters/tree_builder_sections_spec.rb
  spec/routing/miq_policy_routing_spec.rb
Labels: bug

#7234 [JANSA] Dont walk empty child nodes for parent check
  app/assets/javascripts/miq_tree.js
Labels: bug, ivanchuk/yes, trees

#7235 Allow mapping different entity types to the same base category
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
Labels: bug, jansa/yes?

#7228 Add flash message about required restart to VM summary screen
  app/controllers/vm_common.rb
  app/helpers/textual_summary_helper.rb
  app/helpers/vm_helper/textual_summary.rb
  app/views/layouts/_textual_groups_generic.html.haml
Labels: compute/infrastructure, enhancement

#7191 [search_box.spec.js] Fix failing specs
  cypress/integration/ui/searchbox.spec.js
Labels: bug, cypress, test

#7239 [IVANCHUK] Update ui components to 1.2.21
  package.json
  yarn.lock
Labels: dependencies

#7238 webpack - make dev_server config optional
  config/webpack/development.js
  config/webpacker.yml
Labels: developer

#7240 Policy detail - Conditions - replace nested Scopes/Expressions table with divs
  app/views/miq_policy/_policy_details.html.haml
Labels: bug, control, jansa/yes?

#7230 Disable the option to select LDAP and LDAPS
  app/helpers/ops_helper.rb
  app/views/ops/_settings_authentication_tab.html.haml
  spec/helpers/ops_helper_spec.rb
  spec/views/ops/_rbac_group_details.html.haml_spec.rb
Labels: cleanup, technical debt

#7242 Change availability Zones field to non-mandatory
  app/views/cloud_volume/_common_new_edit.html.haml
Labels: bug, compute/cloud, ivanchuk/yes, jansa/yes?

#7215 Allow unconditional revert/delete of snapshots in the 📸🌳
  app/helpers/application_helper/toolbar/x_vm_snapshot_center.rb
Labels: bug, jansa/yes, react, trees

#7181 Replace angular-based infra provider forms with the DDF component
  app/helpers/ems_infra_helper.rb
  app/views/ems_infra/edit.html.haml
  app/views/ems_infra/new.html.haml
Labels: enhancement, jansa/no, react

#7176 Replace old angular ansible tower form with a react based DDF
  app/views/automation_manager/_form.html.haml
  spec/controllers/automation_manager_controller_spec.rb
Labels: enhancement, jansa/no, react
