Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-08, with the labels that each got.

#7246 Set form data after Reset or Save button are pressed
  app/controllers/chargeback_assignment_controller.rb
Labels: bug, jansa/yes?, overview/chargeback

#7245 Add 'geneve' provider network type
  app/javascript/components/cloud-network-form/cloud-network-form.schema.js
  app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
Labels: enhancement, ivanchuk/yes, jansa/yes?, networks

#7247 Toolbar overrides: don't overwrite existing groups
  app/helpers/application_helper/toolbar/override.rb
Labels: bug, toolbars

#7229 Enable I18N translation to service requests.
  app/views/miq_request/_request.html.haml
  app/views/miq_request/_request_dialog_details.html.haml
  app/views/miq_request/_st_prov_show.html.haml
Labels: bug, internationalization, jansa/yes?

#7248 Display the provider's name in the flash when cancelling edit
  app/javascript/components/provider-form/index.jsx
Labels: bug, jansa/no, react

#7250 Fixing spec test failures
  spec/controllers/application_controller/tree_support_spec.rb
  spec/controllers/miq_policy_controller/alert_profiles_spec.rb
  spec/controllers/miq_policy_controller/alerts_spec.rb
  spec/controllers/miq_policy_controller/miq_actions_spec.rb
  spec/controllers/miq_report_controller/trees_spec.rb
  spec/controllers/ops_controller/ops_rbac_spec.rb
  spec/controllers/ops_controller_spec.rb
  spec/controllers/pxe_controller_spec.rb
  spec/controllers/report_controller_spec.rb
  spec/controllers/service_controller_spec.rb
Labels: jansa/yes, test

#7155 Replace old container provider forms with the new DDF version
  app/helpers/ems_container_helper.rb
  app/javascript/components/provider-form/detect-button.jsx
  app/javascript/components/provider-form/index.jsx
  app/views/ems_container/edit.html.haml
  app/views/ems_container/new.html.haml
Labels: enhancement, jansa/no, react

#7252 [JANSA] - Fixing spec test failures on Jansa
  spec/controllers/miq_policy_controller/alert_profiles_spec.rb
Labels: test

#7179 Allow cut & paste in automate entry point input
  app/controllers/catalog_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/helpers/automate_tree_helper.rb
  app/views/catalog/_form_basic_info.html.haml
  app/views/miq_ae_class/_copy_objects_form.html.haml
  config/routes.rb
Labels: automation/automate, enhancement, services

#7256 "Fix" gtl.spec.js
  cypress/integration/ui/gtl.spec.js
Labels: bug, cypress, test

#7254 Fix settings.spec.js
  cypress/integration/ui/settings.spec.js
Labels: bug, cypress, test

#7255 "Fix" toolbar.spec.js
  cypress/integration/ui/toolbar.spec.js
Labels: bug, cypress, test

#7257 [cypress] Breakup and remove commands.js
  cypress/support/assertions/expect_title.js
  cypress/support/commands.js
  cypress/support/commands/explorer.js
  cypress/support/commands/gtl.js
  cypress/support/commands/login.js
  cypress/support/commands/menu.js
  cypress/support/commands/search.js
  cypress/support/commands/toolbar.js
  cypress/support/index.js
Labels: cypress, refactoring, test

#7251 Clean up and delete the code related to the old provider forms
  app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
  app/controllers/ems_block_storage_controller.rb
  app/controllers/ems_cloud_controller.rb
  app/controllers/ems_container_controller.rb
  app/controllers/ems_infra_controller.rb
  app/controllers/ems_network_controller.rb
  app/controllers/ems_object_storage_controller.rb
  app/controllers/ems_physical_infra_controller.rb
  app/controllers/ems_storage_controller.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/ems_common/angular.rb
  app/views/ems_block_storage/edit.html.haml
  app/views/ems_block_storage/new.html.haml
  app/views/shared/views/ems_common/angular/_form.html.haml
  config/routes.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_container_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/ems_physical_infra_controller_spec.rb
  spec/controllers/mixins/ems_common/angular_spec.rb
  spec/controllers/mixins/ems_common_spec.rb
  spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
  spec/routing/ems_cloud_routing_spec.rb
  spec/routing/ems_container_routing_spec.rb
  spec/routing/ems_infra_routing_spec.rb
  spec/routing/ems_physical_infra_routing_spec.rb
  spec/routing/ems_storage_routing_spec.rb
  spec/shared/controllers/shared_examples_for_ems_network_controller.rb
Labels: cleanup

#7265 [HAMMER] - Fixing spec test failures on Hammer
  spec/controllers/miq_policy_controller/alert_profiles_spec.rb
  spec/controllers/miq_policy_controller/alerts_spec.rb
  spec/controllers/miq_policy_controller/miq_actions_spec.rb
Labels: test

#7249 switch parent to ancestry (miq_ae_namespaces)
  app/controllers/tree_controller.rb
Labels: bug

#7262 Fixes TreeController issue
  app/controllers/tree_controller.rb
  spec/controllers/tree_controller_spec.rb
Labels: automation/automate, bug

#7261 Enable 'Save' button after successful RHN credentials validation
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/rhn.rb
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: bug, ivanchuk/yes, jansa/yes, settings

#7269 Replace URI's input-with-dynamic-prefix in PXE form with a textfield
  app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
  app/javascript/forms/input-with-dynamic-prefix.jsx
  app/javascript/forms/mappers/formFieldsMapper.jsx
  app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
  app/javascript/spec/forms/input-with-dynamic-prefix.spec.js
  app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
Labels: cleanup, ivanchuk/no, react

#7266 Drop the RHN updates views and logic
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/settings.rb
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/rhn.rb
  app/views/ops/_all_tabs.html.haml
  app/views/ops/_settings_rhn_edit_tab.html.haml
  app/views/ops/_settings_rhn_tab.html.haml
  app/views/ops/rhn/_info_subscribed.html.haml
  app/views/ops/rhn/_info_unsubscribed.html.haml
  app/views/ops/rhn/_server_table.html.haml
  config/routes.rb
  spec/controllers/ops_controller/settings/common_spec.rb
  spec/routing/ops_routing_spec.rb
  spec/views/ops/_settings_rhn_tab_spec.rb
Labels: cleanup, ivanchuk/no

#7241 [IVANCHUK] Refactor get_rec_cls to get proper record class for various items
  app/controllers/application_controller/ci_processing.rb
  app/controllers/application_controller/compare.rb
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/cloud_object_store_object_controller.rb
  app/controllers/ems_cluster_controller.rb
  app/controllers/ems_infra_controller.rb
  app/controllers/ems_storage_controller.rb
  app/controllers/host_controller.rb
  app/controllers/miq_template_controller.rb
  app/controllers/orchestration_stack_controller.rb
  app/controllers/resource_pool_controller.rb
  app/controllers/service_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_common.rb
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/cloud_object_store_container_spec.rb
  spec/controllers/ems_cluster_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/ems_storage_controller_spec.rb
  spec/controllers/host_controller_spec.rb
  spec/controllers/miq_template_controller_spec.rb
  spec/controllers/orchestration_stack_controller_spec.rb
  spec/controllers/resource_pool_controller_spec.rb
  spec/controllers/service_controller_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_common_spec.rb
Labels: bug, compute/infrastructure

#7271 MiqHashStruct was replaced by OpenStruct in provision workflow
  app/controllers/application_controller/miq_request_methods.rb
Labels: bug, compute/infrastructure

#7272 remove reference to unused dialog field type
  app/views/miq_ae_customization/_dialog_sample.html.haml
Labels: angular dialogs, services, technical debt

#7263 Correctly render add provider screen after accordion switch
  app/controllers/automation_manager_controller.rb
Labels: automation/ansible tower, bug, ivanchuk/yes

#7274 Rename Category and Label in Label Tag Mapping Screen
  app/views/ops/_label_tag_mapping_form.html.haml
Labels: bug, tagging

#6980 Use remove modal for custom button and button group deletion
  app/controllers/application_controller/buttons.rb
  app/controllers/catalog_controller.rb
  app/controllers/miq_ae_customization_controller.rb
  app/helpers/application_helper/toolbar/catalogitem_button_center.rb
  app/helpers/application_helper/toolbar/catalogitem_buttons_center.rb
  app/helpers/application_helper/toolbar/custom_button_center.rb
  app/helpers/application_helper/toolbar/custom_buttons_center.rb
  app/javascript/components/remove-generic-item-modal.jsx
Labels: enhancement

#7202 Honor sorting options in dialog preview
  app/views/miq_ae_customization/_dialog_sample.html.haml
Labels: automation/automate, enhancement

#7260 Call `allowed_for_policies` method to avoid infinite loop
  app/controllers/miq_policy_controller/events.rb
  spec/controllers/miq_policy_controller/events_spec.rb
Labels: bug, control, jansa/yes?

#7276 Allow to display templates set ownership screen
  app/controllers/mixins/actions/vm_actions/ownership.rb
  spec/controllers/mixins/actions/vm_actions/ownership_spec.rb
Labels: bug, compute/infrastructure

#7280 Sort report results by default sort column from view's yaml
  app/controllers/report_controller.rb
Labels: bug, overview/reporting

#7275 Fix header in Set Ownership Screen
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/controllers/vm_common.rb
  spec/controllers/vm_common_spec.rb
Labels: bug

#7264 Filter network providers supporting security group creation
  app/assets/javascripts/controllers/security_group/security_group_form_controller.js
  app/assets/javascripts/services/miq_service.js
Labels: bug, ivanchuk/yes, jansa/yes?, networks

#7236 Use collection name form API yaml configuration in setownership screen
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/views/shared/views/_ownership.html.haml
Labels: bug, jansa/yes?, services
