Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-10, with the labels that each got.

#7368 Set String "Unassigned Buttons" to be Translated
  app/controllers/miq_ae_customization_controller/custom_buttons.rb
Labels: bug, internationalization

#7352 Add name to Configuration Profile
  product/views/ConfigurationProfile.yaml
Labels: enhancement

#7355 Remove exotic DDF components from the componentMapper
  app/javascript/components/catalog-form/catalog-form.schema.js
  app/javascript/components/code-editor/index.js
  app/javascript/components/orchestration-template/orchestration-template-form.schema.js
  app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
  app/javascript/forms/mappers/componentMapper.jsx
  app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
  app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
Labels: cleanup, react

#7369 Get rid of the NTP servers from the Zone and Server screens
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/zones.rb
  app/views/ops/_settings_evm_servers_tab.html.haml
  app/views/ops/_settings_server_tab.html.haml
  app/views/ops/_zone_form.html.haml
  spec/controllers/ops_controller/settings/common_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/views/ops/_settings_evm_servers_tab.html.haml_spec.rb
  spec/views/ops/_zone_form.html.haml_spec.rb
Labels: cleanup

#7381 Fix for Configuration Provider appearing twice
  product/views/ManageIQ_Providers_ConfigurationManager.yaml
Labels: bug, configuration management

#7343 Implementing PolymorphicConditionalButton and enabling it for cloud volumes
  app/helpers/application_helper/button/cloud_volume_backup_create.rb
  app/helpers/application_helper/button/cloud_volume_backup_restore.rb
  app/helpers/application_helper/button/polymorphic_conditional_button.rb
  app/helpers/application_helper/toolbar/cloud_volumes_center.rb
  spec/helpers/application_helper/buttons/cloud_volume_backup_create_spec.rb
  spec/helpers/application_helper/buttons/cloud_volume_backup_restore_spec.rb
  spec/helpers/application_helper/buttons/polymorphic_conditional_button_spec.rb
Labels: enhancement

#7371 Add console link to Configuration Profile
  app/controllers/configuration_profile_controller.rb
  app/helpers/application_helper/button/configuration_profile_console.rb
  app/helpers/application_helper/toolbar/configuration_profile_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  config/routes.rb
Labels: enhancement

#7383 Add New Subnet without Cloud Tenant
  app/views/static/cloud_subnet/cloud-subnet-form.html.haml
Labels: enhancement

#7382 Fix breadcrumb and right cell text of order service
  app/controllers/catalog_controller.rb
Labels: bug, services

#7391 Remove focus tag from polymorphic_conditional_button_spec
  spec/helpers/application_helper/buttons/polymorphic_conditional_button_spec.rb
Labels: test

#7388 /dashboard/logout: don't remember logout as start_url when session invalid
  app/controllers/application_controller.rb
  spec/requests/auth_spec.rb
Labels: bug

#7345 Implementing add new block storage manager functionality
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/ems_block_storages_center.rb
  app/views/ems_block_storage/new.html.haml
  app/views/ems_block_storage/show_list.html.haml
  app/views/ems_storage/show.html.haml
  config/routes.rb
Labels: enhancement, storage

#7384 Make eslint happier about the menu
  app/javascript/components/breadcrumbs/notifications-toggle.jsx
  app/javascript/menu/first-level.jsx
  app/javascript/menu/group-switcher.jsx
  app/javascript/menu/history.js
  app/javascript/menu/icon.jsx
  app/javascript/menu/item-type.js
  app/javascript/menu/main-menu.jsx
  app/javascript/menu/menu-collapse.jsx
  app/javascript/menu/miq-logo.jsx
  app/javascript/menu/navbar.jsx
  app/javascript/menu/search-results.jsx
  app/javascript/menu/search.jsx
  app/javascript/menu/second-level.jsx
  app/javascript/menu/side-nav-menu-link.jsx
  app/javascript/menu/username.jsx
  app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
Labels: cleanup, menus, react

#7396 Remove redundant 'Network' prefix from network menu items
  app/presenters/menu/default_menu.rb
Labels: cleanup, menus

#7387 [IVANCHUK] Update ui-components to 1.2.23
  package.json
  yarn.lock
Labels: dependencies

#7386 [JANSA] Update ui-components to 1.3.8
  package.json
  yarn.lock
Labels: dependencies

#7385 Update ui-components to 1.4.4
  package.json
Labels: dependencies

#7354 implement edit storage manager functionality
  app/controllers/application_controller.rb
  app/controllers/ems_block_storage_controller.rb
  app/controllers/ems_object_storage_controller.rb
  app/controllers/ems_storage_controller.rb
  app/controllers/mixins/storage_common_mixin.rb
  app/helpers/application_helper/toolbar/ems_block_storages_center.rb
  app/helpers/application_helper/toolbar/ems_storage_center.rb
  app/helpers/ems_storage_helper.rb
  app/views/ems_block_storage/edit.html.haml
  app/views/ems_storage/_edit_storage.html.haml
  app/views/ems_storage/edit.html.haml
Labels: enhancement, storage

#7356 Introducing the TreeView component for DDF without React
  app/javascript/components/tree-view/field.jsx
  app/javascript/components/tree-view/helpers.js
  app/javascript/components/tree-view/hierarchical-tree-view.jsx
  app/javascript/forms/mappers/componentMapper.jsx
Labels: enhancement, react

#7398 Expose the API global in the jest testing context
  config/jest.setup.js
Labels: test

#7402 Fix provisioning dialog ':migratable' symbol ref
  app/views/shared/views/_prov_dialog.html.haml
Labels: bug

#7404 Fix propTypes for the MenuItem component
  app/javascript/menu/first-level.jsx
  app/javascript/menu/second-level.jsx
Labels: bug, menus, react

#7379 Added a11y support for list view.
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/list_view.scss
  app/javascript/components/gtl-view.jsx
  app/javascript/components/gtl/DataTable.jsx
  app/javascript/components/gtl/styles.scss
Labels: accessibility, enhancement, gtls

#7405 Enabling textual_summary to work with nil asset_detail
  app/helpers/physical_chassis_helper/textual_summary.rb
  app/helpers/physical_server_helper/textual_summary.rb
  app/helpers/physical_storage_helper/textual_summary.rb
  app/helpers/physical_switch_helper/textual_summary.rb
Labels: enhancement

#7409 Fixed width of Storage Manager select component width to fix truncation
  app/views/cloud_object_store_container/new.html.haml
  app/views/cloud_volume/_common_new_edit.html.haml
Labels: bug, storage

#7370 Added UI support to add/edit OVF Template type Catalog Item(s)
  app/controllers/catalog_controller.rb
  app/views/catalog/_form_basic_info.html.haml
  app/views/catalog/_form_ovf_template_options.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
Labels: enhancement, pending core

#7342 Implementing storage-resource functionality for block storages
  app/controllers/mixins/ems_common.rb
  app/controllers/storage_resource_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/ems_storage_helper/textual_summary.rb
  app/helpers/storage_resource_helper.rb
  app/helpers/storage_resource_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/storage_resource/show.html.haml
  app/views/storage_resource/show_list.html.haml
  app/views/storage_resource/show_policy_timeline.html.haml
  config/routes.rb
  product/views/StorageResource.yaml
  spec/presenters/menu/default_menu_spec.rb
Labels: enhancement

#7374 a11y: Make the menu expand/collapse accessible via keyboard
  app/javascript/menu/main-menu.jsx
  app/javascript/menu/menu-collapse.jsx
Labels: accessibility, enhancement, menus

#7411 Added tests for the Select component
  app/javascript/spec/select/__snapshots__/select.spec.js.snap
  app/javascript/spec/select/select.spec.js
Labels: hacktoberfest, test

#7413 Throw an error if the API or http objects are being interchanged
  app/javascript/http_api/api.js
  app/javascript/http_api/http.js
Labels: developer, enhancement

#7389 Override Navbar component
  app/javascript/menu/main-menu.jsx
  app/views/layouts/_header.html.haml
  config/webpack/shared.js
Labels: enhancement, jansa/yes?

#7418 http_api: spec for API/http url filters
  app/javascript/spec/http_api.spec.js
Labels: test

#7406 a11y: Allow the user to exit the menu when unfocusing or ESC
  app/javascript/menu/main-menu.jsx
  app/javascript/menu/menu-collapse.jsx
Labels: accessibility, menus, react

#7410 Implemented the TreeViewSelector component for DDF
  app/javascript/components/tree-view/base.jsx
  app/javascript/components/tree-view/field.jsx
  app/javascript/components/tree-view/helpers.js
  app/javascript/components/tree-view/index.js
  app/javascript/components/tree-view/redux.jsx
  app/javascript/components/tree-view/selector.jsx
  app/javascript/forms/mappers/componentMapper.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/tree-view/__snapshots__/selector.spec.js.snap
  app/javascript/spec/tree-view/selector.spec.js
  app/javascript/spec/tree-view/tree-view.spec.js
  app/views/shared/_tree.html.haml
Labels: enhancement, react, trees

#7421 Rename the TEXTAREA_FIELD to TEXTAREA in the VM snapshot form
  app/javascript/components/vm-snapshot-form/vm-snapshot-form.schema.js
Labels: bug, react

#7420 Add access for Configured System console
  app/controllers/configured_system_controller.rb
  app/helpers/application_helper/button/configured_system_console.rb
  app/helpers/application_helper/toolbar/configured_system_center.rb
  config/routes.rb
Labels: enhancement

#7416 Adding RSpecs for edit block storage manager
  spec/controllers/mixins/ems_common_spec.rb
  spec/presenters/tree_node/ext_management_system_spec.rb
Labels: enhancement, test

#7423 eslint: update, clean up unused dependencies
  .eslintrc.json
  app/javascript/.eslintrc.json
  package.json
Labels: dependencies, developer

#7426 eslintrc: import/no-unresolved: ignore @@ddf alias
  app/javascript/.eslintrc.json
Labels: developer

#7424 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#7419 Correctly render multi-tags in request details dialog
  app/views/miq_request/_request_dialog_details.html.haml
Labels: bug, ivanchuk/yes, jansa/yes?, services

#7407 Implement support for adding physical storages
  app/controllers/mixins/ems_common.rb
  app/controllers/physical_storage_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/physical_storages_center.rb
  app/helpers/ems_storage_helper/textual_summary.rb
  app/javascript/components/physical-storage-form/index.jsx
  app/javascript/components/physical-storage-form/physical-storage-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/presenters/menu/default_menu.rb
  app/views/physical_storage/new.html.haml
  config/routes.rb
  spec/presenters/menu/default_menu_spec.rb
Labels: enhancement

#7346 Enabling storage-service selection when creating cloud-volume
  app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
  app/controllers/cloud_volume_controller.rb
  app/views/cloud_volume/_common_new_edit.html.haml
Labels: enhancement

#7428 Add Icons for configured system vendor
  app/helpers/configured_system_helper/textual_summary.rb
Labels: configuration management, enhancement, textual summaries

#7273 Allow all providers in tag mapping screen
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  app/views/ops/_label_tag_mapping_form.html.haml
  app/views/ops/_settings_label_tag_mapping_tab.html.haml
  app/views/ops/label_tag_mapping/_tag_category.html.haml
  spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
  spec/views/ops/_label_tag_mapping_form.html.haml_spec.rb
Labels: enhancement

#7432 Marked Strings For Translation in Reports -> Formatting
  app/views/report/_form_formatting.html.haml
Labels: internationalization

#7414 Implementing Dashboard for storage managers
  app/assets/javascripts/controllers/ems_storage_dashboard/heatmap_controller.js
  app/controllers/ems_storage_controller.rb
  app/controllers/ems_storage_dashboard_controller.rb
  app/controllers/mixins/dashboard_view_mixin.rb
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper/toolbar/ems_storage_center.rb
  app/helpers/ems_storage_helper/textual_summary.rb
  app/services/ems_storage_dashboard_service.rb
  app/views/ems_storage/_heatmap.html.haml
  app/views/ems_storage/_show_block_storage_dashboard.html.haml
  app/views/ems_storage/_show_object_storage_dashboard.html.haml
  app/views/ems_storage/show_dashboard.html.haml
  config/routes.rb
  spec/helpers/ems_storage_helper/textual_summary_spec.rb
  spec/shared/controllers/shared_examples_for_ems_storage_controller.rb
Labels: dashboards, enhancement, storage

#7434 Add VmVmware and VmIBM mappable entities for tag mapping
  app/controllers/ops_controller/settings/label_tag_mapping.rb
Labels: enhancement, tagging

#7429 Update DDF version to 2.14.0
  app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
  app/javascript/spec/tree-view/__snapshots__/selector.spec.js.snap
  package.json
Labels: dependencies, react

#7309 Fix Save & Cancel launched from StorageController (Datastores)
  app/controllers/storage_controller.rb
Labels: bug, compute/infrastructure, ivanchuk/yes, jansa/yes?

#7073 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-ui-classic.gemspec
Labels: dependencies, developer, enhancement

#7375 Update carbon packages to their latest versions
  app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
  package.json
Labels: dependencies, enhancement, react

#7415 Fix leftnav icon tooltip and showing user info in side leftnav nav.
  app/javascript/menu/first-level.jsx
  app/javascript/menu/group-switcher.jsx
  app/javascript/menu/main-menu.jsx
  app/javascript/menu/menu-collapse.jsx
  app/javascript/menu/search.jsx
  app/javascript/menu/side-nav-menu-link.jsx
  app/javascript/menu/username.jsx
  app/stylesheet/menu.scss
Labels: accessibility, bug

#7440 Allow i18n in datetimepicker component
  app/helpers/application_helper/form_tags.rb
Labels: internationalization

#7451 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#7431 DDF: submit only fields that are registered in the schema
  app/javascript/forms/data-driven-form.jsx
  app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js
Labels: enhancement, react

#7324 Re-writing Ansible Credentials Form to React
  app/assets/javascripts/components/ansible-credential-options.js
  app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
  app/javascript/components/ansible-credentials-form/ansible-credentials-form.schema.js
  app/javascript/components/ansible-credentials-form/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
  app/javascript/spec/ansible-credentials-form/ansible-credentials-form.spec.js
  app/views/ansible_credential/edit.html.haml
  app/views/ansible_credential/new.html.haml
Labels: dependencies, embedded ansible, pending core, react, refactoring

#7444 Use formApi to change dropdown value in SelectWithOnChange spec
  app/javascript/spec/select/select.spec.js
Labels: test

#7453 Eliminating cyclic dependency for EditingContext
  app/javascript/components/provider-form/editing-context.js
  app/javascript/components/provider-form/index.jsx
  app/javascript/components/provider-form/protocol-selector.jsx
  app/javascript/components/provider-form/provider-credentials.jsx
  app/javascript/components/provider-form/validate-provider-credentials.jsx
Labels: cleanup, react

#7455 change factorygirl to factorybot
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/presenters/tree_builder_report_reports_spec.rb
  spec/presenters/tree_node/miq_product_feature_spec.rb
  spec/services/ems_infra_dashboard_service_spec.rb
Labels: test

#7446 cleanup .travis.yml
  .travis.yml
Labels: developer, test

#7457 Adjusted ansible credential textual summary generation
  app/helpers/ansible_credential_helper/textual_summary.rb
  app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
  spec/helpers/ansible_credential_helper/textual_summary_spec.rb
Labels: bug

#7427 Making the edit service form API-driven and function component
  app/controllers/service_controller.rb
  app/javascript/components/edit-service-form/edit-service-form.schema.js
  app/javascript/components/edit-service-form/index.jsx
  app/javascript/components/service-form/index.jsx
  app/javascript/components/service-form/service-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/service-form/edit-service-form.spec.js
  app/views/service/_service_form.html.haml
Labels: react, services, technical debt

#7437 Forward-Port Translations from Jansa to Master
  app/assets/javascripts/locale/de/app.js
  app/assets/javascripts/locale/en/app.js
  app/assets/javascripts/locale/es/app.js
  app/assets/javascripts/locale/fr/app.js
  app/assets/javascripts/locale/it/app.js
  app/assets/javascripts/locale/ja/app.js
  app/assets/javascripts/locale/ko/app.js
  app/assets/javascripts/locale/pt_BR/app.js
  app/assets/javascripts/locale/zh_CN/app.js
  app/assets/javascripts/locale/zh_TW/app.js
Labels: enhancement, internationalization, kasparov/yes?

#7443 Updated ProtocolSelector component to use SelectWithOnChange
  app/javascript/components/provider-form/protocol-selector.jsx
  app/javascript/components/select/index.jsx
  app/javascript/spec/provider-form/__snapshots__/protocol-selector.spec.js.snap
  app/javascript/spec/provider-form/protocol-selector.spec.js
Labels: react, refactoring

#7462 Make the Flavor form fully API driven and functional
  app/javascript/components/flavor-form/flavor-form.jsx
  app/javascript/components/flavor-form/flavor-form.schema.js
  app/javascript/components/flavor-form/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap
  app/javascript/spec/flavor-form/flavor-form.spec.js
  app/views/flavor/new.html.haml
Labels: react, technical debt

#7469 Make the Settings/About focusable by setting its href to #
  app/javascript/menu/item-type.js
Labels: bug, kasparov/yes?, menus, react
