Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-02, with the labels that each got.

#6632 Fix extra attributes in GOD CustomButton edit page
  app/assets/javascripts/components/generic_object/main-custom-button-form.js
Labels: bug, generic objects, ivanchuk/yes

#6056 Fix tree breadcrumbs on explorer screen missing the tree
  app/assets/javascripts/controllers/tree_view_controller.js
  app/assets/javascripts/miq_angular_application.js
  app/controllers/generic_object_definition_controller.rb
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/javascript/components/breadcrumbs/index.jsx
  app/javascript/components/breadcrumbs/on-click-functions.js
  app/javascript/spec/breadcrumbs/breadcrumbs.spec.js
  app/javascript/spec/breadcrumbs/on-click-functions.spec.js
  app/javascript/spec/helpers/miqAjax.js
  app/views/generic_object_definition/_generic_object_definition_form.html.haml
  spec/controllers/miq_ae_customization_controller_spec.rb
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Labels: breadcrumbs, bug, changelog/no, ivanchuk/yes

#6604 Fix rubocop in Mixins::ContainersCommonMixin
  app/controllers/mixins/containers_common_mixin.rb
Labels: technical debt

#6614 Fix rubocop in Mixins::EmsCommon::Core
  app/controllers/mixins/ems_common/core.rb
Labels: technical debt

#6643 Fix rubocop in Mixins::ManagerControllerMixin
  app/controllers/mixins/manager_controller_mixin.rb
Labels: technical debt

#6626 Fix rubocop in Mixins::EmsCommon
  app/controllers/mixins/ems_common.rb
Labels: technical debt

#6645 Allow non-JSON responses in miqFetch (add `options.skipJsonParsing`)
  app/javascript/http_api/fetch.js
Labels: enhancement, ivanchuk/yes

#6647 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement

#6646 Use cypress for integration tests
  .gitignore
  cypress.json
  cypress/integration/ui/login.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
Labels: dependencies, enhancement, test

#6655 Fix rubocop in Mixins::StartUrl
  app/controllers/mixins/start_url.rb
Labels: technical debt

#6654 Fix rubocop in Mixins::ServiceDialogCreationMixin
  app/controllers/mixins/service_dialog_creation_mixin.rb
Labels: technical debt

#6648 Fix rubocop Mixins::Sandbox
  app/controllers/mixins/sandbox.rb
Labels: technical debt

#6652 Deal with zones when running in pods
  app/controllers/ops_controller/settings/common.rb
  app/helpers/ops_helper.rb
  app/views/ops/_settings_server_tab.html.haml
  spec/controllers/ops_controller/settings/common_spec.rb
Labels: enhancement

#6662 StorageScan button spec - fix spec after .ext_management_systems removal
  spec/helpers/application_helper/buttons/storage_scan_spec.rb
Labels: test

#6660 Fix rubocop in OpsController::OpsRbac
  app/controllers/ops_controller/ops_rbac.rb
Labels: technical debt

#6659 Fix rubocop in OpsController::Diagnostics
  app/controllers/ops_controller/diagnostics.rb
Labels: technical debt

#6658 Fix rubocop in OpsController::Db
  app/controllers/ops_controller/db.rb
Labels: technical debt

#6664 Remove deprecated validate_creds_task
  app/controllers/mixins/ems_common/angular.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
Labels: technical debt

#6666 Revert #6664 to fix credential validation
  app/controllers/mixins/ems_common/angular.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
Labels: bug

#6653 Change update:ui to no longer worry about missing engines
  lib/tasks/manageiq/ui_tasks.rake
Labels: technical debt

#6657 Introduce a DDF component for provider credentials validation
  app/javascript/components/async-credentials/async-provider-credentials.jsx
  app/javascript/forms/mappers/formsFieldsMapper.jsx
Labels: enhancement, react

#6650 remote_consoles - use jquery from npm, not jquery-rails
  app/assets/javascripts/remote_consoles/spice.js
  app/assets/javascripts/remote_consoles/vnc.js
  app/assets/javascripts/remote_consoles/webmks.js
Labels: cleanup

#6673 Send validationDependencies with when validating credentials
  app/javascript/components/async-credentials/async-credentials.jsx
Labels: bug, compute/infrastructure

#6674 EMS validation: send only the listed fields to the API
  app/javascript/components/async-credentials/async-provider-credentials.jsx
Labels: enhancement

#6629 Remove pending specs
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/provider_foreman_controller_spec.rb
  spec/controllers/report_controller_spec.rb
Labels: ivanchuk/no, test

#6641 Do not store Performance::Options instances in the session
  app/controllers/application_controller.rb
  app/controllers/application_controller/performance.rb
  app/controllers/application_controller/performance/options.rb
Labels: bug, ivanchuk/no

#6661 Cypress: menu helper
  cypress/README.md
  cypress/fixtures/example.json
  cypress/integration/ui/menu.spec.js
  cypress/support/commands.js
  package.json
Labels: test

#6678 Fix saving of ems_refresh_worker and ems_metrics_collector_worker
  app/javascript/components/workers-form/workers-form.jsx
Labels: bug, ivanchuk/yes, settings

#6675 Remove GraphQL Explorer from UI
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/graphql_explorer.scss
  app/controllers/graphql_explorer_controller.rb
  app/javascript/graphql-explorer/components/GraphQLExplorer.js
  app/javascript/graphql-explorer/helpers/graphQLFetcher.js
  app/javascript/graphql-explorer/index.js
  app/javascript/packs/component-definitions-common.js
  app/presenters/menu/default_menu.rb
  app/stylesheet/application-webpack.scss
  app/views/graphql_explorer/index.html.haml
  config/routes.rb
  config/webpack/shared.js
  package.json
Labels: cleanup

#6676 Fixed code to show title on empty line chart.
  app/assets/javascripts/components/recent-resource.js
Labels: bug, dashboards, ivanchuk/yes

#6680 Added new Detailed Description field to Group edit/details screen
  app/controllers/ops_controller/ops_rbac.rb
  app/views/ops/_rbac_group_details.html.haml
Labels: enhancement, ivanchuk/yes, settings

#6663 Fix rubocop in OpsController::Settings::AnalysisProfiles
  app/controllers/ops_controller/settings/analysis_profiles.rb
Labels: technical debt

#6665 Fix rubocop in OpsController::Settings::AutomateSchedules
  app/controllers/ops_controller/settings/automate_schedules.rb
Labels: technical debt

#6670 Fix rubocop in OpsController::Settings::CapAndU
  app/controllers/ops_controller/settings/cap_and_u.rb
Labels: technical debt

#6671 Fix rubocop in OpsController::Settings::Common
  app/controllers/ops_controller/settings/common.rb
Labels: technical debt

#6677 Fix rubocop in OpsController::Settings::LabelTagMapping
  app/controllers/ops_controller/settings/label_tag_mapping.rb
Labels: technical debt

#6679 Fix rubocop in OpsController::Settings::Rhn
  app/controllers/ops_controller/settings/rhn.rb
Labels: technical debt

#6682 Remove extraneous line from OpsController::Settings::Schedules
  app/controllers/ops_controller/settings/schedules.rb
Labels: technical debt

#6649 Redirect to proper controller for Edit and other actions on selected Host Aggregate
  app/controllers/host_aggregate_controller.rb
  app/controllers/mixins/ems_common.rb
  spec/controllers/host_aggregate_controller_spec.rb
  spec/controllers/mixins/ems_common_spec.rb
Labels: bug, compute/cloud, ivanchuk/no

#6644 Notification drawer
  app/assets/javascripts/controllers/header/header_controller.js
  app/assets/javascripts/controllers/notifications/notification-drawer.directive.js
  app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
  app/assets/javascripts/controllers/notifications/toast_list_controller.js
  app/assets/javascripts/services/event_notifications_service.js
  app/assets/stylesheets/notifications.scss
  app/javascript/components/notification-drawer/helpers.js
  app/javascript/components/notification-drawer/notification-drawer.jsx
  app/javascript/components/toast-list/toast-list.jsx
  app/javascript/components/top-navbar/notifications.jsx
  app/javascript/miq-redux/actions/notifications-actions.js
  app/javascript/miq-redux/notification-reducer.js
  app/javascript/packs/application-common.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/packs/notification-drawer-common.js
  app/javascript/spec/fixtures/notifications.json
  app/javascript/spec/fixtures/resources.json
  app/javascript/spec/helpers/miqFormatNotification.js
  app/javascript/spec/miq-redux/actions/notifications-actions.spec.js
  app/javascript/spec/miq-redux/notification-reducer.spec.js
  app/javascript/spec/notification-drawer/__snapshots__/notification-drawer.spec.js.snap
  app/javascript/spec/notification-drawer/notification-drawer.spec.js
  app/javascript/spec/toast-list/__snapshots__/toast-list.spec.js.snap
  app/javascript/spec/toast-list/toast-list.spec.js
  app/javascript/spec/top-navbar/__snapshots__/top-navbar.spec.js.snap
  app/javascript/spec/top-navbar/top-navbar.spec.js
  app/views/layouts/_header.html.haml
  app/views/layouts/_notifications_drawer.html.haml
  app/views/layouts/_toast_list.html.haml
  app/views/static/notification_drawer/_notification-body.html.haml
  app/views/static/notification_drawer/notification-drawer.html.haml
  spec/javascripts/services/event_notifications_service_spec.js
Labels: notifications, react

#6681 Cypress - toolbars (and accordion)
  cypress/README.md
  cypress/integration/ui/toolbar.spec.js
  cypress/support/commands.js
Labels: cypress, test

#6544 Limit metric rollups to just default time profile
  app/services/ems_infra_dashboard_service.rb
  spec/services/ems_infra_dashboard_service_spec.rb
Labels: bug, compute/infrastructure, hammer/yes, ivanchuk/yes

#6689 Notification drawer - fix login screen popup
  app/assets/javascripts/miq_global.js
  app/javascript/components/notification-drawer/helpers.js
  app/javascript/components/notification-drawer/notification-drawer.jsx
  app/javascript/components/toast-list/toast-list.jsx
  app/javascript/components/top-navbar/notifications.jsx
  app/javascript/miq-redux/actions/notifications-actions.js
  app/javascript/miq-redux/notification-reducer.js
  app/javascript/notifications/backend.js
  app/javascript/notifications/init.js
  app/javascript/packs/application-common.js
  app/javascript/packs/notification-drawer-common.js
  app/javascript/packs/toolbar-actions-common.js
  app/javascript/spec/miq-redux/actions/notifications-actions.spec.js
  app/javascript/spec/miq-redux/notification-reducer.spec.js
  app/javascript/spec/notification-drawer/notification-drawer.spec.js
  app/javascript/spec/toast-list/toast-list.spec.js
  app/javascript/spec/toolbar-actions/toolbar-actions-delete.spec.js
  app/javascript/spec/toolbar-actions/toolbar-actions-generic.spec.js
  app/javascript/spec/top-navbar/__snapshots__/top-navbar.spec.js.snap
  app/javascript/toolbar-actions/util.js
  app/views/layouts/_notifications_drawer.html.haml
Labels: bug, notifications

#6688 Load inputs for Ansible* methods.
  app/controllers/miq_ae_class_controller.rb
  app/views/miq_ae_class/_method_inputs.html.haml
Labels: automation/automate, bug

#6693 Update react-router*
  app/javascript/miq-redux/reducer.js
  config/webpack/shared.js
  package.json
Labels: dependencies

#6690 Send resource_id via API when editing CustomButton
  app/assets/javascripts/components/generic_object/main-custom-button-form.js
Labels: automation/automate, bug, ivanchuk/no

#6193 [IVANCHUK] Remove tree breadcrumbs
  app/assets/javascripts/controllers/tree_view_controller.js
  app/controllers/automation_manager_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/controllers/provider_foreman_controller.rb
  app/controllers/service_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_cloud_controller.rb
  app/controllers/vm_infra_controller.rb
  app/controllers/vm_or_template_controller.rb
  app/javascript/components/breadcrumbs/on-click-functions.js
  app/javascript/spec/breadcrumbs/on-click-functions.spec.js
  spec/controllers/mixins/breadcrumbs_mixin_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: breadcrumbs, bug

#6154 [IVANCHUK] Update gettext invocation and gettext catalog
  app/javascript/components/firmware-registry/firmware-registry-form.jsx
  locale/ManageIQ_UI_Classic.pot
  locale/en/ManageIQ_UI_Classic.po
Labels: bug, internationalization

#6703 Replaced attribute 'display' to 'visible'
  app/presenters/tree_builder_services.rb
Labels: ivanchuk/no, technical debt

#6704 Rename SecretSwitchField to PasswordField in component mappings
  app/javascript/components/async-credentials/password-field.jsx
  app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
  app/javascript/forms/mappers/formsFieldsMapper.jsx
  app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
  app/javascript/spec/async-credentials/password-field.spec.js
  app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
Labels: enhancement, react

#6706 Inherit `edit` under the AsyncCredentials using the existing context
  app/javascript/components/async-credentials/async-credentials.jsx
  app/javascript/components/async-credentials/password-field.jsx
  app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
  app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
  app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
  app/javascript/spec/async-credentials/password-field.spec.js
  app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
Labels: enhancement, react

#6707 Drop the obsolete `edit` from PasswordField.defaultProps
  app/javascript/components/async-credentials/password-field.jsx
Labels: enhancement, react

#6700 Fix SVG upload, render
  app/assets/javascripts/components/generic_object/custom-image.js
  app/controllers/picture_controller.rb
Labels: bug, generic objects

#6699 Fix rubocop in OpsController::Settings::Upload
  app/controllers/ops_controller/settings/upload.rb
Labels: technical debt

#6685 Fix rubocop in OpsController::Settings::Tags
  app/controllers/ops_controller/settings/tags.rb
Labels: technical debt

#6684 Fix rubocop in OpsController::Settings::Schedules
  app/controllers/ops_controller/settings/schedules.rb
Labels: technical debt

#6702 Changelog for sprint 128, 129, 130
  CHANGELOG.md
Labels: documentation

#6692 Change disk options in oVirts provisioning dialog
  app/views/miq_request/_prov_field.html.haml
  app/views/shared/views/_prov_dialog.html.haml
Labels: compute/infrastructure, enhancement

#6695 Use uri_attributes in CustomButton instead of ae_attributes
  app/assets/javascripts/components/generic_object/main-custom-button-form.js
  spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js
Labels: automation/automate, bug, ivanchuk/yes

#6711 eslint: disable camelcase rule
  .eslintrc.json
  app/assets/javascripts/.eslintrc.json
  app/javascript/components/async-credentials/async-provider-credentials.jsx
  app/javascript/components/pxe-servers-form/pxe-server-form.jsx
  app/javascript/components/tree-view/hierarchical-tree-view.jsx
  app/javascript/spec/toolbar-actions/toolbar-actions-generic.spec.js
Labels: developer

#6712 Render 'layouts/empty' partial correctly.
  app/controllers/provider_foreman_controller.rb
  app/views/provider_foreman/explorer.html.haml
Labels: bug, configuration management, ivanchuk/yes

#6713 Enable buttons only when 1 or more items are selected from the list
  app/helpers/application_helper/toolbar/physical_chassis_list_center.rb
Labels: bug, compute/physical infrastructure, ivanchuk/yes

#6714 Implement helperText on the PasswordField component
  app/javascript/components/async-credentials/password-field.jsx
Labels: enhancement, react

#6691 Move tagging from react-ui-components
  app/javascript/components/taggingWrapper.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/pf-select/pf-select.jsx
  app/javascript/pf-select/select-styles.js
  app/javascript/tagging/actions/actions.js
  app/javascript/tagging/actions/index.js
  app/javascript/tagging/components/InnerComponents/CategoryModifier.js
  app/javascript/tagging/components/InnerComponents/Tag.js
  app/javascript/tagging/components/InnerComponents/TagCategory.js
  app/javascript/tagging/components/InnerComponents/TagModifier.js
  app/javascript/tagging/components/InnerComponents/TagSelector.js
  app/javascript/tagging/components/InnerComponents/TagView.js
  app/javascript/tagging/components/InnerComponents/ValueModifier.js
  app/javascript/tagging/components/InnerComponents/ValueSelector.js
  app/javascript/tagging/components/Tagging/Tagging.js
  app/javascript/tagging/components/TaggingPropTypes.js
  app/javascript/tagging/components/TaggingWithButtons/TaggingWithButtons.jsx
  app/javascript/tagging/containers/tagging.js
  app/javascript/tagging/index.js
  app/javascript/tagging/reducers/index.js
  app/javascript/tagging/reducers/reducers.js
  app/javascript/tagging/sass/_tag-category.scss
  app/javascript/tagging/sass/_tag-selector.scss
  app/javascript/tagging/sass/_tag.scss
  app/javascript/tagging/sass/style.scss
  app/javascript/tagging/stories/tagging.stories.js
  app/javascript/tagging/tests/__snapshots__/category.modifier.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.category.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.modifier.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.selector.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.view.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tagging.test.js.snap
  app/javascript/tagging/tests/__snapshots__/value.modifier.test.js.snap
  app/javascript/tagging/tests/__snapshots__/value.selector.test.js.snap
  app/javascript/tagging/tests/actions.test.js
  app/javascript/tagging/tests/category.modifier.test.js
  app/javascript/tagging/tests/reducers.test.js
  app/javascript/tagging/tests/tag.category.test.js
  app/javascript/tagging/tests/tag.modifier.test.js
  app/javascript/tagging/tests/tag.selector.test.js
  app/javascript/tagging/tests/tag.test.js
  app/javascript/tagging/tests/tag.view.test.js
  app/javascript/tagging/tests/tagging.test.js
  app/javascript/tagging/tests/tagging.with.buttons.test.js
  app/javascript/tagging/tests/tagging.with.reducer.test.js
  app/javascript/tagging/tests/value.modifier.test.js
  app/javascript/tagging/tests/value.selector.test.js
  app/stylesheet/application-webpack.scss
  package.json
Labels: ivanchuk/yes

#6715 Move report formatter and charting to core
  .github/CODEOWNERS
  app/controllers/application_controller.rb
  app/controllers/application_controller/performance.rb
  app/controllers/dashboard_controller.rb
  app/controllers/report_controller/reports.rb
  app/controllers/utilization_controller.rb
  app/helpers/c3_helper.rb
  app/helpers/charting_helper.rb
  app/views/configuration/_ui_1.html.haml
  app/views/dashboard/_widget_chart.html.haml
  app/views/layouts/application.html.haml
  app/views/report/_form_chart.html.haml
  lib/charting.rb
  lib/charting/c3_charting.rb
  lib/report_formatter.rb
  lib/report_formatter/c3.rb
  lib/report_formatter/c3_series.rb
  lib/report_formatter/chart_common.rb
  lib/report_formatter/converter.rb
  lib/report_formatter/html.rb
  lib/report_formatter/report_renderer.rb
  lib/report_formatter/text.rb
  lib/report_formatter/timeline.rb
  lib/report_formatter/timeline_message.rb
  spec/lib/report_formater/c3_formatter_spec.rb
  spec/lib/report_formater/chart_common_spec.rb
  spec/lib/report_formater/text_formatter_spec.rb
  spec/lib/report_formater/timeline_message_spec.rb
  spec/lib/report_formater/timeline_spec.rb
  spec/support/report_helper.rb
Labels: refactoring

#6718 Use product settings for docs & links
  app/presenters/menu/default_menu.rb
  app/views/support/show.html.haml
  config/settings.yml
Labels: technical debt

#6717 Implement helperText for all PasswordField child components
  app/javascript/components/async-credentials/edit-password-field.jsx
  app/javascript/components/async-credentials/password-field.jsx
  app/javascript/forms/mappers/formsFieldsMapper.jsx
  app/javascript/spec/async-credentials/__snapshots__/edit-password-field.spec.js.snap
  app/javascript/spec/async-credentials/edit-password-field.spec.js
Labels: enhancement, react

#6720 Move *FieldVisibilityServices to core
  app/services/auto_placement_visibility_service.rb
  app/services/customize_fields_visibility_service.rb
  app/services/dialog_field_visibility_service.rb
  app/services/linked_clone_visibility_service.rb
  app/services/network_visibility_service.rb
  app/services/number_of_vms_visibility_service.rb
  app/services/pxe_iso_visibility_service.rb
  app/services/request_type_visibility_service.rb
  app/services/retirement_visibility_service.rb
  app/services/service_template_fields_visibility_service.rb
  app/services/sysprep_auto_logon_visibility_service.rb
  app/services/sysprep_custom_spec_visibility_service.rb
  spec/services/auto_placement_visibility_service_spec.rb
  spec/services/customize_fields_visibility_service_spec.rb
  spec/services/dialog_field_visibility_service_spec.rb
  spec/services/linked_clone_visibility_service_spec.rb
  spec/services/network_visibility_service_spec.rb
  spec/services/number_of_vms_visibility_service_spec.rb
  spec/services/pxe_iso_visibility_service_spec.rb
  spec/services/request_type_visibility_service_spec.rb
  spec/services/retirement_visibility_service_spec.rb
  spec/services/service_template_fields_visibility_service_spec.rb
  spec/services/sysprep_auto_logon_visibility_service_spec.rb
  spec/services/sysprep_custom_spec_visibility_service_spec.rb
Labels: refactoring

#6722 Fix Travis Jest failure
  Rakefile
Labels: ivanchuk/no, test
