Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2020-12, with the labels that each got.

#7531 Replace the edit icon with a delete on the CV snapshot delete button
  app/helpers/application_helper/toolbar/cloud_volume_snapshot_center.rb
Labels: bug, toolbars

#7438 Update the name of the labeled_resource for Amazon
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
Labels: enhancement, pending core, tagging

#7518 Rewrite Set retirement date form to DDF/React
  app/assets/javascripts/components/retirement-form.js
  app/controllers/mixins/actions/vm_actions/retire.rb
  app/javascript/components/retirement-form/index.jsx
  app/javascript/components/retirement-form/retirement-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/retirement-form/__snapshots__/retirement-form.spec.js.snap
  app/javascript/spec/retirement-form/retirement-form.spec.js
  app/views/shared/views/_retire.html.haml
  config/routes.rb
  spec/javascripts/components/retirement/retirement-form_spec.js
  spec/routing/service_routing_spec.rb
  spec/routing/shared_examples/vm_common_examples.rb
  spec/routing/vm_or_template_routing_spec.rb
  spec/routing/vm_routing_spec.rb
Labels: react, technical debt

#7535 Drop the DB garbage collection button/handler from the UI
  app/controllers/ops_controller/diagnostics.rb
  app/views/ops/_diagnostics_database_tab.html.haml
  config/routes.rb
  spec/routing/ops_routing_spec.rb
Labels: cleanup, settings

#7380 Change Add cloud key pairs form react
  app/assets/javascripts/controllers/auth_key_pair_cloud/auth_key_pair_cloud_controller.js
  app/controllers/auth_key_pair_cloud_controller.rb
  app/javascript/components/auth-key-pair-cloud/auth-key-pair-cloud-form.schema.js
  app/javascript/components/auth-key-pair-cloud/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/auth-key-pair-cloud/__snapshots__/ansible-credentials-form.spec.js.snap
  app/javascript/spec/auth-key-pair-cloud/ansible-credentials-form.spec.js
  app/views/auth_key_pair_cloud/_form.html.haml
  app/views/auth_key_pair_cloud/new.html.haml
  config/routes.rb
  spec/javascripts/controllers/auth_key_pair_cloud/auth_key_pair_cloud_controller_spec.js
Labels: refactoring

#7537 Replace 'sort_by' with 'order' to prevent error
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
Labels: bug, compute/infrastructure

#7534 Clean up session variable from the orchestration stack retirement
  app/controllers/mixins/actions/vm_actions/retire.rb
Labels: bug, kasparov/no

#7526 Move toolbar component to ui-classic and make it carbon
  app/javascript/components/miq-toolbar.jsx
  app/javascript/components/toolbar/MenuIcon.js
  app/javascript/components/toolbar/Toolbar.jsx
  app/javascript/components/toolbar/ToolbarButton.jsx
  app/javascript/components/toolbar/ToolbarClick.jsx
  app/javascript/components/toolbar/ToolbarContext.jsx
  app/javascript/components/toolbar/ToolbarList.jsx
  app/javascript/components/toolbar/ToolbarView.jsx
  app/javascript/components/toolbar/index.js
  app/javascript/components/toolbar/utility.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/toolbar/__snapshots__/toolbar.test.js.snap
  app/javascript/spec/toolbar/data/toolbar-big.json
  app/javascript/spec/toolbar/data/toolbar-view.json
  app/javascript/spec/toolbar/data/toolbar.json
  app/javascript/spec/toolbar/miq-toolbar.spec.jsx
  app/javascript/spec/toolbar/toolbar.test.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/toolbar.scss
  package.json
Labels: accessibility, dependencies, enhancement

#7540 Update DDF to its latest version, adjust snapshots
  app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
  app/javascript/spec/provider-form/__snapshots__/protocol-selector.spec.js.snap
  app/javascript/spec/select/__snapshots__/select.spec.js.snap
  package.json
Labels: dependencies, react

#7536 Fixed tree selection issues with screens in Reports explorer
  app/controllers/application_controller.rb
  app/javascript/components/gtl-view.jsx
Labels: bug, gtls, kasparov/yes?

#7435 Marked Strings for Translation in Chargeback -> Rates
  app/views/chargeback_rate/_cb_rate_show.html.haml
Labels: bug, internationalization

#7530 Modified HAML File to Reflect Changes Made to MiqReport::GROUPINGS
  app/views/report/_form_sort.html.haml
Labels: bug, internationalization

#7539 Change dashboard toolbar to carbon and fix A11y
  app/javascript/components/dashboard_toolbar.jsx
  app/javascript/components/topology_toolbar.jsx
  app/javascript/spec/toolbar/__snapshots__/dashboard_toolbar.spec.jsx.snap
  app/javascript/spec/toolbar/__snapshots__/topology_toolbar.spec.jsx.snap
  app/stylesheet/toolbar.scss
Labels: accessibility, enhancement

#7450 Make the VM/Instance snapshot form API-driven
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/javascript/components/vm-snapshot-form/vm-snapshot-form.jsx
  app/javascript/components/vm-snapshot-form/vm-snapshot-form.schema.js
  app/views/vm_common/_snap.html.haml
  config/routes.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/routing/vm_infra_routing_spec.rb
  spec/routing/vm_or_template_routing_spec.rb
Labels: react, technical debt

#7542 revert rename of all_vms_and_templates
  app/controllers/application_controller.rb
  app/controllers/vm_common.rb
Labels: bug
