Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-12, with the labels that each got.

#7981 Fix host aggregates create form
  app/controllers/host_aggregate_controller.rb
Labels: bug

#7982 Remove PF react package
  config/webpack/shared.js
  package.json
  yarn.lock
Labels: dependencies, cleanup

#7984 Volume mapping can now be done for Host Initiator Groups
  app/javascript/components/volume-mapping-form/index.jsx
  app/javascript/components/volume-mapping-form/volume-mapping-form.schema.js
Labels: enhancement, storage

#7977 Converted ansible repository form to carbon react
  app/javascript/components/ansible-repository-form/ansible-repository-form.schema.js
  app/javascript/components/ansible-repository-form/index.jsx
  app/javascript/oldjs/controllers/ansible_repository/repository_form_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/ansible-repository-form/__snapshots__/ansible-repository-form.spec.js.snap
  app/javascript/spec/ansible-repository-form/ansible-repository-form.spec.js
  app/views/ansible_repository/_repository_form.html.haml
  app/views/ansible_repository/edit.html.haml
  app/views/ansible_repository/new.html.haml
  spec/javascripts/controllers/ansible_repository/ansible_repository_form_controller_spec.js
Labels: enhancement

#7969 Convert router interface forms
  app/controllers/network_router_controller.rb
  app/javascript/components/network-routers-interfaces-form/index.jsx
  app/javascript/components/network-routers-interfaces-form/network-routers-interfaces-form.schema.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/network_router/network_router_form_controller.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/network-router-form/network-router-form.spec.js
  app/javascript/spec/network-routers-interfaces-form/__snapshots__/network-routers-interfaces-form.spec.js.snap
  app/javascript/spec/network-routers-interfaces-form/network-routers-interfaces-form.spec.js
  app/views/network_router/add_interface_select.html.haml
  app/views/network_router/remove_interface_select.html.haml
  config/routes.rb
  spec/controllers/network_router_controller.spec.rb
  spec/javascripts/controllers/network/network_router_form_controller_spec.js
Labels: enhancement

#7978 Converting haml tables in Automate to React Carbon tables
  app/helpers/miq_ae_class_helper.rb
  app/javascript/components/data-tables/datastore/helper.js
  app/javascript/components/data-tables/datastore/index.jsx
  app/javascript/components/data-tables/db-list/helper.js
  app/javascript/components/data-tables/db-list/index.jsx
  app/javascript/components/data-tables/role-list/helper.js
  app/javascript/components/data-tables/role-list/index.jsx
  app/javascript/components/miq-data-table/helper.js
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/react/textual_summary_click.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/miq-data-table.scss
  app/stylesheet/miq-structured-list.scss
  app/views/miq_ae_class/_class_fields.html.haml
  app/views/miq_ae_class/_class_instances.html.haml
  app/views/miq_ae_class/_class_methods.html.haml
  app/views/miq_ae_class/_class_props.html.haml
  app/views/miq_ae_class/_datastore_list.haml
  app/views/miq_ae_class/_domain_overrides.html.haml
  app/views/miq_ae_class/_instance_fields.html.haml
  app/views/miq_ae_class/_ns_details.html.haml
  app/views/miq_ae_class/_ns_list.html.haml
  app/views/report/_db_list.html.haml
  app/views/report/_role_list.html.haml
Labels: enhancement

#7985 renaming supports :ems_network_new to update
  app/controllers/ems_network_controller.rb
  app/controllers/mixins/storage_common_mixin.rb
  app/helpers/application_helper/button/ems_network.rb
Labels: refactoring, pluggability

#7990 Combine icon cell with name cell of data tables
  app/javascript/components/data-tables/button-group-list/helper.js
  app/javascript/components/data-tables/button-list/helper.js
  app/javascript/components/data-tables/db-list/helper.js
  app/javascript/components/data-tables/gtl/DataTable.jsx
  app/javascript/components/data-tables/optimization/helper.js
  app/javascript/components/data-tables/reports/helper.js
  app/javascript/components/data-tables/role-list/helper.js
  app/javascript/components/miq-data-table/helper.js
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/spec/miq-data-table/__snapshots__/miq-data-table.spec.js.snap
  app/javascript/spec/miq-data-table/data.js
Labels: enhancement

#7974 Creation of host initiator group
  app/controllers/host_initiator_group_controller.rb
  app/helpers/application_helper/button/host_initiator_group_new.rb
  app/helpers/application_helper/toolbar/host_initiator_groups_center.rb
  app/javascript/components/host-initiator-group-form/host-initiator-group-form.schema.js
  app/javascript/components/host-initiator-group-form/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
  app/javascript/spec/host-initiator-group-form/host-initiator-group.spec.js
  app/views/host_initiator_group/new.html.haml
  config/routes.rb
Labels: enhancement

#7991 Floating IPs Form React Conversion
  app/controllers/floating_ip_controller.rb
  app/javascript/components/network-floatingIPs-form/helper.js
  app/javascript/components/network-floatingIPs-form/index.jsx
  app/javascript/components/network-floatingIPs-form/network-floatingIPs-form.schema.js
  app/javascript/oldjs/controllers/floating_ip/floating_ip_form_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/network-floating-ip-form/__snapshots__/network-floating-ip-form.spec.js.snap
  app/javascript/spec/network-floating-ip-form/network-floating-ip-form.spec.js
  app/views/floating_ip/_common_new_edit.html.haml
  app/views/floating_ip/edit.html.haml
  app/views/floating_ip/new.html.haml
  config/routes.rb
  spec/controllers/floating_ip_controller_spec.rb
  spec/javascripts/controllers/floating_ip_form_controller_spec.js
Labels: enhancement

#7996 [WIP] Fix bug in datastore conversion
  app/javascript/components/data-tables/datastore/index.jsx
  app/javascript/components/miq-data-table/helper.js
  app/javascript/spec/textual_summary/data/multilink_table.js
Labels: bug

#7998 Fixed values_at bug
  app/helpers/textual_listview.rb
  app/javascript/react/table_list_view_wrapper.js
Labels: bug, morphy/yes?

#8000 Fix wrongly named spec files
  spec/helpers/application_helper/buttons/smart_state_scan.rb
  spec/helpers/application_helper/buttons/smart_state_scan_spec.rb
  spec/helpers/textual_multilabel_spec.rb
  spec/presenters/tree_node/root_spec.rb
Labels: bug, test
