Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-06, with the labels that each got.

#7753 Fix issue where test setup is inaccurate
  spec/controllers/ops_controller/ops_rbac_spec.rb
Labels: bug, test

#7752 [LASKER] Manual backport 7740
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/miq_policy_controller/events.rb
  app/controllers/miq_policy_controller/policies.rb
  app/controllers/miq_policy_set_controller.rb
  app/controllers/pxe_controller/iso_datastores.rb
  app/controllers/security_policy_rule_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/miq_action_modify.rb
  app/helpers/application_helper/toolbar/miq_policy_center.rb
  app/helpers/application_helper/toolbar/saved_reports_center.rb
  spec/config/routes.pending.yml
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/ems_storage_controller_spec.rb
  spec/controllers/miq_ae_customization_controller_spec.rb
  spec/controllers/miq_alert_controller_spec.rb
  spec/controllers/miq_report_controller/dashboards_spec.rb
  spec/controllers/pxe_controller_spec.rb
  spec/controllers/vm_common_spec.rb
  spec/routes_spec.rb
Labels: bug

#7754 Applying ESLint changes in gtl/table react component.
  app/javascript/components/gtl/DataTable.jsx
Labels: refactoring

#7757 Fix page layout for Automate-->Simulation page
  app/assets/stylesheets/patternfly_overrides.scss
Labels: bug, lasker/yes?

#7758 Add support for cpu/memory hot add in provisioning
  app/views/miq_request/_prov_field.html.haml
  app/views/shared/views/_prov_dialog.html.haml
Labels: enhancement

#7760 Remove unnecessary method
  app/controllers/guest_device_controller.rb
  app/controllers/physical_network_port_controller.rb
Labels: cleanup

#7746 Combine block and object storage and refactor storage submenu.
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/cloud_object_store_object_controller.rb
  app/controllers/cloud_volume_backup_controller.rb
  app/controllers/cloud_volume_controller.rb
  app/controllers/cloud_volume_snapshot_controller.rb
  app/controllers/cloud_volume_type_controller.rb
  app/controllers/ems_block_storage_controller.rb
  app/controllers/ems_object_storage_controller.rb
  app/controllers/ems_storage_controller.rb
  app/controllers/host_initiator_controller.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/volume_mapping_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/ems_block_storages_center.rb
  app/helpers/application_helper/toolbar/ems_storages_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_storage_helper.rb
  app/helpers/volume_mapping_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/services/dialog_local_service.rb
  app/views/ems_block_storage/show_list.html.haml
  app/views/ems_block_storage/show_policy_timeline.html.haml
  app/views/ems_object_storage/show_list.html.haml
  app/views/ems_object_storage/show_policy_timeline.html.haml
  app/views/ems_storage/edit.html.haml
  app/views/ems_storage/new.html.haml
  app/views/ems_storage/show_list.html.haml
  config/routes.rb
  product/views/ems_block_storage.yaml
  product/views/ems_storage.yaml
  spec/config/routes.pending.yml
  spec/controllers/ems_block_storage_controller_spec.rb
  spec/controllers/ems_object_storage_controller_spec.rb
  spec/controllers/ems_storage_controller_spec.rb
  spec/controllers/mixins/ems_common_spec.rb
  spec/presenters/menu/default_menu_spec.rb
  spec/services/dialog_local_service_spec.rb
  spec/shared/controllers/shared_examples_for_ems_block_storage_controller.rb
  spec/shared/controllers/shared_examples_for_ems_object_storage_controller.rb
Labels: enhancement

#7762 Add a multi select component with a select all option
  app/javascript/components/multiselect-with-selectall/index.js
  app/javascript/forms/mappers/componentMapper.jsx
  app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
  app/javascript/spec/pxe-customization-template-form/__snapshots__/pxe-customization-template-form.spec.js.snap
  app/javascript/spec/pxe-image-type-form/__snapshots__/pxe-image-type-form.spec.js.snap
  app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
Labels: enhancement

#7763 Fix scroll top for notifications.
  app/controllers/application_controller.rb
  app/controllers/application_controller/automate.rb
  app/controllers/application_controller/buttons.rb
  app/controllers/application_controller/ci_processing.rb
  app/controllers/application_controller/filter.rb
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/application_controller/performance.rb
  app/controllers/application_controller/timelines.rb
  app/controllers/application_controller/wait_for_task.rb
  app/controllers/condition_controller.rb
  app/controllers/configuration_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/miq_action_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_alert_set_controller.rb
  app/controllers/miq_policy_set_controller.rb
  app/controllers/miq_request_controller.rb
  app/controllers/miq_task_controller.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/controllers/mixins/actions/vm_actions/retire.rb
  app/controllers/mixins/explorer_show.rb
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/diagnostics.rb
  app/controllers/ops_controller/ops_rbac.rb
  app/controllers/ops_controller/settings.rb
  app/controllers/ops_controller/settings/analysis_profiles.rb
  app/controllers/ops_controller/settings/help_menu.rb
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  app/controllers/ops_controller/settings/tags.rb
  app/controllers/report_controller.rb
  app/controllers/report_controller/dashboards.rb
  app/controllers/report_controller/reports/editor.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/flash.rb
  app/javascript/oldjs/miq_explorer.js
  app/javascript/oldjs/miq_flash.js
  app/presenters/explorer_presenter.rb
Labels: enhancement

#7775 Fixed delete subnet queued method name
  spec/controllers/cloud_subnet_controller_spec.rb
Labels: compute/cloud, refactoring

#7774 Fixed error for adding policies
  app/controllers/miq_policy_controller/policies.rb
Labels: bug

#7776 Fixed error for cancel button in template editor
  app/controllers/application_controller/advanced_search.rb
Labels: bug

#7770 Upgrade DDF version from 2.X.X to 3.X.X
  app/javascript/components/catalog-form/catalog-form.schema.js
  app/javascript/components/provider-form/index.jsx
  app/javascript/forms/data-driven-form.jsx
  app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
  app/javascript/spec/async-credentials/async-credentials.spec.js
  app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
  app/javascript/spec/copy-dashboard-form/copy-dashboard-form.spec.js
  app/javascript/spec/forms/__snapshots__/data-driven-form.spec.js.snap
  app/javascript/spec/provider-form/__snapshots__/protocol-selector.spec.js.snap
  app/javascript/spec/provider-form/protocol-selector.spec.js
  app/javascript/spec/pxe-customization-template-form/__snapshots__/pxe-customization-template-form.spec.js.snap
  app/javascript/spec/pxe-image-type-form/__snapshots__/pxe-image-type-form.spec.js.snap
  app/javascript/spec/select/__snapshots__/select.spec.js.snap
  app/javascript/spec/select/select.spec.js
  app/javascript/spec/tree-view/selector.spec.js
  app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
  app/stylesheet/ddf_override.scss
  package.json
Labels: enhancement
