Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-01, with the labels that each got.

#7543 Rewrote Policy Controller to Ensure Strings are Translated Correctly
  app/controllers/miq_policy_controller.rb
Labels: bug, internationalization

#7348 Policy profile de-explorization
  app/controllers/miq_policy_set_controller.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/miq_policy_set_center.rb
  app/helpers/application_helper/toolbar/miq_policy_sets_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/presenters/menu/default_menu.rb
  app/presenters/tree_builder.rb
  app/presenters/tree_builder_policy_profile.rb
  app/presenters/tree_node/miq_policy.rb
  app/presenters/tree_node/miq_policy_set.rb
  app/views/miq_policy_set/_form.html.haml
  app/views/miq_policy_set/_profile_details.html.haml
  app/views/miq_policy_set/_profile_list.html.haml
  app/views/miq_policy_set/edit.html.haml
  app/views/miq_policy_set/explorer.html.haml
  app/views/miq_policy_set/new.html.haml
  app/views/miq_policy_set/show.html.haml
  app/views/miq_policy_set/show_list.html.haml
  config/routes.rb
  spec/controllers/miq_policy_set_controller_spec.rb
  spec/presenters/tree_builder_policy_profile_spec.rb
  spec/presenters/tree_node/miq_policy_set_spec.rb
  spec/routing/miq_policy_set_routing_spec.rb
Labels: enhancement

#7549 [WIP] Attempt to fix CI on master
  spec/controllers/application_controller/buttons_spec.rb
  spec/controllers/application_controller/miq_request_methods_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/miq_ae_class_controller_spec.rb
  spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb
  spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
  spec/controllers/miq_ae_customization_controller/old_dialogs_spec.rb
  spec/controllers/miq_report_controller/menus_spec.rb
  spec/controllers/miq_report_controller/reports/editor_spec.rb
  spec/controllers/miq_request_controller_spec.rb
  spec/controllers/ops_controller/settings/automate_schedules_spec.rb
  spec/controllers/ops_controller/settings/common_spec.rb
  spec/controllers/ops_controller/settings/help_menu_spec.rb
  spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
  spec/controllers/ops_controller/settings/schedules_spec.rb
  spec/controllers/ops_controller/settings/upload_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/controllers/physical_server_controller_spec.rb
  spec/controllers/pxe_controller/pxe_customization_templates_spec.rb
  spec/controllers/report_controller_spec.rb
  spec/controllers/service_controller_spec.rb
Labels: wip

#7550 [KASPAROV] Backport Fix CI after RBAC backports
  spec/controllers/application_controller/buttons_spec.rb
  spec/controllers/application_controller/miq_request_methods_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/miq_ae_class_controller_spec.rb
  spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb
  spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
  spec/controllers/miq_ae_customization_controller/old_dialogs_spec.rb
  spec/controllers/miq_report_controller/menus_spec.rb
  spec/controllers/miq_report_controller/reports/editor_spec.rb
  spec/controllers/miq_request_controller_spec.rb
  spec/controllers/ops_controller/settings/automate_schedules_spec.rb
  spec/controllers/ops_controller/settings/common_spec.rb
  spec/controllers/ops_controller/settings/help_menu_spec.rb
  spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
  spec/controllers/ops_controller/settings/schedules_spec.rb
  spec/controllers/ops_controller/settings/upload_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/controllers/physical_server_controller_spec.rb
  spec/controllers/pxe_controller/pxe_customization_templates_spec.rb
  spec/controllers/report_controller_spec.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, test

#7551 [JANSA] Backport Fix CI after RBAC backports
  spec/controllers/application_controller/buttons_spec.rb
  spec/controllers/application_controller/miq_request_methods_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/miq_ae_class_controller_spec.rb
  spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb
  spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
  spec/controllers/miq_ae_customization_controller/old_dialogs_spec.rb
  spec/controllers/miq_report_controller/menus_spec.rb
  spec/controllers/miq_report_controller/reports/editor_spec.rb
  spec/controllers/miq_request_controller_spec.rb
  spec/controllers/ops_controller/settings/automate_schedules_spec.rb
  spec/controllers/ops_controller/settings/common_spec.rb
  spec/controllers/ops_controller/settings/help_menu_spec.rb
  spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
  spec/controllers/ops_controller/settings/schedules_spec.rb
  spec/controllers/ops_controller/settings/upload_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/controllers/physical_server_controller_spec.rb
  spec/controllers/pxe_controller/pxe_customization_templates_spec.rb
  spec/controllers/report_controller_spec.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, test

#7525 Marked String for Translation in HAML File
  app/views/report/_widget_show.html.haml
Labels: bug, internationalization

#7552 Created a spec that checks all routes for RBAC enforcements
  spec/config/routes.pending.yml
  spec/routes_spec.rb
Labels: test

#7560 [KASPAROV] Adjusted RBAC enforcement checks for Kasparov
  spec/config/routes.pending.yml
Labels: test

#7564 Remove the disablement of the Metrics/LineLength cop from the menu
  app/presenters/menu/default_menu.rb
Labels: developer

#7565 Clean up some false positives from the RBAC specs with extra mocks
  spec/config/routes.pending.yml
  spec/routes_spec.rb
Labels: test

#7481 Rails 6.0
  manageiq-ui-classic.gemspec
  spec/views/ems_container/_form_fields.html.haml_spec.rb
  spec/views/ems_infra/_form_fields.html.haml_spec.rb
  spec/views/host/_form.html.haml_spec.rb
Labels: dependencies

#7572 Added some missing departments into the rubocop overrides
  config/routes.rb
Labels: developer

#7571 [KASPAROV] Clean up some false positives from the RBAC specs with extra mocks
  spec/config/routes.pending.yml
  spec/routes_spec.rb
Labels: test

#7562 Sort MiqWidgetSets according to MiqGroup#dashboard_order in tree
  app/presenters/tree_builder_report_dashboards.rb
Labels: overview/reporting, refactoring, trees

#7546 DDF: fixing the endless render of async dropdowns in provider forms
  app/javascript/components/async-credentials/async-credentials.jsx
Labels: bug, kasparov/no

#7578 Make the RBAC spec's error and false positive messages meaningful
  spec/routes_spec.rb
Labels: kasparov/yes?, test

#7582 Fix the SwiftManager subclass type check in shared_storage_manager_context
  spec/shared/controllers/shared_storage_manager_context.rb
Labels: bug, test

#7558 Split Control Import / Export in to its own controller
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_export_controller.rb
  app/presenters/menu/default_menu.rb
  app/views/miq_policy_export/_export.html.haml
  app/views/miq_policy_export/import.html.haml
  app/views/miq_policy_export/index.html.haml
  config/routes.rb
  spec/config/routes.pending.yml
  spec/controllers/miq_policy_controller_spec.rb
  spec/controllers/miq_policy_export_controller_spec.rb
  spec/routing/miq_policy_export_routing_spec.rb
  spec/routing/miq_policy_routing_spec.rb
Labels: technical debt

#7556 Split policy rsop
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_rsop_controller.rb
  app/helpers/application_helper/page_layouts.rb
  app/presenters/menu/default_menu.rb
  app/views/miq_policy_rsop/_rsop_form.html.haml
  app/views/miq_policy_rsop/_rsop_options.html.haml
  app/views/miq_policy_rsop/_rsop_results.html.haml
  app/views/miq_policy_rsop/index.html.haml
  config/routes.rb
  spec/config/routes.pending.yml
  spec/controllers/miq_policy_controller/rsop_spec.rb
  spec/controllers/miq_policy_controller_spec.rb
  spec/controllers/miq_policy_rsop_controller_spec.rb
  spec/routing/miq_policy_routing_spec.rb
  spec/routing/miq_policy_rsop_routing_spec.rb
Labels: technical debt, unmergeable

#7557 Split policy log
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_log_controller.rb
  app/presenters/menu/default_menu.rb
  app/views/layouts/_log_viewer.html.haml
  app/views/miq_policy_log/index.html.haml
  config/routes.rb
  spec/config/routes.pending.yml
  spec/controllers/miq_policy_controller_spec.rb
  spec/controllers/miq_policy_log_controller_spec.rb
  spec/routing/miq_policy_log_routing_spec.rb
  spec/routing/miq_policy_routing_spec.rb
Labels: technical debt, unmergeable

#7577 Implement show list for Host initiators
  app/controllers/host_initiator_controller.rb
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/host_initiator_helper.rb
  app/helpers/host_initiator_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/host_initiator/show.html.haml
  app/views/host_initiator/show_list.html.haml
  config/routes.rb
  product/views/HostInitiator.yaml
  spec/config/routes.pending.yml
  spec/presenters/menu/default_menu_spec.rb
Labels: enhancement, storage

#7575 [spec] Fix create_user_with_group errors
  spec/controllers/application_controller/compare_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/report_controller_spec.rb
  spec/presenters/tree_builder_report_saved_reports_spec.rb
Labels: bug, test

#7590 Fix missing window.locale, update to json-based po_to_json
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/de/app.js
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/en/app.js
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/es/app.js
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/fr/app.js
  app/javascript/oldjs/locale/index.js
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/it/app.js
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ja/app.js
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/ko/app.js
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/pt_BR/app.js
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_CN/app.js
  app/javascript/oldjs/locale/zh_TW.json
  app/javascript/oldjs/locale/zh_TW/app.js
Labels: bug, internationalization

#7579 fix error in policy condition edit: no include? for nil
  app/controllers/application_controller/filter.rb
  app/controllers/application_controller/filter/expression.rb
  spec/controllers/application_controller/filter/expression_spec.rb
Labels: bug

#7589 Remove the physical infra provider change password feature
  app/controllers/ems_physical_infra_controller.rb
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
  app/javascript/oldjs/components/index.js
  app/javascript/oldjs/components/physical_infrastructures/change-password.js
  app/views/ems_physical_infra/change_password.html.haml
  app/views/static/ems_physical_infra/change_password.html.haml
  config/routes.rb
  spec/javascripts/components/physical_infrastructures/change-password_spec.js
Labels: cleanup, compute/physical infrastructure, kasparov/no

#7588 gtl unSelectAll - fix missing dispatch, call reduceSelectedItem directly
  app/javascript/components/gtl-view.jsx
Labels: bug, gtls

#7458 Marked Strings for Translation in Network -> Providers
  app/presenters/tree_builder_protect.rb
Labels: bug, internationalization

#7586 Adding host_initiators for block-storage-dashboard
  app/helpers/ems_storage_helper/textual_summary.rb
  app/services/ems_storage_dashboard_service.rb
  spec/helpers/ems_storage_helper/textual_summary_spec.rb
Labels: enhancement

#7591 Update manageiq-style
  .codeclimate.yml
Labels: developer

#7594 Fix specs related to widget set factories
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/miq_report_controller/dashboards_spec.rb
  spec/controllers/miq_report_controller/trees_spec.rb
  spec/controllers/report_controller_spec.rb
Labels: bug, test

#7584 Drop the provider discovery feature from the UI
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/actions/host_actions/discover.rb
  app/helpers/application_helper/discover.rb
  app/helpers/application_helper/toolbar/ems_infras_center.rb
  app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
  app/helpers/application_helper/views_shared.rb
  app/views/ems_container/discover.html.haml
  app/views/ems_infra/discover.html.haml
  app/views/ems_physical_infra/discover.html.haml
  app/views/layouts/_discover.html.haml
  app/views/layouts/_discover_credentials.html.haml
  config/routes.rb
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/routing/ems_cloud_routing_spec.rb
  spec/routing/ems_infra_routing_spec.rb
  spec/routing/ems_physical_infra_routing_spec.rb
  spec/routing/host_routing_spec.rb
  spec/routing/shared_examples.rb
  spec/routing/shared_examples/discovery_examples.rb
Labels: cleanup, kasparov/no

#7604 Remove ui plugin dialog-user call
  app/controllers/dashboard_controller.rb
  app/javascript/packs/provider-dialogs-common.js
  config/routes.rb
  spec/config/routes.pending.yml
  spec/controllers/dashboard_controller_spec.rb
Labels: technical debt

#7573 [rails6] Use ActiveSupport::ParameterFilter
  app/controllers/application_controller.rb
Labels: developer, technical debt

#7574 [rails6] Use relative paths for layouts
  app/controllers/application_controller/report_downloads.rb
  spec/controllers/application_controller/compare_spec.rb
  spec/controllers/application_controller/report_downloads_spec.rb
Labels: technical debt

#7533 Prevented Text-Wrapping in Column Titles (CSS)
  app/assets/stylesheets/list_view.scss
  app/javascript/components/gtl/DataTable.jsx
Labels: bug, internationalization

#7601 remove unused scrutinizer yaml and readme badge
  .scrutinizer.yml
  README.md
Labels: developer

#7600 remove unused variables
  app/controllers/catalog_controller.rb
  app/controllers/host_aggregate_controller.rb
  app/controllers/miq_event_controller.rb
  spec/controllers/automation_manager_controller_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/helpers/application_helper/buttons/instance_attach_spec.rb
Labels: cleanup

#7608 print/textual_summary: remove provider_foreman code
  app/views/layouts/print/textual_summary.html.haml
Labels: technical debt

#7609 Dead render partial
  app/views/chargeback_rate/_rates_tabs.html.haml
  app/views/configuration/show.html.haml
  app/views/dashboard/_dropdownbar.html.haml
  app/views/miq_alert/_alert_details.html.haml
  app/views/miq_policy/explorer.html.haml
  app/views/miq_request/_prov_wf.html.haml
  app/views/miq_template/show.html.haml
  app/views/service/_explorer.js.haml
Labels: cleanup
