Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-10, with the labels that each got.

#7876 Convert AuthKey operations to SupportsFeatureMixin
  app/helpers/application_helper/button/auth_key_pair_cloud_create.rb
  spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb
Labels: technical debt

#7862 Added option for delete volume mapping
  app/helpers/application_helper/toolbar/volume_mapping_center.rb
  app/helpers/application_helper/toolbar/volume_mappings_center.rb
Labels: enhancement, morphy/yes?

#7857 Alert Profile Form React Conversion
  app/controllers/miq_alert_set_controller.rb
  app/javascript/components/miq-alert-set-form/helper.js
  app/javascript/components/miq-alert-set-form/index.jsx
  app/javascript/components/miq-alert-set-form/miq-alert-set-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/miq-alert-set-form/__snapshots__/miq-alert-set-form.spec.js.snap
  app/javascript/spec/miq-alert-set-form/miq-alert-set-form.spec.js
  app/stylesheet/ddf_override.scss
  app/views/miq_alert_set/_form.html.haml
  app/views/miq_alert_set/edit.html.haml
  app/views/miq_alert_set/new.html.haml
  spec/controllers/miq_alert_set_controller_spec.rb
Labels: enhancement

#7886 Fix provision screen multi tags assignment
  app/javascript/components/taggingWrapper.jsx
Labels: bug, morphy/yes?

#7882 Convert detach_volume to SupportsFeatureMixin
  app/helpers/application_helper/button/volume_detach.rb
  spec/helpers/application_helper/buttons/volume_detach_spec.rb
Labels: bug, technical debt

#7879 User should not be able to edit Purpose Tags from Service / Request page
  app/controllers/miq_request_controller.rb
  app/javascript/components/taggingWrapper.jsx
  app/javascript/pf-select/pf-select.jsx
  app/javascript/tagging/components/InnerComponents/CategoryModifier.js
  app/javascript/tagging/components/InnerComponents/Tag.js
  app/javascript/tagging/components/InnerComponents/TagCategory.js
  app/javascript/tagging/components/InnerComponents/TagSelector.js
  app/javascript/tagging/components/InnerComponents/TagView.js
  app/javascript/tagging/components/InnerComponents/ValueModifier.js
  app/javascript/tagging/components/InnerComponents/ValueSelector.js
  app/javascript/tagging/components/Tagging/Tagging.js
  app/javascript/tagging/tests/__snapshots__/category.modifier.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.category.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.modifier.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.selector.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tag.view.test.js.snap
  app/javascript/tagging/tests/__snapshots__/tagging.test.js.snap
  app/javascript/tagging/tests/__snapshots__/value.modifier.test.js.snap
  app/javascript/tagging/tests/__snapshots__/value.selector.test.js.snap
  app/views/miq_request/_prov_field.html.haml
  app/views/shared/views/_prov_dialog.html.haml
Labels: bug, unmergeable, morphy/no

#7838 Remove patternfly-sass gems packages and use nodemodules
  app/assets/stylesheets/about_modal_background.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/login.scss
  app/javascript/packs/application-common.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/legacy/about_modal_background.scss
  app/stylesheet/legacy/aggregate_status_card.scss
  app/stylesheet/legacy/alerts.scss
  app/stylesheet/legacy/angular.scss
  app/stylesheet/legacy/codemirror_editor.scss
  app/stylesheet/legacy/compare_drift.scss
  app/stylesheet/legacy/data_driven_forms_overrides.scss
  app/stylesheet/legacy/dialog_fields.scss
  app/stylesheet/legacy/dual_list.scss
  app/stylesheet/legacy/dynamic_prefix_form_input.scss
  app/stylesheet/legacy/fonticon_picker.scss
  app/stylesheet/legacy/icon_customizations.scss
  app/stylesheet/legacy/list_view.scss
  app/stylesheet/legacy/login.scss
  app/stylesheet/legacy/main.scss
  app/stylesheet/legacy/metrics.scss
  app/stylesheet/legacy/miq_tree.scss
  app/stylesheet/legacy/patternfly_overrides.scss
  app/stylesheet/legacy/piecharts.scss
  app/stylesheet/legacy/print.scss
  app/stylesheet/legacy/remote_console.scss
  app/stylesheet/legacy/report-data-table.scss
  app/stylesheet/legacy/report_colors.scss
  app/stylesheet/legacy/timeline.scss
  app/stylesheet/legacy/topology-toolbar.scss
  app/stylesheet/legacy/topology.scss
  app/stylesheet/legacy/variables.scss
  app/stylesheet/quadicon.scss
  app/views/dashboard/oidc_login.html.haml
  app/views/dashboard/saml_login.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/login.html.haml
  app/views/layouts/print.html.haml
  app/views/layouts/remote_console.html.haml
  app/views/layouts/report_only.html.haml
  config/webpack/loaders.js
  config/webpack/shared.js
  lib/manageiq/ui/classic/engine.rb
  manageiq-ui-classic.gemspec
  package.json
  vendor/assets/stylesheets/brand.scss
  yarn.lock
Labels: enhancement, dependencies

#7920 Fixed Retire Form and added time to retire form
  app/javascript/components/retirement-form/helper.js
  app/javascript/components/retirement-form/index.jsx
  app/javascript/components/retirement-form/retirement-form.schema.js
  app/javascript/spec/retirement-form/__snapshots__/retirement-form.spec.js.snap
  app/javascript/spec/retirement-form/retirement-form.spec.js
  app/stylesheet/ddf_override.scss
  app/views/shared/views/_retire.html.haml
  package.json
  yarn.lock
Labels: bug, unmergeable, dependencies
