Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-03, with the labels that each got.

#7640 Moved Configured Systems out of Ansible Tower Explorer
  app/controllers/automation_manager_configured_system_controller.rb
  app/controllers/automation_manager_controller.rb
  app/controllers/mixins/sandbox.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/automation_manager_configured_system_center.rb
  app/helpers/application_helper/toolbar/automation_manager_configured_systems_center.rb
  app/helpers/automation_manager_configured_system_helper.rb
  app/presenters/menu/default_menu.rb
  app/presenters/tree_builder.rb
  app/views/automation_manager_configured_system/show.html.haml
  app/views/automation_manager_configured_system/show_list.html.haml
  config/routes.rb
  spec/config/routes.pending.yml
  spec/controllers/automation_manager_controller_spec.rb
Labels: enhancement, pending core, unmergeable

#7656 Added Margin to the Bottom of React Forms
  app/stylesheet/application-webpack.scss
  app/stylesheet/ddf_override.scss
Labels: lasker/yes?, redesign

#7649 Fix keyboard accessibility for compare and drift screens
  app/assets/stylesheets/patternfly_overrides.scss
  app/controllers/application_controller/compare.rb
  app/helpers/application_helper/listnav.rb
  app/views/layouts/_center_div_with_listnav.html.haml
  app/views/layouts/_compare.html.haml
  app/views/layouts/_content.html.haml
  app/views/layouts/listnav/_compare_sections.html.haml
  spec/helpers/application_helper_spec.rb
Labels: accessibility, bug

#7651 Filter/group by tag in chargeback for container images
  app/views/report/_form_filter_chargeback.html.haml
Labels: enhancement, lasker/yes?

#7659 Update DDF mapper version
  package.json
Labels: bug, dependencies, lasker/yes?

#7646 Rework to not use SupportsFeatureMixin::UnknownFeatureError
  app/helpers/application_helper/button/generic_feature_button_with_disable.rb
  spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb
Labels: refactoring

#7663 Fix checking for blank log contents
  app/controllers/miq_ae_tools_controller.rb
Labels: bug, lasker/yes?

#7618 Fix translation of style column
  app/helpers/report_helper.rb
  app/views/report/_form_styling.html.haml
Labels: bug, internationalization

#7666 Fix placeholder prop console error
  app/javascript/menu/search.jsx
Labels: bug

#7667 Rearranged Configuration/Automation menus
  app/presenters/menu/default_menu.rb
  spec/presenters/tree_builder_ops_rbac_features_spec.rb
Labels: enhancement

#7661 Fix ddf components style issues
  app/stylesheet/ddf_override.scss
Labels: bug, formatting/styling

#7665 Change url_parms to accepts Procs instead of eval of Strings
  app/helpers/application_helper/toolbar/drift_center.rb
  app/helpers/application_helper/toolbar/summary_center.rb
  app/helpers/application_helper/toolbar/summary_center_restful.rb
  app/helpers/application_helper/toolbar_builder.rb
  spec/helpers/application_helper/toolbar_builder_spec.rb
Labels: technical debt

#7668 Translations provided on 2021-03-12
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: enhancement, internationalization, lasker/yes?

#7673 Fix i18n message
  app/helpers/application_helper/button/delete_server.rb
  app/helpers/application_helper/button/role_suspend.rb
Labels: bug, internationalization

#7677 Fixed i18n `n__` call syntax.
  app/javascript/components/breadcrumbs/notifications-toggle.jsx
  app/javascript/components/notification-drawer/helpers.js
Labels: bug

#7676 Add vendor to configured systems and target platform to configuration profiles
  product/views/ConfigurationProfile.yaml
  product/views/ConfiguredSystem.yaml
Labels: enhancement, lasker/yes?

#7622 Rewriting PXE Customization Template Form to React
  app/controllers/pxe_controller.rb
  app/controllers/pxe_controller/pxe_customization_templates.rb
  app/javascript/components/code-editor/index.js
  app/javascript/components/pxe-customization-template-form/index.jsx
  app/javascript/components/pxe-customization-template-form/pxe-customization-template-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/pxe-customization-template-form/__snapshots__/pxe-customization-template-form.spec.js.snap
  app/javascript/spec/pxe-customization-template-form/pxe-customization-template-form.spec.js
  app/views/pxe/_template_details.html.haml
  app/views/pxe/_template_form.html.haml
  config/routes.rb
  spec/controllers/pxe_controller/pxe_customization_templates_spec.rb
  spec/routing/pxe_routing_spec.rb
Labels: refactoring

#7648 Added GUI cross-ref between host-initiator and cloud-volume.
  app/controllers/cloud_volume_controller.rb
  app/controllers/host_initiator_controller.rb
  app/helpers/cloud_volume_helper/textual_summary.rb
  app/helpers/host_initiator_helper/textual_summary.rb
  app/views/cloud_volume/show.html.haml
  app/views/host_initiator/show.html.haml
  spec/helpers/cloud_volume_helper/textual_summary_spec.rb
Labels: enhancement

#7507 Formatted Date and Time for Different Locales
  app/views/catalog/_ot_tree_show.html.haml
  product/views/OrchestrationTemplate.yaml
Labels: enhancement, internationalization

#7681 Revert "Formatted Date and Time for Different Locales"
  app/views/catalog/_ot_tree_show.html.haml
  product/views/OrchestrationTemplate.yaml
Labels: bug

#7670 Move remaining components in react-ui-components to ui-classic
  app/javascript/components/aggregate_status_card.jsx
  app/javascript/components/quadicon/Quadicon.jsx
  app/javascript/components/quadicon/Quaditem.jsx
  app/javascript/components/quadicon/index.js
  app/javascript/components/textual_summary/empty_group.jsx
  app/javascript/components/textual_summary/generic_group.jsx
  app/javascript/components/textual_summary/generic_table_row.jsx
  app/javascript/components/textual_summary/icon_or_image.jsx
  app/javascript/components/textual_summary/index.jsx
  app/javascript/components/textual_summary/multilink_table.jsx
  app/javascript/components/textual_summary/operation_ranges.jsx
  app/javascript/components/textual_summary/simple_table.jsx
  app/javascript/components/textual_summary/table_list_view.jsx
  app/javascript/components/textual_summary/tag_group.jsx
  app/javascript/components/textual_summary/textual_group.jsx
  app/javascript/components/textual_summary/textual_row.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/packs/globals.js
  app/javascript/react/generic_group_wrapper.jsx
  app/javascript/react/table_list_view_wrapper.js
  app/javascript/react/textual_summary_wrapper.jsx
  app/javascript/spec/quadicon/data/quadicons.js
  app/javascript/spec/quadicon/tests/__snapshots__/quadicon.test.js.snap
  app/javascript/spec/quadicon/tests/quadicon.test.js
  app/javascript/spec/textual_summary/data/generic_group.js
  app/javascript/spec/textual_summary/data/multilink_table.js
  app/javascript/spec/textual_summary/data/operation_ranges.js
  app/javascript/spec/textual_summary/data/simple_table.js
  app/javascript/spec/textual_summary/data/table_list_view.js
  app/javascript/spec/textual_summary/data/tag_group.js
  app/javascript/spec/textual_summary/data/textual_summary.js
  app/javascript/spec/textual_summary/tests/__snapshots__/generic_group.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/generic_table_row.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/icon_or_image.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/operation_ranges.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/tag_group.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/textual_summary.test.js.snap
  app/javascript/spec/textual_summary/tests/generic_group.test.js
  app/javascript/spec/textual_summary/tests/generic_table_row.test.js
  app/javascript/spec/textual_summary/tests/icon_or_image.test.js
  app/javascript/spec/textual_summary/tests/multilink_table.test.js
  app/javascript/spec/textual_summary/tests/operation_ranges.test.js
  app/javascript/spec/textual_summary/tests/simple_table.test.js
  app/javascript/spec/textual_summary/tests/table_list_view.test.js
  app/javascript/spec/textual_summary/tests/tag_group.test.js
  app/javascript/spec/textual_summary/tests/textual_summary.test.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/notifications.scss
  app/stylesheet/quadicon.scss
  package.json
Labels: dependencies, lasker/yes?, technical debt

#7684 Fixed policy profile delete button to redirect to show_list.
  app/helpers/application_helper/toolbar/miq_policy_set_center.rb
  app/helpers/application_helper/toolbar/miq_policy_sets_center.rb
Labels: bug, lasker/yes?

#7658 Convert provider charts to carbon
  app/javascript/components/provider-dashboard-charts/charts_config.js
  app/javascript/components/provider-dashboard-charts/emptyChart.js
  app/javascript/components/provider-dashboard-charts/helpers.js
  app/javascript/components/provider-dashboard-charts/pod-trend-charts/index.js
  app/javascript/components/provider-dashboard-charts/pod-trend-charts/podsAreaChart.js
  app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/index.js
  app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationDonutChart.js
  app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationMemoryDonutChart.js
  app/javascript/components/provider-dashboard-charts/recent-host-chart/hostLineChart.js
  app/javascript/components/provider-dashboard-charts/recent-host-chart/index.js
  app/javascript/components/provider-dashboard-charts/recent-vm-chart/index.js
  app/javascript/components/provider-dashboard-charts/recent-vm-chart/vmAreaChart.js
  app/javascript/components/provider-dashboard-charts/servers-pie-chart/index.js
  app/javascript/components/provider-dashboard-charts/servers-pie-chart/serversAvailablePieChart.js
  app/javascript/components/provider-dashboard-charts/servers-pie-chart/serversHealthPieChart.js
  app/javascript/components/provider-dashboard-charts/usage-network-image-charts/index.js
  app/javascript/components/provider-dashboard-charts/usage-network-image-charts/usageAreaChart.js
  app/javascript/oldjs/components/pf_charts/trends-chart.component.js
  app/javascript/oldjs/controllers/ems_infra_dashboard/heatmap_controller.js
  app/javascript/oldjs/controllers/mixins/charts-mixin.js
  app/javascript/packs/component-definitions-common.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/charts.scss
  app/views/ems_cloud/_show_dashboard.html.haml
  app/views/ems_container/_show_dashboard.html.haml
  app/views/ems_infra/_show_dashboard.html.haml
  app/views/ems_physical_infra/_show_dashboard.html.haml
  app/views/physical_infra_overview/show.html.haml
Labels: accessibility, enhancement

#7691 Updated Translations from 2021-03-27
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: internationalization, lasker/yes?
