Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-08, with the labels that each got.

#7806 Fix for miq_set_change for custom button create
  app/controllers/application_controller/buttons.rb
  app/controllers/miq_ae_customization_controller/custom_buttons.rb
Labels: bug

#7807 Revert carbon charts change for fonts issue
  package.json
Labels: dependencies

#7810 Fix charts resizing and remove toolbar
  app/javascript/components/carbon-charts/areaChart.js
  app/javascript/components/carbon-charts/groupChart.js
  app/javascript/components/carbon-charts/groupHorizontalChart.js
  app/javascript/components/carbon-charts/lineChart.js
  app/javascript/components/carbon-charts/stackBarChart.js
  app/javascript/components/carbon-charts/stackHorizontalChart.js
  app/javascript/components/carbon-charts/stackedAreaChart.js
  app/javascript/components/provider-dashboard-charts/charts_config.js
  app/javascript/components/provider-dashboard-charts/pod-trend-charts/podsAreaChart.js
  app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationDonutChart.js
  app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationMemoryDonutChart.js
  app/javascript/components/provider-dashboard-charts/recent-host-chart/hostLineChart.js
  app/javascript/components/provider-dashboard-charts/recent-vm-chart/vmAreaChart.js
  app/javascript/components/provider-dashboard-charts/usage-network-image-charts/usageAreaChart.js
Labels: bug

#7811 Fix Refresh and powerstate of configuration provider
  app/controllers/application_controller/ci_processing.rb
  app/javascript/components/gtl-view.jsx
Labels: bug

#7799 Ability to add custom close function to modal
  app/javascript/packs/provider-dialogs-common.js
  app/javascript/provider-dialogs/modal.js
Labels: enhancement

#7814 Add Different Titles for Alert Page New/Edit
  app/controllers/miq_alert_controller.rb
Labels: bug

#7812 Add Different Title Name for Action Form When Add/Edit
  app/controllers/miq_action_controller.rb
Labels: enhancement

#7820 [LASKER] Fix refresh powerstate action for configuration managers
  app/controllers/application_controller/ci_processing.rb
Labels: bug, lasker/yes?

#7808 Convert policy profiles form react and ddf
  app/controllers/miq_policy_set_controller.rb
  app/javascript/components/policy-profile-form/index.js
  app/javascript/components/policy-profile-form/policy-profile-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/policy-profile-form/__snapshots__/policy-profile-form.spec.js.snap
  app/javascript/spec/policy-profile-form/policy-profile-form.spec.js
  app/stylesheet/ddf_override.scss
  app/views/miq_policy_set/_form.html.haml
  app/views/miq_policy_set/edit.html.haml
  app/views/miq_policy_set/new.html.haml
  app/views/miq_policy_set/show.html.haml
  config/routes.rb
  spec/controllers/miq_policy_set_controller_spec.rb
  spec/routing/miq_policy_set_routing_spec.rb
Labels: enhancement

#7788 Add recordID info to params passed to cloud_volumes api
  app/javascript/components/cloud-volume-form/index.jsx
Labels: bug

#7803 Add status and host_cluster_name to host_initiators table
  product/views/HostInitiator.yaml
Labels: enhancement

#7825 Lockdown execjs to 2.7.0
  manageiq-ui-classic.gemspec
Labels: bug, javascript infrastructure, lasker/yes?

#7822 Added charts toolbar back and updated charts and d3 packages to latest
  app/javascript/components/carbon-charts/areaChart.js
  app/javascript/components/carbon-charts/groupChart.js
  app/javascript/components/carbon-charts/groupHorizontalChart.js
  app/javascript/components/carbon-charts/lineChart.js
  app/javascript/components/carbon-charts/stackBarChart.js
  app/javascript/components/carbon-charts/stackHorizontalChart.js
  app/javascript/components/carbon-charts/stackedAreaChart.js
  app/javascript/components/provider-dashboard-charts/pod-trend-charts/podsAreaChart.js
  app/javascript/components/provider-dashboard-charts/recent-host-chart/hostLineChart.js
  app/javascript/components/provider-dashboard-charts/recent-vm-chart/vmAreaChart.js
  app/javascript/packs/globals.js
  package.json
Labels: bug

#7815 Fix cloud network clear form issue
  app/javascript/components/cloud-network-form/cloud-network-form.jsx
  app/javascript/components/cloud-network-form/cloud-network-form.schema.js
  app/javascript/components/provider-form/index.jsx
  app/javascript/components/subnet-form/index.jsx
  app/javascript/components/subnet-form/subnet-form.schema.js
  app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
  app/javascript/spec/cloud-network-form/cloud-network-form.spec.js
  app/javascript/spec/subnet-form/__snapshots__/subnet-form.spec.js.snap
  app/stylesheet/ddf_override.scss
Labels: bug

#7826 Refactor ApplicationHelper#records_support_feature? method
  app/helpers/application_helper.rb
Labels: refactoring

#7817 added columns and props for health state of cloud volume
  app/helpers/cloud_volume_helper/textual_summary.rb
  product/views/CloudVolume.yaml
  spec/helpers/cloud_volume_helper/textual_summary_spec.rb
Labels: enhancement

#7827 Remove unused ApplicationHelper#type_has_quadicon method
  app/helpers/application_helper.rb
Labels: technical debt

#7832 Fix subnet form issue
  app/javascript/components/subnet-form/subnet-form.schema.js
Labels: bug

#7834 No more coffee (gem) for rails
  lib/manageiq/ui/classic/engine.rb
  manageiq-ui-classic.gemspec
Labels: technical debt

#7828 Trim ApplicationController::CiProcessing#testable_action method
  app/controllers/application_controller/ci_processing.rb
  spec/controllers/application_controller/ci_processing_spec.rb
Labels: technical debt

#7821 Fix IBM storageManager id for Cloud Volume Form
  app/controllers/mixins/ems_common.rb
Labels: bug

#7830 Simplified logic in ApplicationController#task_supported method to *always* use SupportsFeatureMixin
  app/controllers/application_controller.rb
Labels: technical debt

#7654 Ensured Related Dialog Fields are Synchronized when Adding a New OVF Service Template
  app/controllers/catalog_controller.rb
  app/views/catalog/_form_ovf_template_options.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
  spec/controllers/catalog_controller_spec.rb
Labels: enhancement

#7835 Latest uglifier, 4.2.0 prevents runtime uglifier asset compilation
  manageiq-ui-classic.gemspec
Labels: enhancement, dependencies, javascript infrastructure, changelog/no

#7793 Action Form React Conversion
  app/controllers/miq_action_controller.rb
  app/javascript/components/action-form/action-form.schema.js
  app/javascript/components/action-form/helper.js
  app/javascript/components/action-form/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
  app/javascript/spec/action-form/action-form.spec.js
  app/stylesheet/ddf_override.scss
  app/views/miq_action/_action_options.html.haml
  app/views/miq_action/_form.html.haml
  app/views/miq_action/edit.html.haml
  app/views/miq_action/new.html.haml
  spec/controllers/miq_action_controller_spec.rb
Labels: enhancement

#7652 Rewriting PXE ISO Datastore/Image Forms to React
  app/controllers/pxe_controller.rb
  app/controllers/pxe_controller/iso_datastores.rb
  app/controllers/pxe_controller/pxe_servers.rb
  app/javascript/components/pxe-customization-template-form/pxe-customization-template-form.schema.js
  app/javascript/components/pxe-image-type-form/pxe-image-type-form.schema.js
  app/javascript/components/pxe-iso-datastore-form/index.jsx
  app/javascript/components/pxe-iso-datastore-form/pxe-iso-datastore-form.schema.js
  app/javascript/components/pxe-iso-image-form/index.jsx
  app/javascript/components/pxe-iso-image-form/pxe-iso-image-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/pxe-customization-template-form/__snapshots__/pxe-customization-template-form.spec.js.snap
  app/javascript/spec/pxe-customization-template-form/pxe-customization-template-form.spec.js
  app/javascript/spec/pxe-image-type-form/__snapshots__/pxe-image-type-form.spec.js.snap
  app/javascript/spec/pxe-image-type-form/pxe-image-type-form.spec.js
  app/javascript/spec/pxe-iso-datastore-form/__snapshots__/pxe-iso-datastore-form.spec.js.snap
  app/javascript/spec/pxe-iso-datastore-form/pxe-iso-datastore-form.spec.js
  app/javascript/spec/pxe-iso-image-form/__snapshots__/pxe-iso-image-form.spec.js.snap
  app/javascript/spec/pxe-iso-image-form/pxe-iso-image-form.spec.js
  app/views/pxe/_iso_datastore_details.html.haml
  app/views/pxe/_iso_datastore_form.html.haml
  app/views/pxe/_iso_img_form.html.haml
  config/routes.rb
  spec/controllers/pxe_controller/iso_datastores_spec.rb
  spec/routing/pxe_routing_spec.rb
Labels: enhancement

#7833 Fix Chargeback assignments compute page translations.
  app/views/chargeback_assignment/_compute_assignments.html.haml
Labels: bug, lasker/yes?
