Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-04, with the labels that each got.

#7696 Fix breadcrumb for Add /Edit policies and policy profiles
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_set_controller.rb
Labels: bug

#7697 Fix testcases and breadcrumb for policies
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_set_controller.rb
  spec/controllers/miq_policy_controller_spec.rb
  spec/controllers/miq_policy_set_controller_spec.rb
Labels: bug

#7698 Fix settings--> tasks table rows
  app/controllers/application_controller.rb
  app/controllers/miq_task_controller.rb
  app/helpers/application_helper.rb
  app/javascript/components/gtl/DataTable.jsx
  app/stylesheet/application-webpack.scss
  app/stylesheet/data-table.scss
Labels: bug

#7690 Modified "My Settings" to Prevent Invalid Argument Error
  app/javascript/components/visual-settings-form/index.jsx
  app/javascript/components/visual-settings-form/visual-settings-form.schema.js
Labels: bug

#7699 Updated Translations from 2021-04-03
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
Labels: internationalization, lasker/yes?

#7702 Handle incoming numerics for id that are bigger than a bigint
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
Labels: bug

#7700 Translated Strings in Control->Policy
  app/views/miq_policy/_form.html.haml
Labels: bug

#7703 Fix chargeback report tag and group by tag bug
  app/controllers/report_controller/reports/editor.rb
Labels: bug

#7704 Modified CSS to Prevent Text Wrapping in Certain Locales
  app/assets/stylesheets/patternfly_overrides.scss
  app/views/report/_form.html.haml
  app/views/report/_form_chart.html.haml
  app/views/report/_form_columns.html.haml
  app/views/report/_form_consolidate.html.haml
  app/views/report/_form_filter.html.haml
  app/views/report/_form_formatting.html.haml
  app/views/report/_form_sort.html.haml
Labels: bug, internationalization

#7708 Changed "Created New Network Router" Dialog
  app/controllers/network_router_controller.rb
Labels: bug

#7707 Fix Attach Cloud Volume form
  app/javascript/oldjs/controllers/cloud_volume/cloud_volume_form_controller.js
Labels: bug, lasker/yes?

#7701 change notification drawer to carbon and fix A11y
  app/javascript/components/breadcrumbs/notifications-toggle.jsx
  app/javascript/components/notification-drawer/helpers.js
  app/javascript/components/notification-drawer/notification-drawer.jsx
  app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
  app/javascript/spec/notification-drawer/__snapshots__/notification-drawer.spec.js.snap
  app/javascript/spec/notification-drawer/notification-drawer.spec.js
  app/stylesheet/notifications.scss
  app/views/layouts/_header.html.haml
  app/views/layouts/_searchbar.html.haml
Labels: accessibility, enhancement

#7705 Fix provision instance table and deprecated checkbox
  app/controllers/application_controller/miq_request_methods.rb
  app/controllers/application_controller/report_data_additional_options.rb
  app/javascript/components/gtl-view.jsx
  app/javascript/components/gtl/DataTable.jsx
  app/javascript/components/gtl/StaticGTLView.jsx
Labels: bug, lasker/yes?

#7714 Fix edit cloud volume api call and pass record id
  app/javascript/components/cloud-volume-form/index.jsx
Labels: lasker/yes?

#7715 Replace CloudVolume#validate_update_volume with supports?(:update)
  app/controllers/cloud_volume_controller.rb
Labels: refactoring, technical debt

#7716 Updated Carbon Component Mapper
  package.json
Labels: dependencies, lasker/yes?

#7717 [LASKER] yarn: lock versions by adding yarn.lock in lasker
  .gitignore
  yarn.lock
Labels: dependencies

#7720 Handle Unicode characters in httpd auth headers
  app/controllers/dashboard_controller.rb
  spec/controllers/dashboard_controller_spec.rb
Labels: bug, lasker/yes?

#7722 Convert cloud tenant charts to carbon
  app/views/cloud_tenant/_show_dashboard.html.haml
Labels: enhancement

#7724 Delete stale provider dashboard (pattern fly) charts code.
  app/javascript/components/provider-dashboard-charts/usage-network-image-charts/index.js
  app/javascript/oldjs/components/index.js
  app/javascript/oldjs/components/pf_charts/donut-chart.component.js
  app/javascript/oldjs/components/pf_charts/donut-pct-chart.component.js
  app/javascript/oldjs/components/pf_charts/group-chart.component.js
  app/javascript/oldjs/components/pf_charts/line-chart.component.js
  app/javascript/oldjs/components/pf_charts/pie-chart.component.js
  app/javascript/oldjs/components/pf_charts/sparkline-chart.component.js
  app/javascript/oldjs/components/pf_charts/trends-chart.component.js
  app/javascript/oldjs/components/pf_charts/utilization-trend-chart.component.js
  app/javascript/oldjs/components/recent-resource.js
  app/javascript/oldjs/controllers/ems_container_dashboard/recent_images_line_chart_controller.js
  app/javascript/oldjs/controllers/ems_container_dashboard/recent_pods_line_chart_controller.js
  app/javascript/oldjs/controllers/ems_container_dashboard/trends_chart_controller.js
  app/javascript/oldjs/controllers/ems_container_dashboard/utilization_trend_chart_controller.js
  app/javascript/oldjs/controllers/ems_infra_dashboard/utilization_trend_chart_controller.js
  app/javascript/oldjs/controllers/ems_physical_infra_dashboard/recent_servers_line_chart_controller.js
  app/javascript/oldjs/controllers/ems_physical_infra_dashboard/server_health_pie_chart_controller.js
  app/javascript/oldjs/controllers/index.js
  app/views/cloud_tenant/_recent-images-line-chart.html.haml
  app/views/cloud_tenant/_recent-instances-line-chart.html.haml
  app/views/ems_cloud/_recent-images-line-chart.html.haml
  app/views/ems_cloud/_recent-instances-line-chart.html.haml
  app/views/ems_container/_recent-images-line-chart.html.haml
  app/views/ems_container/_recent-pods-line-chart.html.haml
  app/views/ems_container/_trends-chart.html.haml
  app/views/ems_container/_utilization-trend-chart.html.haml
  app/views/ems_infra/_recent-hosts-line-chart.html.haml
  app/views/ems_infra/_recent-vms-line-chart.html.haml
  app/views/ems_infra/_utilization-trend-chart.html.haml
  app/views/ems_physical_infra/_donut-pct-chart.html.haml
  app/views/static/ems_physical_infra/group-chart.html.haml
  app/views/static/ems_physical_infra/recent-servers-line-chart.html.haml
  app/views/static/pf_charts/donut-chart.html.haml
  app/views/static/pf_charts/donut-pct-chart.html.haml
  app/views/static/pf_charts/group-chart.html.haml
  app/views/static/pf_charts/line-chart.html.haml
  app/views/static/pf_charts/sparkline-chart.html.haml
  app/views/static/pf_charts/trends-chart.html.haml
  app/views/static/pf_charts/utilization-trend-chart.html.haml
  spec/javascripts/controllers/ems_physical_infra/server_health_pie_chart_spec.js
Labels: technical debt

#7650 [ops_controller/settings/zones.rb] Soft delete auth
  app/controllers/ops_controller/settings/zones.rb
  app/views/ops/_zone_form.html.haml
  spec/controllers/ops_controller/settings/zones_spec.rb
Labels: technical debt
