Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-07, with the labels that each got.

#7778 fix host-initiator form
  app/javascript/components/host-initiator-form/host-initiator-form.schema.js
Labels: bug, storage

#7779 fix broken breadcrumb url for physical_storage
  config/routes.rb
  spec/config/routes.pending.yml
Labels: bug, storage

#7761 Time profile form conversion
  app/controllers/configuration_controller.rb
  app/javascript/components/settings-time-profile-form/helper.js
  app/javascript/components/settings-time-profile-form/index.jsx
  app/javascript/components/settings-time-profile-form/settings-time-profile-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/settings-time-profile-form/__snapshots__/settings-time-profile-form.spec.js.snap
  app/javascript/spec/settings-time-profile-form/settings-time-profile-form.spec.js
  app/stylesheet/ddf_override.scss
  app/views/configuration/_timeprofile_days_hours.html.haml
  app/views/configuration/_timeprofile_form.html.haml
  app/views/configuration/show.html.haml
  app/views/configuration/timeprofile_edit.html.haml
  config/routes.rb
  spec/routing/configuration_routing_spec.rb
Labels: dependencies

#7780 Fix Action Form Delete Button
  app/javascript/components/remove-generic-item-modal.jsx
Labels: bug

#7767 Fix rows selection across multiple pages in table view
  app/controllers/application_controller.rb
  app/controllers/application_controller/ci_processing.rb
  app/controllers/application_controller/report_data_additional_options.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/javascript/components/gtl-view.jsx
  app/javascript/components/gtl/DataTable.jsx
  app/javascript/oldjs/miq_application.js
Labels: bug

#7783 Show Secondary Data for Run Ansible Playbook Action
  app/controllers/miq_action_controller.rb
  app/views/miq_action/show.html.haml
Labels: bug

#7785 Fix validation error message display in providers screen
  app/javascript/forms/helper-text-block.jsx
  app/javascript/spec/async-credentials/async-credentials.spec.js
Labels: bug

#7777 Rename Flavors cpus -> total_cpu_cores and add cpu_sockets
  app/helpers/flavor_helper/textual_summary.rb
  spec/helpers/flavor_helper/textual_summary_spec.rb
Labels: refactoring

#7786 [KASPAROV] Reverting ES6 fixes to fix test cases in kasparov branch
  app/assets/javascripts/controllers/buttons/button_group_controller.js
  app/javascript/components/tree-view/redux.jsx
Labels: refactoring

#7781 Add operating system and background icon for powerstate in vms table
  app/javascript/components/gtl/DataTable.jsx
  lib/gtl_formatter.rb
  product/views/ManageIQ_Providers_InfraManager_Template.yaml
  product/views/ManageIQ_Providers_InfraManager_Vm.yaml
  product/views/VmOrTemplate.yaml
  spec/controllers/application_controller/report_data_spec.rb
Labels: enhancement

#7769 [widget_generate_content_spec.rb] Fix let(:record)
  spec/helpers/application_helper/buttons/widget_generate_content_spec.rb
Labels: test

#7789 Resolving nil UI exception
  app/helpers/configuration_script_helper.rb
  app/views/configuration_script/show.html.haml
Labels: automation/ansible tower, bug

#7790 Add dom-to-image package for carbon charts
  app/stylesheet/charts.scss
  package.json
Labels: bug, dependencies

#7794 Remove dom-to-image package and fix charts css
  app/stylesheet/charts.scss
  package.json
Labels: bug, dependencies

#7797 Remove storage manager view
  product/views/StorageManager.yaml
Labels: storage, technical debt

#7801 Fixed error message persists across customization explorer modules
  app/controllers/miq_ae_customization_controller.rb
Labels: bug

#7802 Various refactorings to handle brakeman issues
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_ae_customization_controller/old_dialogs.rb
  app/controllers/ops_controller/ops_rbac.rb
Labels: lasker/yes?, refactoring

#7804 Lock carbon charts version to fix fonts issue
  package.json
Labels: bug, dependencies

#7798 Moved fields for add cloud network to provider repo
  app/javascript/components/cloud-network-form/cloud-network-form.jsx
  app/javascript/components/cloud-network-form/cloud-network-form.schema.js
  app/javascript/helpers/network-providers.js
  app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
  app/javascript/spec/cloud-network-form/cloud-network-form.spec.js
Labels: bug, dependencies
