Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-11, with the labels that each got.

#7937 Prefer math.div over / for division due to deprecation
  app/stylesheet/quadicon.scss
Labels: refactoring

#7916 Deleting Code For Rename VM
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/actions/vm_actions/rename.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper/toolbar/vm_infras_center.rb
  config/routes.rb
  spec/controllers/resource_pool_controller_spec.rb
Labels: bug, technical debt

#7939 fix lint errors in scss files
  app/javascript/tagging/sass/_tag.scss
  app/stylesheet/application-webpack.scss
  app/stylesheet/breadcrumbs.scss
  app/stylesheet/button-group.scss
  app/stylesheet/carbon.scss
  app/stylesheet/charts.scss
  app/stylesheet/data-table.scss
  app/stylesheet/ddf_override.scss
  app/stylesheet/legacy/about_modal_background.scss
  app/stylesheet/legacy/alerts.scss
  app/stylesheet/legacy/codemirror_editor.scss
  app/stylesheet/legacy/compare_drift.scss
  app/stylesheet/legacy/data_driven_forms_overrides.scss
  app/stylesheet/legacy/dual_list.scss
  app/stylesheet/legacy/dynamic_prefix_form_input.scss
  app/stylesheet/legacy/fonticon_picker.scss
  app/stylesheet/legacy/icon_customizations.scss
  app/stylesheet/legacy/login.scss
  app/stylesheet/legacy/main.scss
  app/stylesheet/legacy/miq_tree.scss
  app/stylesheet/legacy/patternfly_overrides.scss
  app/stylesheet/legacy/piecharts.scss
  app/stylesheet/legacy/print.scss
  app/stylesheet/legacy/topology.scss
  app/stylesheet/legacy/variables.scss
  app/stylesheet/menu-colors.scss
  app/stylesheet/menu.scss
  app/stylesheet/notifications.scss
  app/stylesheet/quadicon.scss
  app/stylesheet/toolbar.scss
  app/stylesheet/tree.scss
Labels: refactoring

#7938 Fix issue allowing users to select previous dates on retire form
  app/javascript/components/retirement-form/helper.js
  app/javascript/components/retirement-form/index.jsx
  app/javascript/components/retirement-form/retirement-form.schema.js
  app/stylesheet/ddf_override.scss
Labels: bug

#7942 Fix duplication issues in style sheets
  app/stylesheet/legacy/topology.scss
  app/stylesheet/notifications.scss
  app/stylesheet/toolbar.scss
Labels: cleanup

#7944 Made retire form error string more informative
  app/javascript/components/retirement-form/retirement-form.schema.js
Labels: bug, enhancement

#7945 Fixed bug with removing retirement date for multiple instances
  app/javascript/components/retirement-form/index.jsx
Labels: bug

#7943 Delete DatabaseBackup related views
  app/controllers/ops_controller/diagnostics.rb
  app/controllers/ops_controller/settings/schedules.rb
  app/javascript/oldjs/components/ops/log-collection-form.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/ops/diagnostics_database_form_controller.js
  app/javascript/oldjs/controllers/schedule/schedule_form_controller.js
  app/javascript/oldjs/services/index.js
  app/javascript/oldjs/services/miq_db_backup_service.js
  app/views/ops/_diagnostics_database_tab.html.haml
  app/views/ops/_schedule_form_filter.html.haml
  app/views/ops/_schedule_show.html.haml
  app/views/static/ops/log_collection/log_collection.html.haml
  config/routes.rb
  spec/controllers/ops_controller_spec.rb
  spec/javascripts/components/ops/log_collection_form_spec.js
  spec/javascripts/controllers/ops/diagnostics_database_form_controller_spec.js
  spec/javascripts/controllers/schedule/schedule_form_controller_spec.js
  spec/routing/ops_routing_spec.rb
Labels: technical debt

#7941 Add stylelint-scss
  .stylelintrc
  package.json
  yarn.lock
Labels: dependencies

#7952 Update Jquery-ui version
  package.json
  yarn.lock
Labels: enhancement, dependencies

#7859 Converted network routers form to react
  app/controllers/network_router_controller.rb
  app/javascript/components/routers-form/RoutersForm.schema.js
  app/javascript/components/routers-form/index.jsx
  app/javascript/oldjs/controllers/network_router/network_router_form_controller.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/network-router-form/__snapshots__/network-router-form.spec.js.snap
  app/javascript/spec/network-router-form/network-router-form.spec.js
  app/views/network_router/_common_new_edit.haml
  config/routes.rb
  spec/controllers/network_router_controller_spec.rb
  spec/javascripts/controllers/network/network_router_form_controller_spec.js
Labels: enhancement

#7922 remove cockpit
  app/controllers/container_node_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/vm_remote.rb
  app/helpers/application_helper/button/cockpit_console.rb
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  app/helpers/application_helper/toolbar/container_node_center.rb
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/javascript/spec/toolbar/data/toolbar-big.json
  config/routes.rb
  spec/config/routes.pending.yml
  spec/helpers/application_helper/buttons/cockpit_console_spec.rb
Labels: technical debt

#7956 Fixed generic objects form submit bug
  app/javascript/components/generic-objects-form/helper.js
  app/javascript/components/generic-objects-form/index.jsx
Labels: bug

#7954 Use standard CRUD features for AuthKeyPair and HostAggregate
  app/controllers/host_aggregate_controller.rb
  app/helpers/application_helper/button/auth_key_pair_cloud_create.rb
  app/helpers/application_helper/button/new_host_aggregate.rb
  app/helpers/application_helper/toolbar/host_aggregate_center.rb
  spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb
Labels: refactoring

#7959 Rename supported_subclasses to permitted_subclasses
  app/controllers/cloud_object_store_container_controller.rb
Labels: refactoring

#7963 Remove unnecessary caller to VMDBLogger#filename
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/diagnostics.rb
Labels: bug, technical debt

#7965 Replace VMDBLogger#contents with Vmdb::Loggers.contents
  app/controllers/miq_ae_tools_controller.rb
  app/controllers/miq_policy_log_controller.rb
  app/controllers/ops_controller/diagnostics.rb
Labels: refactoring

#7947 Removed tabs for utilization and timelines in server diagnostics
  app/controllers/application_controller/timelines.rb
  app/controllers/ops_controller/diagnostics.rb
  app/views/layouts/_tl_options.html.haml
  app/views/ops/_all_tabs.html.haml
  app/views/ops/_diagnostics_timelines_tab.html.haml
  app/views/ops/_diagnostics_utilization_tab.html.haml
  app/views/ops/_logs_selected.html.haml
  spec/views/ops/_all_tabs.html.haml_spec.rb
Labels: cleanup

#7964 Fix vms table os column image
  lib/gtl_formatter.rb
Labels: bug

#7966 Fix hosts network page tree view
  app/controllers/host_controller.rb
Labels: bug

#7893 Data Table conversion from Patternfly to Carbon
  app/javascript/.eslintrc.json
  app/javascript/components/data-tables/button-group-list/helper.js
  app/javascript/components/data-tables/button-group-list/index.jsx
  app/javascript/components/data-tables/button-list/helper.js
  app/javascript/components/data-tables/button-list/index.jsx
  app/javascript/components/data-tables/gtl/DataTable.jsx
  app/javascript/components/data-tables/gtl/StaticGTLView.jsx
  app/javascript/components/data-tables/gtl/data/gtl-small.json
  app/javascript/components/data-tables/gtl/index.js
  app/javascript/components/data-tables/gtl/utils.js
  app/javascript/components/data-tables/object-types-list/helper.js
  app/javascript/components/data-tables/object-types-list/index.jsx
  app/javascript/components/data-tables/optimization/helper.js
  app/javascript/components/data-tables/optimization/listen.js
  app/javascript/components/data-tables/optimization/optimization_list.js
  app/javascript/components/data-tables/optimization/refresh.js
  app/javascript/components/data-tables/optimization/transform.js
  app/javascript/components/data-tables/reports/ReportList.jsx
  app/javascript/components/data-tables/reports/helper.js
  app/javascript/components/gtl-view.jsx
  app/javascript/components/gtl/DataTable.jsx
  app/javascript/components/miq-data-table/helper.js
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/components/miq-pagination.jsx
  app/javascript/oldjs/miq_list_grid.js
  app/javascript/optimization/optimization_list.js
  app/javascript/packs/application-common.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/miq-data-table/__snapshots__/miq-data-table.spec.js.snap
  app/javascript/spec/miq-data-table/data.js
  app/javascript/spec/miq-data-table/miq-data-table.spec.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/miq-data-table.scss
  app/views/optimization/show_list.html.haml
  app/views/report/_report_list.html.haml
  app/views/shared/buttons/_ab_list.html.haml
  spec/views/report/_report_list.html.haml_spec.rb
  yarn.lock
Labels: enhancement

#7891 Search bar conversion
  app/javascript/components/search-bar/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/search-bar/__snapshots__/search-bar.spec.js.snap
  app/javascript/spec/search-bar/search-bar.spec.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/search-bar.scss
  app/views/layouts/_searchbar.html.haml
  app/views/layouts/_x_adv_searchbox.html.haml
  spec/views/layouts/_center_div_no_listnav.html.haml_spec.rb
  spec/views/layouts/_searchbar.html.haml_spec.rb
Labels: enhancement

#7968 Remove search from forms
  app/views/layouts/_searchbar.html.haml
Labels: bug

#7953 Add filter dropdown to replace left side filter section in non explorer screens.
  app/controllers/application_controller/filter.rb
  app/javascript/components/filter-dropdown/index.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/filter-dropdown/__snapshots__/filter-dropdown.spec.js.snap
  app/javascript/spec/filter-dropdown/filter-dropdown.spec.js
  app/stylesheet/data-table.scss
  app/views/layouts/_center_div_with_listnav.html.haml
  spec/controllers/application_controller/filter_spec.rb
  spec/controllers/cloud_volume_controller_spec.rb
  spec/controllers/ems_cloud_controller_spec.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/floating_ip_controller_spec.rb
  spec/controllers/host_controller_spec.rb
  spec/shared/controllers/shared_example_for_set_default_in_search.rb
Labels: enhancement

#7971 Fix generic objects view filter
  app/views/layouts/_center_div_with_listnav.html.haml
Labels: bug

#7972 Use the group_levels method since the constant was removed
  app/controllers/application_controller/timelines/options.rb
Labels: bug

#7975 drop role_allows helper
  app/helpers/application_helper.rb
  app/helpers/orchestration_stack_helper/textual_summary.rb
Labels: refactoring

#7955 Convert orchestration stack copy to carbon react
  app/javascript/components/orchestration-template/orcherstration-template-form.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/orchestration_template/orchestration_template_copy_controller.js
  app/javascript/spec/orchestration-template/__snapshots__/orchestration-template-form.spec.js.snap
  app/javascript/spec/orchestration-template/orchestration-template-form.spec.js
  app/views/orchestration_stack/_copy_orchestration_template.html.haml
  spec/controllers/orchestration_stack_controller_spec.rb
  spec/javascripts/controllers/orchestration_template/orchestration_template_copy_controller_spec.js
Labels: enhancement

#7973 Remove patternfly-react references in button form and test files.
  app/javascript/components/fonticon-picker/index.jsx
  app/javascript/spec/async-credentials/edit-password-field.spec.js
Labels: enhancement

#7958 Use `.providers_supporting` from SupportsFeatureMixin
  app/controllers/host_aggregate_controller.rb
  app/helpers/application_helper/button/auth_key_pair_cloud_create.rb
  app/helpers/application_helper/button/new_host_aggregate.rb
Labels: refactoring

#7949 KWArgs Role
  app/controllers/ops_controller/ops_rbac.rb
  app/helpers/application_helper.rb
  spec/helpers/application_helper/buttons/catalog_item_button_spec.rb
Labels: rbac, ruby3
