Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2021-05, with the labels that each got.

#7726 Monitor > alerts > all alert bug fixed
  app/javascript/oldjs/services/alerts_center_service.js
Labels: bug

#7729 Fix not yet renamed chargeback_rates features
  app/controllers/chargeback_rate_controller.rb
  spec/controllers/chargeback_rate_controller_spec.rb
Labels: bug, overview/chargeback

#7732 Fix background color of navbar items on hover
  app/stylesheet/menu.scss
Labels: bug

#7719 Add last refresh status for provider dashboards
  app/controllers/container_dashboard_controller.rb
  app/helpers/textual_mixins/textual_refresh_status.rb
  app/javascript/components/aggregate_status_card.jsx
  app/javascript/components/refresh-data-notification.jsx
  app/javascript/components/refresh-notifications.jsx
  app/javascript/packs/component-definitions-common.js
  app/services/container_dashboard_service.rb
  app/services/ems_cloud_dashboard_service.rb
  app/services/ems_dashboard_service.rb
  app/services/ems_infra_dashboard_service.rb
  app/services/ems_physical_infra_dashboard_service.rb
  app/services/ems_storage_dashboard_service.rb
  app/stylesheet/notifications.scss
  app/views/ems_container/_show_dashboard.html.haml
  config/routes.rb
Labels: enhancement

#7725 Handle queue workers inheriting values from worker_base: fix incorrect count and memory threshold values on workers tab
  app/javascript/components/workers-form/workers-form.jsx
  app/javascript/spec/workers-form/workers-form.spec.js
Labels: bug, lasker/yes?, settings

#7733 Fix tenants tree in Edit catalog item
  app/javascript/components/tree-view/redux.jsx
  app/javascript/oldjs/controllers/buttons/button_group_controller.js
  app/views/layouts/angular/_x_edit_buttons_angular.html.haml
Labels: bug

#7736 Fix invalid feature in spec
  spec/controllers/miq_alert_controller_spec.rb
Labels: bug, test

#7737 Fix right hand side title when search text present
  app/controllers/application_controller.rb
  app/controllers/infra_networking_controller.rb
  app/controllers/storage_controller.rb
  app/controllers/vm_common.rb
Labels: bug

#7741 Fixed bug of description appearing instead of name in category creation success message
  app/controllers/ops_controller/settings/tags.rb
Labels: bug

#7739 Convert the vm-common-rename-form to React
  app/controllers/mixins/actions/vm_actions/rename.rb
  app/controllers/vm_common.rb
  app/javascript/components/vm-common-rename-form/index.jsx
  app/javascript/components/vm-common-rename-form/vm-common-rename-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/vm-common-rename-form/__snapshots__/vm-common-rename-form.spec.js.snap
  app/javascript/spec/vm-common-rename-form/vm-common-rename-form.spec.js
  app/views/vm_common/_rename.html.haml
  config/routes.rb
  spec/controllers/mixins/actions/vm_actions/rename_spec.rb
Labels: enhancement

#7734 Convert the subnet form to DDF
  app/controllers/cloud_subnet_controller.rb
  app/javascript/components/subnet-form/index.jsx
  app/javascript/components/subnet-form/subnet-form.schema.js
  app/javascript/oldjs/components/cloud_subnet/cloud-subnet-form.js
  app/javascript/oldjs/components/index.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/subnet-form/__snapshots__/subnet-form.spec.js.snap
  app/javascript/spec/subnet-form/subnet-form.spec.js
  app/views/cloud_subnet/edit.html.haml
  app/views/cloud_subnet/new.html.haml
  app/views/static/cloud_subnet/cloud-subnet-form.html.haml
  config/routes.rb
  package.json
  spec/controllers/cloud_subnet_controller_spec.rb
  spec/javascripts/components/cloud_subnet/cloud_subnet_form_spec.js
Labels: dependencies

#7743 Fixed download buttons for automation-configured systems
  config/routes.rb
Labels: bug

#7740 Fix broken privilege assertions - raise errors in non-production on future broken feature assertions
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/miq_policy_controller/events.rb
  app/controllers/miq_policy_controller/policies.rb
  app/controllers/miq_policy_set_controller.rb
  app/controllers/pxe_controller/iso_datastores.rb
  app/controllers/security_policy_rule_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/miq_action_modify.rb
  app/helpers/application_helper/toolbar/miq_policy_center.rb
  app/helpers/application_helper/toolbar/saved_reports_center.rb
  app/presenters/menu/default_menu.rb
  spec/config/routes.pending.yml
  spec/controllers/ems_storage_controller_spec.rb
  spec/controllers/miq_ae_customization_controller_spec.rb
  spec/controllers/miq_alert_controller_spec.rb
  spec/controllers/miq_report_controller/dashboards_spec.rb
  spec/controllers/pxe_controller_spec.rb
  spec/controllers/vm_common_spec.rb
  spec/routes_spec.rb
Labels: bug, dependencies

#7744 Notification should not display when last refresh data is unavailable
  app/javascript/components/aggregate_status_card.jsx
Labels: bug

#7735 Convert Add/Edit Zone Form to React
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/settings/zones.rb
  app/javascript/components/zone-form/index.jsx
  app/javascript/components/zone-form/zone-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
  app/javascript/spec/zone-form/zone-form.spec.js
  app/views/ops/_settings_evm_servers_tab.html.haml
  app/views/ops/_zone_form.html.haml
  config/routes.rb
  spec/controllers/ops_controller/settings/zones_spec.rb
  spec/controllers/ops_settings_spec.rb
  spec/routing/ops_routing_spec.rb
  spec/views/ops/_zone_form.html.haml_spec.rb
Labels: enhancement

#7747 Fixed the missing information for volume info icon
  app/views/miq_request/_prov_dialog_volume_fieldset.html.haml
Labels: bug

#7748 Fix BG color of react form when opened from dashboard view.
  app/views/layouts/_center_div_no_listnav.html.haml
Labels: bug

#7749 Fixed missing request page buttons
  app/controllers/miq_request_controller.rb
Labels: bug

#7750 Fix console error in tenant dashboard
  app/javascript/components/aggregate_status_card.jsx
Labels: bug

#7738 Convert new/edit host-aggregate form to react.
  app/controllers/host_aggregate_controller.rb
  app/javascript/components/host-aggregate-form/host-aggregate-form.schema.js
  app/javascript/components/host-aggregate-form/index.jsx
  app/javascript/oldjs/controllers/host_aggregate/host_aggregate_form_controller.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/host-aggregate-form/__snapshots__/host-aggregate-form.spec.js.snap
  app/javascript/spec/host-aggregate-form/host-aggregate-form.spec.js
  app/views/host_aggregate/add_host_select.html.haml
  app/views/host_aggregate/edit.html.haml
  app/views/host_aggregate/new.html.haml
  app/views/host_aggregate/remove_host_select.html.haml
  app/views/layouts/angular/_x_custom_form_buttons_angular.html.haml
  spec/controllers/host_aggregate_controller_spec.rb
Labels: enhancement
