Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2022-08, with the labels that each got.

#8373 timeline feature for physical storage
  app/controllers/physical_storage_controller.rb
  app/helpers/application_helper/toolbar/physical_storage_center.rb
  config/routes.rb
  spec/config/routes.pending.yml
Labels: enhancement, compute/physical infrastructure

#8389 Set ems storage "Region" label to provider_region
  app/helpers/ems_storage_helper/textual_summary.rb
Labels: bug

#8392 Remove byebug require
  app/controllers/mixins/actions/vm_actions/ownership.rb
Labels: technical debt

#8377 Set clone request_type based on the source object type
  app/controllers/application_controller.rb
  app/controllers/vm_common.rb
Labels: enhancement

#8390 CSS Enhancements
  app/javascript/components/remove-catalog-item-modal.jsx
  app/javascript/components/vm-edit-form/vm-edit-form.schema.js
  app/javascript/forms/form-buttons.jsx
  app/javascript/forms/miq-button.jsx
  app/stylesheet/ddf_override.scss
  app/stylesheet/menu.scss
Labels: enhancement, internationalization, najdorf/yes?

#8388 Add public_network option to GCE provisioning
  app/views/shared/views/_prov_dialog.html.haml
Labels: enhancement, compute/cloud

#8385 Upgrade carbon components react version to 7.56.0
  app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
  app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
  app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
  app/javascript/spec/async-credentials/__snapshots__/edit-password-field.spec.js.snap
  app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
  app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
  app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
  app/javascript/spec/cloud-database-form/__snapshots__/cloud-database-form.spec.js.snap
  app/javascript/spec/cloud-object-store-container-form/__snapshots__/cloud-object-store-container-form.spec.js.snap
  app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
  app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
  app/javascript/spec/code-editor/__snapshots__/code-editor.spec.js.snap
  app/javascript/spec/filter-dropdown/__snapshots__/filter-dropdown.spec.js.snap
  app/javascript/spec/forms/__snapshots__/data-driven-form.spec.js.snap
  app/javascript/spec/generic-objects-form/__snapshots__/generic-objects-form.spec.js.snap
  app/javascript/spec/host-aggregate-form/__snapshots__/host-aggregate-form.spec.js.snap
  app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
  app/javascript/spec/miq-alert-set/__snapshots__/miq-alert-set.spec.js.snap
  app/javascript/spec/miq-policy-set/__snapshots__/miq-policy-set.spec.js.snap
  app/javascript/spec/notification-drawer/__snapshots__/notification-drawer.spec.js.snap
  app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap
  app/javascript/spec/pxe-customization-template-form/__snapshots__/pxe-customization-template-form.spec.js.snap
  app/javascript/spec/pxe-image-type-form/__snapshots__/pxe-image-type-form.spec.js.snap
  app/javascript/spec/pxe-iso-datastore-form/__snapshots__/pxe-iso-datastore-form.spec.js.snap
  app/javascript/spec/pxe-iso-image-form/__snapshots__/pxe-iso-image-form.spec.js.snap
  app/javascript/spec/remove-catalog-item-modal/__snapshots__/remove-catalog-item-modal.spec.js.snap
  app/javascript/spec/remove-generic-item-modal/__snapshots__/remove-generic-item-modal.spec.js.snap
  app/javascript/spec/search-bar/__snapshots__/search-bar.spec.js.snap
  app/javascript/spec/settings-time-profile-form/__snapshots__/settings-time-profile-form.spec.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/generic_group.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/generic_table_row.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/operation_ranges.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/tag_group.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/textual_summary.test.js.snap
  app/javascript/spec/toolbar/__snapshots__/dashboard_toolbar.spec.jsx.snap
  app/javascript/spec/tree-view/__snapshots__/selector.spec.js.snap
  app/javascript/spec/widget-wrapper/__snapshots__/widget-wrapper.spec.js.snap
  app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
  package.json
  yarn.lock
Labels: dependencies, security fix

#8396 Fixed typo for services ownership title
  app/controllers/service_controller.rb
Labels: bug

#8338 AWX template support for catalog
  app/controllers/catalog_controller.rb
  app/views/catalog/_form_basic_info.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/service/_svcs_show.html.haml
Labels: enhancement

#8397 Fix tasks delete all bug
  app/controllers/miq_task_controller.rb
Labels: bug

#8395 Fix button group form missing group_index on submit
  app/javascript/components/button-group/helper.js
  app/javascript/components/button-group/index.jsx
Labels: bug

#8403 Fixed private key field for provider forms
  app/javascript/components/async-credentials/password-field.jsx
  app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
Labels: bug

#8404 Fixing dropdown values
  app/views/report/_form_formatting.html.haml
Labels: bug

#8406 Fix typo preventing usage of the correct double
  spec/controllers/ops_controller/settings/schedules_spec.rb
Labels: bug/sporadic test failure

#8407 Fix images padding in summary pages
  app/stylesheet/miq-structured-list.scss
Labels: enhancement

#8411 Rails 6.1: ActionView::Base new now has 3 required arguments
  spec/javascripts/support/jasmine_helper.rb
Labels: rails6.1

#8412 Update ui locale english json for August 9th.
  app/javascript/oldjs/locale/en.json
Labels: internationalization

#8413 Catches undefined values
  app/javascript/components/action-form/action-form.schema.js
  app/javascript/components/action-form/helper.js
  app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
Labels: bug

#8398 modified host initiator form to accept multiple iqns
  app/javascript/components/host-initiator-form/host-initiator-form.schema.js
Labels: enhancement

#8391 errors when using searchbar
  app/javascript/components/search-bar/index.jsx
  app/javascript/http_api/http.js
Labels: bug

#8418 rename Vm Operation context
  app/controllers/application_controller/ci_processing.rb
Labels: technical debt

#8416 Fixes Component Overlapping in Service -> Catalog Form
  app/stylesheet/ddf_override.scss
Labels: bug

#8375 add storage resource to volume Relationships
  app/helpers/cloud_volume_helper/textual_summary.rb
  spec/helpers/cloud_volume_helper/textual_summary_spec.rb
Labels: enhancement

#8409 Fix dashboard widget tables scaling
  app/stylesheet/dashboard.scss
Labels: bug

#8420 Modified Allowed Function to Include Provision Dialog Forms
  app/controllers/miq_ae_customization_controller.rb
Labels: bug, oparin/yes?

#8423 Updated json files for August 15.
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: enhancement, internationalization

#8405 Removing more attach/detach content
  app/controllers/vm_cloud_controller.rb
  app/javascript/components/cloud-volume-form/attach-detach-cloud-volume-form.jsx
  app/javascript/components/cloud-volume-form/attach-detach-cloud-volume.schema.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/vm_cloud/vm_cloud_attach_form_controller.js
  app/javascript/oldjs/controllers/vm_cloud/vm_cloud_detach_form_controller.js
  app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
  app/javascript/spec/cloud-volume-form/attach-detach-cloud-volume-form.spec.js
  app/views/cloud_volume/attach.html.haml
  app/views/cloud_volume/detach.html.haml
  app/views/vm_common/_attach.html.haml
  app/views/vm_common/_detach.html.haml
  spec/controllers/vm_cloud_controller_spec.rb
  spec/javascripts/controllers/vm_cloud/vm_cloud_detach_form_controller_spec.js
Labels: enhancement

#8401 Put `physical_storage_timeline` redirect in `specific_buttons`
  app/controllers/physical_storage_controller.rb
Labels: bug

#8408 Fix rails 6.1 errors is now array warnings
  app/controllers/application_controller/advanced_search.rb
  app/controllers/application_controller/buttons.rb
  app/controllers/application_controller/ci_processing.rb
  app/controllers/catalog_controller.rb
  app/controllers/chargeback_rate_controller.rb
  app/controllers/condition_controller.rb
  app/controllers/host_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/miq_ae_customization_controller/old_dialogs.rb
  app/controllers/miq_alert_controller.rb
  app/controllers/miq_policy_controller/policies.rb
  app/controllers/mixins/manager_controller_mixin.rb
  app/controllers/ops_controller/ops_rbac.rb
  app/controllers/ops_controller/settings/analysis_profiles.rb
  app/controllers/ops_controller/settings/label_tag_mapping.rb
  app/controllers/ops_controller/settings/tags.rb
  app/controllers/ops_controller/settings/upload.rb
  app/controllers/ops_controller/settings/zones.rb
  app/controllers/pxe_controller/pxe_servers.rb
  app/controllers/report_controller/dashboards.rb
  app/controllers/report_controller/menus.rb
  app/controllers/report_controller/reports/editor.rb
  app/controllers/report_controller/schedules.rb
  app/controllers/report_controller/widgets.rb
Labels: technical debt, rails7

#8427 Remove unused angular controllers
  app/javascript/oldjs/controllers/cloud_volume/cloud_volume_form_controller.js
  app/javascript/oldjs/controllers/fonticon_picker_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/mixins/charts-mixin.js
Labels: technical debt

#8430 Fix main menu search error
  app/javascript/menu/search-results.jsx
Labels: bug

#8421 validate iqn and wwpn according to rules
  app/javascript/components/host-initiator-form/host-initiator-form.schema.js
  app/javascript/components/host-initiator-form/index.jsx
Labels: bug

#8431 Updated UI translations
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: enhancement, internationalization, oparin/yes?
