Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2022-02, with the labels that each got.

#8082 Update webpack-dev-server for CVE
  package.json
  yarn.lock
Labels: dependencies, security fix

#8084 Remove Hakiri
  README.md
Labels: developer, cleanup

#8085 update precss version
  package.json
  yarn.lock
Labels: dependencies, security fix

#8086 Allow rails 6.1/6.0
  manageiq-ui-classic.gemspec
Labels: dependencies, rails6.1

#8087 Update compress-webpack-plugin version
  package.json
  yarn.lock
Labels: dependencies, security fix

#7408 Display all added/saved volume data in UI.
  app/views/miq_request/_prov_dialog_volume_fieldset.html.haml
Labels: bug

#7377 Fix volumes boolean fields in '_prov_dialog_volume_fieldset.html.haml'
  app/views/miq_request/_prov_dialog_volume_fieldset.html.haml
Labels: bug

#8076 Prevent drag drop widgets with dashboard_view role
  app/javascript/angular/dashboard/widget-wrapper.js
  app/views/dashboard/_widget.html.haml
Labels: enhancement

#8092 update code mirror package and create-react-context package
  package.json
  yarn.lock
Labels: dependencies, security fix

#8098 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .gitignore
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script.sh
  bin/ci/before_install.sh
  bin/ci/before_script.sh
  bin/ci/dead_method_check.sh
  bin/setup
  bin/update
  lib/tasks/manageiq/ui_tasks.rake
  manageiq-ui-classic.gemspec
  spec/other/travis_spec.rb
Labels: test, developer, dependencies

#8094 update webpack dev server
  package.json
  yarn.lock
Labels: technical debt, dependencies, security fix

#8102 Fix style for full screen dashboard custom report
  app/stylesheet/miq-data-table.scss
Labels: enhancement

#8103 Remove fail-fast now that GHA are working
  .github/workflows/ci.yaml
Labels: test

#8099 Add Build History Graph to README.md
  README.md
Labels: test, developer

#8104 Remove old ansible credentials haml file
  app/views/ansible_credential/_credential_form.html.haml
Labels: technical debt

#8096 Fix cloud volume form
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
  app/javascript/components/cloud-volume-form/index.jsx
Labels: enhancement

#8107 Fix toolbar reset for chargeback reports
  app/javascript/components/data-tables/report-data-table/report-data-table.jsx
  app/javascript/spec/report-data-table.spec.js
Labels: bug

#8106 add optional disable button for cloud volume
  app/helpers/application_helper/toolbar/cloud_volume_center.rb
  app/helpers/application_helper/toolbar/cloud_volumes_center.rb
Labels: enhancement, morphy/yes?

#8108 Disable template cloning for IBM Power HMC infrastructure provider
  app/helpers/application_helper/button/button_template_clone.rb
  app/helpers/application_helper/toolbar/template_infras_center.rb
Labels: enhancement

#8093 Remove adhoc metrics in container provider dashboard
  app/controllers/container_dashboard_controller.rb
  app/controllers/container_node_controller.rb
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/container_node_center.rb
  app/helpers/application_helper/toolbar/ems_container_center.rb
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/live_metrics/ad_hoc_metrics_controller.js
  app/javascript/oldjs/controllers/live_metrics/util/metrics-config-factory.js
  app/javascript/oldjs/controllers/live_metrics/util/metrics-http-factory.js
  app/javascript/oldjs/controllers/live_metrics/util/metrics-parse-url-factroy.js
  app/javascript/oldjs/controllers/live_metrics/util/metrics-utils-factory.js
  app/services/hawkular_proxy_service.rb
  app/services/prometheus_proxy_service.rb
  app/stylesheet/legacy/metrics.scss
  app/views/ems_container/_show_ad_hoc_metrics.html.haml
  app/views/ems_container/ad_hoc/_chart_view.html.haml
  app/views/ems_container/ad_hoc/_chart_view_form.html.haml
  app/views/ems_container/ad_hoc/_list_view.html.haml
  app/views/ems_container/ad_hoc/_list_view_blank.html.haml
  app/views/ems_container/ad_hoc/_list_view_form.html.haml
  app/views/shared/views/ems_common/_show.html.haml
  spec/controllers/ems_container_controller_spec.rb
Labels: technical debt

#8105 [MORPHY] update carbon charts version
  app/javascript/packs/globals.js
  app/stylesheet/ddf_override.scss
  package.json
  yarn.lock
Labels: bug, dependencies

#8111 Remove test cases for live metrics controller
  spec/javascripts/controllers/container_live_dashboard/container_live_dashboard_controller_spec.js
  spec/javascripts/fixtures/json/container_live_dashboard_metrics_response.json
  spec/javascripts/fixtures/json/container_live_dashboard_response.json
  spec/javascripts/fixtures/json/container_live_dashboard_tenant_response.json
  spec/javascripts/fixtures/json/container_live_dashboard_wo_default_response.json
Labels: test, cleanup

#8110 Fix automation structured list
  app/helpers/miq_ae_class_helper.rb
Labels: bug

#8115 Deleted unused haml file controller code
  app/views/floating_ip/_common_new_edit.html.haml
  app/views/floating_ip/edit.html.haml
  app/views/floating_ip/new.html.haml
Labels: bug

#8118 Fix performance charts titles
  app/javascript/components/performance-charts/areaChart.js
  app/javascript/components/performance-charts/index.jsx
  app/javascript/components/performance-charts/lineChart.js
  app/stylesheet/charts.scss
  app/views/layouts/_perf_chart_js.html.haml
Labels: bug

#8112 Converted Add/Remove Security Groups Form to React
  app/javascript/components/vm-cloud-add-remove-security-group-form/index.jsx
  app/javascript/components/vm-cloud-add-remove-security-group-form/vm-cloud-add-security-form.schema.js
  app/javascript/oldjs/components/index.js
  app/javascript/oldjs/components/vm_cloud/vm-cloud-add-security-group.js
  app/javascript/oldjs/components/vm_cloud/vm-cloud-remove-security-group.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/add-remove-security-groups-form/__snapshots__/add-remove-security-groups-form.spec.js.snap
  app/javascript/spec/add-remove-security-groups-form/add-remove-security-groups-form.spec.js
  app/views/static/vm_cloud/add_security_group.html.haml
  app/views/static/vm_cloud/remove_security_group.html.haml
  app/views/vm_common/_add_security_group.html.haml
  app/views/vm_common/_remove_security_group.html.haml
  spec/javascripts/components/vm_cloud/vm-cloud-add-security-group_spec.js
  spec/javascripts/components/vm_cloud/vm-cloud-remove-security-group_spec.js
Labels: enhancement

#8113 Fixed dashboard charts title issue
  app/javascript/components/carbon-charts/areaChart.js
  app/javascript/components/carbon-charts/donutChart.js
  app/javascript/components/carbon-charts/groupChart.js
  app/javascript/components/carbon-charts/groupHorizontalChart.js
  app/javascript/components/carbon-charts/lineChart.js
  app/javascript/components/carbon-charts/pieChart.js
  app/javascript/components/carbon-charts/stackBarChart.js
  app/javascript/components/carbon-charts/stackHorizontalChart.js
  app/javascript/components/carbon-charts/stackedAreaChart.js
  app/javascript/components/dashboard-charts/index.jsx
  app/stylesheet/charts.scss
  app/views/dashboard/_widget_chart.html.haml
Labels: bug, najdorf/yes?

#8121 [MORPHY] Fix about modal BG image
  app/assets/stylesheets/about_modal_background.scss
Labels: bug

#8114 Added validation to forms with emptySchema
  app/javascript/components/cloud-network-form/cloud-network-form.jsx
  app/javascript/components/cloud-network-form/cloud-network-form.schema.js
  app/javascript/components/cloud-volume-form/index.jsx
  app/javascript/components/network-floatingIPs-form/index.jsx
  app/javascript/components/network-floatingIPs-form/network-floatingIPs-form.schema.js
  app/javascript/components/network-security-groups-form/index.jsx
  app/javascript/components/network-security-groups-form/network-security-groups-form.schema.js
  app/javascript/components/routers-form/RoutersForm.schema.js
  app/javascript/components/routers-form/index.jsx
  app/javascript/components/subnet-form/index.jsx
  app/javascript/components/subnet-form/subnet-form.schema.js
  app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
  app/javascript/spec/network-floating-ip-form/__snapshots__/network-floating-ip-form.spec.js.snap
  app/javascript/spec/network-router-form/__snapshots__/network-router-form.spec.js.snap
  app/javascript/spec/network-security-groups-form/__snapshots__/network-security-groups-form.spec.js.snap
  app/javascript/spec/subnet-form/__snapshots__/subnet-form.spec.js.snap
  app/stylesheet/ddf_override.scss
Labels: enhancement

#8078 Convert Add / Remove Host form for Host Aggregate
  app/javascript/components/host-aggregate-form/add-remove-host-aggregate-form.jsx
  app/javascript/components/host-aggregate-form/add-remove-host-aggregate-form.schema.js
  app/javascript/oldjs/controllers/host_aggregate/host_aggregate_form_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/host-aggregate-form/__snapshots__/host-aggregate-form.spec.js.snap
  app/javascript/spec/host-aggregate-form/host-aggregate-form.spec.js
  app/views/host_aggregate/add_host_select.html.haml
  app/views/host_aggregate/remove_host_select.html.haml
Labels: enhancement

#8120 Fix Providers column inconsistency issue in table header
  product/views/ManageIQ_Providers_CloudManager_Template.yaml
  product/views/ManageIQ_Providers_CloudManager_Vm.yaml
  product/views/SecurityGroup.yaml
Labels: enhancement, najdorf/yes?

#8127 Fix provision show/hide deprecate column mismatch
  app/controllers/application_controller/miq_request_methods.rb
  spec/controllers/application_controller/miq_request_methods_spec.rb
Labels: bug, najdorf/yes?

#8128 Hide custom logos upload tab for podified env
  app/views/ops/_all_tabs.html.haml
Labels: bug, najdorf/yes?

#8126 Fix container dashboard charts
  app/javascript/components/provider-dashboard-charts/charts_config.js
  app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationDonutChart.js
  app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationMemoryDonutChart.js
  app/stylesheet/charts.scss
Labels: bug, najdorf/yes?

#8123 Fix provider dashboard charts title and sort order
  app/javascript/components/provider-dashboard-charts/pod-trend-charts/podsAreaChart.js
  app/javascript/components/provider-dashboard-charts/recent-host-chart/hostLineChart.js
  app/javascript/components/provider-dashboard-charts/recent-vm-chart/index.js
  app/javascript/components/provider-dashboard-charts/recent-vm-chart/vmAreaChart.js
  app/javascript/components/provider-dashboard-charts/usage-network-image-charts/index.js
  app/javascript/components/provider-dashboard-charts/usage-network-image-charts/usageAreaChart.js
  app/services/ems_dashboard_service.rb
Labels: bug, najdorf/yes?

#8129 Add supports iso_datastore checks
  app/controllers/pxe_controller/iso_datastores.rb
  app/helpers/application_helper/button/iso_datastore_new.rb
Labels: enhancement

#8133 Fix dashboard charts footer css
  app/stylesheet/legacy/patternfly_overrides.scss
Labels: bug

#8131 Fix advanced search modal css
  app/stylesheet/legacy/patternfly_overrides.scss
Labels: bug, najdorf/yes?

#8009 update node version
  .github/workflows/ci.yaml
  package.json
Labels: dependencies

#8137 Fix Conditions description clear issue when dropdown value changes
  app/views/condition/_form.html.haml
Labels: bug, najdorf/yes?

#8132 Update Response message for defining new host initiator and volume ma…
  app/javascript/components/host-initiator-form/index.jsx
  app/javascript/components/volume-mapping-form/index.jsx
Labels: enhancement, najdorf/yes?

#8100 Make dashboard two column design
  app/controllers/dashboard_controller.rb
  app/controllers/report_controller/dashboards.rb
  app/helpers/dashboard_helper.rb
  app/stylesheet/application-webpack.scss
  app/stylesheet/dashboard.scss
  app/views/dashboard/show.html.haml
  app/views/report/_db_widgets.html.haml
Labels: enhancement

#8134 Cleanup IsoDatastore supporting()
  app/controllers/pxe_controller/iso_datastores.rb
  app/helpers/application_helper/button/iso_datastore_new.rb
Labels: refactoring

#8122 Allows for SSH GitHub Repo
  app/javascript/components/ansible-repository-form/ansible-repository-form.schema.js
  app/javascript/components/ansible-repository-form/helpers.jsx
  app/javascript/components/ansible-repository-form/index.jsx
  app/javascript/spec/ansible-repository-form/helpers.spec.js
  package.json
  yarn.lock
Labels: bug, dependencies, najdorf/yes?

#8142 Downgrade node version to 14
  .github/workflows/ci.yaml
  package.json
Labels: dependencies

#8147 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: test, developer

#8141 Fix instance edit page from availability zone summary
  app/controllers/vm_common.rb
  app/helpers/application_helper/page_layouts.rb
  app/views/vm/edit.html.haml
Labels: bug, najdorf/yes?

#8139 Remove overlay_dark.png and references
  app/assets/images/layout/overlay_dark.png
  app/stylesheet/legacy/patternfly_overrides.scss
Labels: technical debt, graphics, najdorf/yes?

#8144 Log depot edit: undefined variable bug fix
  app/controllers/ops_controller/diagnostics.rb
Labels: bug

#8140 show zone collect logs
  app/views/ops/_logs_selected.html.haml
Labels: bug, najdorf/yes?

#8150 Use class_by_ems to access correct provider class
  app/helpers/application_helper/button/host_initiator_group_new.rb
  app/helpers/application_helper/button/host_initiator_new.rb
Labels: refactoring, najdorf/yes?
