Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2022-07, with the labels that each got.

#8347 Update non-English json files after June 31 fixes
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: bug, internationalization, najdorf/yes?

#8332 Fix storage resource heatmap
  app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
  app/services/ems_storage_dashboard_service.rb
Labels: bug

#8348 Refactored custom button form
  app/javascript/components/generic-objects-form/custom-button-form/custom-button-form.schema.js
  app/javascript/components/generic-objects-form/custom-button-form/helper.js
  app/javascript/spec/custom-buttom-form/__snapshots__/custom-button-form.spec.js.snap
Labels: refactoring

#8344 add missing label for custom wwpn
  app/javascript/components/host-initiator-form/host-initiator-form.schema.js
Labels: bug

#8319 Adding "Management Console" access for a PowerVS VM
  app/controllers/vm_remote.rb
  app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
  config/routes.rb
  spec/config/routes.pending.yml
Labels: enhancement

#8349 Refactored host initiator form to fix lint issues and add simple valu…
  app/javascript/components/host-initiator-form/host-initiator-form.schema.js
  app/javascript/components/host-initiator-form/index.jsx
Labels: refactoring

#8294 Updating default value of <Choose> to be nil in drop-downs
  app/controllers/miq_policy_rsop_controller.rb
  app/views/miq_policy_rsop/_rsop_form.html.haml
Labels: bug, najdorf/yes?

#8357 remove remaining ad_hoc_references
  app/controllers/mixins/ems_common.rb
Labels: technical debt

#8279 implemented validation storage system button
  app/javascript/components/physical-storage-form/editing-context.js
  app/javascript/components/physical-storage-form/index.jsx
  app/javascript/components/physical-storage-form/physical-storage-form.schema.js
  app/javascript/components/physical-storage-form/validate-storage-credentials.jsx
  app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap
Labels: enhancement

#8353 Update carbon-components package
  package.json
  yarn.lock
Labels: enhancement, dependencies

#8321 Fix chargeback preview server error
  app/helpers/application_helper/toolbar/x_vm_center.rb
  app/javascript/components/data-tables/report-data-table/report-data-table.jsx
  app/javascript/spec/report-data-table.spec.js
Labels: bug

#8327 Converted Dashboard Widgets summary pages from HAML to React
  app/helpers/condition_helper.rb
  app/helpers/miq_alert_helper.rb
  app/helpers/report_helper.rb
  app/helpers/report_helper/report_dashboard_widget_helper.rb
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/spec/miq-alert/__snapshots__/miq-alert.spec.js.snap
  app/stylesheet/miq-structured-list.scss
  app/views/report/_widget_show.html.erb
  app/views/report/_widget_show.html.haml
  spec/controllers/miq_report_controller/trees_spec.rb
Labels: enhancement

#8363 Fixes Missing Id Error When Copying a Chargeback Rate
  app/controllers/chargeback_rate_controller.rb
Labels: bug

#8362 Multiselect option display issue
  app/views/miq_request/_request_dialog_details.html.haml
Labels: bug

#8366 change snapshot error to default error
  spec/helpers/application_helper/buttons/vm_snapshot_add_spec.rb
  spec/helpers/application_helper/buttons/vm_snapshot_revert_spec.rb
Labels: enhancement, test, rbac

#8370 Re-enable Template Clone UI button for ibm_power_hmc provider
  app/helpers/application_helper/button/button_template_clone.rb
  app/helpers/application_helper/toolbar/template_infras_center.rb
Labels: enhancement

#8371 Use array_including to fix sporadic tags failure
  spec/controllers/application_controller/tags_spec.rb
Labels: test, bug/sporadic test failure

#8369 Fix Provider charts style
  app/stylesheet/charts.scss
Labels: bug

#8374 Remove image when no text is available in data tables
  app/javascript/components/miq-data-table/miq-table-cell.jsx
Labels: bug

#8378 Update ui locale json files for July 25th.
  app/javascript/oldjs/locale/en.json
Labels: internationalization, najdorf/yes?

#8379 Remove unused show_actions haml for generic object definitions
  app/views/generic_object_definition/_show_actions.html.haml
  app/views/generic_object_definition/_show_list.html.haml
Labels: technical debt

#8381 Fixed catalog items button group form
  app/javascript/components/button-group/helper.js
  app/javascript/components/button-group/index.jsx
Labels: bug

#8382 support character encoding in content_type
  spec/controllers/tree_controller_spec.rb
Labels: enhancement, rails6.1

#8380 Translations for strings in textual_summary.rb
  app/helpers/cloud_database_helper/textual_summary.rb
  app/helpers/cloud_network_helper/textual_summary.rb
  app/helpers/security_group_helper/textual_summary.rb
Labels: enhancement, internationalization, najdorf/yes?

#8376 HeatmapChartGraph: show an empty chart when data is not null but undefined - new PR
  app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
  app/javascript/components/provider-dashboard-charts/helpers.js
Labels: bug

#8116 Switch Redhat references to oVirt
  app/helpers/provision_customize_helper.rb
  app/views/shared/views/_prov_dialog.html.haml
Labels: enhancement

#8339 Creating UI for Cloud Database logic
  app/controllers/cloud_database_controller.rb
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper/button/new_cloud_database.rb
  app/helpers/application_helper/toolbar/cloud_database_center.rb
  app/helpers/application_helper/toolbar/cloud_databases_center.rb
  app/javascript/components/cloud-database-form/cloud-database-form.jsx
  app/javascript/components/cloud-database-form/cloud-database-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/cloud-database-form/__snapshots__/cloud-database-form.spec.js.snap
  app/javascript/spec/cloud-database-form/cloud-database-form.spec.js
  app/views/cloud_database/edit.haml
  app/views/cloud_database/new.haml
  config/routes.rb
Labels: enhancement
