Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2022-06, with the labels that each got.

#8286 Fixed pagination translations
  app/javascript/components/miq-pagination.jsx
Labels: bug

#8290 Updated oldjs locales from June 1st translations
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
Labels: internationalization, najdorf/yes?

#8292 Fixed catalog item summary page
  app/views/catalog/_sandt_tree_show.html.haml
Labels: bug

#8295 Update english old js json files after some i18n fixes
  app/javascript/oldjs/locale/en.json
Labels: bug, internationalization, najdorf/yes

#8287 Fixed no VMWare templates in Provision Requests
  app/controllers/application_controller/miq_request_methods.rb
  app/views/miq_request/_pre_prov.html.haml
  spec/controllers/application_controller/miq_request_methods_spec.rb
Labels: bug, najdorf/yes

#8293 Removing Interpolation across code (i18n)
  app/helpers/ops_helper.rb
  app/javascript/components/ansible-repository-form/index.jsx
  app/javascript/components/button-group/index.jsx
  app/javascript/components/cloud-object-store-container-form/index.jsx
  app/javascript/components/container-projects/chart-card.jsx
  app/javascript/components/dashboard-widgets/widget-wrapper/helper.jsx
  app/javascript/components/generic-objects-form/custom-button-form/index.jsx
  app/javascript/components/miq-pagination.jsx
  app/javascript/components/network-security-groups-form/index.jsx
  app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
  app/javascript/components/remove-generic-item-modal.jsx
  app/javascript/components/retirement-form/index.jsx
  app/javascript/components/routers-form/index.jsx
  app/javascript/components/vm-cloud-add-remove-security-group-form/index.jsx
  app/javascript/components/workers-form/helpers.jsx
  app/javascript/menu/group-switcher.jsx
  app/javascript/menu/search-results.jsx
Labels: bug, internationalization, najdorf/yes?

#8306 June 7th translation bug fixes from core: 21926
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: bug, internationalization, najdorf/yes?

#8303 Fix vertical label for translated strings for data table
  app/stylesheet/miq-data-table.scss
Labels: bug, internationalization, najdorf/yes?

#8308 [NAJDORF] Removing Interpolation across code (i18n)
  app/helpers/ops_helper.rb
  app/javascript/components/ansible-repository-form/index.jsx
  app/javascript/components/miq-pagination.jsx
  app/javascript/components/network-security-groups-form/index.jsx
  app/javascript/components/retirement-form/index.jsx
  app/javascript/components/routers-form/index.jsx
  app/javascript/components/workers-form/helpers.jsx
  app/javascript/menu/group-switcher.jsx
  app/javascript/menu/search-results.jsx
Labels: bug, internationalization

#8307 Updated English oldjs after UI 8293 and Core 21930
  app/javascript/oldjs/locale/en.json
Labels: bug, internationalization, najdorf/yes

#8309 Test host charts with various applies_to_method
  spec/services/charts_layout_service_spec.rb
Labels: bug, test

#8304 Fix service catalog form elements overlap with notifications
  app/stylesheet/notifications.scss
Labels: bug, najdorf/yes?

#8312 Supports changes to rhv provider form
  app/javascript/components/provider-form/index.jsx
Labels: bug, najdorf/yes?

#8315 Remove old zoomed chart code
  app/views/dashboard/_zoomed_chart.html.haml
Labels: technical debt

#8314 Fixed missing title/breadcrumb translations
  app/controllers/host_initiator_group_controller.rb
  app/controllers/physical_storage_controller.rb
  app/controllers/storage_resource_controller.rb
Labels: bug, internationalization

#8317 Update the UI's en json file after #8313
  app/javascript/oldjs/locale/en.json
Labels: bug, internationalization, najdorf/yes?

#8316 Upgrade ddf version to 3.18.2
  package.json
  yarn.lock
Labels: bug, dependencies

#8325 Fix no records found typo references
  app/javascript/components/data-tables/db-list/index.jsx
  app/javascript/components/data-tables/report-data-table/report-data-table.jsx
  app/javascript/components/gtl-view.jsx
  app/javascript/components/no-records-found.jsx
  app/javascript/packs/component-definitions-common.js
Labels: enhancement

#8326 [WIP] Upgrade charts version to 0.58.0
  package.json
  yarn.lock
Labels: wip, dependencies, security fix

#8328 Fixed flavors form
  app/javascript/components/flavor-form/flavor-form.schema.js
  app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap
Labels: bug

#8330 Remove special UI code to handle Ovirt metrics/keypair selectors
  app/javascript/components/provider-form/index.jsx
Labels: bug, najdorf/no

#8333 Fixed file size validation bug
  app/javascript/forms/mappers/validatorMapper.jsx
  app/javascript/spec/generic-objects-form/__snapshots__/generic-objects-form.spec.js.snap
Labels: bug

#8335 Fixed copy dashboard form bug
  app/javascript/components/copy-dashboard-form/copy-dashboard-form.schema.js
Labels: bug

#8334 Refactored generic object form to use simple value for searchable field
  app/javascript/components/generic-objects-form/generic-objects-form.schema.js
  app/javascript/components/generic-objects-form/index.jsx
  app/javascript/spec/generic-objects-form/__snapshots__/generic-objects-form.spec.js.snap
Labels: refactoring

#8331 Fixed button permission issues for firmware registry and vm right siz…
  app/helpers/application_helper/toolbar/firmware_registries_center.rb
  app/helpers/application_helper/toolbar/firmware_registry_center.rb
  app/helpers/application_helper/toolbar/right_size_view.rb
Labels: bug

#8336 remove db checks on every request and use in memory cache (dev only)
  app/helpers/application_helper.rb
Labels: developer, cleanup

#8341 Add a timeout for the setup-ruby job in ci.yaml
  .github/workflows/ci.yaml
Labels: bug, test

#8229 De explorization of Service Pages
  app/controllers/application_controller/advanced_search.rb
  app/controllers/application_controller/ci_processing.rb
  app/controllers/catalog_controller.rb
  app/controllers/mixins/actions/vm_actions/ownership.rb
  app/controllers/mixins/actions/vm_actions/retire.rb
  app/controllers/mixins/sandbox.rb
  app/controllers/service_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/toolbar/service/vmdb_mixin.rb
  app/helpers/application_helper/toolbar/service_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/javascript/components/edit-service-form/index.jsx
  app/javascript/components/set-ownership-form/index.jsx
  app/javascript/oldjs/controllers/dialog_user/dialog_user_reconfigure_controller.js
  app/javascript/spec/set-ownership-form/set-ownership-form.spec.js
  app/presenters/menu/default_menu.rb
  app/presenters/tree_builder.rb
  app/services/dialog_local_service.rb
  app/views/service/edit.html.haml
  app/views/service/explorer.html.haml
  app/views/service/retire.html.haml
  app/views/service/service_ownership.html.haml
  app/views/service/show.html.haml
  app/views/service/show_list.html.haml
  config/routes.rb
  product/views/Service.yaml
  spec/config/routes.pending.yml
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/application_controller/tree_support_spec.rb
  spec/controllers/service_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/routing/service_routing_spec.rb
  spec/services/dialog_local_service_spec.rb
Labels: enhancement
