Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2022-03, with the labels that each got.

#8101 populate itemIds with gridchecks values if such values exists
  app/javascript/components/remove-generic-item-modal.jsx
Labels: bug

#8153 fix date format in provider dashboard charts
  app/javascript/components/provider-dashboard-charts/helpers.js
Labels: bug, najdorf/yes?

#8152 Remove image Right-Size button from toolbar
  app/helpers/application_helper/toolbar/template_clouds_center.rb
  app/helpers/application_helper/toolbar/x_template_cloud_center.rb
Labels: bug, najdorf/yes?

#8157 Revert "Allows for SSH GitHub Repo"
  app/javascript/components/ansible-repository-form/ansible-repository-form.schema.js
  app/javascript/components/ansible-repository-form/helpers.jsx
  app/javascript/components/ansible-repository-form/index.jsx
  app/javascript/spec/ansible-repository-form/helpers.spec.js
  package.json
  yarn.lock
Labels: dependencies, najdorf/yes?

#8156 Validate provider fields in edit form.
  app/javascript/components/async-credentials/async-credentials.jsx
Labels: bug, wip, najdorf/yes?

#8158 Fixed dashboard widget remove
  app/controllers/dashboard_controller.rb
Labels: bug, najdorf/yes?

#8154 Updated carbon charts version
  package.json
  yarn.lock
Labels: enhancement, dependencies

#8165 Update keypair schema to fix validation
  app/javascript/components/auth-key-pair-cloud/auth-key-pair-cloud-form.schema.js
  app/javascript/spec/auth-key-pair-cloud/__snapshots__/ansible-credentials-form.spec.js.snap
Labels: bug, najdorf/yes?

#8167 Fix attach and detach cloud volume notification
  app/controllers/cloud_volume_controller.rb
Labels: bug, najdorf/yes?

#8168 Update validation for edit cloud volume button
  app/controllers/cloud_volume_controller.rb
  app/helpers/application_helper/toolbar/cloud_volume_center.rb
  app/helpers/application_helper/toolbar/cloud_volumes_center.rb
Labels: bug, najdorf/yes?

#8169 put the login into a form
  app/views/dashboard/login.html.haml
  spec/views/dashboard/login.html.haml_spec.rb
Labels: bug, najdorf/no

#8160 Remove miq_bootstrap from react pages
  app/views/cloud_tenant/_show_dashboard.html.haml
  app/views/ems_cloud/_show_dashboard.html.haml
  app/views/ems_physical_infra/_show_dashboard.html.haml
  app/views/physical_infra_overview/show.html.haml
Labels: technical debt

#8170 Translations provided on 2022-03-09
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: internationalization, najdorf/yes?

#8172 Autogenerated from ManageIQ/manageiq#21773
  app/javascript/oldjs/locale/fr.json
Labels: bug, internationalization, najdorf/yes

#8151 Remove col3 reference from dashboard
  app/controllers/dashboard_controller.rb
  app/controllers/report_controller/dashboards.rb
  app/helpers/dashboard_helper.rb
  app/javascript/oldjs/miq_application.js
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/miq_report_controller/dashboards_spec.rb
Labels: enhancement

#8162 Converted widget wrapper to carbon react
  app/controllers/dashboard_controller.rb
  app/javascript/angular/dashboard/dropdown-menu.js
  app/javascript/angular/dashboard/index.js
  app/javascript/angular/dashboard/widget-chart.js
  app/javascript/angular/dashboard/widget-empty.js
  app/javascript/angular/dashboard/widget-error.js
  app/javascript/angular/dashboard/widget-footer.js
  app/javascript/angular/dashboard/widget-menu.js
  app/javascript/angular/dashboard/widget-report.js
  app/javascript/angular/dashboard/widget-spinner.js
  app/javascript/angular/dashboard/widget-wrapper.js
  app/javascript/angular/index.js
  app/javascript/components/widget-chart/index.jsx
  app/javascript/components/widget-error/index.jsx
  app/javascript/components/widget-footer/index.jsx
  app/javascript/components/widget-menu/index.jsx
  app/javascript/components/widget-report/index.jsx
  app/javascript/components/widget-wrapper/helper.jsx
  app/javascript/components/widget-wrapper/index.jsx
  app/javascript/components/widget-zoom/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/dashboard/mocks.js
  app/javascript/spec/dashboard/widget-empty.spec.js
  app/javascript/spec/dashboard/widget-wrapper.spec.js
  app/javascript/spec/widget-wrapper/__snapshots__/widget-wrapper.spec.js.snap
  app/javascript/spec/widget-wrapper/widget-wrapper.spec.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/charts.scss
  app/stylesheet/widget.scss
  app/views/dashboard/_widget.html.haml
  config/routes.rb
  spec/routing/dashboard_routing_spec.rb
  yarn.lock
Labels: enhancement

#8073 Heat map chart conversion
  app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
  app/javascript/components/provider-dashboard-charts/heat-map-chart/index.js
  app/javascript/components/provider-dashboard-charts/helpers.js
  app/javascript/oldjs/controllers/ems_container_dashboard/heatmap_controller.js
  app/javascript/oldjs/controllers/ems_infra_dashboard/heatmap_controller.js
  app/javascript/oldjs/controllers/ems_storage_dashboard/heatmap_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/miq_c3_config.js
  app/javascript/packs/component-definitions-common.js
  app/stylesheet/charts.scss
  app/views/ems_container/_heatmap.html.haml
  app/views/ems_container/_show_dashboard.html.haml
  app/views/ems_infra/_heatmap.html.haml
  app/views/ems_infra/_show_dashboard.html.haml
  app/views/ems_storage/_heatmap.html.haml
  app/views/ems_storage/_show_block_storage_dashboard.html.haml
  app/views/ems_storage/_show_object_storage_dashboard.html.haml
Labels: enhancement, dependencies

#8185 Fix genealogy tree selection
  app/javascript/oldjs/miq_tree.js
Labels: bug, najdorf/yes?

#8164 Adding ssh and url check for ansible repository form
  app/javascript/components/ansible-repository-form/ansible-repository-form.schema.js
  app/javascript/components/ansible-repository-form/helpers.jsx
  app/javascript/spec/ansible-repository-form/helpers.spec.js
Labels: bug

#8188 Fixed add new time profile error
  app/views/configuration/timeprofile_edit.html.haml
Labels: bug, najdorf/yes?

#8183 Converting control condition list
  app/helpers/condition_helper.rb
  app/javascript/spec/miq-condition/miq-condition-spec.js
  app/javascript/spec/miq-condition/miq-condition.data.js
  app/views/condition/show.html.haml
Labels: enhancement

#8181 Converting control alert-profiles list
  app/helpers/miq_alert_set_helper.rb
  app/javascript/spec/miq-alert-set/__snapshots__/miq-alert-set.spec.js.snap
  app/javascript/spec/miq-alert-set/miq-alert-set.data.js
  app/javascript/spec/miq-alert-set/miq-alert-set.spec.js
  app/views/miq_alert_set/show.html.haml
Labels: enhancement

#8182 Converting control events list
  app/helpers/miq_event_definition_helper.rb
  app/javascript/spec/miq-event-definition/__snapshots__/miq-event-definition.spec.js.snap
  app/javascript/spec/miq-event-definition/miq-event-definition.data.js
  app/javascript/spec/miq-event-definition/miq-event-definition.spec.js
  app/views/miq_event_definition/show.html.haml
Labels: enhancement

#8194 fix console route testcases
  spec/config/routes.pending.yml
Labels: test

#8180 Converting control action list
  app/helpers/miq_action_helper.rb
  app/javascript/spec/miq-action/__snapshots__/miq-action.spec.js.snap
  app/javascript/spec/miq-action/miq-action.data.js
  app/javascript/spec/miq-action/miq-action.spec.js
  app/views/miq_action/show.html.haml
Labels: enhancement

#8184 Remove double flash message
  app/helpers/gtl_helper.rb
  app/javascript/components/gtl-view.jsx
Labels: bug

#8197 March 9th and 14th translations with fixes
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: internationalization

#8198 Add native_console button for ems_infra providers
  app/controllers/ems_infra_controller.rb
  app/helpers/application_helper/toolbar/ems_infra_center.rb
  config/routes.rb
  spec/controllers/ems_infra_controller_spec.rb
Labels: enhancement, compute/infrastructure

#8195 fix sort columns
  lib/gtl_formatter.rb
Labels: bug, najdorf/yes?

#8171 Remove caching from menu manager custom loaders
  app/presenters/menu/custom_loader.rb
  app/presenters/menu/manager.rb
  app/presenters/menu/yaml_loader.rb
  spec/presenters/menu/custom_loader_spec.rb
  spec/presenters/menu/custom_menu_loader_spec.rb
  spec/presenters/menu/menu_manager_spec.rb
Labels: enhancement
