Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2022-10, with the labels that each got.

#8458 Convert catalog summary request-info tabs from HAML to react
  app/helpers/catalog_helper.rb
  app/helpers/request_info_helper.rb
  app/javascript/components/miq-custom-tab/index.jsx
  app/javascript/spec/miq-custom-tab/__snapshots__/miq-custom-tab.spec.js.snap
  app/javascript/spec/miq-custom-tab/miq-custom-tab.spec.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/catalog-custom-component.scss
  app/views/catalog/_sandt_tree_custom_image_form.html.haml
  app/views/catalog/_sandt_tree_request.html.haml
  app/views/catalog/_sandt_tree_show.html.haml
  app/views/miq_request/_prov_wf.html.haml
Labels: enhancement

#8472 Treat our locale json files as binary in git
  .gitattributes
Labels: developer

#8473 Safe delete saved reports
  app/controllers/application_controller.rb
Labels: bug

#8475 Fix dashboard chart legend items in fullscreen in Firefox
  app/stylesheet/dashboard.scss
Labels: bug

#8214 Server Placement Group
  app/controllers/mixins/ems_common.rb
  app/controllers/placement_group_controller.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/placement_group_center.rb
  app/helpers/application_helper/toolbar/placement_groups_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_cloud_helper/textual_summary.rb
  app/helpers/placement_group.rb
  app/helpers/placement_group_helper.rb
  app/helpers/placement_group_helper/textual_summary.rb
  app/helpers/vm_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/miq_request/_prov_field.html.haml
  app/views/placement_group/show.html.haml
  app/views/placement_group/show_list.html.haml
  app/views/shared/views/_prov_dialog.html.haml
  config/routes.rb
  product/views/PlacementGroup.yaml
  product/views/PlacementGroup.yml
  spec/config/routes.pending.yml
  spec/helpers/ems_cloud_helper/textual_summary_spec.rb
  spec/helpers/placement_group_helper/textual_summary_spec.rb
  spec/helpers/vm_helper/textual_summary_spec.rb
  spec/routing/placement_group_routing_spec.rb
Labels: enhancement, compute/cloud

#8481 Fix reference to old placement_group_list feature
  app/presenters/menu/default_menu.rb
Labels: bug

#8476 Fix compare selected items during compare by adding default selected …
  app/controllers/application_controller/compare.rb
Labels: bug

#8482 Fix VM textual summary for placement group
  app/helpers/vm_helper/textual_summary.rb
Labels: bug

#8483 [MORPHY] Manually backport #7834
  lib/manageiq/ui/classic/engine.rb
  manageiq-ui-classic.gemspec
Labels: technical debt

#8433 Timeline options
  app/javascript/components/timeline-options/helper.js
  app/javascript/components/timeline-options/timeline-options-simple.schema.js
  app/javascript/components/timeline-options/timeline-options.jsx
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/timeline/timeline_options_controller.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/timeline-options-form/__snapshots__/timeline-options-form.spec.js.snap
  app/javascript/spec/timeline-options-form/sample-data.js
  app/javascript/spec/timeline-options-form/timeline-options-form.spec.js
  app/views/layouts/_tl_options.html.haml
  app/views/layouts/_tl_show.html.haml
  spec/javascripts/controllers/timeline/timeline_options_controller_spec.js
Labels: enhancement

#8485 October 13 english translations
  app/javascript/oldjs/locale/en.json
Labels: internationalization

#8487 Fix googlefont references
  app/stylesheet/carbon.scss
Labels: bug

#8478 Fix lifecycle provision of template
  app/helpers/vm_cloud_helper.rb
Labels: bug

#8452 New vm resize ddf form created
  app/controllers/mixins/actions/vm_actions/resize.rb
  app/controllers/vm_common.rb
  app/javascript/components/vm-resize-form/vm-resize-form.jsx
  app/javascript/components/vm-resize-form/vm-resize.schema.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/vm_cloud/vm_cloud_resize_form_controller.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/vm-resize-form/__snapshots__/vm-resize-form.spec.js.snap
  app/javascript/spec/vm-resize-form/vm-resize-form.spec.js
  app/views/miq_request/_reconfigure_show.html.haml
  app/views/vm_common/_resize.html.haml
  config/routes.rb
  spec/controllers/mixins/actions/vm_actions/resize_spec.rb
  spec/controllers/vm_cloud_controller_spec.rb
  spec/javascripts/controllers/vm_cloud/vm_cloud_resize_form_controller_spec.js
Labels: enhancement

#8486 switch placement group from text-field to pull down field - vm provis…
  app/views/miq_request/_prov_field.html.haml
Labels: enhancement, compute/cloud

#8493 Updating terser to 4.8.1
  package.json
  yarn.lock
Labels: dependencies, security fix

#8494 Updating d3-color
  package.json
  yarn.lock
Labels: unmergeable, dependencies, security fix

#8495 Fixes Password Field so it is Correctly Rendered as a Text Area
  app/javascript/components/async-credentials/password-field.jsx
  app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
Labels: bug

#8499 Fix container-dashboard's overview's breadcrumb link
  app/controllers/container_dashboard_controller.rb
Labels: bug

#8498 Always display the Provision instance action buttons at the bottom
  app/stylesheet/miq-data-table.scss
  app/views/miq_request/_pre_prov.html.haml
Labels: bug

#8500 choose host initiator group on host creation
  app/javascript/components/host-initiator-form/host-initiator-form.schema.js
Labels: enhancement
