Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2022-05, with the labels that each got.

#8246 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#8250 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#8247 rename CloudVolume#attach_volume to attach
  app/controllers/vm_cloud_controller.rb
  app/helpers/application_helper/button/volume_attach.rb
  app/helpers/application_helper/button/volume_detach.rb
  spec/helpers/application_helper/buttons/volume_attach_spec.rb
  spec/helpers/application_helper/buttons/volume_detach_spec.rb
Labels: enhancement

#8252 fixed cops
  spec/helpers/application_helper/buttons/volume_attach_spec.rb
Labels: technical debt, test

#8243 fix Define New volume Mapping form
  app/javascript/components/volume-mapping-form/volume-mapping-form.schema.js
Labels: bug, najdorf/yes?

#8255 Upgrade webpack-dev-server to 4.9.0
  package.json
  yarn.lock
Labels: dependencies, security fix

#8249 del host initiator
  app/helpers/application_helper/toolbar/host_initiator_center.rb
  app/helpers/application_helper/toolbar/host_initiators_center.rb
Labels: enhancement, compute/physical infrastructure

#8254 Upgrading Attach/Detach functionality
  app/controllers/cloud_volume_controller.rb
  app/javascript/components/cloud-volume-form/attach-detach-cloud-volume-form.jsx
  app/javascript/components/cloud-volume-form/attach-detach-cloud-volume.schema.js
  app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
  app/javascript/spec/cloud-volume-form/attach-detach-cloud-volume-form.spec.js
Labels: enhancement

#8256 [NAJDORF] Upgrade webpack dev server to 4.9.0 on najdorf
  package.json
  yarn.lock
Labels: dependencies, security fix

#8259 Upgrade moment package to 2.29.2
  package.json
  yarn.lock
Labels: dependencies, security fix, najdorf/yes

#8245 Cloud volume create snapshot form conversion
  app/controllers/cloud_volume_controller.rb
  app/javascript/components/cloud-volume-actions-form/create-snapshot.schema.js
  app/javascript/components/cloud-volume-actions-form/helper.js
  app/javascript/components/cloud-volume-actions-form/index.jsx
  app/javascript/oldjs/controllers/cloud_volume/cloud_volume_form_controller.js
  app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
  app/javascript/spec/cloud-volume-actions-form/cloud-volume-actions-form.spec.js
  app/views/cloud_volume/snapshot_new.html.haml
  config/routes.rb
  spec/controllers/cloud_volume_controller_spec.rb
Labels: enhancement

#8260 Fixed translation functions on pagination strings
  app/javascript/components/miq-pagination.jsx
Labels: bug, internationalization

#8257 Convert container projects dashboard
  app/javascript/components/container-projects/area-chart-card.jsx
  app/javascript/components/container-projects/bar-chart-card.jsx
  app/javascript/components/container-projects/chart-card.jsx
  app/javascript/components/container-projects/empty-card.jsx
  app/javascript/components/container-projects/helper.jsx
  app/javascript/components/container-projects/index.jsx
  app/javascript/components/container-projects/table-card.jsx
  app/javascript/components/container-projects/trend-chart-card.jsx
  app/javascript/components/provider-dashboard-charts/charts_config.js
  app/javascript/components/provider-dashboard-charts/pod-trend-charts/index.js
  app/javascript/components/provider-dashboard-charts/pod-trend-charts/podsAreaChart.js
  app/javascript/oldjs/controllers/container_dashboard/container_project_dashboard_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/chart-card/__snapshots__/chart-card.spec.js.snap
  app/javascript/spec/chart-card/chart-card.spec.js
  app/javascript/spec/container-projects/__snapshots__/container-projects.spec.js.snap
  app/javascript/spec/container-projects/container-projects.spec.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/cloud-container-projects-dashboard.scss
  app/views/container_project/_show_dashboard.html.haml
  spec/javascripts/controllers/containers/container_project_dashboard_controller_spec.js
Labels: enhancement

#8175 Allow changing UI worker memory threshold on UI
  app/javascript/components/workers-form/workers-form.jsx
  app/javascript/components/workers-form/workers.schema.js
Labels: enhancement

#8244 Server profile details
  app/controllers/physical_server_controller.rb
  app/helpers/physical_server_helper/textual_summary.rb
  product/views/PhysicalServer.yaml
Labels: enhancement

#8186 Fix View yaml to point to valid fields
  product/views/PhysicalServer.yaml
  product/views/PhysicalStorage.yaml
  product/views/Storage.yaml
Labels: bug, unmergeable, najdorf/yes?

#8265 Fixed IBM Cloud edit provider authentication issue
  app/javascript/components/provider-form/index.jsx
Labels: bug, najdorf/yes?

#8266 move AvailabilityMixin over to SupportsFeatureMixin
  app/controllers/cloud_object_store_container_controller.rb
  app/controllers/mixins/actions/host_actions/misc.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/generic_feature_button_with_disable.rb
  app/helpers/application_helper/button/host_feature_button.rb
  app/helpers/application_helper/button/host_feature_button_with_disable.rb
  spec/controllers/storage_controller_spec.rb
  spec/helpers/application_helper/buttons/generic_feature_button_spec.rb
  spec/helpers/application_helper/buttons/host_feature_button_spec.rb
  spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb
Labels: technical debt

#8263 Fix RemoveGenericItemModal Controlled Component Warning
  app/javascript/components/remove-generic-item-modal.jsx
Labels: bug

#8269 use parent for creating namespaces instead of parent_id
  spec/controllers/miq_ae_class_controller_spec.rb
Labels: test, automation/automate

#8268 convert update_attributes to update
  spec/controllers/catalog_controller_spec.rb
Labels: test, rails6.1

#8272 Remove unused configuration views
  app/views/layouts/listnav/_configuration_profile.html.haml
  app/views/layouts/listnav/_configured_system.html.haml
  app/views/layouts/listnav/_ems_configuration.html.haml
Labels: technical debt

#8273 Remove angular quadicon code
  app/controllers/application_controller/report_downloads.rb
  app/controllers/vm_common.rb
  app/stylesheet/legacy/compare_drift.scss
  app/views/layouts/print.html.haml
  app/views/shared/_compare_header_expanded.html.haml
  app/views/shared/_quadicon.html.haml
Labels: technical debt

#8267 auto call calculate_properties when testing enabled and disabled buttons
  spec/helpers/application_helper/buttons/ae_copy_simulate_spec.rb
  spec/helpers/application_helper/buttons/availability_zone_performance_spec.rb
  spec/helpers/application_helper/buttons/availability_zone_timeline_spec.rb
  spec/helpers/application_helper/buttons/collect_logs_spec.rb
  spec/helpers/application_helper/buttons/customization_template_new_spec.rb
  spec/helpers/application_helper/buttons/dashboard_delete_spec.rb
  spec/helpers/application_helper/buttons/db_new_spec.rb
  spec/helpers/application_helper/buttons/db_seq_edit_spec.rb
  spec/helpers/application_helper/buttons/ems_cluster_performance_spec.rb
  spec/helpers/application_helper/buttons/ems_cluster_timeline_spec.rb
  spec/helpers/application_helper/buttons/host_check_compliance_spec.rb
  spec/helpers/application_helper/buttons/host_performance_spec.rb
  spec/helpers/application_helper/buttons/host_timeline_spec.rb
  spec/helpers/application_helper/buttons/iso_datastore_new_spec.rb
  spec/helpers/application_helper/buttons/miq_action_delete_spec.rb
  spec/helpers/application_helper/buttons/miq_action_edit_spec.rb
  spec/helpers/application_helper/buttons/miq_alert_delete_spec.rb
  spec/helpers/application_helper/buttons/miq_request_delete_spec.rb
  spec/helpers/application_helper/buttons/new_cloud_tenant_spec.rb
  spec/helpers/application_helper/buttons/new_flavor_spec.rb
  spec/helpers/application_helper/buttons/new_host_aggregate_spec.rb
  spec/helpers/application_helper/buttons/orchestration_stack_retire_now_spec.rb
  spec/helpers/application_helper/buttons/rbac_role_delete_spec.rb
  spec/helpers/application_helper/buttons/rbac_role_edit_spec.rb
  spec/helpers/application_helper/buttons/rbac_tenant_delete_spec.rb
  spec/helpers/application_helper/buttons/rbac_user_copy_spec.rb
  spec/helpers/application_helper/buttons/rbac_user_delete_spec.rb
  spec/helpers/application_helper/buttons/report_only_spec.rb
  spec/helpers/application_helper/buttons/service_retire_now_spec.rb
  spec/helpers/application_helper/buttons/set_ownership_spec.rb
  spec/helpers/application_helper/buttons/storage_delete_spec.rb
  spec/helpers/application_helper/buttons/storage_scan_spec.rb
  spec/helpers/application_helper/buttons/view_dashboard_spec.rb
  spec/helpers/application_helper/buttons/view_summary_spec.rb
  spec/helpers/application_helper/buttons/vm_instance_template_scan_spec.rb
  spec/helpers/application_helper/buttons/vm_native_console_spec.rb
  spec/helpers/application_helper/buttons/vm_snapshot_add_spec.rb
  spec/helpers/application_helper/buttons/vm_snapshot_revert_spec.rb
  spec/helpers/application_helper/buttons/vm_vmrc_console_spec.rb
  spec/helpers/application_helper/buttons/zone_delete_spec.rb
  spec/support/examples_group/shared_examples_for_analysis_profile_action_buttons.rb
  spec/support/examples_group/shared_examples_for_check_compliance_buttons.rb
  spec/support/examples_group/shared_examples_for_disabled_buttons.rb
  spec/support/examples_group/shared_examples_for_enabled_buttons.rb
  spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb
  spec/support/examples_group/shared_examples_for_performance_buttons.rb
  spec/support/examples_group/shared_examples_for_rbac_group_buttons.rb
  spec/support/examples_group/shared_examples_for_render_report_buttons.rb
  spec/support/examples_group/shared_examples_for_smart_state_scan_buttons.rb
  spec/support/examples_group/shared_examples_for_timeline_buttons.rb
Labels: test

#8274 Converting host config summary pages from HAML to React
  app/helpers/host_helper.rb
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/spec/miq-action/__snapshots__/miq-action.spec.js.snap
  app/javascript/spec/miq-alert-set/__snapshots__/miq-alert-set.spec.js.snap
  app/javascript/spec/miq-alert/__snapshots__/miq-alert.spec.js.snap
  app/javascript/spec/miq-event-definition/__snapshots__/miq-event-definition.spec.js.snap
  app/javascript/spec/miq-policy-set/__snapshots__/miq-policy-set.spec.js.snap
  app/views/host/_config.html.haml
Labels: enhancement

#8271 SupportsFeatureMixin use stub_supports
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/views/vm_common/_reconfigure.html.haml
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/cloud_object_store_container_spec.rb
  spec/controllers/cloud_object_store_object_spec.rb
  spec/controllers/security_group_controller_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb
  spec/helpers/application_helper/buttons/ems_timeline_spec.rb
  spec/helpers/application_helper/buttons/generic_feature_button_spec.rb
  spec/helpers/application_helper/buttons/host_feature_button_spec.rb
  spec/helpers/application_helper/buttons/instance_associate_floating_ip_spec.rb
  spec/helpers/application_helper/buttons/instance_disassociate_floating_ip_spec.rb
  spec/helpers/application_helper/buttons/instance_reset_spec.rb
  spec/helpers/application_helper/buttons/storage_scan_spec.rb
  spec/helpers/application_helper/buttons/vm_instance_template_scan_spec.rb
  spec/helpers/application_helper/buttons/vm_retire_now_spec.rb
  spec/helpers/application_helper/buttons/vm_retire_spec.rb
  spec/helpers/application_helper/buttons/vm_snapshot_remove_one_spec.rb
  spec/helpers/application_helper/buttons/volume_attach_spec.rb
  spec/helpers/application_helper/buttons/volume_detach_spec.rb
  spec/spec_helper.rb
  spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb
Labels: technical debt

#8278 Removed old configuration manager angular code
  app/javascript/oldjs/controllers/configuration_manager_form_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/services/configuration_manager_service/configuration_manager_service.js
  app/javascript/oldjs/services/index.js
  app/views/configuration_manager/_shared_form.html.haml
  spec/javascripts/controllers/configuration_manager/configuration_manager_form_controller_spec.js
Labels: technical debt

#8280 Update oldjs with May 24th translations
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: enhancement, internationalization, najdorf/yes?

#8284 Remove unused angular aggregate status code
  app/javascript/oldjs/components/index.js
  app/javascript/oldjs/components/pf_charts/aggregate-status-card.component.js
  app/javascript/oldjs/controllers/ems_common/aggregate_status_card_controller.js
  app/javascript/oldjs/controllers/index.js
  app/views/static/ems_common/aggregate-status-card.html.haml
  app/views/static/pf_charts/aggregate-status-card.html.haml
  spec/javascripts/controllers/ems_infra/aggregate_status_card_controller_spec.js
Labels: technical debt

#8285 Remove recent resource haml file
  app/views/static/recent-resource.html.haml
Labels: technical debt

#8283 Delete transform and mass transform vms
  app/controllers/application_controller/ci_processing.rb
  app/controllers/application_controller/explorer.rb
  app/controllers/mixins/actions/provider_actions/mass_transform.rb
  app/controllers/mixins/actions/vm_actions/transform.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper/button/mass_transform_vm_button.rb
  app/helpers/application_helper/button/transform_vm_button.rb
  spec/controllers/ems_infra_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: technical debt
