Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2023-07, with the labels that each got.

#8846 Fixed ansible repository refresh buttons
  app/helpers/application_helper/toolbar/ansible_repository_center.rb
Labels: bug

#8710 Angular to react conversion Reconfigure form
  app/helpers/vm_infra_helper.rb
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/components/reconfigure-vm-form/disk-form-fields.js
  app/javascript/components/reconfigure-vm-form/drive-form-fields.js
  app/javascript/components/reconfigure-vm-form/helper.js
  app/javascript/components/reconfigure-vm-form/helpers/disk.js
  app/javascript/components/reconfigure-vm-form/helpers/drive.js
  app/javascript/components/reconfigure-vm-form/helpers/general.js
  app/javascript/components/reconfigure-vm-form/helpers/network.js
  app/javascript/components/reconfigure-vm-form/index.jsx
  app/javascript/components/reconfigure-vm-form/network-form-fields.js
  app/javascript/components/reconfigure-vm-form/reconfigure-form-fields.js
  app/javascript/components/reconfigure-vm-form/reconfigure-form.schema.js
  app/javascript/components/reconfigure-vm-form/reconfigure-table/index.jsx
  app/javascript/components/reconfigure-vm-form/reconfigure-template.jsx
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/reconfigure/reconfigure_form_controller.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/prov-grid/__snapshots__/prov-grid.spec.js.snap
  app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
  app/javascript/spec/reconfigure-vm-form/data.js
  app/javascript/spec/reconfigure-vm-form/datatable-data.js
  app/javascript/spec/reconfigure-vm-form/reconfigure-table/reconfigure-table.spec.js
  app/javascript/spec/reconfigure-vm-form/reconfigure-vm-form.spec.js
  app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
  app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap
  app/javascript/spec/tenant-quota-form/__snapshots__/tenant-quota-form.spec.js.snap
  app/stylesheet/miq-data-table.scss
  app/views/vm_common/_reconfigure.html.haml
  spec/controllers/vm_infra_controller_spec.rb
  spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js
  spec/views/vm_common/_reconfigure.html.haml_spec.rb
Labels: enhancement

#8848 Mark workflow controllers as prototype
  app/controllers/workflow_controller.rb
  app/controllers/workflow_repository_controller.rb
Labels: enhancement, petrosian/yes?

#8854 Fixed workflow repository specs
  spec/controllers/workflow_repository_controller_spec.rb
Labels: bug

#8851 Fixed tasks table
  app/javascript/components/settings-tasks-form/index.jsx
  app/javascript/components/settings-tasks-form/load-table-helper.js
  app/javascript/spec/settings-tasks_form/__snapshots__/settings-tasks-form.spec.js.snap
  app/views/layouts/_tasks.html.haml
Labels: bug, petrosian/yes?

#8833 Separate role access restrictions for catalog items
  app/controllers/ops_controller/ops_rbac.rb
  app/helpers/ops_helper/role_rbac_details_helper.rb
  app/views/ops/_rbac_role_details.html.haml
Labels: enhancement

#8856 Mark Switch Labels for Translation in Settings-Category Form
  app/javascript/components/settings-category-form/schema.js
  app/javascript/spec/settings-category-form/__snapshots__/settings-category-form.spec.js.snap
Labels: bug

#8855 Fixed cypress logout test
  cypress/e2e/ui/login.cy.js
Labels: test, cypress

#8857 Added Overview > Dashboard Cypress tests
  cypress/e2e/ui/Overview/dashboard.cy.js
Labels: test, cypress

#8861 Update cypress version
  package.json
  yarn.lock
Labels: test, dependencies, cypress

#8860 Fixed dashboard tests
  cypress/e2e/ui/Overview/dashboard.cy.js
Labels: test, cypress

#8852 Filter effect text and clear option missing in sub listing pages
  app/controllers/vm_common.rb
Labels: bug, petrosian/yes?

#8804 Fix overview->assignments accessibility check violation
  app/views/chargeback_assignment/_form.html.haml
Labels: bug

#8863 Delete the cypress videos for passing tests on CI
  cypress.config.js
Labels: test, cypress

#8844 Introducing embedded_workflow to dynamic select box in service dialogs
  app/controllers/catalog_controller.rb
  app/controllers/mixins/automation_mixin.rb
  app/helpers/miq_ae_customization_helper.rb
  app/javascript/oldjs/controllers/dialog_editor/dialog_editor_controller.js
  app/javascript/oldjs/services/dialog_editor_http_service.js
  app/views/miq_ae_customization/editor.html.haml
  package.json
  yarn.lock
Labels: enhancement, dependencies

#8866 Add Cypress to GitHub Actions
  .github/workflows/cypress.yaml
  Rakefile
  bin/before_install
  bin/setup
Labels: test, cypress

#8862 Add Missing Routes to Configuration Profiles
  config/routes.rb
  spec/config/routes.pending.yml
Labels: bug, morphy/yes?, petrosian/yes?

#8864 po to json from July 11th
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: enhancement, internationalization, petrosian/yes?

#8815 Adding embedded workflows to service catalog item
  app/controllers/catalog_controller.rb
  app/controllers/mixins/automation_mixin.rb
  app/helpers/automate_tree_helper.rb
  app/helpers/catalog_helper.rb
  app/javascript/components/workflows/helper.js
  app/javascript/components/workflows/workflow-entry-points.jsx
  app/javascript/oldjs/miq_application.js
  app/javascript/packs/component-definitions-common.js
  app/stylesheet/miq-data-table.scss
  app/views/catalog/_embedded_workflows_modal.html.haml
  app/views/catalog/_entry_point_selector.html.haml
  app/views/catalog/_form_basic_info.html.haml
  app/views/catalog/_provision_entry_point.html.haml
  app/views/catalog/_reconfigure_entry_point.html.haml
  app/views/catalog/_retire_entry_point.html.haml
  config/routes.rb
  spec/config/routes.pending.yml
  spec/controllers/catalog_controller_spec.rb
Labels: enhancement, dependencies

#8868 Fix utilization chart
  app/javascript/components/performance-charts/groupChart.js
  app/javascript/components/performance-charts/index.jsx
Labels: bug, morphy/yes, petrosian/yes

#8869 [MORPHY] Fix Data/X-Axis Display Issue in Performance Charts
  app/javascript/components/carbon-charts/helpers.js
  app/javascript/components/performance-charts/areaChart.js
  app/javascript/components/performance-charts/lineChart.js
Labels: bug

#8872 [MORPHY] Add Missing Routes to Configuration Profiles
  config/routes.rb
  spec/config/routes.pending.yml
Labels: bug

#8870 Update GitHub Actions versions
  .github/workflows/ci.yaml
  .github/workflows/cypress.yaml
Labels: dependencies

#8879 Ensure yarn.lock is not updated by yarn install
  lib/tasks/manageiq/ui_tasks.rake
Labels: bug, petrosian/yes
