Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2023-03, with the labels that each got.

#8648 React Schedule Component refactor
  app/controllers/ops_controller/settings/schedules.rb
  app/javascript/components/schedule-form/helper.js
  app/javascript/components/schedule-form/index.jsx
  app/javascript/components/schedule-form/schedule-form-fields.js
  app/javascript/components/schedule-form/schedule-form.schema.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/schedule/schedule_form_controller.js
  app/javascript/spec/schedule-form/__snapshots__/schedule-form.spec.js.snap
  app/stylesheet/settings.scss
  spec/javascripts/controllers/schedule/schedule_form_controller_spec.js
Labels: technical debt

#8656 Capabilities fields modification and parsing
  app/helpers/storage_resource_helper/textual_summary.rb
  app/helpers/storage_service_helper/textual_summary.rb
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
  app/javascript/components/cloud-volume-form/index.jsx
  app/javascript/components/storage-service-form/index.jsx
  app/javascript/components/storage-service-form/storage-service-form.schema.js
  app/javascript/helpers/enhanced-select.js
  app/javascript/helpers/load-capabilities.js
  app/javascript/helpers/storage_manager/filter-by-capabilities-utils.js
  app/javascript/helpers/storage_manager/filter-resources-by-capabilities.js
  app/javascript/helpers/storage_manager/filter-service-by-capabilities.js
  app/javascript/helpers/storage_manager/load-provider-capabilities.js
  app/javascript/helpers/storage_manager/validate-names.js
Labels: enhancement

#8677 Regenerated yarn.lock file
  app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
  app/javascript/spec/cloud-object-store-container-form/__snapshots__/cloud-object-store-container-form.spec.js.snap
  app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
  app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
  app/javascript/spec/vm-floating-ips-form/__snapshots__/vm-floating-ips-form.spec.js.snap
  yarn.lock
Labels: security fix, petrosian/yes?

#8659 Refactor build_audit_* methods and reuse password masking from core
  app/controllers/application_controller.rb
  app/controllers/host_controller.rb
  app/controllers/miq_ae_class_controller.rb
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/ops_rbac.rb
  app/controllers/ops_controller/settings/analysis_profiles.rb
  app/controllers/ops_controller/settings/common.rb
  app/controllers/ops_controller/settings/schedules.rb
  spec/controllers/application_controller/build_audit_spec.rb
  spec/controllers/ops_controller_spec.rb
Labels: refactoring, petrosian/yes?

#8667 Link component redirects correctly now
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/textual_summary.test.js.snap
Labels: bug

#8632 volume create basic mode: validate chosen service has attached resources
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
Labels: bug

#8676 Order Container#hourly_metrics for widgets
  app/services/container_service_mixin.rb
Labels: bug, bug/sporadic test failure

#8673 Fix for provider dashboard page where items were not being loaded
  app/javascript/components/ems_container_dashboard/helper.js
  app/javascript/components/ems_container_dashboard/index.js
  app/services/container_dashboard_service.rb
Labels: bug, petrosian/yes?

#8674 Fix for chargeback saved reports with undefined method
  app/helpers/chargeback_report_helper.rb
Labels: bug, petrosian/yes?

#8680 host initiator name length validation
  app/javascript/components/host-initiator-form/host-initiator-form.schema.js
Labels: enhancement

#8679 JSON translations fixes from core PR 22389
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: petrosian/yes

#8685 Fix forbidden pages notification
  app/controllers/application_controller.rb
Labels: bug, petrosian/yes

#8684 Fixed users dropdown + adds spec tests
  app/javascript/components/service-request-default/index.jsx
  app/javascript/components/service-request-default/service-request-default.schema.js
  app/javascript/spec/service-request-default-form/__snapshots__/service-request-default-form.spec.js.snap
  app/javascript/spec/service-request-default-form/dummy-data.js
  app/javascript/spec/service-request-default-form/service-request-default-form.spec.js
Labels: bug, najdorf/yes?, oparin/yes?, petrosian/yes

#8644 Settings map tabs list conversion from HAML to react
  app/helpers/ops_helper.rb
  app/helpers/ops_helper/settings_label_tag_mapping_helper.rb
  app/javascript/components/settings-label-tag-mapping/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap
  app/javascript/spec/settings-label-tag-mapping/data.js
  app/javascript/spec/settings-label-tag-mapping/settings-label-tag-mapping.spec.js
  app/stylesheet/miq-custom-tab.scss
  app/views/ops/_settings_label_tag_mapping_tab.html.haml
  spec/views/ops/_settings_label_tag_mapping_tab.html.haml_spec.rb
Labels: enhancement

#8681 Fix group switching dropdown visibility
  app/javascript/menu/group-switcher.jsx
  app/stylesheet/menu.scss
Labels: bug, petrosian/yes

#8692 Bump caniuse-lite
  yarn.lock
Labels: dependencies

#8696 Updated po_to_json from core 22399
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: internationalization, petrosian/yes

#8697 Fixing Link Component
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/textual_summary.test.js.snap
Labels: bug

#8678 Fix for selected item missing in genealogy compare selector
  app/javascript/components/tree-view/redux.jsx
  app/javascript/oldjs/miq_tree.js
  app/stylesheet/tree.scss
Labels: bug, petrosian/yes

#8694 Add big banner around the app controller default error handler
  app/controllers/application_controller.rb
Labels: cleanup

#8686 Schedule summary conversion from HAML to React
  app/helpers/ops_helper.rb
  app/helpers/settings_schedule_helper.rb
  app/views/ops/_schedule_show.html.erb
  app/views/ops/_schedule_show.html.haml
Labels: enhancement

#8706 Fix forbidden page notifications for configurations page
  app/controllers/configuration_controller.rb
  spec/config/routes.pending.yml
Labels: bug, petrosian/yes

#8705 changing backticks to single quotes
  app/helpers/settings_schedule_helper.rb
Labels: bug

#8698 Fixed bug in schedule form
  app/javascript/components/schedule-form/helper.js
  app/javascript/components/schedule-form/index.jsx
  app/javascript/components/schedule-form/schedule-form-fields.js
  app/javascript/spec/schedule-form/__snapshots__/schedule-form.spec.js.snap
Labels: bug

#8703 Try to catch ui classic security issues before they're merged
  .github/workflows/ci.yaml
  Rakefile
Labels: enhancement, petrosian/yes?

#8711 Correct Missing Service Summary Tabs
  app/views/service/show.html.haml
Labels: bug, petrosian/yes

#8713 Fix summary label wrapping for long text without spaces
  app/stylesheet/miq-structured-list.scss
Labels: bug

#8672 Live migrate form angular to react conversion
  app/javascript/components/live-migrate-form/helper.js
  app/javascript/components/live-migrate-form/index.jsx
  app/javascript/components/live-migrate-form/live-migrate-form.schema.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/controllers/vm_cloud/vm_cloud_live_migrate_form_controller.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/live-migrate-form/__snapshots__/live-migrate-form.spec.js.snap
  app/javascript/spec/live-migrate-form/data.js
  app/javascript/spec/live-migrate-form/live-migrate-form.spec.js
  app/stylesheet/settings.scss
  app/views/vm_common/_live_migrate.html.haml
  spec/javascripts/controllers/vm_cloud/vm_cloud_live_migrate_form_controller_spec.js
Labels: enhancement

#8691 server summary conversion from HAML to React
  app/helpers/ops_helper.rb
  app/helpers/ops_helper/settings_server_desc_helper.rb
  app/views/ops/_server_desc.html.erb
  app/views/ops/_server_desc.html.haml
Labels: enhancement

#8618 Create physical storage with capabilities
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
  app/javascript/components/physical-storage-form/index.jsx
  app/javascript/components/physical-storage-form/physical-storage-form.schema.js
  app/javascript/components/storage-service-form/storage-service-form.schema.js
  app/javascript/helpers/storage_manager/filter-by-capabilities-utils.js
  app/javascript/helpers/storage_manager/filter-service-by-capabilities.js
  app/javascript/helpers/storage_manager/load-provider-capabilities.js
  app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap
  app/javascript/spec/physical-storage-form/physical-storage-form.spec.js
Labels: enhancement

#8662 Select storage resources to attach in storage service create
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
  app/javascript/components/storage-service-form/index.jsx
  app/javascript/components/storage-service-form/storage-service-form.schema.js
Labels: enhancement, unmergeable

#8688 Zone summary conversion from HAML to React
  app/helpers/ops_helper.rb
  app/helpers/ops_helper/settings_zone_helper.rb
  app/views/ops/_settings_evm_servers_tab.html.erb
  app/views/ops/_settings_evm_servers_tab.html.haml
Labels: enhancement

#8721 Toggle primary nav menu item
  app/javascript/menu/main-menu.jsx
Labels: bug

#8712 Fixed Text Overlap in NavMenu Search Bar
  app/javascript/menu/search.jsx
Labels: bug

#8730 Remove empty, duplicated, or incorrectly split up files.
  app/controllers/miq_event_controller.rb
  app/helpers/miq_template_helper.rb
  app/helpers/miq_template_helper/textual_summary.rb
  app/helpers/placement_group.rb
  app/presenters/tree_builder_condition.rb
Labels: technical debt

#8716 Sorting timeline data by date
  app/javascript/components/timeline-options/timeline-helper.js
Labels: bug, petrosian/yes?

#8717 Rbac tag summary conversion from HAML to React
  app/helpers/ops_helper.rb
  app/helpers/settings_rbac_tag_helper.rb
  app/views/ops/_rbac_tag_box.html.erb
  app/views/ops/_rbac_tag_box.html.haml
Labels: enhancement

#8733 Removing flash message
  app/controllers/application_controller/timelines.rb
Labels: enhancement, petrosian/yes?

#8725 Fix for `Service#service_retire_now` retiring VMs
  app/controllers/service_controller.rb
  spec/controllers/service_controller_spec.rb
Labels: bug, oparin/yes?, petrosian/yes?

#8670 added name validation to name field
  app/javascript/components/cloud-volume-form/clone-cloud-volume-form.jsx
  app/javascript/components/cloud-volume-form/clone-cloud-volume.schema.js
Labels: enhancement

#8641 add delete and update to host initiator groups
  app/controllers/host_initiator_group_controller.rb
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/toolbar/host_initiator_group_center.rb
  app/helpers/application_helper/toolbar/host_initiator_groups_center.rb
  app/helpers/application_helper/toolbar/storage_services_center.rb
  app/javascript/components/host-initiator-group-form/editing-context.js
  app/javascript/components/host-initiator-group-form/host-initiator-group-form.schema.js
  app/javascript/components/host-initiator-group-form/index.jsx
  app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
  app/views/host_initiator_group/edit.html.haml
  config/routes.rb
Labels: enhancement
