Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2023-02, with the labels that each got.

#8522 Add shared processor pool field option to provision form
  app/views/miq_request/_prov_field.html.haml
  app/views/shared/views/_prov_dialog.html.haml
Labels: enhancement

#8605 Fix translation for settings collect log form title
  app/javascript/components/diagnostics-collect-log-form/schema.js
Labels: enhancement

#8614 Ensure success and failure audit logs are cut
  app/controllers/application_controller.rb
  app/controllers/mixins/actions/vm_actions/reconfigure.rb
  app/controllers/mixins/actions/vm_actions/resize.rb
  spec/controllers/application_controller_spec.rb
Labels: enhancement

#8620 Ofer/765865 disable volume validation when editing
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
  app/javascript/helpers/validate-names.js
Labels: bug

#8626 remove host_os_create_types
  app/views/host/_form.html.haml
Labels: technical debt

#8627 Add session id logging
  app/controllers/application_controller.rb
Labels: enhancement

#8629 Add physical storage column to volumes list
  product/views/CloudVolume.yaml
Labels: enhancement

#8634 Bump http-cache-semantics
  package.json
  yarn.lock
Labels: dependencies, security fix

#8630 validate name in volumes
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
Labels: enhancement

#8615 Fix Policies accessibility violations
  app/stylesheet/legacy/patternfly_overrides.scss
  app/views/layouts/_center_div_no_listnav.html.haml
  app/views/miq_policy_export/_export.html.haml
Labels: bug, accessibility

#8611 Fix Services accessibility violations
  app/javascript/components/filter-dropdown/index.js
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/components/miq-pagination.jsx
  app/javascript/menu/search.jsx
  app/javascript/spec/filter-dropdown/__snapshots__/filter-dropdown.spec.js.snap
  app/stylesheet/data-table.scss
  app/stylesheet/ddf_override.scss
  app/views/layouts/_center_div_with_listnav.html.haml
Labels: bug, accessibility

#8621 Fix selected items during compare
  app/controllers/vm_common.rb
Labels: bug

#8623 Fixes in volume create
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
Labels: bug

#8637 Disable Remove service from inventory button when no services are sel…
  app/helpers/application_helper/toolbar/service/vmdb_mixin.rb
Labels: bug

#8617 storage service endpoint
  app/controllers/mixins/ems_common.rb
  app/controllers/storage_resource_controller.rb
  app/controllers/storage_service_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/button/storage_service_new.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/storage_service_center.rb
  app/helpers/application_helper/toolbar/storage_services_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/cloud_volume_helper/textual_summary.rb
  app/helpers/ems_storage_helper/textual_summary.rb
  app/helpers/storage_resource_helper/textual_summary.rb
  app/helpers/storage_service_helper.rb
  app/helpers/storage_service_helper/textual_summary.rb
  app/javascript/components/storage-service-form/index.jsx
  app/javascript/components/storage-service-form/storage-service-form.schema.js
  app/javascript/helpers/load-capabilities.js
  app/javascript/packs/component-definitions-common.js
  app/presenters/menu/default_menu.rb
  app/services/ems_storage_dashboard_service.rb
  app/views/storage_service/new.html.erb
  app/views/storage_service/show.html.haml
  app/views/storage_service/show_list.html.haml
  config/routes.rb
  product/views/StorageService.yaml
  spec/config/routes.pending.yml
  spec/helpers/cloud_volume_helper/textual_summary_spec.rb
  spec/helpers/ems_storage_helper/textual_summary_spec.rb
  spec/presenters/menu/default_menu_spec.rb
Labels: enhancement

#8631 enhanced storage resource textual summary page
  app/controllers/storage_resource_controller.rb
  app/helpers/storage_resource_helper/textual_summary.rb
  config/routes.rb
  spec/config/routes.pending.yml
Labels: enhancement, storage

#8562 React Timeline Chart and Table Component
  app/controllers/application_controller/timelines.rb
  app/javascript/components/timeline-options/timeline-chart.jsx
  app/javascript/components/timeline-options/timeline-helper.js
  app/javascript/components/timeline-options/timeline-options-simple.schema.js
  app/javascript/components/timeline-options/timeline-options.jsx
  app/javascript/components/timeline-options/timeline-page.jsx
  app/javascript/components/timeline-options/timeline-table.jsx
  app/javascript/oldjs/application.js
  app/javascript/oldjs/miq_timeline.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/packs/globals.js
  app/javascript/spec/timeline-options-form/__snapshots__/timeline-chart.spec.js.snap
  app/javascript/spec/timeline-options-form/__snapshots__/timeline-options-form.spec.js.snap
  app/javascript/spec/timeline-options-form/__snapshots__/timeline-table.spec.js.snap
  app/javascript/spec/timeline-options-form/sample-table-data.js
  app/javascript/spec/timeline-options-form/timeline-chart.spec.js
  app/javascript/spec/timeline-options-form/timeline-options-form.spec.js
  app/javascript/spec/timeline-options-form/timeline-page.spec.js
  app/javascript/spec/timeline-options-form/timeline-table.spec.js
  app/stylesheet/application-webpack.scss
  app/stylesheet/charts.scss
  app/stylesheet/miq-data-table.scss
  app/views/dashboard/_tl_detail.html.haml
  app/views/layouts/_timeline.html.haml
  app/views/layouts/_tl_detail.html.haml
  app/views/layouts/_tl_show.html.haml
  package.json
  spec/javascripts/globals_pack_spec.js
  yarn.lock
Labels: enhancement, dependencies

#8638 Convert assert_rbac from Rbac.search to Rbac.filtered
  app/controllers/application_controller.rb
Labels: performance

#8643 Removing missed d3 require checks
  app/javascript/packs/globals.js
  spec/javascripts/globals_pack_spec.js
Labels: bug

#8400 Display Request Logs in Services->Requests
  app/javascript/components/data-tables/requests-table/index.jsx
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/miq-data-table/__snapshots__/miq-data-table.spec.js.snap
  app/javascript/spec/prov-grid/__snapshots__/prov-grid.spec.js.snap
  app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
  app/javascript/spec/tenant-quota-form/__snapshots__/tenant-quota-form.spec.js.snap
  app/javascript/spec/timeline-options-form/__snapshots__/timeline-table.spec.js.snap
  app/stylesheet/miq-data-table.scss
  app/views/miq_request/_request.html.haml
Labels: enhancement

#8645 Settings zone list conversion from HAML to React
  app/helpers/ops_helper.rb
  app/helpers/zones_helper.rb
  app/javascript/components/settings-zone/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/stylesheet/miq-data-table.scss
  app/views/ops/_settings_list_tab.html.haml
Labels: enhancement

#8646 Edited _request.haml to Make Code Clearer
  app/views/miq_request/_request.html.haml
Labels: technical debt

#8650 Hide Monitor menu
  app/presenters/menu/default_menu.rb
  config/routes.rb
Labels: technical debt

#8636 Fix dashboard widget overflow menu list visibility
  app/javascript/components/dashboard-widgets/widget-wrapper/index.jsx
Labels: bug

#8607 Convert Company tags contents from HAML to React
  app/controllers/ops_controller/settings/tags.rb
  app/helpers/ops_helper.rb
  app/helpers/ops_helper/settings_tab_helper.rb
  app/helpers/settings_tags_tabs_helper.rb
  app/javascript/components/miq-data-table/helper.js
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/components/miq-structured-list/helpers.js
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/components/miq-structured-list/miq-structured-list-inputs.jsx
  app/javascript/components/settings-company-tags-entry-form/index.jsx
  app/javascript/components/settings-company-tags-entry-form/schema.js
  app/javascript/components/settings-company-tags/helper.js
  app/javascript/components/settings-company-tags/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/miq-alert-set/__snapshots__/miq-alert-set.spec.js.snap
  app/javascript/spec/miq-policy-set/__snapshots__/miq-policy-set.spec.js.snap
  app/stylesheet/miq-data-table.scss
  app/views/ops/_classification_entry.html.haml
  app/views/ops/_settings_co_tags_tab.html.haml
  config/routes.rb
  spec/config/routes.pending.yml
Labels: enhancement, petrosian/yes?

#8663 Fix javascript specs by moving to new Chrome headless mode
  spec/javascripts/support/jasmine_helper.rb
Labels: bug, test, morphy/yes, najdorf/yes, oparin/yes, petrosian/yes

#8658 Fixing a Typo
  app/javascript/components/schedule-form/schedule-form-fields.js
  app/javascript/spec/schedule-form/__snapshots__/schedule-form.spec.js.snap
Labels: enhancement

#8669 Fix spec:javascript issue with getting the fixtures
  spec/javascripts/controllers/tree_view_controller/tree_view_controller_spec.js
Labels: test

#8668 po_to_json using ManageIQ/manageiq#22378
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: internationalization, petrosian/yes?

#8665 Add handling of older Chrome versions in jasmine specs
  spec/javascripts/support/jasmine_helper.rb
Labels: test
