Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2023-06, with the labels that each got.

#8810 Container and container node timelines require ems
  spec/controllers/container_controller_spec.rb
  spec/controllers/container_node_controller_spec.rb
Labels: bug, test, petrosian/no

#8805 Initial cypress fix
  app/views/layouts/_tabs.html.haml
  cypress.json
  cypress/integration/ui/gtl.spec.js
  cypress/integration/ui/login.spec.js
  cypress/integration/ui/menu.spec.js
  cypress/integration/ui/searchbox.spec.js
  cypress/integration/ui/settings.spec.js
  cypress/integration/ui/toolbar.spec.js
  cypress/support/assertions/expect_title.js
  cypress/support/commands/explorer.js
  cypress/support/commands/gtl.js
  cypress/support/commands/login.js
  cypress/support/commands/menu.js
  cypress/support/commands/search.js
  cypress/support/commands/toolbar.js
  spec/controllers/orchestration_stack_controller_spec.rb
Labels: test, cypress

#8811 Update cypress
  cypress.config.js
  cypress.json
  cypress/e2e/ui/gtl.cy.js
  cypress/e2e/ui/login.cy.js
  cypress/e2e/ui/menu.cy.js
  cypress/e2e/ui/searchbox.cy.js
  cypress/e2e/ui/settings.cy.js
  cypress/e2e/ui/toolbar.cy.js
  cypress/support/e2e.js
  package.json
  yarn.lock
Labels: dependencies

#8800 Updated rake locale: po_to_json from May 14th catalogs
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: enhancement, internationalization

#8813 Added menu item tests to check for non error screens
  app/views/layouts/_tabs.html.haml
  cypress.config.js
  cypress/e2e/ui/menu.cy.js
Labels: test, cypress

#8818 Fixed Provider Edit Form Preventing You From Saving Without Changing The Name
  app/javascript/components/provider-form/index.jsx
Labels: bug, petrosian/yes?

#8820 Change redirects to be portable
  spec/javascripts/support/jasmine_helper.rb
Labels: bug

#8819 Fixed missing menu tests
  cypress/e2e/ui/menu.cy.js
Labels: test, cypress

#8822 Fix searchbox cypress tests
  cypress/e2e/ui/searchbox.cy.js
  cypress/support/commands/search.js
Labels: test, cypress

#8814 Enhance the MiqStructuredList for summary pages
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/stylesheet/miq-structured-list.scss
Labels: enhancement

#8825 Fix text truncation in data tables
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/stylesheet/miq-data-table.scss
Labels: bug, petrosian/yes?

#8824 Fixed empty db menu tests
  cypress/support/commands/menu.js
Labels: test, cypress

#8828 Add logout cypress test
  cypress/e2e/ui/login.cy.js
Labels: test, cypress

#8830 Remove unneccessary cypress tests
  cypress/e2e/ui/gtl.cy.js
  cypress/e2e/ui/settings.cy.js
  cypress/e2e/ui/toolbar.cy.js
Labels: technical debt, test, cypress

#8829 Update searchbox tests
  cypress/e2e/ui/searchbox.cy.js
Labels: test, cypress

#8821 Translation fixes from 06/01
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: bug, internationalization, petrosian/yes

#8831 Fix page title on auth_error screen
  app/controllers/dashboard_controller.rb
Labels: bug

#8835 Added Button Helper For Embedded Workflows
  app/helpers/application_helper/button/embedded_workflow.rb
Labels: enhancement, embedded workflows

#8827 Fixed physical providers empty page
  app/javascript/components/pf_aggregate_status_card.jsx
Labels: bug

#8832 Enhance data tables to fix minor alignments issues
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/stylesheet/miq-data-table.scss
Labels: bug, petrosian/yes

#8843 Fix the request refresh button
  app/controllers/miq_request_controller.rb
Labels: bug

#8841 Fix dropdown options that overlaps with header
  app/stylesheet/legacy/dialog_fields.scss
Labels: bug

#8809 failure in resource compliance check in storage service update shouldn't block form submission
  app/javascript/components/storage-service-form/get-compliant-resources.jsx
Labels: bug, petrosian/yes?
