Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2023-05, with the labels that each got.

#8770 Changed Button To Force Menu to Collapse on Click
  app/javascript/menu/main-menu.jsx
Labels: bug, petrosian/yes?

#8766 Role rbac summary conversion
  app/helpers/ops_helper.rb
  app/helpers/ops_helper/role_rbac_details_helper.rb
  app/views/ops/_rbac_role_details.html.haml
Labels: enhancement

#8776 add icon for non_operational
  lib/gtl_formatter.rb
Labels: bug

#8750 storage service edit mode: check which attached resources are compliant to selected capabilities
  app/javascript/components/async-action-button.jsx
  app/javascript/components/storage-service-form/get-compliant-resources.jsx
  app/javascript/components/storage-service-form/index.jsx
  app/javascript/components/storage-service-form/storage-service-form.schema.js
Labels: enhancement, storage

#8647 Implement cloud snapshot collector, list page, create & delete methods
  app/helpers/application_helper/toolbar/cloud_volume_snapshot_center.rb
  app/helpers/application_helper/toolbar/cloud_volume_snapshots_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/services/ems_storage_dashboard_service.rb
Labels: enhancement

#8778 update non_operational to match other non_operational status
  lib/gtl_formatter.rb
Labels: bug, petrosian/yes?

#8771 Add support for zeitwerk autoloader/reloader
  Rakefile
  app/controllers/application_controller.rb
  app/controllers/catalog_controller.rb
  app/controllers/configuration_controller.rb
  app/controllers/container_build_controller.rb
  app/controllers/container_controller.rb
  app/controllers/container_group_controller.rb
  app/controllers/container_image_controller.rb
  app/controllers/container_image_registry_controller.rb
  app/controllers/container_node_controller.rb
  app/controllers/container_project_controller.rb
  app/controllers/container_replicator_controller.rb
  app/controllers/container_route_controller.rb
  app/controllers/container_service_controller.rb
  app/controllers/container_template_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/ems_container_controller.rb
  app/controllers/mixins/chargeback_preview.rb
  app/controllers/mixins/chargeback_preview_mixin.rb
  app/controllers/mixins/containers_common_mixin.rb
  app/controllers/mixins/containers_external_logging_support_mixin.rb
  app/controllers/mixins/sandbox.rb
  app/controllers/mixins/service_dialog_creation_mixin.rb
  app/controllers/mixins/start_url.rb
  app/controllers/mixins/vm_show_mixin.rb
  app/controllers/persistent_volume_controller.rb
  app/controllers/vm_cloud_controller.rb
  app/controllers/vm_common.rb
  app/controllers/vm_infra_controller.rb
  app/controllers/vm_or_template_controller.rb
  app/helpers/application_helper.rb
  app/helpers/textual_mixins/device.rb
  app/helpers/textual_mixins/textual_devices.rb
  app/presenters/tree_state.rb
  lib/gtl_formatter.rb
  lib/manageiq-ui-classic.rb
  lib/manageiq/ui/classic/engine.rb
  manageiq-ui-classic.gemspec
  spec/controllers/sandbox_spec.rb
  spec/helpers/textual_mixins/textual_devices_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#8779 Fix quota list visibility for tenants
  app/helpers/ops_helper/textual_summary.rb
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/components/textual_summary/table_list_view.jsx
  app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/views/ops/_rbac_tenant_details.html.haml
Labels: bug, petrosian/yes

#8639 iterator errors as an array (6.1.3.1 change)
  app/controllers/ops_controller/settings/common.rb
Labels: bug, rails6.1

#8789 Fix for missing tab contents while adding service catalog item and provisioning instance
  app/stylesheet/miq-custom-tab.scss
  app/views/miq_request/_prov_wf.html.haml
Labels: bug

#8788 Mark Strings in Request Details for Translation
  app/controllers/mixins/breadcrumbs_mixin.rb
  app/helpers/request_details_helper.rb
  app/views/layouts/_tabs.html.haml
Labels: bug

#8785 Fix snapshots for TableListView component
  app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
  app/javascript/spec/textual_summary/data/table_list_view.js
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/javascript/spec/textual_summary/tests/table_list_view.test.js
Labels: test, petrosian/yes?

#8792 [PETROSIAN] Fixing snapshots for TableListView component
  app/helpers/ops_helper/textual_summary.rb
  app/javascript/components/miq-structured-list/index.jsx
  app/javascript/components/textual_summary/table_list_view.jsx
  app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
  app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
  app/javascript/spec/textual_summary/data/table_list_view.js
  app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
  app/views/ops/_rbac_tenant_details.html.haml
Labels: bug

#8756 fix refresh for storage manager models
  app/controllers/cloud_volume_controller.rb
  app/controllers/host_initiator_controller.rb
  app/controllers/host_initiator_group_controller.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/ems_common/metrics.rb
  app/controllers/mixins/ems_common/refresh.rb
  app/controllers/physical_storage_controller.rb
  app/controllers/storage_service_controller.rb
  app/controllers/volume_mapping_controller.rb
  app/helpers/application_helper/toolbar/cloud_volume_center.rb
  app/helpers/application_helper/toolbar/cloud_volumes_center.rb
  app/helpers/application_helper/toolbar/host_initiator_center.rb
  app/helpers/application_helper/toolbar/host_initiator_group_center.rb
  app/helpers/application_helper/toolbar/host_initiator_groups_center.rb
  app/helpers/application_helper/toolbar/host_initiators_center.rb
  app/helpers/application_helper/toolbar/physical_storage_center.rb
  app/helpers/application_helper/toolbar/physical_storages_center.rb
  app/helpers/application_helper/toolbar/storage_service_center.rb
  app/helpers/application_helper/toolbar/storage_services_center.rb
  app/helpers/application_helper/toolbar/volume_mapping_center.rb
  app/helpers/application_helper/toolbar/volume_mappings_center.rb
Labels: bug

#8774 Adding menu items and pages for Workflows, WorkFlowCredentials, WorkflowRepositories
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/controllers/workflow_controller.rb
  app/controllers/workflow_repository_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/title.rb
  app/helpers/workflow_helper.rb
  app/helpers/workflow_helper/textual_summary.rb
  app/helpers/workflow_repository_helper.rb
  app/helpers/workflow_repository_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/layouts/_tag_edit_items.html.haml
  app/views/workflow/show.html.haml
  app/views/workflow/show_list.html.haml
  app/views/workflow_repository/show.html.haml
  app/views/workflow_repository/show_list.html.haml
  config/routes.rb
  product/views/ManageIQ_Providers_EmbeddedAnsible_AutomationManager_ConfigurationScriptSource.yaml
  product/views/ManageIQ_Providers_Workflows_AutomationManager_ConfigurationScriptSource.yaml
  product/views/ManageIQ_Providers_Workflows_AutomationManager_Workflow.yaml
  spec/config/routes.pending.yml
  spec/controllers/ansible_credential_controller_spec.rb
Labels: enhancement

#8795 Fix for timing issues in search bar component
  app/javascript/components/search-bar/index.jsx
  app/javascript/spec/search-bar/__snapshots__/search-bar.spec.js.snap
Labels: bug

#8604 Ofer/326040 list capabilities for physical storage
  app/helpers/physical_storage_helper/textual_summary.rb
  spec/helpers/physical_storage_helper/textual_summary_spec.rb
Labels: enhancement

#8783 Remove monitoring code
  app/controllers/alerts_list_controller.rb
  app/controllers/alerts_overview_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/title.rb
  app/javascript/oldjs/controllers/alerts/alerts_list_controller.js
  app/javascript/oldjs/controllers/alerts/alerts_overview_controller.js
  app/javascript/oldjs/controllers/alerts/edit_alert_dialog_controller.js
  app/javascript/oldjs/controllers/index.js
  app/javascript/oldjs/services/alerts_center_service.js
  app/javascript/oldjs/services/index.js
  app/presenters/menu/default_menu.rb
  app/views/alerts_list/show.html.haml
  app/views/alerts_overview/show.html.haml
  app/views/layouts/_center_div_no_listnav.html.haml
  app/views/shared/views/_alerts_list.html.haml
  app/views/shared/views/_show_alerts_list.html.haml
  app/views/shared/views/_show_alerts_overview.html.haml
  spec/config/routes.pending.yml
  spec/javascripts/controllers/alerts_center/alerts_list_controller_spec.js
  spec/javascripts/controllers/alerts_center/alerts_overview_controller_spec.js
  spec/javascripts/services/alerts_center_service_spec.js
Labels: technical debt

#8796 drop Vmdb::GlobalMethod#column_type
  app/controllers/application_controller.rb
Labels: technical debt

#8794 Adding payload data to workflows
  app/javascript/components/workflows/workflow_payload.jsx
  app/javascript/packs/component-definitions-common.js
  app/views/workflow/show.html.haml
  package.json
  yarn.lock
Labels: enhancement, dependencies
