Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2023-11, with the labels that each got.

#8948 Fix for missing toast notifications
  app/javascript/components/toast-list/toast-item.jsx
  app/javascript/components/toast-list/toast-list.jsx
  app/javascript/miq-redux/notification-reducer.js
  app/javascript/spec/toast-list/__snapshots__/toast-list.spec.js.snap
Labels: bug, quinteros/yes

#8955 Fix table header accessibility issues
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
  app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
  app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap
  app/javascript/spec/tenant-quota-form/__snapshots__/tenant-quota-form.spec.js.snap
  app/javascript/spec/workflow-credential-mapping-form/__snapshots__/workflow-credential-mapping-form.spec.js.snap
Labels: bug, accessibility

#8952 Fixed explorer tree accessibility violations
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/views/layouts/listnav/_explorer.html.haml
  spec/helpers/application_helper_spec.rb
Labels: bug, accessibility

#8940 Fixed accessibility issues with the server settings authentication page
  app/views/ops/_settings_authentication_tab.html.haml
Labels: bug, accessibility

#8950 Remove Id from Host Endpoint When Submitting Form
  app/javascript/components/host-edit-form/host-edit-form.jsx
Labels: bug

#8960 Updated ui json files after core 22770 22781
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: internationalization, quinteros/yes

#8930 Fix for custom button action events
  app/controllers/application_controller/buttons.rb
  app/controllers/service_controller.rb
  spec/controllers/application_controller/buttons_spec.rb
Labels: bug

#8957 Use new dedicated my_settings_view permission
  app/controllers/configuration_controller.rb
Labels: bug, quinteros/yes

#8962 Update ui json files after core 22777, 22783, 22788
  app/javascript/oldjs/locale/de.json
  app/javascript/oldjs/locale/en.json
  app/javascript/oldjs/locale/es.json
  app/javascript/oldjs/locale/fr.json
  app/javascript/oldjs/locale/it.json
  app/javascript/oldjs/locale/ja.json
  app/javascript/oldjs/locale/ko.json
  app/javascript/oldjs/locale/pt_BR.json
  app/javascript/oldjs/locale/zh_CN.json
  app/javascript/oldjs/locale/zh_TW.json
Labels: bug, internationalization, quinteros/yes

#8963 Resorted component-definitions-common.js
  app/javascript/packs/component-definitions-common.js
Labels: formatting/styling, cleanup

#8967 Fix copy time profile error
  app/views/configuration/_timeprofile_form.html.haml
Labels: bug

#8953 Fixed Service Reconfigure Form and Request Summary Pages
  app/controllers/service_controller.rb
  app/views/miq_request/_service_reconfigure_show.html.haml
  app/views/service/service_reconfigure.html.haml
  app/views/shared/dialogs/_reconfigure_dialog.html.haml
  config/routes.rb
Labels: bug

#8918 Integrating the CodeMirror into MiqStructuredList component.
  app/helpers/miq_ae_class_helper.rb
  app/javascript/components/miq-structured-list/helpers.js
  app/javascript/components/miq-structured-list/miq-structured-list-body/value-tags/miq-structured-list-inputs.jsx
  app/javascript/components/miq-structured-list/miq-structured-list-body/value-types/miq-structured-list-object.jsx
  app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
  app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
  app/javascript/spec/textual_summary/data/code_mirror_data.js
  app/views/miq_ae_class/_method_inputs.html.haml
Labels: enhancement

#8968 Update yarn to stable v4.0.2
  .yarn/releases/yarn-4.0.0-rc.51.cjs
  .yarn/releases/yarn-4.0.2.cjs
  .yarnrc.yml
  package.json
Labels: dependencies

#8973 Replace .haml-lint.yml with a symlink to .rubocop.yml
  .haml-lint.yml
Labels: enhancement

#8969 Fix settings permissions
  app/controllers/configuration_controller.rb
  app/presenters/menu/default_menu.rb
  app/views/configuration/_ui_3.html.haml
  app/views/configuration/_ui_4.html.haml
  app/views/configuration/show.html.haml
Labels: bug

#8965 Remove legacy settings code
  app/controllers/application_controller.rb
  app/controllers/configuration_controller.rb
  app/helpers/configuration_helper.rb
  app/helpers/configuration_helper/configuration_view_helper.rb
  config/routes.rb
  spec/helpers/configuration_helper/configuration_view_helper_spec.rb
  spec/helpers/configuration_helper_spec.rb
  spec/routing/configuration_routing_spec.rb
Labels: technical debt

#8980 Fix my settings error screen
  app/controllers/configuration_controller.rb
Labels: bug
