Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2023-01, with the labels that each got.

#8587 Update the copyright date
  README.md
Labels: documentation

#8586 Fix typo 'can not' -> 'cannot'
  app/controllers/condition_controller.rb
Labels: bug

#8590 VM Provision Environment Tab Fix
  app/helpers/request_info_helper.rb
Labels: bug

#8583 Fix dashboard accessibility check violations
  app/javascript/components/dashboard-widgets/widget-wrapper/index.jsx
  app/javascript/components/dashboard_toolbar.jsx
  app/javascript/menu/first-level.jsx
  app/javascript/menu/group-switcher.jsx
  app/javascript/menu/menu-collapse.jsx
  app/javascript/menu/search.jsx
  app/javascript/menu/side-nav-menu-link.jsx
  app/javascript/menu/username.jsx
  app/javascript/spec/toolbar/__snapshots__/dashboard_toolbar.spec.jsx.snap
  app/javascript/spec/widget-wrapper/__snapshots__/widget-wrapper.spec.js.snap
  app/stylesheet/menu.scss
  app/views/layouts/_center_div_dashboard_no_listnav.html.haml
  app/views/layouts/_tabs.html.haml
Labels: bug

#8592 Removing moment-timezone-0.4.1 and bumping moment-timezone to 0.5.40
  package.json
  yarn.lock
Labels: dependencies, security fix

#8593 add host initiator groups to ems storage dashboard
  app/controllers/mixins/ems_common.rb
  app/services/ems_storage_dashboard_service.rb
Labels: enhancement

#8584 List resource capabilities in summary page
  app/helpers/storage_resource_helper/textual_summary.rb
Labels: enhancement

#8582 storage manager volume create: basic and advanced modes
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
  app/javascript/components/cloud-volume-form/index.jsx
Labels: enhancement

#8597 Schedule edit bug fix
  app/controllers/ops_controller/settings/schedules.rb
Labels: bug

#8588 Drop SCVMM provider
  app/views/shared/views/_prov_dialog.html.haml
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/mixins/ems_common_spec.rb
  spec/presenters/tree_node/ext_management_system_spec.rb
  spec/presenters/tree_node/host_spec.rb
  spec/presenters/tree_node/vm_or_template_spec.rb
Labels: technical debt

#8612 fixes for host initiator groups
  app/controllers/mixins/ems_common.rb
  app/helpers/application_helper/toolbar/host_initiator_group_center.rb
  app/helpers/application_helper/toolbar/host_initiator_groups_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_storage_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/services/ems_storage_dashboard_service.rb
  spec/helpers/ems_storage_helper/textual_summary_spec.rb
Labels: bug

#8609 added validation to volume and service names
  app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
  app/javascript/helpers/validate-names.js
Labels: enhancement

#8603 Settings Category From conversion from HAML to react
  app/controllers/ops_controller/settings/tags.rb
  app/javascript/components/settings-category-form/index.jsx
  app/javascript/components/settings-category-form/schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/settings-category-form/__snapshots__/settings-category-form.spec.js.snap
  app/javascript/spec/settings-category-form/settings-category-form.spec.js
  app/views/ops/_category_form.html.erb
  app/views/ops/_category_form.html.haml
Labels: refactoring

#8594 Settings Analysis Profile summary conversion from HAML to React
  app/helpers/ops_helper.rb
  app/helpers/settings_analysis_profile_helper.rb
  app/javascript/components/miq-structured-list/helpers.js
  app/views/ops/_ap_show.html.erb
  app/views/ops/_ap_show.html.haml
Labels: enhancement

#8598 Upgrade Json5
  package.json
  yarn.lock
Labels: dependencies, security fix

#8602 fix refresh ems storage manager for physical storage refresh button
  app/controllers/physical_storage_controller.rb
  app/helpers/application_helper/toolbar/physical_storages_center.rb
Labels: bug

#8599 Adrian/462593 add search on missing objects
  app/helpers/application_helper.rb
  app/helpers/application_helper/page_layouts.rb
Labels: enhancement

#8506 [MORPHY] Fix dashboard widget refresh and zoom
  app/javascript/angular/dashboard/widget-wrapper.js
Labels: bug

#8596 Fix editing of tags for a service
  app/controllers/application_controller.rb
  app/controllers/application_controller/tags.rb
  app/views/service/show.html.haml
Labels: bug

#8601 Settings company categories list conversion from HAML to react
  app/helpers/ops_helper.rb
  app/helpers/settings_tags_tabs_helper.rb
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/components/settings-company-categories/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/miq-data-table/data.js
  app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
  app/javascript/spec/settings-compan-categories/data.js
  app/javascript/spec/settings-compan-categories/settings-company-categories.spec.js
  app/stylesheet/miq-custom-tab.scss
  app/views/ops/_settings_co_categories_tab.html.haml
Labels: enhancement
