Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2024-08, with the labels that each got.

#9228 Fix textual summary duplication bug
  app/javascript/react/textual_summary_wrapper.jsx
Labels: bug

#9239 Update pending yarn npm audit list
  .yarnrc.yml
Labels: security

#9241 Use npmAuditExcludePackages instead of npmAuditIgnoreAdvisories
  .yarnrc.yml
Labels: enhancement, security

#9242 Fix translation issues
  app/javascript/components/AeInlineMethod/NamespaceSelector.jsx
  app/javascript/components/AeInlineMethod/index.jsx
Labels: bug, internationalization

#9231 Rails7 test fixes
  spec/controllers/vm_cloud_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
Labels: rails7

#9243 Use Rails 7 way to set yaml permitted classes
  app/controllers/ops_controller/settings/common.rb
Labels: rails7

#9238 Use ruby 3.1 for code coverage
  .github/workflows/ci.yaml
Labels: test, developer

#9244 Use uglifier harmony mode to handle es6 syntax with rails 7
  lib/manageiq/ui/classic/engine.rb
Labels: bug, rails7

#9224 Fix provider charts tooltip
  app/javascript/components/provider-dashboard-charts/charts_config.js
Labels: bug

#9245 Wrap the uglifier compressor with harmony support
  lib/manageiq/ui/classic/engine.rb
  lib/manageiq/ui/classic/js_compressor.rb
Labels: bug, rails7

#9249 Fix the VM Infra button checking EmsCloud providers
  app/helpers/application_helper/button/vm_miq_request_new.rb
  spec/helpers/application_helper/buttons/vm_miq_request_new_spec.rb
Labels: bug, petrosian/yes?, quinteros/yes?, radjabov/yes?

#8929 Add Resource Pool UI for Cloud managers
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/generic_show_mixin.rb
  app/controllers/resource_pool_cloud_controller.rb
  app/controllers/resource_pool_infra_controller.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/resource_pool_cloud_center.rb
  app/helpers/application_helper/toolbar/resource_pool_clouds_center.rb
  app/helpers/application_helper/toolbar/resource_pool_infra_center.rb
  app/helpers/application_helper/toolbar/resource_pool_infras_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_cloud_helper/textual_summary.rb
  app/helpers/resource_pool_cloud_helper.rb
  app/helpers/resource_pool_cloud_helper/textual_summary.rb
  app/helpers/resource_pool_config_helper.rb
  app/helpers/resource_pool_infra_helper.rb
  app/helpers/resource_pool_infra_helper/textual_summary.rb
  app/helpers/vm_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/resource_pool_cloud/_config.html.haml
  app/views/resource_pool_cloud/show.html.haml
  app/views/resource_pool_cloud/show_list.html.haml
  app/views/resource_pool_infra/_config.html.haml
  app/views/resource_pool_infra/show.html.haml
  app/views/resource_pool_infra/show_list.html.haml
  config/routes.rb
  product/views/ManageIQ_Providers_CloudManager_ResourcePool.yaml
  product/views/ManageIQ_Providers_InfraManager_ResourcePool.yaml
  spec/config/routes.pending.yml
  spec/controllers/resource_pool_cloud_controller_spec.rb
  spec/controllers/resource_pool_infra_controller_spec.rb
  spec/helpers/ems_cloud_helper/textual_summary_spec.rb
  spec/helpers/resource_pool_cloud_helper/textual_summary_spec.rb
  spec/helpers/resource_pool_infra_helper/textual_summary_spec.rb
  spec/helpers/vm_helper/textual_summary_spec.rb
  spec/presenters/menu/default_menu_spec.rb
  spec/routing/resource_pool_cloud_routing_spec.rb
  spec/routing/resource_pool_infra_routing_spec.rb
Labels: enhancement

#9254 Drop include_concern in ResourcePool Helpers
  app/helpers/resource_pool_cloud_helper.rb
  app/helpers/resource_pool_cloud_helper/textual_summary.rb
  app/helpers/resource_pool_infra_helper.rb
  spec/config/routes.pending.yml
Labels: bug

#9257 Revert cloud resource pools
  app/controllers/application_controller/ci_processing.rb
  app/controllers/mixins/ems_common.rb
  app/controllers/mixins/generic_show_mixin.rb
  app/controllers/resource_pool_controller.rb
  app/controllers/resource_pool_infra_controller.rb
  app/controllers/vm_common.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/listnav.rb
  app/helpers/application_helper/page_layouts.rb
  app/helpers/application_helper/toolbar/resource_pool_center.rb
  app/helpers/application_helper/toolbar/resource_pool_cloud_center.rb
  app/helpers/application_helper/toolbar/resource_pool_clouds_center.rb
  app/helpers/application_helper/toolbar/resource_pools_center.rb
  app/helpers/application_helper/toolbar_chooser.rb
  app/helpers/ems_cloud_helper/textual_summary.rb
  app/helpers/resource_pool_cloud_helper.rb
  app/helpers/resource_pool_cloud_helper/textual_summary.rb
  app/helpers/resource_pool_helper.rb
  app/helpers/resource_pool_helper/textual_summary.rb
  app/helpers/resource_pool_infra_helper.rb
  app/helpers/vm_helper/textual_summary.rb
  app/presenters/menu/default_menu.rb
  app/views/resource_pool/_config.html.haml
  app/views/resource_pool/show.html.haml
  app/views/resource_pool/show_list.html.haml
  app/views/resource_pool_infra/_config.html.haml
  app/views/resource_pool_infra/show.html.haml
  app/views/resource_pool_infra/show_list.html.haml
  config/routes.rb
  product/views/ManageIQ_Providers_CloudManager_ResourcePool.yaml
  product/views/ManageIQ_Providers_InfraManager_ResourcePool.yaml
  spec/config/routes.pending.yml
  spec/controllers/resource_pool_cloud_controller_spec.rb
  spec/controllers/resource_pool_controller_spec.rb
  spec/helpers/ems_cloud_helper/textual_summary_spec.rb
  spec/helpers/resource_pool_helper/textual_summary_spec.rb
  spec/helpers/resource_pool_infra_helper/textual_summary_spec.rb
  spec/helpers/vm_helper/textual_summary_spec.rb
  spec/presenters/menu/default_menu_spec.rb
  spec/routing/resource_pool_infra_routing_spec.rb
  spec/routing/resource_pool_routing_spec.rb
Labels: bug
