Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2024-02, with the labels that each got.

#9062 Fix typo for CatalogResource
  app/javascript/components/data-tables/catalog-resource/index.jsx
  app/javascript/packs/component-definitions-common.js
Labels: technical debt

#9065 Beautify the NotificationDrawer component
  app/javascript/components/notification-drawer/notification-drawer.jsx
  app/javascript/spec/notification-drawer/__snapshots__/notification-drawer.spec.js.snap
  app/stylesheet/notifications.scss
Labels: enhancement

#9061 Fix dashboard missing chart
  app/javascript/components/carbon-charts/groupChart.js
  app/javascript/components/carbon-charts/helpers.js
  app/javascript/components/dashboard-widgets/dashboard-charts/index.jsx
Labels: bug

#9063 Disable ip address fields when dhcp is selected
  app/controllers/application_controller/miq_request_methods.rb
Labels: bug

#9068 Add noopener noreferrer to blank targets
  app/javascript/components/dashboard-widgets/widget-wrapper/helper.jsx
  app/javascript/spec/widget-wrapper/__snapshots__/widget-wrapper.spec.js.snap
  app/javascript/spec/widget-wrapper/widget-wrapper.spec.js
  app/presenters/widget_presenter.rb
Labels: enhancement, morphy/yes, quinteros/yes

#9076 [MORPHY] Add noopener noreferrer to blank targets
  app/presenters/widget_presenter.rb
Labels: enhancement

#9077 [MORPHY] Remove unnecessary regex
  app/javascript/oldjs/controllers/live_metrics/util/metrics-parse-url-factroy.js
Labels: refactoring

#9080 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#9082 Refactor chargeback rates cypress tests
  cypress/README.md
  cypress/e2e/ui/Overview/Chargeback/rates.cy.js
  cypress/support/assertions/expect_rates_table.js
  cypress/support/commands/gtl.js
  cypress/support/e2e.js
Labels: test, refactoring, cypress

#9079 Fix debug toast wrapper style
  app/javascript/oldjs/miq_debug.css
Labels: enhancement

#9084 Fix typo in comments for ansible-playbook catalog form
  app/javascript/components/ansible-playbook-edit-catalog-form/helper.js
Labels: enhancement

#9085 Fix Embededded Typos
  app/controllers/catalog_controller.rb
  app/controllers/mixins/automation_mixin.rb
  app/javascript/oldjs/miq_application.js
  config/routes.rb
  product/views/ManageIQ_Providers_Workflows_AutomationManager_Workflow.yaml
  spec/config/routes.pending.yml
Labels: bug

#9074 Button summary conversion from HAML to React
  app/helpers/miq_ae_customization_helper.rb
  app/helpers/shared_helper/ab_list_helper.rb
  app/views/shared/buttons/_ab_show.html.haml
Labels: enhancement

#9087 Fixed cypress readme and comments
  cypress/README.md
  cypress/support/assertions/expect_rates_table.js
  cypress/support/assertions/expect_text.js
  cypress/support/assertions/expect_title.js
  cypress/support/commands/explorer.js
  cypress/support/commands/gtl.js
  cypress/support/commands/login.js
  cypress/support/commands/menu.js
Labels: documentation, cypress

#9086 Fixed Empty Applied Tag Section in Control Actions Summary Page
  app/helpers/miq_action_helper.rb
Labels: bug

#9078 fix hostname error
  app/controllers/application_controller/miq_request_methods.rb
Labels: bug

#9088 Button group summary page react conversion.
  app/helpers/miq_ae_customization_helper.rb
  app/helpers/shared_helper/ab_list_helper.rb
  app/helpers/shared_helper/ab_show_helper.rb
  app/views/shared/buttons/_ab_list.html.haml
Labels: enhancement

#9092 Added search bars to control pages
  app/controllers/condition_controller.rb
  app/controllers/miq_action_controller.rb
  app/controllers/miq_alert_controller.rb
  app/controllers/miq_alert_set_controller.rb
  app/controllers/miq_event_definition_controller.rb
  app/controllers/miq_policy_controller.rb
  app/controllers/miq_policy_set_controller.rb
Labels: bug, enhancement

#9094 Fixed Incorrect Values Being Displayed When Editing Action
  app/javascript/components/action-form/helper.js
Labels: bug

#9096 Fix duplicate DOM ID warning in automate modal form
  app/views/miq_ae_class/_all_tabs.html.haml
  app/views/miq_ae_class/_class_methods.html.haml
Labels: bug

#9095 Fix styles for control action summary and form pages
  app/controllers/miq_action_controller.rb
  app/helpers/miq_action_helper.rb
  app/javascript/components/action-form/action-form.schema.js
  app/javascript/components/miq-structured-list/miq-structured-list-body/value-types/miq-structured-list-object.jsx
  app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
  app/stylesheet/ddf_override.scss
  app/stylesheet/miq-structured-list.scss
  app/views/miq_action/show.html.haml
Labels: enhancement
