Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2024-05, with the labels that each got.

#9177 Fix failing terraform rbac specs
  spec/config/routes.pending.yml
Labels: bug

#9174 Fix request page tags bug
  app/views/miq_request/_request_dialog_details.html.haml
Labels: bug

#9168 Fix output page toolbar bugs
  app/controllers/ansible_repository_controller.rb
  app/controllers/application_controller/tags.rb
  app/controllers/workflow_repository_controller.rb
  app/helpers/application_helper/toolbar/ansible_repository_center.rb
  app/helpers/application_helper/toolbar/workflow_repository_center.rb
  app/views/ansible_repository/_output.html.haml
  app/views/workflow_repository/_output.html.haml
Labels: bug

#9142 UI changes to use the renamed product features from core #22971
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/controllers/application_controller.rb
  app/controllers/workflow_credential_controller.rb
  app/controllers/workflow_repository_controller.rb
  app/helpers/application_helper/toolbar/ansible_credential_center.rb
  app/helpers/application_helper/toolbar/ansible_credentials_center.rb
  app/helpers/application_helper/toolbar/ansible_repositories_center.rb
  app/helpers/application_helper/toolbar/ansible_repository_center.rb
  app/helpers/application_helper/toolbar/workflow_credential_center.rb
  app/helpers/application_helper/toolbar/workflow_credentials_center.rb
  app/helpers/application_helper/toolbar/workflow_repositories_center.rb
  app/helpers/application_helper/toolbar/workflow_repository_center.rb
  app/presenters/menu/default_menu.rb
  spec/controllers/ansible_credential_controller_spec.rb
  spec/controllers/ansible_repository_controller_spec.rb
  spec/controllers/workflow_credential_controller_spec.rb
  spec/controllers/workflow_repository_controller_spec.rb
Labels: enhancement

#9186 Fix workflow states table
  app/javascript/components/request-workflow-status/data.js
  app/javascript/components/request-workflow-status/request-workflow-status-item.jsx
Labels: bug

#9171 Remove multiple title for provisioning pages
  app/stylesheet/miq-data-table.scss
  app/views/miq_request/_pre_prov.html.haml
Labels: enhancement

#9180 Fix AttachDetachCloudVolumeForm test
  app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
  app/javascript/spec/cloud-volume-form/attach-detach-cloud-volume-form.spec.js
Labels: test

#9179 Fix HostEditForm test
  app/javascript/spec/host-edit-form/helper-data.js
  app/javascript/spec/host-edit-form/host-edit-form.spec.js
Labels: test

#9178 Fix CloudObjectStoreContainerForm test
  app/javascript/spec/cloud-object-store-container-form/__snapshots__/cloud-object-store-container-form.spec.js.snap
  app/javascript/spec/cloud-object-store-container-form/cloud-object-store-container-form.spec.js
Labels: test

#9176 [MORPHY] Fix Contrast issue No Use Of Eval
  app/javascript/oldjs/miq_application.js
  app/views/automation_manager/_inventory_group.html.haml
  app/views/catalog/explorer.html.haml
  app/views/layouts/_performance_async.html.haml
  app/views/layouts/_tl_show_async.html.haml
  app/views/ops/_diagnostics_utilization_tab.html.haml
  app/views/ops/explorer.html.haml
  app/views/report/explorer.html.haml
  app/views/storage/_storage_list.html.haml
  app/views/utilization/index.html.haml
  app/views/vm_infra/explorer.html.haml
  app/views/vm_or_template/explorer.html.haml
  spec/views/availability_zone/show.html.haml_spec.rb
  spec/views/host/_show.html.haml_spec.rb
  spec/views/vm/_show.html.haml_spec.rb
Labels: bug

#9191 Add current state to workflow states table and format duration time
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/components/request-workflow-status/data.js
  app/stylesheet/miq-data-table.scss
Labels: enhancement

#9181 Fix ansible tower and embedded workflows lists
  app/controllers/configuration_script_controller.rb
  app/helpers/application_helper.rb
  app/helpers/application_helper/title.rb
  app/javascript/oldjs/services/dialog_editor_http_service.js
Labels: bug

#9195 Remove current workflow state if its done
  app/javascript/components/request-workflow-status/data.js
Labels: bug, radjabov/yes

#9197 Fix guest devices summary page
  app/controllers/guest_device_controller.rb
  config/routes.rb
Labels: bug, radjabov/yes?

#9198 Show volume templates in image list view
  app/controllers/mixins/generic_show_mixin.rb
Labels: bug, radjabov/yes?
