Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2024-04, with the labels that each got.

#9140 Fix embedded page toolbars
  app/controllers/ansible_credential_controller.rb
  app/controllers/ansible_repository_controller.rb
  app/controllers/application_controller/tags.rb
  app/controllers/workflow_credential_controller.rb
  app/controllers/workflow_repository_controller.rb
  app/helpers/application_helper/toolbar/ansible_repositories_center.rb
  app/helpers/application_helper/toolbar/workflow_repositories_center.rb
  spec/controllers/workflow_credential_controller_spec.rb
Labels: bug, radjabov/yes?

#9144 Fixed missing surveys table
  app/controllers/configuration_script_controller.rb
  app/helpers/configuration_script_helper.rb
  app/views/configuration_script/show.html.haml
Labels: bug, radjabov/yes?

#9146 Fix Optimization Queue Report
  app/javascript/components/data-tables/optimization/helper.js
  app/javascript/helpers/custom-click-handler.js
Labels: bug, radjabov/yes

#9143 Fix company tags style
  app/javascript/components/settings-company-tags/index.jsx
  app/stylesheet/application-webpack.scss
  app/stylesheet/miq-custom-accordion.scss
Labels: enhancement

#9152 drop stub_supports :supports
  spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb
Labels: test

#9151 Fix MiqFormRenderer test
  app/javascript/spec/forms/__snapshots__/data-driven-form.spec.js.snap
  app/javascript/spec/forms/data-driven-form.spec.js
Labels: test

#9150 Fix ZoneForm test
  app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
  app/javascript/spec/zone-form/zone-form.spec.js
Labels: test

#9149 Fix PxeIsoDatastoreForm test
  app/javascript/spec/pxe-iso-datastore-form/__snapshots__/pxe-iso-datastore-form.spec.js.snap
  app/javascript/spec/pxe-iso-datastore-form/pxe-iso-datastore-form.spec.js
Labels: test

#9147 Fix DiagnosticsCURepairForm test
  app/javascript/spec/c-and-u-collections-form/__snapshots__/c-and-u-collections-form.spec.js.snap
  app/javascript/spec/c-and-u-collections-form/c-and-u-collections-form.spec.js
Labels: test

#9145 Fix CloudVolumeActions test
  app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
  app/javascript/spec/cloud-volume-actions-form/cloud-volume-actions-form.spec.js
Labels: test

#9133 Fix TimelineTable test case
  app/javascript/components/timeline-options/timeline-table.jsx
  app/javascript/spec/timeline-options-form/timeline-table.spec.js
Labels: test

#9132 Fix SettingsLabelTabMapping for data-tables test case
  app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap
  app/javascript/spec/settings-label-tag-mapping/data.js
Labels: test

#9130 Fix MiqCustomTab test cases
  app/helpers/catalog_helper.rb
  app/helpers/request_info_helper.rb
  app/helpers/utilization_helper.rb
  app/javascript/components/miq-custom-tab/helper.js
  app/javascript/components/miq-custom-tab/index.jsx
  app/javascript/spec/miq-custom-tab/__snapshots__/miq-custom-tab.spec.js.snap
  app/javascript/spec/miq-custom-tab/miq-custom-tab.spec.js
Labels: test

#9128 Fix AnsiblePlaybookWorkflow test case
  app/javascript/components/ansible-playbook-workflow/index.jsx
Labels: test

#8887 Add icons and provider name to a few screens
  app/helpers/auth_key_pair_cloud_helper/textual_summary.rb
  app/helpers/resource_pool_helper/textual_summary.rb
  lib/gtl_formatter.rb
  product/views/Container.yaml
  product/views/ManageIQ_Providers_CloudManager_AuthKeyPair.yaml
  product/views/PlacementGroup.yaml
  product/views/ResourcePool.yaml
  product/views/Switch.yaml
  spec/helpers/auth_key_pair_cloud_helper/textual_summary_spec.rb
  spec/helpers/resource_pool_helper/textual_summary_spec.rb
Labels: enhancement, stale

#9153 stub_supports uses specific class
  spec/controllers/application_controller/ci_processing_spec.rb
  spec/controllers/cloud_object_store_object_spec.rb
  spec/controllers/storage_controller_spec.rb
  spec/controllers/vm_infra_controller_spec.rb
  spec/helpers/application_helper/buttons/vm_retire_now_spec.rb
  spec/helpers/application_helper/buttons/vm_retire_spec.rb
  spec/helpers/application_helper/buttons/volume_detach_spec.rb
Labels: test

#9155 Fix MiqStructuredList test
  app/javascript/components/miq-structured-list/index.jsx
Labels: test

#9154 Fix RemoveCatalogItemModal test
  app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js
Labels: test

#9089 convert ServiceTemplate.orderable? to supports?(:order)
  app/controllers/orchestration_stack_controller.rb
  app/helpers/application_helper/button/orchestration_template_orderable.rb
  app/helpers/application_helper/button/orchestration_template_view_in_catalog.rb
  app/views/orchestration_stack/_stack_orchestration_template.html.haml
  spec/controllers/orchestration_stack_controller_spec.rb
Labels: refactoring

#9110 Display OS 'name' as 'Description'
  app/helpers/textual_mixins/textual_os_info.rb
Labels: enhancement, compute/cloud

#9167 Cleanup VmResize component and fix lint errors
  app/javascript/components/vm-resize-form/vm-resize-form.jsx
  app/javascript/spec/vm-resize-form/vm-resize-form.spec.js
Labels: enhancement

#9166 Fix MiqStructuredListSub test
  app/javascript/components/miq-structured-list/miq-structured-list-body/value-types/miq-structured-list-sub.jsx
Labels: test

#9165 Fix ProvGrid test
  app/javascript/spec/prov-grid/__snapshots__/prov-grid.spec.js.snap
  app/javascript/spec/prov-grid/prov-vm-grid-data.js
Labels: test

#9164 Fix HostInitiatorGroupForm test
  app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
  app/javascript/spec/host-initiator-group-form/host-initiator-group.spec.js
Labels: test

#9161 Fix ServiceDialogFromOt test
  app/javascript/spec/service-dialog-from-form/service-dialog-from-form.spec.js
Labels: test

#9158 Fix TreeSelector test
  app/javascript/components/tree-view/selector.jsx
  app/javascript/spec/tree-view/__snapshots__/selector.spec.js.snap
  app/javascript/spec/tree-view/selector.spec.js
Labels: test

#9160 Fix publish virtual-machines purpose tags style
  app/views/miq_request/_prov_field.html.haml
Labels: enhancement

#9159 Search feature for provisioning instance and virtual machines
  app/controllers/application_controller/miq_request_methods.rb
  app/javascript/components/filter-provision-instance/index.jsx
  app/javascript/packs/component-definitions-common.js
  app/stylesheet/miq-data-table.scss
  app/stylesheet/search-bar.scss
  app/views/miq_request/_pre_prov.html.haml
Labels: enhancement

#9170 Fixed schedule summary page request value
  app/helpers/settings_schedule_helper.rb
Labels: bug
