Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2024-07, with the labels that each got.

#9119 Prepend ActionView::Helpers::NumberHelper with our NumberHelper
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
Labels: bug, rails7

#9220 Fix request form automation fields
  app/views/miq_request/_request_dialog_details.html.haml
Labels: bug, radjabov/yes?

#9221 Update carbon packages
  package.json
  yarn.lock
Labels: dependencies

#9222 Update moment to 2.29.2 through resolution
  package.json
  yarn.lock
Labels: dependencies

#9226 Fix automate specs
  spec/controllers/application_controller/automate_spec.rb
Labels: bug

#9227 Add known pending package security issues to a pending list
  .yarnrc.yml
Labels: security

#9215 Rails 7 compatible changes (part 1)
  app/controllers/ops_controller/settings/common.rb
  spec/views/availability_zone/show.html.haml_spec.rb
  spec/views/catalog/_form.html.haml_spec.rb
  spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
  spec/views/dashboard/login.html.haml_spec.rb
  spec/views/ems_cluster/show.html.haml_spec.rb
  spec/views/host/_show.html.haml_spec.rb
  spec/views/layouts/_center_div_no_listnav.html.haml_spec.rb
  spec/views/layouts/_item.html.haml_spec.rb
  spec/views/layouts/_searchbar.html.haml_spec.rb
  spec/views/layouts/_user_input_filter.html.haml_spec.rb
  spec/views/layouts/list_grid.html.haml_spec.rb
  spec/views/layouts/perf_charts_js_spec.rb
  spec/views/miq_ae_class/_class_fields.html.haml_spec.rb
  spec/views/miq_ae_class/_fields_seq_form.html.haml_spec.rb
  spec/views/miq_ae_class/_instance_fields.html.haml_spec.rb
  spec/views/miq_ae_class/_method_inputs.html.haml_spec.rb
  spec/views/miq_ae_class/show.html.haml_spec.rb
  spec/views/miq_alert/_show.html.haml_spec.rb
  spec/views/ops/_label_tag_mapping_form.html.haml_spec.rb
  spec/views/ops/_rbac_tenant_details.html.haml_spec.rb
  spec/views/ops/_rbac_user_details.html.haml_spec.rb
  spec/views/ops/_settings_cu_collection_tab.html.haml_spec.rb
  spec/views/report/_report_list.html.haml_spec.rb
  spec/views/report/_widget_form_menu.html.haml_spec.rb
  spec/views/shared/buttons/_ab_form.html.haml_spec.rb
  spec/views/vm/_show.html.haml_spec.rb
Labels: enhancement, rails7

#9214 Add annotations on container summary pages that contain labels
  app/controllers/container_group_controller.rb
  app/controllers/container_node_controller.rb
  app/controllers/container_replicator_controller.rb
  app/controllers/container_route_controller.rb
  app/controllers/container_service_controller.rb
  app/controllers/container_template_controller.rb
  app/helpers/container_summary_helper.rb
Labels: enhancement

#9188 Provision Dialog Form conversion from HAML to React
  app/controllers/miq_ae_customization_controller.rb
  app/controllers/miq_ae_customization_controller/old_dialogs.rb
  app/javascript/components/miq-ae-customization/index.jsx
  app/javascript/components/miq-ae-customization/miq-ae-customization-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/javascript/spec/miq-ae-customization-form/__snapshots__/miq-ae-customization-form.spec.js.snap
  app/javascript/spec/miq-ae-customization-form/miq-ae-customization-form.spec.js
  app/stylesheet/ddf_override.scss
  app/views/miq_ae_customization/_old_dialogs_details.html.haml
  config/routes.rb
  cypress/e2e/ui/Automation/Embedded-Automate/customization.cy.js
Labels: enhancement

#9230 Convert provision dialog summary form to React
  app/controllers/miq_ae_customization_controller.rb
  app/helpers/miq_ae_customization_helper.rb
  app/views/miq_ae_customization/_old_dialogs_details.html.haml
  cypress/e2e/ui/Automation/Embedded-Automate/customization.cy.js
Labels: enhancement

#9232 [Morphy] Update moment-timezone
  package.json
  yarn.lock
Labels: dependencies, security fix

#9059 Filtering and selecting embedded methods used in the inline-methods form pages
  app/controllers/miq_ae_class_controller.rb
  app/javascript/components/AeInlineMethod/FilterNamespace.jsx
  app/javascript/components/AeInlineMethod/NamespaceSelector.jsx
  app/javascript/components/AeInlineMethod/helper.js
  app/javascript/components/AeInlineMethod/index.jsx
  app/javascript/components/AeInlineMethod/style.scss
  app/javascript/components/miq-data-table/index.jsx
  app/javascript/components/miq-data-table/miq-table-cell.jsx
  app/javascript/packs/component-definitions-common.js
  app/stylesheet/miq-data-table.scss
  app/views/miq_ae_class/_embedded_methods.html.haml
  config/routes.rb
  package.json
  spec/config/routes.pending.yml
  yarn.lock
Labels: enhancement, dependencies

#9233 [Morphy] Update minimist
  package.json
  yarn.lock
Labels: dependencies, security fix

#9235 [Morphy] Fix cypress test assertion imports
  cypress/support/index.js
Labels: bug

#9236 [Morphy] Pin moment timezone
  package.json
  yarn.lock
Labels: dependencies, security fix

#9237 Ignore the latest bootstrap vulnerability until we can upgrade
  .yarnrc.yml
Labels: bug, security

#9234 [Morphy] Upgrade tough cookie to 4.1.3
  package.json
  yarn.lock
Labels: dependencies, security fix
