Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2024-10, with the labels that each got.

#9278 Remove newlines from result message
  app/controllers/miq_ae_tools_controller.rb
Labels: bug, internationalization

#9279 fix scss warning on division
  app/stylesheet/quadicon.scss
Labels: technical debt

#9283 Remove unused namespace angular code
  app/javascript/oldjs/components/index.js
  app/javascript/oldjs/components/miq_ae_class/namespace-form.js
  app/views/static/miq_ae_class/namespace_form.html.haml
  spec/javascripts/components/miq_ae_class/namespace_form_spec.js
Labels: technical debt

#9282 Update angular to 1.8.3
  package.json
  yarn.lock
Labels: dependencies

#9287 Remove unused angular controllers
  app/javascript/oldjs/components/index.js
  app/javascript/oldjs/components/provider-option-field-input.js
  app/javascript/oldjs/components/provier-option-section.js
  app/views/static/provider_option_field_input.html.haml
  app/views/static/provider_option_section.html.haml
Labels: technical debt

#9288 Remove unused angular verify button code
  app/javascript/oldjs/components/index.js
  app/javascript/oldjs/components/verify-button.js
  app/views/layouts/angular/_form_buttons_verify_angular.html.haml
  app/views/static/verify-button.html.haml
  spec/javascripts/components/verify-button_spec.js
Labels: technical debt

#9285 Show Terraform Template stack stdout
  app/helpers/application_helper/toolbar/service_center.rb
  app/views/service/_svcs_show.html.haml
Labels: enhancement, radjabov/yes?

#9293 Fix bin/webpack when ui-classic not bundled
  bin/webpack
  config/webpack/configuration.js
  config/webpack/shared.js
  lib/tasks/manageiq/ui_tasks.rake
Labels: bug, ruby3.3

#9273 Add option to create new dialog for terraform template in service catalog item
  app/javascript/components/terraform-template-catalog-form/terraform-template-catalog-form.schema.js
Labels: enhancement

#9294 Add bundler path
  lib/tasks/manageiq/ui_tasks.rake
Labels: bug

#9295 Fix issue when using kerberos auth with Rails 7
  app/controllers/application_controller/wait_for_task.rb
Labels: bug, rails7, radjabov/yes

#9286 Drop sass rails
  config/initializers/assets.rb
  lib/manageiq/ui/classic/engine.rb
  manageiq-ui-classic.gemspec
Labels: wip, dependencies, ruby3.3

#9298 Add external auth spec
  spec/controllers/dashboard_controller_spec.rb
Labels: test, radjabov/yes

#9296 Fix Chrome autofilling password when editing a schema
  app/views/miq_ae_class/_class_fields.html.haml
Labels: bug

#9290 Fix explorer title width
  app/javascript/components/gtl-view.jsx
  app/javascript/react/textual_summary_wrapper.jsx
  app/stylesheet/legacy/patternfly_overrides.scss
Labels: bug

#9299 Ensure uploaded images are image files
  app/controllers/catalog_controller.rb
  app/controllers/mixins/image_validation_mixin.rb
  app/controllers/ops_controller/settings/upload.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/ops_controller/settings/upload_spec.rb
  spec/fixtures/favicon.ico
  spec/fixtures/favicon.png.ico
  spec/fixtures/image.jpg
  spec/fixtures/image.png
  spec/fixtures/test.txt
  spec/fixtures/test.txt.ico
  spec/fixtures/test.txt.png
Labels: security fix

#9266 Fix generic object embedded table
  app/controllers/generic_object_controller.rb
  app/controllers/mixins/custom_buttons.rb
  app/controllers/service_controller.rb
  app/helpers/application_helper/toolbar/generic_object_center.rb
  app/helpers/application_helper/toolbar/mixins/custom_button_toolbar_mixin.rb
  app/helpers/service_helper/textual_summary.rb
  app/views/service/show.html.haml
Labels: bug
