Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2025-04, with the labels that each got.

#9390 Pin cheerio package version
  package.json
  yarn.lock
Labels: dependencies

#9383 Remove unused method
  app/controllers/application_controller.rb
Labels: technical debt

#9380 Upgrade cypress to allow Firefox tests to proceed.
  cypress/downloads/downloads.html
  package.json
  yarn.lock
Labels: dependencies, cypress

#9389 Fix tag category pages
  app/controllers/ops_controller.rb
  app/controllers/ops_controller/settings/tags.rb
  app/views/ops/_all_tabs.html.haml
  app/views/ops/_settings_my_company_categories_tab.html.haml
Labels: bug

#9391 Use Arel.sql to statically cast sql
  app/services/cloud_tenant_dashboard_service.rb
  app/services/ems_dashboard_service.rb
Labels: refactoring

#9261 Convert textualempty table to react
  app/helpers/generic_object_helper/textual_summary.rb
  app/javascript/components/textual_summary/empty_group.jsx
  spec/helpers/generic_object_helper/textual_summary_spec.rb
Labels: enhancement

#9306 Refactor key value list component
  app/javascript/components/ansible-playbook-edit-catalog-form/helper.js
  app/javascript/components/ansible-playbook-edit-catalog-form/index.jsx
  app/javascript/components/key-value-list/index.jsx
  app/javascript/components/terraform-template-catalog-form/helper.js
  app/javascript/components/terraform-template-catalog-form/index.jsx
  app/javascript/components/terraform-template-catalog-form/terraform-template-catalog-form.schema.js
  app/javascript/forms/mappers/componentMapper.jsx
  app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
  app/javascript/spec/add-remove-security-groups-form/__snapshots__/add-remove-security-groups-form.spec.js.snap
  app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
  app/javascript/spec/c-and-u-collections-form/__snapshots__/c-and-u-collections-form.spec.js.snap
  app/javascript/spec/cloud-database-form/__snapshots__/cloud-database-form.spec.js.snap
  app/javascript/spec/cloud-object-store-container-form/__snapshots__/cloud-object-store-container-form.spec.js.snap
  app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
  app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
  app/javascript/spec/data-store-fore/__snapshots__/datastore-form.spec.js.snap
  app/javascript/spec/diagnostics-collect-log-form/__snapshots__/diagnostics-collect-log-form.spec.js.snap
  app/javascript/spec/embedded-terraform-credentials-form/__snapshots__/embedded-terraform-credentials-form.spec.js.snap
  app/javascript/spec/evacuate-form/__snapshots__/evacuate-form.spec.js.snap
  app/javascript/spec/generic-objects-form/__snapshots__/generic-objects-form.spec.js.snap
  app/javascript/spec/host-aggregate-form/__snapshots__/host-aggregate-form.spec.js.snap
  app/javascript/spec/host-edit-form/__snapshots__/host-edit-form.spec.js.snap
  app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
  app/javascript/spec/live-migrate-form/__snapshots__/live-migrate-form.spec.js.snap
  app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap
  app/javascript/spec/pxe-customization-template-form/__snapshots__/pxe-customization-template-form.spec.js.snap
  app/javascript/spec/pxe-image-type-form/__snapshots__/pxe-image-type-form.spec.js.snap
  app/javascript/spec/pxe-iso-datastore-form/__snapshots__/pxe-iso-datastore-form.spec.js.snap
  app/javascript/spec/pxe-iso-image-form/__snapshots__/pxe-iso-image-form.spec.js.snap
  app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
  app/javascript/spec/schedule-form/__snapshots__/schedule-form.spec.js.snap
  app/javascript/spec/service-request-default-form/__snapshots__/service-request-default-form.spec.js.snap
  app/javascript/spec/settings-category-form/__snapshots__/settings-category-form.spec.js.snap
  app/javascript/spec/settings-time-profile-form/__snapshots__/settings-time-profile-form.spec.js.snap
  app/javascript/spec/vm-floating-ips-form/__snapshots__/vm-floating-ips-form.spec.js.snap
  app/javascript/spec/vm-resize-form/__snapshots__/vm-resize-form.spec.js.snap
  app/javascript/spec/workflow-credential-mapping-form/__snapshots__/workflow-credential-mapping-form.spec.js.snap
  app/javascript/spec/workflow-credentials-form/__snapshots__/workflow-credentials-form.spec.js.snap
  app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
Labels: refactoring

#9392 Fix settings authentication form provider type ids
  app/views/ops/_settings_authentication_tab.html.haml
Labels: bug, spassky/yes?

#9402 Update Yarn to v4.9.1
  .yarn/releases/yarn-4.7.0.cjs
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  package.json
Labels: dependencies

#9409 Upgrade react router
  package.json
  yarn.lock
Labels: dependencies

#9411 Remove dead code
  app/javascript/oldjs/services/miq_service.js
  spec/javascripts/services/miq_service_spec.js
Labels: technical debt

#9410 Define a custom script dataType converter, don't override the base one
  app/javascript/oldjs/jquery_overrides.js
  app/javascript/oldjs/miq_application.js
Labels: bug, spassky/yes
