Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2025-03, with the labels that each got.

#9370 Add cachetextconv to instructions
  .gitattributes
Labels: developer

#9367 Fix searchbar formtoken issue
  app/javascript/components/search-bar/index.jsx
  app/javascript/spec/search-bar/__snapshots__/search-bar.spec.js.snap
Labels: bug, spassky/yes

#9371 Fix provider dashboard charts converted time bug
  app/javascript/components/provider-dashboard-charts/helpers.js
Labels: bug

#9361 Update babel/traverse
  package.json
  yarn.lock
Labels: dependencies

#9362 Update lodash to 4.7.21
  package.json
  yarn.lock
Labels: dependencies

#9375 Update moment
  package.json
  yarn.lock
Labels: dependencies

#9378 Update cypress env
  .github/workflows/cypress.yaml
Labels: test, cypress

#9379 Update caniuse-lite to remove outdated warning
  yarn.lock
Labels: dependencies

#9376 Fix catalog item tags
  app/helpers/catalog_helper/textual_summary.rb
Labels: bug, spassky/yes?

#9384 Update @babel/runtime
  yarn.lock
Labels: dependencies

#9385 Update @babel/runtime-corejs2
  yarn.lock
Labels: dependencies
