Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2025-08, with the labels that each got.

#9530 Fixed toolbar to throw error on wrong option
  cypress/README.md
  cypress/support/commands/custom_logging_commands.js
  cypress/support/commands/toolbar.js
  cypress/support/e2e.js
Labels: test, cypress

#9538 Updated README and method-level docs for expect_alert commands
  cypress/README.md
  cypress/support/assertions/expect_alerts.js
Labels: cypress

#9516 Edit collect logs form cypress refactor
  cypress/e2e/ui/Settings/Application-Settings/edit_collect_logs.cy.js
Labels: test, cypress

#9505 Fix the settings ops schedule toolbar
  app/controllers/ops_controller/settings/schedules.rb
Labels: bug

#9479 Fix task page bugs
  app/controllers/miq_task_controller.rb
  app/javascript/components/settings-tasks-form/index.jsx
  app/views/layouts/_tasks.html.haml
Labels: bug

#9559 Updated selector for flash message
  cypress/support/assertions/expect_alerts.js
Labels: cypress

#9560 Enhance intercept api command
  cypress/README.md
  cypress/e2e/ui/validate-intercept-api-command.cy.js
  cypress/support/commands/api_commands.js
  cypress/support/e2e.js
Labels: test, cypress, spassky/yes

#9523 Bypass feature validation for dynamic tenant features
  app/controllers/ops_controller/ops_rbac.rb
  app/helpers/application_helper.rb
  cypress/e2e/ui/Settings/Application-Settings/settings_access_control.cy.js
Labels: bug, spassky/yes

#9593 [Morphy] Update semver packages
  yarn.lock
Labels: dependencies

#9564 [Morphy] Update minimatch
  package.json
  yarn.lock
Labels: dependencies

#9571 [Morphy] Update ip
  package.json
  yarn.lock
Labels: dependencies

#9595 [Morphy] Update form-data
  package.json
  yarn.lock
Labels: dependencies

#9596 [Morphy] Update got
  yarn.lock
Labels: dependencies

#9599 [Morphy] Update got
  package.json
  yarn.lock
Labels: dependencies

#9600 [Morphy] Update bootstrap morphy
  package.json
  yarn.lock
Labels: dependencies

#9568 Resolve duplicate Basic Info heading in create catalog item form
  app/controllers/catalog_controller.rb
Labels: bug, test
