Repository ManageIQ/manageiq-ui-classic, pull requests merged in 2025-01, with the labels that each got.

#9325 Update react-codemirror2
  package.json
  yarn.lock
Labels: dependencies

#9324 Fix table pagination setting
  app/javascript/components/gtl-view.jsx
Labels: bug

#9326 Updated bootstrap select
  package.json
  yarn.lock
Labels: dependencies, radjabov/yes?

#9327 Allow ui classic to run CI in act
  Rakefile
  bin/before_install
  config/jasmine_overrides.rb
Labels: developer

#9322 Update jquery to 3.7.1
  app/javascript/oldjs/import.js
  app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js
  config/jest.setup.js
  package.json
  spec/javascripts/automate_import_export_spec.js
  spec/javascripts/import_spec.js
  spec/javascripts/miq_application_spec.js
  spec/javascripts/services/miq_service_spec.js
  yarn.lock
Labels: dependencies
